### DISCUSSION TITLE
Tracking the progress of your addons when running "copilot deploy"

### DISCUSSION THREAD

**Discussion by efekarakus** [aws/copilot-cli#1907] [Show and tell]
Hi y'all!

In Copilot v1.2.0, we added support to visualize the status of your deployment when running `copilot deploy` (#1742). Here is a sample gif:
![create-svc](https://user-images.githubusercontent.com/879348/106821892-e74e5300-6632-11eb-827b-17ae62274f11.gif)

The progress tracker can track updates for your [addon templates](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/). If you have already existing templates under `addons/` and want to view updates when running `copilot deploy`, you can do so by adding a [`Metadata`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html) attribute to your resources. For example:
```yaml
Resources:
  MyTable:
    Metadata:
      'aws:copilot:description': 'My DynamoDB table'
    Type: AWS::DynamoDB::Table
```
By adding the `'aws:copilot:description'` Metadata, Copilot can now render the  `'My DynamoDB table'` description when running `copilot deploy`.

For new addons, we'll add a description by default.
