### DISCUSSION TITLE
Building multiple pipelines from different branches of a single repo

### DISCUSSION THREAD

**Discussion by huanjani** [aws/copilot-cli#1925] [Show and tell]
We have a more baked-in solution in the works, but in the meantime, here is a workaround for creating different pipelines for the branches of a source repository. 

**For the first pipeline**:

1. From the first git branch, run `copilot pipeline init`. 
2. After the `buildspec.yml` and `pipeline.yml` files are created in the `copilot` directory, check that the pipeline manifest (`pipeline.yml`) has the desired branch. If not, edit the manifest to change it to the name of the current/desired branch. 
3. Add, commit, and push to the git remote.
4. Run `copilot pipeline update` to build the pipeline.

**For the second pipeline**:

1. `git checkout` the second git branch. Run `copilot pipeline init`. Select the same repository url as you did above.
2. This time, after the `buildspec.yml` and `pipeline.yml` files are created, go into the pipeline manifest file (`pipeline.yml`) and *change the name: field to a pipeline name that is different than that of the first pipeline*, and confirm that the branch is the desired second branch.
3. Add, commit, and push to the git remote from this second branch.
4. Run `copilot pipeline update` to build the second pipeline.

**Sample `pipeline.yml` snippets (pay particular attention to the `name` and `branch` fields)**:
```yaml
# "pipeline.yaml" to trigger a pipeline from a "dev" branch.

name: pipeline-appName-repoName-dev # Add "-dev" suffix in your pipeline name.
version: 1
source:
  provider: CodeCommit
  properties:
    branch: dev                     # Make sure your branch points to "dev"
    repository: https://us-west-2.console.aws.amazon.com/codesuite/codecommit/repositories/repoName/browse
```
```yaml
# Second "pipeline.yml" in the "prod" branch.

name: pipeline-appName-repoName-prod # Add "-prod" suffix in your pipeline name.
version: 1
source:
  provider: CodeCommit
  properties:
    branch: prod                     # Make sure your branch points to "prod"
    repository: https://us-west-2.console.aws.amazon.com/codesuite/codecommit/repoName/aws-sample/browse
```

Of course, eventually you will probably want to merge dev into prod, but still maintain the separate pipelines. To do this:

1. Add a `.gitattributes` file in the branch to be merged into the other (here, dev)
2. Add `pipeline.yml merge=ours` to the file. 
3. Add and commit the `.gitattributes` file.  

Locally, this will prevent the pipeline manifest from being merged with the other branch and thereby maintain distinct pipelines. (See https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes.) To merge with a remote host, you'll have to manually reconcile conflicts in the `pipeline.yml`, then revert the pipeline name after merging.

Let us know how this works for you!

**Comment by joshgoodson** [comment]
@huanjani have these discussions involved cross-account pipelines at all? Say I have a prod account and dev account and would like to create a cross-account pipeline to go from qa in our dev account to ultimately a production deployment in another account?

Or do you know of any examples in which this is possible today?

**Reply by huanjani** [reply]
Hi, @joshgoodson! 

If I'm understanding correctly, what you're describing is actually the workflow we had in mind when we designed Copilot pipelines. If you initialize environments in different accounts, you can add those environments as deployment stages when you run `pipeline init`. See https://aws.github.io/copilot-cli/docs/credentials/#environment-credentials. 

Does that help?

**Reply by dannysteenman** [reply]
Hi @huanjani! From what I tested it doesn't work to create a cross-account pipeline yet. I created an issue for that:

https://github.com/aws/copilot-cli/issues/2533

**Reply by joshgoodson** [reply]
@dannysteenman to get cross account pipelines working, I only deployed the pipeline in a single account and then deployed the env in the other account - I can then place the envs in the pipeline manifest and it appears like it will deploy using the single pipeline in the account you ran `copilot pipeline init/update` on. I haven't actually released a change through the pipeline from a qa to a prod like env yet, but I was able to update the pipeline and have it added with manual approval turned on for it. I just have two different aws profiles I use locally and specified it when I created each env
```
copilot app init AppName --domain AppDomain.com 
copilot env init -a AppName -n qa --profile dev
copilot env init -a AppName -n prod --profile prod
```
Then in my pipeline manifest am able to update the pipeline with this
```
stages:
    -
      name: qa
      test_commands: [echo 'running tests', make test]
    -
      name: prod
      requires_approval: true
```
