### DISCUSSION TITLE
Could we get an example of a Redis Elasticache addon?

### DISCUSSION THREAD

**Discussion by DennisSSDev** [aws/copilot-cli#2011] [Q&A] [answered]
Hi

I wanted to make a caching layer for my backend (private) service using elasticache + redis.

Could we get an example of a simple addon yaml file that creates a 50mb redis elasticache instance that respects the default copilot backend service private network setup?

All other settings such as replication can be assumed to be whatever you want, I just want to see how the most barebones elastic cache redis addon file looks like 😄

**Comment by efekarakus** [comment, marked as answer]
Hi @DennisSSDev !

Sorry this is a bit late but here is a working template for using a private elasticache cluster!  
https://gist.github.com/efekarakus/fe694581c88e03eedb38f17b8ddc68a7

<details>
  <summary> Addon template for Redis </summary>

```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  # Subnet group to control where the Redis gets placed
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Group of subnets to place Redis into
      SubnetIds: !Split [ ',', { 'Fn::ImportValue': !Sub '${App}-${Env}-PrivateSubnets' } ]
  
  # Security group to add the Redis cluster to the VPC,
  # and to allow the Fargate containers to talk to Redis on port 6379
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Redis Security Group"
      VpcId: { 'Fn::ImportValue': !Sub '${App}-${Env}-VpcId' }
  
  # Enable ingress from other ECS services created within the environment.
  RedisIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from Fargate containers
      GroupId: !Ref 'RedisSecurityGroup'
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId: { 'Fn::ImportValue': !Sub '${App}-${Env}-EnvironmentSecurityGroup' }

  # The cluster itself.
  Redis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: cache.m4.large
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref 'RedisSubnetGroup'
      VpcSecurityGroupIds:
        - !GetAtt 'RedisSecurityGroup.GroupId'

  # Redis endpoint stored in SSM so that other services can retrieve the endpoint.
  RedisEndpointAddressParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${App}/${Env}/${Name}/redis'   # Other services can retrieve the endpoint from this path.
      Type: String
      Value: !GetAtt 'Redis.RedisEndpoint.Address'

Outputs:
  RedisEndpoint:
    Description: The endpoint of the redis cluster
    Value: !GetAtt 'Redis.RedisEndpoint.Address'
```
</details>

This will create an elasticache cluster that's available to all your Copilot services in your VPC. 

If you want other services to access this cluster you can inject the endpoint in the manifest like this:
```yaml
secrets:
  REDIS_ENDPOINT: /{app}/{env}/{main service name}/redis
```

Hope this helps!

**Reply by sugarjig** [reply]
This worked great for me on the first deployment, but then on subsequent deployments I got this:
```
execute svc deploy: deploy service: change set with name copilot-xxx for stack xxx has no changes: Resource handler returned message: "Invalid request provided: Create TaskDefinition: The Systems Manager parameter name specified for secret REDIS_HOST is invalid. The parameter name can be up to 2048 characters and include the following letters and symbols: a-zA-Z0-9_.-, (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: xxx; Proxy: null)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
```
I thought changing the `/`s in the name to `.`s might fix the issue, but no luck. Deleting the parameter from Parameter Store did not fix the issue, either. I'm resorting to deleting the service and recreating it with `.`s in the parameter name to see if that works better.

**Reply by sugarjig** [reply]
After recreating the service and trying to deploy it with the Redis cluster addon, I'm now getting
```
deploy service: change set with name copilot-xxx for stack xxx has no changes
```

**Reply by Lou1415926** [reply]
Hello @sugarjig !

This is so weird! Usually it should be fine to have `/` in secret's value source like in `/my-app/my-env/my-service/redis`.  We'll inform the container team about this error message.

I tried to do two consecutive deployments on a service with a secret that contains "/" and was able to do it with success. Would you mind giving us more information so that we could try to reproduce the error? 

I've seen people trying to specify a version number at the end by doing `SECRET_NAME: /path/to/secret:<version_number>`. This won't work since `:` is indeed not allowed.

Please let us know!

-----
Edit:

On a second thought, I realize there may be something else to the situation you're encountering.

I suspect that the "change set with name ... for stack ... has no changes" error and the "The Systems Manager parameter name specified for secret REDIS_HOST is invalid." are caused by two separate reasons.

I was able to reproduce your error message by doing the following:
1. Create an invalid addon (e.g. by including `!Ref an-invalid-reference`)
2. Modify the service's manifest by including `SECRET_NAME: secret_value_with_invalid_{character}`

A rather popular cause for the "change set with name ... for stack ... has no changes" error for services that are deployed with an add-on is that the add-on template is invalid in some way. Could you check [this](https://github.com/aws/copilot-cli/issues/2089#issuecomment-832296866) and [this](https://github.com/aws/copilot-cli/issues/2257#issuecomment-831383461) out and see if they help?

**Reply by sugarjig** [reply]
Ah. I tried the exact template in the example, and that worked. I had made some modifications that were apparently not valid. Thanks for your help!

**Reply by TillaTheHun0** [reply]
Thanks for this example! A couple questions.

Adding `RedisSecurityGroup.GroupId` to `Redis.Properties.VpcSecurityGroupIds` adds Redis to the VPC, but doesn't set any Ingress/Egress for Redis, as that is what `RedisIngress` is doing, correct?

Per the [Copilot docs](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/):
> If you need to add a security group to your ECS service, you can define a Security Group in your template, and then add it as an Output. The security group will be automatically attached to your ECS service.

Based on that, if I wanted _only_ the ECS service that this Redis "addon" is nested under, to be able to consume the Redis resource, would I create a security group resource, add it as the `RedisIngress.Properties.SourceSecurityGroupId`, and then add that same security group as an `Output`?

So perhaps somethings like:
```yaml
...
Resources:
  # Add this
  RedisSourceSecurityGroup:
    Metadata:
      'aws:copilot:description': 'An EC2 Security Group to add to our ECS Service, in order to consume Redis'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Redis Consumer Security Group"
      VpcId: { 'Fn::ImportValue': !Sub '${App}-${Env}-VpcId' }

  RedisSecurityGroup:
    Metadata:
      'aws:copilot:description': 'An EC2 Security Group to add the Redis cluster to the environment VPC and enable ingress from our ECS Service'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Redis Security Group"
      VpcId: { 'Fn::ImportValue': !Sub '${App}-${Env}-VpcId' }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !GetAtt 'RedisSourceSecurityGroup.GroupId' # Ref new security group here

...
Outputs:
  RedisEndpoint:
    Description: The endpoint of the redis cluster
    Value: !GetAtt 'Redis.RedisEndpoint.Address'
  # Add as an output and Copilot adds to our ECS Service
  RedisSourceSecurityGroup:
    Description: "The EC2 Security Group to add to our ECS Service, in order to consume Redis."
    Value: !Ref RedisSourceSecurityGroup
```

Edit: added example
