### DISCUSSION TITLE
Launching workloads without internet access

### DISCUSSION THREAD

**Discussion by huanjani** [aws/copilot-cli#2378] [Show and tell]
Copilot enables you to launch tasks in private subnets (whether your workload is a [scheduled job](https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/#network-vpc-placement), [load-balanced web service](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement), or [backend service](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#network-vpc-placement)), automatically creating [NAT gateways](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) for internet connectivity.

However, isolated tasks that are not internet-facing do not need NAT gateways; instead they require [VPC Endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html) to communicate with other AWS services. You can [import an existing VPC](https://aws.github.io/copilot-cli/docs/concepts/environments/#customize-your-environment) with the necessary endpoints, and specify `private` subnet placement in your service or job [manifest](https://aws.github.io/copilot-cli/docs/manifest/overview/). 

### Not sure what resources you'll need? Use this template:

```
Resources:
  # A Virtual Private Cloud to control networking of your AWS resources.
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default

  # Private subnets.
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: false

  # Security Group to allow use of VPC Endpoints.
  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: "Security group to allow use of VPC Endpoints."
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: HTTPS
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/0

  # Route table for gateway endpoint(s).
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  # Associations between your route table and subnets.
  RouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PrivateSubnet1

  RouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PrivateSubnet2

  # Gateway endpoint for S3.
  S3GatewayVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref RouteTable
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC

  # Interface endpoints.
  # Enables pulling images from ECR.
  EcrApiVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcId: !Ref VPC
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup

  EcrDkrVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcId: !Ref VPC
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup

  # Enables CloudWatch logging.
  LogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcId: !Ref VPC
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
```
### Add more VPC endpoints depending on which services you need access to.

For [Systems Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-create-vpc.html) (to enable exec functionality and more):
```
SSMVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup

EC2MessagesVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup

EC2VPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup

SSMMessagesVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
For [Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html):
```
SecretsManagerVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
For [Key Management Service](https://docs.aws.amazon.com/kms/latest/developerguide/kms-vpc-endpoint.html):
```
KMSVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.kms
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
For [Auto Scaling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-vpc-endpoints.html):
```
AutoScalingVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.autoscaling
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
To connect to an [Elastic File System](https://docs.aws.amazon.com/efs/latest/ug/efs-vpc-endpoints.html) volume:
```
EFSVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.elasticfilesystem
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
For [DynamoDB](https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-ddb.html), [you’ll need](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/vpc-endpoints-dynamodb-tutorial.html) another [gateway endpoint](https://docs.aws.amazon.com/vpc/latest/privatelink/vpce-gateway.html) (like S3, above):
```
# Gateway endpoint for DynamoDB.
DynamoDBGatewayVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Gateway
    RouteTableIds:
      - !Ref RouteTable
    ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
    VpcId: !Ref VPC
```
For[ RDS/Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/vpc-interface-endpoints.html):
```
RDSVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
    ServiceName: !Sub com.amazonaws.${AWS::Region}.rds
    VpcId: !Ref VPC
    SecurityGroupIds:
      - !Ref VPCEndpointSecurityGroup
```
