### DISCUSSION TITLE
Cloudfront in front of ALB

### DISCUSSION THREAD

**Discussion by afgallo** [aws/copilot-cli#2629] [Q&A]
Hi there,

Wondering if anyone has an addon example on how to add a cloudfront distribution in front of an ALB and lock down the ALB to serve traffic only from Cloudfront?

Thanks!

**Comment by afgallo** [comment]
Hi @efekarakus would love your view on the below, just not sure whether I'm using the right variable names on my `Ref` statements, namely `PublicLoadBalancerDNSName`, `DomainNameRecordSet`, `EnvironmentHostedZone` and `HTTPCert`. This would help me mitigate #2602 before v.1.9.0 is released. And I also think having CloudFront in front of my front-end service is a really good architecture option too 😃

Cheers,
Andre

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudfront instance for the front-end service

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: alb
          DomainName: !Ref PublicLoadBalancerDNSName
          OriginPath: /
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
                - Authorization
                - Accept
                - Accept-Encoding
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: alb
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: '/index.html'
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Aliases:
          - !Sub ${Env}.${App}.domain.com
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref HTTPSCert
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018

  DNSARecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Sub ${Env}.${App}.domain.com, .]]
      RecordSets:
      - Name: !Ref DomainNameRecordSet
        Type: A
        AliasTarget:
          HostedZoneId: !Ref EnvironmentHostedZone
          DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName

```
