### DISCUSSION TITLE
More detailed example for the nginx sidecar use case

### DISCUSSION THREAD

**Discussion by vkuts** [aws/copilot-cli#2674] [Q&A] [answered]
Hi copilot team,
Sorry if this has been covered elsewhere, but I couldn't figure out how to get nginx running as a sidecar to front a web service. More specifically, I can't seem to get the url of the web service right in nginx config. I assumed that the networking mode amongst the containers running within a task is akin to docker bridge mode, and so they should be able to find each other via their container names, but it doesn't seem to be the case.

Here's the rough idea of how I attempted it:
```
name: frontend
type: Load Balanced Web Service
http:
  path:  /
  targetContainer: nginx

  image:
    port: 8080
    location: ###
  
  sidecars:
    nginx:
      port: 80
      image: ####
      depends_on:
        frontend: start
```

And my nginx.conf instructs it to reach the web service like so (nginx.conf):
```
http {
  # ...
   upstream frontend {
    server frontend:8080;
  }
  
  server {
  listen 80;

  location ~ ^\/api($|\/) {
    proxy_pass http://frontend:8080;
  }
}
```
With this kind of setup, nginx errors like so ` [emerg] 1#1: host not found in upstream "frontend:8080" in /etc/nginx/nginx.conf:47"`

I've also tried making nginx the main container, and the webserver containers its sidecars, but that fails in a similar way.
