### DISCUSSION TITLE
Managed EFS

### DISCUSSION THREAD

**Discussion by christopherrbyrd** [aws/copilot-cli#2809] [Q&A]
Hey there,

I'm a copilot newbie, so pardon any dumb questions in advance ;-) Here's the issue I'm experiencing. When I try to add a managed EFS to my application/service nothing happens. The documentation states to "add the storage field" to the manifest.yml file. For example,

storage:
  volumes:
    myManagedEFSVolume:
      efs: true
      path: /var/efs
      read_only: false

After modifying the manifest and deploying the service Copilot (or CloudFormation) does not recognize the changes. I'm I missing something?

Note: copilot version: v1.10.0, MacOS 11.2

**Comment by efekarakus** [comment]
Hi @christopherrbyrd ! 

I've tried to reproduce the issue but the EFS file system seems to be created. These are the steps that I took:
1. Modified the `copilot/<svc>/manifest.yml` to add the `efs` configuration:
```yaml
name: frontend
type: Load Balanced Web Service

storage:
  volumes:
    myManagedEFSVolume:
      efs: true
      path: /var/efs
      read_only: false
```
2. Ran `copilot deploy` and deployed my "frontend" service to a "test" environment:
```
✔ Proposing infrastructure changes for stack demo-test-frontend 
- Updating the infrastructure for stack demo-test-frontend                    [update in progress]  [34.2s]
  - An EFS access point to handle POSIX permissions                           [not started]         
  - Update your environment's shared resources                                [update in progress]  [6.3s]
  - An ECS service to run and maintain your tasks in the environment cluster  [not started]         
  - An ECS task definition to group your containers and run them on ECS       [not started]         
  - An IAM role to control permissions for the containers in your tasks       [not started] 
```

If it's okay to copy/paste your manifest.yml file we might be able to troubleshoot too!

**Reply by christopherrbyrd** [reply]
Thanks @efekarakus for following up on this. Here's my modified manifest.yml file. 

```
### The manifest for the "dispatch" service.
### Read the full specification for the "Request-Driven Web Service" type at:
### https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/

### Your service name will be used in naming your resources like log groups, App Runner services, etc.
name: dispatch
### The "architecture" of the service you're running.
type: Request-Driven Web Service

image:
  ### The name of the Docker image.
  location: XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/docker-flask-cache-awslinux:latest
  ### Port exposed through your container to route traffic to it.
  port: 5000

### Number of CPU units for the task.
cpu: 1024
### Amount of memory in MiB used by the task.
memory: 2048


storage:
  volumes:
    myManagedEFSVolume:
      efs: true
      path: /tmp
      read_only: false
```

#Here's the output from copilot deploy:

```
✔ Proposing infrastructure changes for stack digital-dispatch-test-dispatch 
- Creating the infrastructure for stack digital-dispatch-test-dispatch            [create complete]  [358.8s]
  - An IAM Role for App Runner to use on your behalf to pull your image from ECR  [create complete]  [14.9s]
  - An Addons CloudFormation Stack for your additional AWS resources              [create complete]  [51.6s]
    - An IAM ManagedPolicy for your service to access the copilot-bucket bucket   [create complete]  [13.7s]
    - A bucket policy to deny unencrypted access to the bucket and its contents   [create complete]  [4.0s]
    - An Amazon S3 bucket to store and retrieve objects for copilot-bucket        [create complete]  [21.7s]
  - An IAM role to control permissions for the containers in your service         [create complete]  [13.6s]
  - An App Runner service to run and manage your containers                       [create complete]  [288.7s]
✔ Deployed service dispatch.
```
