### DISCUSSION TITLE
How to access Aurora from a scheduled job

### DISCUSSION THREAD

**Discussion by coopsmoss** [aws/copilot-cli#3084] [Q&A] [answered]
Hi there,

 I configured an Aurora database through copilot for my load balanced service and I now need to get access to it from my new scheduled job.

On the API an environment variable is automatically there when the container runs, is it possible to set this up for the scheduled job too?
I tried this  kind of thing in the manifest to no avail. Both with the name of the secret and also with the arn of the secret.
```
environments:
  prod:
    secrets:
      MYAURORACLUSTER_SECRET: myaurorclusterAuroraSecret-12345678
  test:
    secrets:
      MYAURORACLUSTER_SECRET: myaurorclusterAuroraSecret-12345678
```

Beyond passing in the secret do I need to do anything regarding security groups etc. Or is everything within the same environment accessible by default?

Thanks a lot for your help
