### DISCUSSION TITLE
Configuring scale-in and scale-out period in manifest.yml

### DISCUSSION THREAD

**Discussion by anne-montoya** [aws/copilot-cli#3161] [Q&A]
I'm using auto scaling by following this guide https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count
How can I configure scale-in and scale-out period? 

Snippet of my manifest.yml
```
environments:
  test:
    count:
      range: 1-3
      cpu_percentage: 40
      memory_percentage: 60
```
