### DISCUSSION TITLE
How scaling by requests works?

### DISCUSSION THREAD

**Discussion by coopsmoss** [aws/copilot-cli#3392] [Q&A] [answered]
Hi there, I'm just looking for a little bit of clarification regarding scaling based on requests as [seen here](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count)

The docs say "Scale up or down based on the request count handled per tasks."
I interpret that to mean simultaneous requests per instance, so I was planning to set it to something quite low like 3,4,5 (because our requests take somewhat long to process) but the example docs has a huge number:

```
count:
  range: 1-10
  cpu_percentage: 70
  memory_percentage: 80
  requests: 10000
  response_time: 2s
```

It has 10,000 which makes me wary that I'm misunderstanding how this operates. I just don't want to set it too low and then have my application scale to the max right away. Is it 10,000 per minute/hour/etc?

So just looking for some clarification on that. Thanks a lot in advance.
