### DISCUSSION TITLE
How can I have multiple scheduled jobs use the same image?

### DISCUSSION THREAD

**Discussion by DrewVartanian** [aws/copilot-cli#3598] [Q&A] [answered]
I have multiple Copilot scheduled jobs, deployed with Pipeline.  Each job is set to use the same dockerfile and target for the build, with different entrypoints for when they run.  Currently, Pipeline will build out and push separate images for each job, and I was wondering if there is any way to have it just build one image, and use that for each job?

**Comment by dannyrandall** [comment, marked as answer]
Hey!:blush: Does this look like the same issue you're running into? https://github.com/aws/copilot-cli/issues/1943

If so, could you add a +1 to the issue and add your use case?

**Reply by DrewVartanian** [reply]
Thanks.  I added the following comment to the thread.

In my case, I'm specifying different the entrypoints using the entrypoint field in the copilot service manifests, with the image.build.dockerfile and image.build.target set to the same value for the different services.  It looks something like:
```
image:
  build:
    dockerfile: ./Dockerfile
    target: job

entrypoint: "php /pathtocodebase/job1.php"
```
and
```
image:
  build:
    dockerfile: ./Dockerfile
    target: job

entrypoint: "php /pathtocodebase/job2.php"
```
That said, using a shared entrypoint script that differentiates based on COPILOT_SERVICE_NAME would work fine as well.
