### DISCUSSION TITLE
Using "--internal-alb-allow-vpc-ingress" with "copilot env deploy"

### DISCUSSION THREAD

**Discussion by rverpillot** [aws/copilot-cli#4032] [Q&A] [answered]
I'm trying to convert current scripts to create copilot environment to the new environment deployment feature of copilot, but I can't figure out how to translate the flag "--internal-alb-allow-vpc-ingress". When I enable this flag in "copilot env init", the environment manifest generated doesn't seem to use it, and I can't find anything in the documentation about it.

**Comment by efekarakus** [comment, marked as answer]
Hi Regis! 👋 

Apologies, looks like we forgot to translate that flag in the manifest file 🤦 
I believe what you are looking for is this field: https://aws.github.io/copilot-cli/docs/manifest/environment/#http-private-security-groups-ingress

```yaml
type: Environment

http:
  private:
    security_groups:
      ingress: # Enable incoming traffic within the VPC to the internal load balancer.
        from_vpc: true
```

Hope this helps!
