### DISCUSSION TITLE
Deploying from Bitbucket pipeline

### DISCUSSION THREAD

**Discussion by iamsajithk** [aws/copilot-cli#4124] [General]
How to deploy from Bitbucket using bitbucket-pipelines.yml. I am getting "Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?" error when trying with an ubuntu image with docker and copilot installed on it. Anyone had success in this?

**Comment by iamhopaul123** [comment]
Hello @iamsajithk this is most likely because Copilot is trying to build an image from local dockerfile, which requires Docker daemon to be running. Or you can use an existing image by specifying [`image.location`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location). If you are still getting this error could you check if you are using the latest binary in your build environment?

Another question will be did you run `copilot` command in a container? If so you might need `privileged` for it.

**Comment by iamsajithk** [comment]
Made it working using the following pipeline yml file.

```
image: sajithkw/ubuntu-aws-copilot:latest

pipelines:
  branches:
    dev:
      - parallel:
        - step:
            name: Deploy using AWS Copilot
            services:
              - docker
            script:
              - export export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
              - export export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
              - export export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
              - copilot deploy --env dev
```

Used a custom ubuntu image with copilot installed as a base image.

```
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
# Install base packages
RUN apt-get update -yqq && apt-get install curl sudo -yqq
# Install AWS Copilot
RUN curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x copilot && sudo mv copilot /usr/local/bin/copilot && copilot --help
#CMD ["/run.sh"]
```
