### DISCUSSION TITLE
Sharing a database between microservices

### DISCUSSION THREAD

**Discussion by efekarakus** [aws/copilot-cli#4275] [Show and tell]
> _A frequently asked question while creating a microservice architecture with AWS Copilot is how to share a database between these services._

We outlined solutions in https://github.com/aws/copilot-cli/issues/4273#issuecomment-1353484075 and https://github.com/aws/copilot-cli/issues/2495#issuecomment-866188721, so I'm copying it over here in order to make it easier to discover the solution.

1. **[preferred] Only one microservice should have read/write access to the database, remaining services access data through communication with  [service connect](https://aws.github.io/copilot-cli/docs/developing/svc-to-svc-communication/)**. 
One microservice should run `copilot storage init` to create the RDS cluster and have direct access to the database. This service can expose an API so that internal services can retrieve data from the database. For example, if the service with the database is called "warehouse" and exposes port 80 in `image.build`, then we can add a new API in the "warehouse" service for say "GET /inventory/{productId}". Then the backend service can make a request to that path:
   ```go
   resp, err := http.Get("http://warehouse/inventory/1234") 
   ```
<p align="center">
   <img src="https://user-images.githubusercontent.com/879348/207929379-62907835-cd59-4d8e-b186-bdc6ac985bb7.png" width="400px" />
</p>
   The tradeoff is that it's a bit more work upfront then just letting other services access the database. However, you gain the benefit of data encapsulation so you can always change the underlying data model safely. This architecture is preferred if you have several teams in your organization that need to work independently from each other.

<br/>
<br/>

2. **An alternative proposal is to allow ingress from all the services in the environment by modifying the security group of the RDS cluster.**
There is a `<App>-<Env>-EnvironmentSecurityGroup` that's assigned to all services. After copilot generates the addon template with `storage init`, you can modify the CloudFormation template and add this  ingress rule to the cluster's security group. Here is a snippet that may work for you:
   ```yaml
   <clusterName>DBClusterSecurityGroup: # replace <clusterName> 
     Metadata:
       'aws:copilot:description': 'A security group for your DB cluster <cluster>' # replace <clusterName> 
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupDescription: The Security Group for the database cluster.
       SecurityGroupIngress:
         - ToPort: 5432
           FromPort: 5432
           IpProtocol: tcp
           Description: !Sub 'From the Aurora Security Group of the workload ${Name}.'
           SourceSecurityGroupId: !Ref backendclusterSecurityGroup
         - ToPort: 5432 # The additional ingress rule that you can add for other service to access the cluster
           FromPort: 5432
           IpProtocol: tcp
           Description: From Environment Security Group
           SourceSecurityGroupId: 
             Fn::ImportValue: 
               !Sub '${App}-${Env}-EnvironmentSecurityGroup'
   ```
   With this ingress, the cluster's security group will allow access from all services deployed in the environment. 
   You'll need to also update the manifest of the remaining services with the database secret created in the addon stack.
   ```yaml
   secrets:
     DBCREDENTIAL: <secret ARN>
   ```
   For additional ways of injecting a secret from AWS Secrets Manager [see the following guide.](https://aws.github.io/copilot-cli/docs/developing/secrets/#in-secrets-manager)
   
   The tradeoff is that we created tight coupling between our services because now they can impact each other. Services are all aware of the database schema, and a service A can modify data that it shouldn't. However, this setup is a lot more agile and easier to get going. This architecture is preferred if you're a smaller organization with a few teams and high trust.
   
Hope this helps!
