### DISCUSSION TITLE
Is there a way to config Pipeline to source from ECR repository

### DISCUSSION THREAD

**Discussion by ShanikaEdiriweera** [aws/copilot-cli#4905] [Q&A]
Is there a way to config Pipeline to source from ECR repository rather than selecting one of GitHub, Bitbucket, CodeCommit since my repo is in Gitlab. What are my options to create a copilot pipeline?

It would be ideal if something like below is possible.
```
source:
  # The name of the provider that is used to store the source artifacts.
  provider: ECR
  # Additional properties that further specify the location of the artifacts.
  properties:
    tag: latest
    repository: <erc-repository-url>
```
