### DISCUSSION TITLE
Manifest Environment Variables for Array

### DISCUSSION THREAD

**Discussion by Kqirk** [aws/copilot-cli#4907] [Q&A] [answered]
Hi,

Is there an example on how to parse an array of strings from a shell variable to the manifest.yml?

- I'm trying to to parameterise my security_groups field for different environments.
- My current approach is using a script to set the shell variables before deploying as per https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/
- I'm using "source .env" to set the shell variables 
- There should be no issues with my set up as it works for non array strings

- My code is as follows: 

manifest.yaml:
network: 
   vpc:
      security_groups: ${SECURITY_GROUPS}

my .env file (values substituted out):
SECURITY_GROUPS=["sg-1","sg-2","sg-3","sg-4"]

The error:
unable to unmarshal "security_groups" field into slice of strings or compose-style map

- I've also tried many different variations of where I placed the double quotes, using () instead of [], they all return the same error

- A way that would work is:

security_groups:
    -${sg_1}
    -${sg_2} 
     ...

- However, that would cause some mismatch if the number of SGs differ etc.

Any advice and help would be greatly appreciated. Thank you for reading this and for your time.

**Comment by Lou1415926** [comment, marked as answer]
Hello @Kqirk 👋🏼 I can confirm that non-array env vars aren't supported in the manifest yet. 

A short explanation - ⬇️  is not working because `${SECURITY_GROUPS}` is recognized as a string first, before Copilot even tries to read it as an env var. This causes failure to unmarshal, because `security_groups` as a YAML field is expecting `slice of strings or compose-style map`. 
```yaml
network:
  vpc:
    security_groups: ${SECURITY_GROUPS}
```

This is an interesting case that you raised, perhaps Copilot should support non-string env vars types.

For now, I think you probably do need to write it as  ⬇️  unfortunately : (  
```yaml
security_groups:
  -${sg_1}
  -${sg_2}
```
I understand that the number of SGs might differ across envs, but are they not known in advance? Are you probably aware that manifest supports [environment overrides](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#environments) like below:
```yaml
network:
  vpc:
     security_groups: ["sg-1","sg-2"]
environments:
  test:
    network:
      vpc:
       security_groups: ["sg-3","sg-4", "sg-5"]
  prod:
    network:
      vpc:
       security_groups: ["sg-3","sg-4"]
```
