### DISCUSSION TITLE
does manifest support awslogs logConfiguration parameters?

### DISCUSSION THREAD

**Discussion by rmarops** [aws/copilot-cli#5188] [Q&A] [answered]
Is it possible to configure the manifest to pass these parameters?  I think some people are enabling cloudwatch logs manually from cli but i'd want it set consistently for every deployment

example
```
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "ecslogs",
                    "awslogs-region": "us-west-2",
                    "awslogs-create-group": "true",
                    "awslogs-stream-prefix": "ecs"
                }
            }
```

**Comment by KollaAdithya** [comment, marked as answer]
Hello @rmarops !
Sorry for delayed response. Copilot currently doesn't allow you to configure these values through manifest.
By default the values will be
```
  LogDriver: awslogs
  Options:
    awslogs-region: !Ref AWS::Region
    awslogs-group: !Ref LogGroup
    awslogs-stream-prefix: copilot
```
If you want to configure you can definitely use [`yaml patches`   ](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) to override these values.
