### DISCUSSION TITLE
Scheduled scaling as an addon

### DISCUSSION THREAD

**Discussion by Lou1415926** [aws/copilot-cli#5250] [Show and tell]
- The solution presented below is a _starting point_ from which users can build their own scheduled scaling addons. Users need to modify the template to work for their requirements.
- The solution is built on top of the [addons feature](https://aws.github.io/copilot-cli/docs/developing/addons/workload/).
- Related: #4233

---

1. Define `copilot/<svc>/addons/addons.parameters.yml`
```yaml
Parameters:
  ServiceName: !GetAtt Service.Name
```

2. Define `copilot/<svc>/addons/scheduled-scaling.yml`
```yaml
Parameters:
  # Required parameters by AWS Copilot.
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  # Additional parameters defined in addons.parameters.yml
  ServiceName:
    Type: String

Type: AWS::ApplicationAutoScaling::ScalableTarget
Properties: 
  MaxCapacity: 1
  MinCapacity: 1o
  ResourceId: !Ref ServiceName
  RoleARN: ...
  ScalableDimension: ecs:service:DesiredCount
  ScheduledActions: 
    - ScalableTargetAction:
        MinCapacity: 10 # Scale to 10
        MaxCapacity: 10
      Schedule: cron(...)
      ScheduledActionName: ScaleTo10EverySaturdayFrom9to18
  ServiceNamespace: ecs

```
