### DISCUSSION TITLE
Recommended best practices to test multiple services

### DISCUSSION THREAD

**Discussion by jerometremblay** [aws/copilot-cli#5391] [Q&A]
What are the recommended best practices to test multiple services?

When I deploy i have one pipeline for each service, and they are all deployed in parallel. But how should I test everything? Should I use a single pipeline? A pipeline dedicated to e2e tests with a wait stage that checks all dependencies and wait that they are all deployed to the latest version?

**Comment by KollaAdithya** [comment]
Hello @jerometremblay !

For your use case which is to deploy all the services in parallel and once all the services are deployed run e2e tests, you can definitely use a single pipeline.

You can use [stages.deployments](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-deployments) and ([stages.test_commands](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-test-cmds) or [stages.post_deployments](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-postdeployments))to deploy all the services  to a particular environment and finally run e2e tests.

Here is how the pipeline manifest can look like:
```
stages:
  - name: test
    deployments:  # deploys api and frontend services to test environment in parallel.
      api:
      frontend:
    test_commands:
      - make e2e-test # runs e2e tests after deployment is successful.
```
