### DISCUSSION TITLE
Change base build image of tests

### DISCUSSION THREAD

**Discussion by jerometremblay** [aws/copilot-cli#5409] [Q&A] [answered]
In my pipeline manifest.yml i have this:

```
build:
  image: aws/codebuild/standard:7.0
```

The main buildspec.yml now use this ubuntu as the base image.

However, during the tests in "stages" it still use the default [aws/codebuild/amazonlinux2-x86_64-standard:4.0](https://aws.github.io/copilot-cli/docs/concepts/pipelines/#:~:text=Pre%2Ddeployments%2C%20post%2Ddeployments%2C%20and%20test%20commands%20generate%20CodeBuild%20projects%20with%20the%20aws/codebuild/amazonlinux2%2Dx86_64%2Dstandard%3A4.0%20image)

```
stages:
  - # The name of the environment.
    name: tests
    post_deployments:
      tests:
        buildspec: copilot/pipelines/root-main-app/buildspecs/post_buildspec.yml
        configuration:
          BatchEnabled: true

```

Is it possible to use the same base image as the default, or override it per-stage?
