### DISCUSSION TITLE
Pipeline deploy causing temporal 503 on services?

### DISCUSSION THREAD

**Discussion by tyoc213** [aws/copilot-cli#5482] [Q&A] [answered]
Hi there, been deploying with a new pipeline my 5 services now on testing, but I have seen that while they are being deployed I got a 503 service temporarily unavailable, in particular in the 3rd stage of the pipeline (1. source, 2. build, 3. deploy).

Is this intended? I thought the purpose of the pipelines was to have zero downtime? or Im wrong in this?

![image](https://github.com/aws/copilot-cli/assets/506234/403601a3-8194-4943-ad75-59f14b64722f)

By the way, I havent seen this if I use from command line the `copilot svc deploy -n x --e staging` only seen this downtime while executing stage 3 of the pipeline.

**Comment by Lou1415926** [comment]
Hello @tyoc213 👋🏼! This is not intended nor expected. It is also peculiar that it behaves differently in pipeline and from the cli. Both he pipeline and the cli send update request to CloudFormation, which then triggers update to the ECS / App Runner service. By the time CloudFormation accepts the update request, everything should be the same whether the request originates from the pipeline or from the cli 🤔 .


A few questions:
1. Did you observe this on all 5 services when deploying to "deploy"?
2. Have you configured the [`deployment`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment) field? If so, what is the configuration?
3. Can you take a look at the CloudFormation stack, go to the "Events" tab, and see if anything is unexpected there (e.g. any red `XXX_FAILED_YYY` events)

**Reply by tyoc213** [reply]
<img width="330" alt="image" src="https://github.com/aws/copilot-cli/assets/506234/3f57e675-48bc-475c-a0f8-df8bab708b27">

This is the deploy order, the second line 1 is an api the other 2 are a webapp, third like are kind of "jobs" no front to internet.

1. I Observed it in the the api and on 1 of the the webapps, I think the other too but Im sure only from the one I got the screenshot.
2. yea, here it is mostly

```
stages:
    - name: staging
      deployments:
        redis-server:
        api:
          depends_on: [redis-server]
        no_web_job_1:
          depends_on: [api]
        no_web_job_2:
          depends_on: [api]
        web-app-1:
          depends_on: [redis-server]
        web-app-2:
          depends_on: [redis-server
```
3. Indeed an error on one of the instances that I change to spot instance from normal instance: `Resource handler returned message: "Invalid request provided: CreateService error: SC service is already used by arn:aws:servicediscovery:us-east-1:2633525XXXXX:namespace/ns-jm7syw53gidXXXXX (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 20a91d34-dcb1-438d-9c6a-c9cb71272901; Proxy: null)" (RequestToken: b64ea67d-9da7-563c-5a7e-11XXXXXXXXXX, HandlerErrorCode: InvalidRequest)`

@Lou1415926  Let me try to remove this and redeploy with the spot instance and see if I that clears the temporal 503.
