### DISCUSSION TITLE
Using environments as tenants.

### DISCUSSION THREAD

**Discussion by jerometremblay** [aws/copilot-cli#5511] [Q&A]
I have a collection of applications i want to use with several tenants. Each tenant get it's own aws account, and all resources required to run their own instance of the applications: Databases, ec2 instances, aws batches, subnets, s3, etc.

I thought that those tenant instances looked a lot like environments.  All applications would have the same environments (or more precisely, the same environment names), ex. dev, tenant1, tenant2. 

What I am not sure how to handle is the domain name. The documentation states that i should use one of those:

- {domain}, such as example.aws
- {subdomain}.{domain}, such as v1.example.aws
- {appName}.{domain}, such as coolapp.example.aws
- {subdomain}.{appName}.{domain}, such as v1.coolapp.example.aws
- {envName}.{appName}.{domain}, such as test.coolapp.example.aws
- {subdomain}.{envName}.{appName}.{domain}, such as v1.test.coolapp.example.aws

What I would actually need is {subdomain}.{appName}.{envName}.{domain} but i'm not sure that it would be possible, as that means that several applications would modify the same dns zone.

Any ideas on how how could I proceed, or general suggestions about handling multiple tenants in silo like that.

**Comment by Caio-Domingos** [comment]
Firstly, you have the option to create your own custom domains by using http.alias. This allows for the customization of each environment, as you can override settings in different environments to achieve this. Ideally, it's also beneficial to configure the network settings in a way that isolates each environment within its own space in the VPC. This helps to prevent one client from potentially affecting another.

Ex.:
```yaml
name: my-cool-app
type: Load Balanced Web Service

environments:
  dev:
    http:
      alias: dev.my-cool-app.example.com
    network:
      vpc:
        placement: 'isolated'
  tenant1:
    http:
      alias: tenant1.my-cool-app.example.com
    network:
      vpc:
        placement: 'isolated'
  tenant2:
    http:
      alias: tenant2.my-cool-app.example.com
    network:
      vpc:
        placement: 'isolated'

image:
  build: ./Dockerfile
  port: 80

cpu: 256
memory: 512
count: 1

network:
  vpc:
    subnets:
      - subnet-0bb1c79de3EXAMPLE
      - subnet-0bb2c79de3EXAMPLE
    security_groups:
      - sg-0bb1c79de3EXAMPLE
```
