### DISCUSSION TITLE
per environment yamlpatch override

### DISCUSSION THREAD

**Discussion by erpadmin** [aws/copilot-cli#5616] [Q&A]
I need to be able to specify different certs to use for NLB TLS based on environment.  This is a side discussion for https://github.com/aws/copilot-cli/discussions/5474

I have the following block in yamlpatch override @ service/copilot/service/overrides/cfn.patches.yml
```
# Add an TLS listener.
- op: add
  path: /Resources/NLBListenerTLS
  value:
    Metadata: 
      'aws:copilot:description': 'An TLS listener on port `443` that forwards traffic to your tasks'
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref NetworkLoadBalancerTargetGroupTLS 
          Type: forward
      LoadBalancerArn: !Ref PublicNetworkLoadBalancer
      Port: 443
      Protocol: TLS
      Certificates:
        - CertificateArn: <your certificate ARN>                               <----- **Is it possible to set this value based on Environment?**
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
```

Is it possible to use one cert for qa and one for prod?
@Lou1415926

**Comment by Lou1415926** [comment]
One thing I can think of is to use CloudFormation's [`Mappings`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) section. As an example:
```yaml
- op: add
   path: /Mappings
   value:
     NLBCertificates:
       qa:
         Certificate: <arn1>
       prod:
         Certificate: <arn2>
- op: add
   path: /Resources/NLBListenerTLS
   value:
     Properties:
      Certificates:
        - CertificateArn:
             Fn::FindInMap: [NLBCertificates, Ref: Env, Certificate]

```
