### DISCUSSION TITLE
Backend Service with API Gateway frontend

### DISCUSSION THREAD

**Discussion by andrea-avogadro-archiva** [aws/copilot-cli#5646] [Q&A] [answered]
Hi, 
does a Backend Service that is exposed to the public internet via an API Gateway make sense? I'd like to use API GW built-in authentication mechanism. Is there any example? On the API GW side which is the right integration type? Thanks

**Comment by KollaAdithya** [comment]
Hello @andrea-avogadro-archiva 👋 

Here is a workaround from an old GH [issue](https://github.com/aws/copilot-cli/issues/2050#issuecomment-812838310) on configuring an API Gateway with a backend service using Addons.

**Reply by andrea-avogadro-archiva** [reply]
Hi, 
following the issue I'm creating a Backend Service. Then, via workload addons: an API GW, a Network LB (that will be connected to the internal ALB) and a VPC link that will connect the API GW to the NLB.

The problem with the addons is that they depends on resources (ALB) that will be created during the service deploy: I have the following error: `ValidationError: Template format error: Unresolved resource dependencies [InternalLoadBalancer]`

Is there a way to solve this?
Thanks
Andrea

**Reply by KollaAdithya** [reply]
Hello @andrea-avogadro-archiva !

Can you paste the addon template that you are using for creating API Gateway.

**Reply by andrea-avogadro-archiva** [reply]
Here it is (please note that some resources are still missing).

These are for the API GW:
```

  ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: !Sub '${App}-${Env}-api-gw'
        Description: 'SAP WS API Gateway'
        EndpointConfiguration:
          Types:
            - REGIONAL

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref ApiGatewayRestApi
```
And these are for the NLB:

```
  NlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: NLB SG, allow access from API GW
      VpcId:
        Fn::ImportValue: !Sub '${App}-${Env}-VpcId' # Taken from the outputs of the "env" stack
#  TODO    SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 80
#          ToPort: 80
#          CidrIp:
#            Fn::GetAtt:
#              - Fn::ImportValue: !Sub '${App}-${Env}-VpcId'
#              - 'CidrBlock'
     #  Amazon EC2 creates a default egress rule that allows egress traffic on all ports and IP protocols to any location

  PrivateNetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${App}-${Env}-private-nlb'
      IpAddressType: ipv4
      Type: network
      Scheme: internal
      Subnets: !Split [",", Fn::ImportValue: !Sub '${App}-${Env}-PrivateSubnets'] # Taken from the outputs of the "env" stack
      SecurityGroups:
        - !Ref NlbSecurityGroup

  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: InternalLoadBalancer
    Properties:
      Name: !Sub '${App}-${Env}-alb-tg'
      TargetType: alb
      Protocol: TCP
      Port: 80
      HealthCheckPath: /actuator/health
      VpcId:
        Fn::ImportValue: !Sub '${App}-${Env}-VpcId'
      Targets:
        - Id: !Sub ${InternalAlbArn}

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref PrivateNetworkLoadBalancer
      Port: 80
      Protocol: "TCP"
      DefaultActions:
        - Type: "forward"
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AlbTargetGroup
```
The problem is on the Target Group that needs a reference to the internal ALB (`InternalAlbArn`).
I've defined an input parameter (in the `addons.parameters.yml` file) like this:

```
Parameters:
  InternalAlbArn: !Ref InternalLoadBalancer # Taken from the resources of the "env" stack
```
If this addon is created **after** the main stack everything works fine.

Many thanks
Andrea
