### DISCUSSION TITLE
Enable cloudfront caching for specific service

### DISCUSSION THREAD

**Discussion by jetaggart** [aws/copilot-cli#5687] [Q&A]
I have an environment set up with cdn on for cloudfront:

```
cdn:
  terminate_tls: true

http:
  public:
    security_groups:
      ingress:
        restrict_to:
          cdn: true

```

I have a service (imgproxy) running as a load balanced service inside ecs. How can I enable caching in the cloudfront instance just for this service but not affect other services/apis?
