### DISCUSSION TITLE
Configure cloudfront behaviors

### DISCUSSION THREAD

**Discussion by jetaggart** [aws/copilot-cli#5688] [Q&A]
Using `cdn: true` in an environment how can I modify the cloudfront behavior configuration? I can do it manually but it causes drift.

**Comment by Lou1415926** [comment]
Like this ⬇️ !

```
cdn:
  certificate: "arn:aws:acm:us-east-1:1234567890:certificate/e5a6e114-b022-45b1-9339-38fbfd6db3e2"
  terminate_tls: false
  static_assets:
    path: static/*
    <more configs...>
```

doc link: https://aws.github.io/copilot-cli/docs/manifest/environment/#cdn
