### DISCUSSION TITLE
Mounting SecretsManager secret as a file

### DISCUSSION THREAD

**Discussion by al-dpopowich** [aws/copilot-cli#5690] [Ideas]
I am investigating transitioning our current use of (the now deprecated) [compose-ecs](https://github.com/docker/compose-ecs) to copilot.  One feature I'm sorely missing is the ability to declare secrets that will result in a mounted file on the running container.  For example, when using `compose-ecs`, I could have in my `docker-compose.yml` file:

```yaml
secrets:
   credentials:
      name: "arn:aws:secretsmanager:us-east-2:0123456789:secret:beta/credentials-YOOdYl"
      external: true
      keys: "*"

   app_config:
      name: "arn:aws:secretsmanager:us-east-2:0123456789:secret:beta/app-config-sODUXp"
      external: true
```

And in my running container see the following files, the content of each being the value stored in SecretsManager:

```
# ls -lR /run/secrets/
/run/secrets:
total 4
-rw-r--r-- 1 root root 2345 Feb 23 14:33 app_config
drwxr-xr-x 2 root root 4096 Feb 23 14:31 credentials

/run/secrets/credentials:
total 12
-rw-r--r-- 1 root root 25 Feb 23 14:31 db1
-rw-r--r-- 1 root root 25 Feb 23 14:31 db2
-rw-r--r-- 1 root root 25 Feb 23 14:31 redis
```

The convenience of this cannot be overstated.  Note how `keys: "*"` exploded each key in the JSON value of `credentials` to its own file.  And for the configuration file, `app_config`, containing dozens and dozens of items (many containing sensitive data), can be found by may app with one environment variable:

```
APP_CONFIG=/run/secrets/app_config
```

In [compose-ecs](https://github.com/docker/compose-ecs/blob/main/ecs/secrets/Dockerfile) they created a sidecar that would do this mount.  I'm investigating if I can grab this image and use it as a sidecar with a copilot application, but meanwhile wondering:

1. Is this something copilot already has and I'm missing it?
2. If not, can something like this be added to copilot?  (Maybe ingesting the go code from `compose-ecs`?)
3. Otherwise, what are best practices for loading whole configuration files (with possibly several sensitive pieces of data) without having to create a secret for each.  Private s3 bucket?
