### DISCUSSION TITLE
How can we set the ECS Cluster name in YAML override

### DISCUSSION THREAD

**Discussion by WillGibson** [aws/copilot-cli#5745] [Q&A] [answered]
This looks legit to me in `copilot/environments/overrides/cfn.patches.yml`...

```yaml
# Set ECS Cluster name so that we can reference it in Terraform without using an external data source
- op: replace
  path: /Resources/Cluster/Properties/ClusterName
  value: !Sub '${AppName}-${EnvName}'
```

`copilot svc deploy` does nothing with it though and `copilot env deploy` says...

```
deploy environment tf-will: generate template: override template: unable to apply the "replace" patch at index 0: key "/Resources/Cluster/Properties": "ClusterName" not found in map
```

`ClusterName` looks like the right thing in [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-clustername).

What am I missing here?
