### DISCUSSION TITLE
Why does my test env gets a `503 Service Temporarily Unavailable` but my prod does not?

### DISCUSSION THREAD

**Discussion by lominming** [aws/copilot-cli#5809] [Q&A] [answered]
- Created code pipeline and apps deployment for `test` and `prod` environments
- When I deploy, somehow `test` will go down during deployment `503 Service Temporarily Unavailable` but my prod does not

How do I ensure that my ECS does not go down during deployments?

**Comment by iamhopaul123** [comment]
Hey @lominming. Do you have different configuration for `test` and `prod`? Usually during deployment your ECS service won't go down because old tasks won't be tore down until new tasks are stable. Can you share you service manifest file here?

**Reply by lominming** [reply]
This is the `app/manifest.yml` file:

```
# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: app
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  path: '/'
  alias: ['example.com', 'www.example.com']

# Configuration for your containers and service.
image:
  build: app/Dockerfile.prod
  port: 3000


cpu: 4096
memory: 16384
platform: linux/x86_64 
# count: 1       # Number of tasks that should be running in your service.
count:
  range: 1-5
  cooldown:
    in: 60s
    out: 30s
  cpu_percentage: 70
  requests: 30
  response_time: 2s
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.

variables:
  NODE_ENV: production

# You can override any of the values defined above by environment.
environments:
  prod:
    variables:
      AWS_ENV: prod
  test:
    variables:
      AWS_ENV: test
    cpu: 2048
    memory: 4096
    count: 1                # Number of tasks to run for the "test" environment.
    deployment:             # The deployment strategy for the "test" environment.
      rolling: 'recreate'   # Stops existing tasks before new ones are started for faster deployments.
    http:
      path: '/'
      alias: ['test.openexus.com']
      healthcheck:
        path: '/'
        unhealthy_threshold: 5
        interval: 60s
        timeout: 30s
        grace_period: 240s
```
