### DISCUSSION TITLE
Using Volumes to copy files from Sidecar to root volume of Essential Container

### DISCUSSION THREAD

**Discussion by tonydekeizer** [aws/copilot-cli#5964] [Q&A]
We have an existing docker compose environment we are trying to move to Copilot.
The following snippet of the docker compose file represents a basic overview of the process i.e
Run a container that generates some files using a script (in this case a war file) and copy that to the main containers tomcat webapps folder which then starts up when this has been completed successfully.

```
services:
  application-init:
    env_file:
      - application.env
    image: XXXXXXXXXbootstrap:latest
    volumes:
      - tomcat:/tomcat
  application:
    env_file:
      - application.env
    image: tomcat:latest
    volumes:
      - tomcat:/usr/local/tomcat
    depends_on:
      application-init:
        condition: service_completed_successfully
```

I am trying to move the deployment to ECS using copilot and I need some advice on how to replicate this process.  
I am aware that I can use a sidecar to do the application-init component and exit and make the essential container dependent on the sidecar's successful exit but I am unsure how to define the volumes correctly. 

Can a sidecar access the root volume of the main container ?
Can it copy files into this volume ?
How do I define the storage and mount_points directives in copilot to acheive this ?

Any advice would be greatly appreciated.  :-)

Cheers
Tony
