### DISCUSSION TITLE
Connecting to existing RDS postgres server

### DISCUSSION THREAD

**Discussion by mooktakim** [aws/copilot-cli#6028] [Q&A]
Hi,

I am trying to allow connecting to an existing RDS server, but I am having a hard time.
I tried to deploy to the existing VPC to help with this, if there's a way to not do this, please let me know.

Security Groups:
- `application-servers` - included this in copilot config
- `database-servers` - allows inbound PostgresSQL port access from `application-servers`. RDS server has this security group.

`copilot/environments/production/manifest.yml`:
```yaml
name: production
type: Environment

network:
  vpc:
    id: 'vpc-02506b063f5c12113'

observability:
  container_insights: false
```

`copilot/web/manifest.yml`:
```yaml
name: web
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck: '/up'

image:
  build: Dockerfile
  port: 3000

cpu: 512       # Number of CPU units for the task.
memory: 1024   # Amount of memory in MiB used by the task.
platform: linux/x86_64  # See https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform
count: 1       # Number of tasks that should be running in your service.

exec: true     # Enable running commands in your container.
network:
  vpc:
    security_groups:
      - 'sg-043aeda513a7f3da8' # application-servers group
```

In the application I am using the connection endpoint URL `appdb.xxx123.eu-west-2.rds.amazonaws.com`.

I just can't see why it wouldn't connect. Its timing out every time.
I could setup rds from copilot yes, but I need this db to be separate.
