### ISSUE TITLE
storage init: DDB with no LSE includes empty LSE section in the template

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1072]
If I run storage init for a DDB table:
```
[rear-window-fe] copilot storage init                                                                                             master  ✗ ✭ ✱
Only found one service in workspace, defaulting to: fe
Storage type: DynamoDB
Storage resource name: game
Partition key: game_id
Partition key datatype: String
Sort key? No
✔ Wrote CloudFormation template for DynamoDB Table game at copilot/fe/addons/game.yml
```

The generated CF looks like this:

```yaml
  game:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub ${App}-${Env}-${Name}-game
      AttributeDefinitions:
        - AttributeName: game_id
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: game_id
          KeyType: HASH
      LocalSecondaryIndexes:
```

The empty `LocalSecondaryIndexes` isn't valid and causes the deployment to fail.
