### ISSUE TITLE
Missing docs related to importing externally defined secrets from parameter store

### ISSUE THREAD

**Issue by FarmaanElahi** [aws/copilot-cli#1121]
V0.1.0 has breaking change where it now requires any parameter from parameter store to have 2 specific tags defined . Those are `copilot-application` and `copilot-environment`. 

Value for `copilot-application` and `copilot-environment` should be same as `app` name `env` name defined in the cli

**Comment by FarmaanElahi** [comment]
Generated cloudformation snippet
```
- PolicyName: !Join ['', [!Ref AppName, '-', !Ref EnvName, '-', !Ref ServiceName, SecretsPolicy]]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ssm:GetParameters'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
                Condition:
                  StringEquals:
                    'ssm:ResourceTag/copilot-application': !Sub '${AppName}'
                    'ssm:ResourceTag/copilot-environment': !Sub '${EnvName}'
              - Effect: 'Allow'
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
                Condition:
                  StringEquals:
                    'secretsmanager:ResourceTag/copilot-application': !Sub '${AppName}'
                    'secretsmanager:ResourceTag/copilot-environment': !Sub '${EnvName}'
```
