### ISSUE TITLE
Instructions on using EFS / S3 are unclear

### ISSUE THREAD

**Issue by izaacdb** [aws/copilot-cli#1166]
I've read through `https://github.com/aws/copilot-cli/wiki/Additional-AWS-Resources` which doesn't really explain how to use Amazon file systems. Can anyone provide examples of EFS / S3 configurations?

**Comment by AmitBaranes** [comment]
+1

**Comment by efekarakus** [comment]
Heya! We just released [v0.2.0](https://github.com/aws/copilot-cli/releases/tag/v0.2.0) which introduced a new command `storage init` that should make creating an S3 bucket easier! Can you give it a try and let us know if it helps solve your usecase?

For EFS, we have a task that's in the backlog https://github.com/aws/copilot-cli/issues/948 to enable overriding the task definition for [efs volumes](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html) however we haven't started working on it yet.

**Comment by bvtujo** [comment]
Hi @izaacdb! This template is accessible through the newly released `copilot storage init` command. You can run the following:

```bash
$ copilot storage init --svc frontend --name user-data-bucket --storage-type S3
```
to create an S3 bucket named "user-data-bucket" associated with and accessible by the "frontend" service in this sample. 

Under the hood, the `storage init` command populates the template you've linked and writes it to the `copilot/<service>/addons` folder. Then, when you run `copilot svc deploy`, we'll create the bucket for you and inject an environment variable containing the bucket's name into your service container so it's easy for your code to access. 

EFS is a bit more involved and isn't supported yet, since as Efe said we'll need to enable task definition overrides in the manifest in order to allow your services to mount the right volumes before we can programmatically generate the CF for you with `storage init`.

**Comment by devvaneio** [comment]
Can I use a existing S3 bucket?

**Comment by efekarakus** [comment]
Heya @lusatiro,

You should be able to! 
1. You can provide your bucket name as [an environment variable in the manifest](https://aws.github.io/copilot-cli/docs/developing/environment-variables/)
2. You can add an an [addon with the necessary permissions](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) to access the bucket:
```yaml
# under ./copilot/<svcName>/addons/s3-permissions.yml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  MyAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectACL
              - s3:PutObjectTagging
              - s3:DeleteObject
              - s3:RestoreObject
            Resource: <YOUR_BUCKET_ARN>
          - Sid: S3ListAction
            Effect: Allow
            Action: s3:ListBucket
            Resource: <YOUR_BUCKET_ARN>
Outputs:
  MyAccessPolicyARN:
    Value: !Ref MyAccessPolicy
```
This will attach the `MyAccessPolicy` to your ECS Task Role to access the S3 bucket
