### ISSUE TITLE
Support using an image rather than a Dockerfile in the build section

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1177]
Right now, customers need to have a local Dockerfile/code to deploy their services. We've heard a few times that some customers want to deploy an already published image rather than having to build locally. 

In the future perhaps we can support something like

```yaml
image:
  # Location of existing image
  name: kohidave/my-published-image
  # Port exposed through your container to route traffic to it.
  port: 8080
```
