### ISSUE TITLE
Support sticky sessions for LB Web Service

### ISSUE THREAD

**Issue by stephentuso** [aws/copilot-cli#1271]
I'm having trouble finding anything in issues or documentation about:

 - Enabling HTTPS on the ALB
 - Enabling sticky sessions

Is it possible to configure those through copilot?

**Comment by efekarakus** [comment]
Heya @stephentuso !

For HTTPS, we support it with the `--domain` flag while running `app init` (https://github.com/aws/copilot-cli/wiki/app-init-command#what-are-the-flags). Our teammate @kohidave wrote an extensive guide here on how to set it up: https://github.com/kohidave/dns-and-lb-copilot-demo

Unfortunately, we don't support sticky sessions atm, I've marked it as a feature request.

**Comment by tam0ri** [comment]
I'll try to implement the feature. Currently I plan to add a new property into manifest as below:

```yaml
name: front-end
type: Load Balanced Web Service

image:
  # Path to your service's Dockerfile.
  build: ./Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 8080

http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/"
  # healthcheck: '/'
  stickiness_duration: 86400
```

If there is better way to change manifest, please suggest it.

**Comment by efekarakus** [comment]
Heya @git823 ! :wave:

That'd be amazing! I think that mostly looks good, what do you think of the following:
```yaml
# The http.stickiness section should be optional and accept both of these different formats:

# Basic:
http:
  stickiness: true # Uses the default 1day duration.

# Advanced:
http:
  stickiness:
     duration: 24h # Accepts the basic https://golang.org/pkg/time/#ParseDuration units ("s", "m", "h")
```

The reason why I'm thinking of providing Option 1. is because when we support NLB as a load balancer instead of ALB, then there won't be a duration field so to provide a common `stickiness` interface across load balancer types we can make duration to be a subfield of `stickiness`.

Does that make sense?

**Comment by tam0ri** [comment]
It looks nice! On the other hand, I think it seems to be strange a bit because manifest schema is not fixed. In Option 1, the type of stickiness is boolean, but the type of stickiness is object in Option 2. What do you think about the following example? 

```yaml
http:
  stickiness:
     enabled: true
     duration: 24h # Accepts the basic https://golang.org/pkg/time/#ParseDuration units ("s", "m", "h").
```

stickiness.enabled might be redundant, but the type becomes fixed from manifest schema perspective. If users don't specify stickiness.duration, Copilot assumes default value.

**Comment by efekarakus** [comment]
Gotcha yeah that also makes sense 😄 
I proposed those two options because we're trying to expose difficult settings progressively with the CLI. For example, we did that for the `image.build` field: https://github.com/aws/copilot-cli/wiki/Services#build

```yaml
image:
  build: path/to/dockerfile

# Or

image:
  build:
    dockerfile: path/to/dockerfile
    context: context/dir
    args:
      key: value
```

What do you think of just starting with the following? we can release that first and see if anyone asks to customize the duration. If they do then we can add option2.
```yaml
http:
  stickiness: true # Uses the default 1day duration.
```
