### ISSUE TITLE
Add DocumentDB support

### ISSUE THREAD

**Issue by aumanjoa** [aws/copilot-cli#1402]
Hi,

Great CLI! 
Please add support for DocumentDB.

Is there a workaround to use DocumentDB already?

**Comment by kohidave** [comment]
Hi there! You can add a DocumentDB to a service by using the addons feature: https://github.com/aws/copilot-cli/wiki/Additional-AWS-Resources

You just need the CloudFormation for a DocDB and the next time you deploy, copilot will provision it!

**Comment by aumanjoa** [comment]
@kohidave may you can help me. I try to create my documentDB as addon but I always get this error:
>  ERROR: json: cannot unmarshal string into Go struct field .DependsOn of type []string

My yaml file looks like this:

```
Resources:
  DBCluster:
    Type: "AWS::DocDB::DBCluster"
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: "testsapicluster"
      MasterUsername: "uperusername"
      MasterUserPassword: "superSecurePassword"
  DBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: "test-api-instance"
      DBInstanceClass: "db.r5.large"
    DependsOn: DBCluster
  
Outputs:
  # 2. If you want to inject a property of your resource as an environment variable to your ECS task,
  # then you need to define an output for it.
  #
  # For example, the output MyTableName will be injected in capital snake case, MY_TABLE_NAME, to your task.
  ClusterId:
    Value: !Ref DBCluster
  ClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint
  ClusterReadEndpoint:
    Value: !GetAtt DBCluster.ReadEndpoint
  ClusterPort:
    Value: !GetAtt DBCluster.Port
  InstanceId:
    Value: !Ref DBInstance
  InstancePort:
    Value: !GetAtt DBInstance.Port
  InstanceEndpoint:
    Value: !GetAtt DBInstance.Endpoint
```

I have run this template via Cloudformation in the console, it worked fine there

**Comment by efekarakus** [comment]
heya @aumanjoa, that's very strange that the YAML parser is erroring on the `DependsOn` statement. We'll keep investigatingg. In the mean time to unblock you, you can actually remove the `DependsOn: DBCluster` line and the addon stack will deploy successfully (tried it out locally)

**Comment by efekarakus** [comment]
Heya @aumanjoa, with the template above if you change: `DependsOn: DBCluster` to `DependsOn: [DBCluster]` it should work for now. The reason is that the underlying library that we use [goformation](https://github.com/awslabs/goformation/) seems to expect the DependsOn field to be a list of strings instead of a single value.

**Comment by Voyen** [comment]
Is there some way to specify which VPC addon resources get created in?
I'm trying to create a DocumentDB resource much like this example, however the service this addon is for is failing to connect since the cluster gets created in the default VPC but the service goes into the copilot environment's VPC.

**Comment by efekarakus** [comment]
Hi @Voyen 👋 

Yes, there is a way! For example, in the "Aurora" addon we do this:
https://github.com/aws/copilot-cli/blob/1732fe05a0afd8dfec63f3e241d97247dedae131/templates/addons/aurora/cf.yml#L47-L48

You can get the VPC ID like this:
https://github.com/aws/copilot-cli/blob/1732fe05a0afd8dfec63f3e241d97247dedae131/templates/addons/aurora/cf.yml#L55-L57

If you need the security group to give access to containers in your application:
```
SourceSecurityGroupId: { 'Fn::ImportValue': !Sub '${App}-${Env}-EnvironmentSecurityGroup' }
```

Each addon template needs to have the following parameters defined:
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
```
