### ISSUE TITLE
Feature request: Export load balancer ARN from the application CF template

### ISSUE THREAD

**Issue by perevernihata** [aws/copilot-cli#1434]
Currently, only PublicLoadBalancerDNSName is exported, therefore if you want to add custom listeners via addon - it is not possible without some custom resource (lambda) to find correct ALB which will be complicated. 
Should be easy to change? :) 

```
  PublicLoadBalancerArm:
    Condition: CreatePublicLoadBalancer
    Value: !GetAtt PublicLoadBalancer.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PublicLoadBalancerArn
```
Just add to this file?
https://github.com/aws/copilot-cli/blob/87308f4a50fe22dd3e8c85b9ea567bdca51053de/templates/environment/versions/cf-v1.0.0.yml

**Comment by iamhopaul123** [comment]
Hello @perevernihata. Good call! It's already on our schedule. We have a plan for adding this output after the feature of enabling users to upgrade their environment.

**Comment by bathsundeep-graticule** [comment]
@iamhopaul123 Any update on this feature? Would love to get the Load Balancer's ARN for use in an environment addons stack

**Comment by iamhopaul123** [comment]
We currently have a workaround for it: you can use [env override](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) and deploy the env with the following override file

```yaml
- op: add
  path: /Outputs/PublicLoadBalancerArn
  value:
    Condition: CreatePublicLoadBalancer
    Value: !GetAtt PublicLoadBalancer.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PublicLoadBalancerArn
```
