### ISSUE TITLE
Failed to deploy service when changing the http path

### ISSUE THREAD

**Issue by pcolazurdo** [aws/copilot-cli#1455]
Hi team,

I had one service deployed ok, but found that the path was wrong so I tried updating it and redeploying. I got the following error when doing so.

```
✘ Failed to deploy service.

✘ deploy service: wait until stack modernization-lab-test-legacy-web update is complete: ResourceNotReady: failed waiting for successful resource state
```

When looking into CloudFormation, the error is: 
```
HTTPListenerRule | UPDATE_FAILED | One or more priorities not found (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: PriorityInUse;
```

Just if it helps for reproduction, the specific part of new manifest looks like:

```
image:
  # Docker build arguments. You can specify additional overrides here. Supported: dockerfile, context, args
  build: nginx/Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

http:
  # Requests to this path will be forwarded to your service. 
  # To match all requests you can use the "/" path. 
  path: '/'
  # You can specify a custom health check path. The default is "/"
  # healthcheck: '/'
  # You can enable sticky sessions.
  # stickiness: true
```
