### ISSUE TITLE
Can't programmatically run task from task created by copilot (permissions issue)

### ISSUE THREAD

**Issue by Envek** [aws/copilot-cli#1507]
I want to run some one-off task from application running inside another ECS task created by `copilot deploy`.

To do this I've created following Managed Policy as [addon](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/):

```yaml
Resources:
  RunECSTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - ecs:RunTask
            Effect: Allow
            Resource: '*' # TODO: Get ARN of cluster somehow (we have only its ID in outputs)
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: '*'

Outputs:
  RunECSTaskPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role to run auxiliary one-off ECS tasks"
    Value: !Ref RunECSTaskPolicy
```

`iam:PassRole` is required as per [ECS guide for IAM roles for tasks](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-iam-roles.html).

However, copilot also creates inline policy `DenyIAMExceptTaggedRoles` which denies all IAM operations:

https://github.com/aws/copilot-cli/blob/d70f8cc1eb7f920748e176cc08b06e2abd20fc77/templates/workloads/common/cf/taskrole.yml#L13-L19

And as [`Deny` is always takes precedence over `Allow`](https://serverfault.com/a/1004624) I'm getting `AccessDeniedException` in response for `RunTask` API request. Output from CloudTrail:

```
    "eventSource": "ecs.amazonaws.com",
    "eventName": "RunTask",
    "awsRegion": "ap-northeast-1",
    "userAgent": "aws-sdk-nodejs-v3-@aws-sdk/client-ecs/1.0.0-gamma.11 linux/v12.18.4 exec-env/AWS_ECS_FARGATE",
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::account:assumed-role/app-env-svc1-TaskRole-1DRA7DPG1VH1L/1efbfbd886dd4c10bd943a9a2f57773e is not authorized to perform: iam:PassRole on resource: arn:aws:iam::account:role/app-env-svc2-ExecutionRole-ALJBQ921DFEQ with an explicit deny",
```

If I drop `DenyIAMExceptTaggedRoles` inline policy manually via AWS web console then request will succeed and task will be run successfully.

**Questions:**
 1. Is there a way to workaround this explicit deny without forking and building my own version of copilot? 
 2. Why this explicit deny for Task Role is needed after all?
 3. Can we remove inline policy and suggest users to create ManagedPolicy by their own instead?

**Comment by bvtujo** [comment]
Hi @Envek, thanks so much for the detailed issue. Could we get a few more details about your use case (i.e. is the one-off task run on a schedule from within the container, in response to a load balancer metric, or in response to some sort of event from the service code or CloudWatch)? 

That will really help us understand how we can help you with a workaround. 

To answer some of your questions, we add the explicit Deny so that tasks using the Copilot task role can only assume other roles created with Copilot. This was done due to security concerns from penetration testers: if, for instance, a task is compromised and someone gains remote code execution, there can be no privilege escalation--since the rogue task can only assume other roles which were created by Copilot, it can't get access to your Admin role or roles with access to other sensitive data. 

We don't recommend modifying the policies that Copilot generates, as they've undergone pretty rigorous security reviews, but we definitely want to find out how we can support your use case!

**Comment by Envek** [comment]
>  Could we get a few more details about your use case (i.e. is the one-off task run on a schedule from within the container, in response to a load balancer metric, or in response to some sort of event from the service code or CloudWatch)?

None of those. This one-off task intended to be run in response to user action.

E.g. application user presses kind of “Start” button somewhere in application's UI which (among other things) starts resource-heavy ECS task until “Stop” button will be pressed by the user (or timeout expires).

For now, I have two copilot-generated services:
 1. Main load balanced service (let's call it `app`) which provides UI, REST API and implements business logic.
 2. Auxiliary backend service (let's call it `streamer`) with `count: 0`. This is one-off tasks I want to `runTask` and `stopTask` when my app users perform some actions in the `app` service.
    _It's a bit hacky, but it is convenient to let copilot build Dockerfile, push image to ECR and create task definition which will be used in `runTask` API later by single `copilot svc deploy` command._

>  we add the explicit Deny so that tasks using the Copilot task role can only assume other roles created with Copilot.

 1. Why explicit Deny is needed for that? It will be implicitly denied unless I will create allowing policy in addons by myself.
 2. But I'm trying to launch task which definition and roles _are_ created with copilot.

**Comment by Envek** [comment]
Worked around this by using [Step Functions to run ECS tasks](https://docs.aws.amazon.com/step-functions/latest/dg/sample-project-container-task-notification.html).

Aside from fixing permissions problem (as starting execution of step function doesn't require `iam:PassRole`), it also allows to restart tasks on failure and terminate on timeout (and gives control on restarts and timeouts), so it even feels more correct despite big increase in complexity.

<details>
  <summary>Here is code samples for those who interested.</summary>

Copilot [addon](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) file `copilot/app/addons/task-execution-stuff.yml`:

```yml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt 'StateMachineRole.Arn'
      DefinitionString: !Sub
      - |
        {
          "Version": "1.0",
          "Comment": "Run AWS Fargate task",
          "TimeoutSeconds": ${Timeout},
          "StartAt": "Run Fargate Task",
          "States": {
            "Run Fargate Task": {
              "Type": "Task",
              "Resource": "arn:aws:states:::ecs:runTask.sync",
              "Parameters": {
                "LaunchType": "FARGATE",
                "PlatformVersion": "LATEST",
                "Cluster": "${ClusterArn}",
                "TaskDefinition": "${TaskDefinition}",
                "NetworkConfiguration": {
                  "AwsvpcConfiguration": {
                    "Subnets": ["${Subnets}"],
                    "AssignPublicIp": "${AssignPublicIp}",
                    "SecurityGroups": ["${SecurityGroups}"]
                  }
                },
                "Overrides": {
                  "ContainerOverrides": [
                    {
                      "Name": "streamer",
                      "Environment": [
                        { "Name": "MEETING_URL", "Value.$": "$.meetingUrl" },
                        { "Name": "STREAMING_URL", "Value.$": "$.rtmpUrl" }
                      ]
                    }
                  ]
                }
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "States.ALL"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": ${Retries},
                  "BackoffRate": 1.5
                }
              ],
              "End": true
            }
          }
        }
      - Timeout: 21600 # 6 hours
        Retries: 5
        TaskDefinition: !Sub "${App}-${Env}-streamer"
        ClusterArn:
          Fn::Sub:
            - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterID}
            - ClusterID:
                Fn::ImportValue:
                  !Sub '${App}-${Env}-ClusterId'
        Subnets:
          Fn::Join:
            - '","'
            - - Fn::Select:
                - 0
                - Fn::Split:
                  - ','
                  - Fn::ImportValue: !Sub '${App}-${Env}-PublicSubnets'
              - Fn::Select:
                - 1
                - Fn::Split:
                  - ','
                  - Fn::ImportValue: !Sub '${App}-${Env}-PublicSubnets'
        AssignPublicIp: 'ENABLED'
        SecurityGroups:
          Fn::ImportValue:
            !Sub "${App}-${Env}-EnvironmentSecurityGroup"

  StateMachineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'states.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: StateMachine
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: '*'
            # - !GetAtt TaskExecutionRole.Arn
            # - !GetAtt TaskRole.Arn
          - Effect: Allow
            Action: 'ecs:RunTask'
            Resource: '*' # ARN needed !Sub "${App}-${Env}-streamer"
            Condition:
              ArnEquals:
                'ecs:cluster':
                  Fn::Sub:
                    - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterID}
                    - ClusterID:
                        Fn::ImportValue:
                          !Sub '${App}-${Env}-ClusterId'
          - Effect: Allow
            Action:
            - 'ecs:StopTask'
            - 'ecs:DescribeTasks'
            Resource: '*'
            Condition:
              ArnEquals:
                'ecs:cluster':
                  Fn::Sub:
                    - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterID}
                    - ClusterID:
                        Fn::ImportValue:
                          !Sub '${App}-${Env}-ClusterId'
          - Effect: Allow
            Action:
            - 'events:PutTargets'
            - 'events:PutRule'
            - 'events:DescribeRule'
            Resource: !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule'

  # policy for app's task role to start execution of step function (which will run task with a streamer)
  StreamerRunPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - states:ListExecutions
            - states:StartExecution
            Effect: Allow
            Resource: !Ref StateMachine
          - Action:
            - states:DescribeExecution
            - states:StopExecution
            Effect: Allow
            Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:*:*"

Outputs:
  StreamerStepFunction:
    Description: "The ARN of the StateMachine which will start and monitor ECS task with streamer."
    Value: !Ref StateMachine
  StreamerRunPolicy:
    Description: "The ARN of the ManagedPolicy to attach to the task role to run ECS tasks with streamer."
    Value: !Ref StreamerRunPolicy
  AwsRegion:
    Description: "Current AWS region where app is running"
    Value: !Sub "${AWS::Region}"
```

And how to use it via [AWS SDK JS v3](https://github.com/aws/aws-sdk-js-v3):

```typescript
import { SFN } from "@aws-sdk/client-sfn";
import { v4 as uuid } from "uuid";

const client = new SFN({ region: process.env.AWS_REGION });

const response = await client.startExecution({
  stateMachineArn: process.env.STREAMER_STEP_FUNCTION,
  name:  `entity-${entityId}-${uuid()}`, // Every execution name must be unique
  input: JSON.stringify({ meetingUrl: "https://example.com", rtmpUrl: "rtmp://user:pass@example.com/app/stream" }),
});
```
</details>
