### ISSUE TITLE
feature request: ALB supports Host Header

### ISSUE THREAD

**Issue by snowsky** [aws/copilot-cli#1515]
Copilot only supports "Path Pattern" now. We got a requirement to add a host header to ALB rule. Can the cloudformation resource codes be customized to do do?

**Comment by kohidave** [comment]
Hi! Thank you so much for reaching out :D 

So host headers work best if your ALB has a custom DNS name. If you configure your [app](https://aws.github.io/copilot-cli/docs/concepts/applications/#additional-app-configurations) with a DNS name - then Copilot will switch to using `host` based routing. 

Your endpoints will go from:
`http://alb-generated-url.elb.us-east-1.amazonaws.com/service-name` to 
`https://service-name.env-name.app-name.domain` (we'll also generate an ACM cert for you)

Which uses host header routing. 

We also have some plans to extend exactly how that routing works: #1188 

Hope that helps!

**Comment by snowsky** [comment]
Thanks @kohidave for the prompt response and sorry for my late follow-up 👍 

A quick question, how could I configure to add a header in routing rules?

**Comment by iamhopaul123** [comment]
Hello @snowsky. Sorry for the late reply. For now within Copilot you can't add a header to the routing rules. However, you might find it helpful to use the ec2 console to manually add a header routing rule to the ALB listener.

**Comment by snowsky** [comment]
Thanks @iamhopaul123 for the update. Is there any plan to add this feature?

**Comment by iamhopaul123** [comment]
Can I ask why you want to add a host header to the rule? If it is because you want a custom domain name, then yes we plan to enhance our current default domain name. We might allow users to give aliases to the default domain or give custom domain name.

**Comment by snowsky** [comment]
yes, got the same thought to have a custom domain name.

**Comment by imaginarynik** [comment]
Is this still the case? I wish to add header based listener rule to route traffic to a dedicated service/task...
any clue, guys?

**Comment by Lou1415926** [comment]
@imaginarynik Hello 👋🏼 I will respond in this issue as this one seems more similar to your use case. Related: https://github.com/aws/copilot-cli/issues/2817.

If you simply want the traffic to be routed to, say,the service "web", then you can use the [`alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) field.

Copilot will automatically generate a template with [the desired host-header configuration](https://github.com/aws/copilot-cli/blob/9e603256b49561fd894942040286d160ee4d70bb/internal/pkg/template/templates/workloads/partials/cf/https-listener.yml#L107) to achieve your goal.

**Comment by imaginarynik** [comment]
@Lou1415926  thank you for responding. I appreciate it. The config I want is that: all the traffic to my ALB goes through the regular listener rule to say, XYZ tasks. Now, I want that if the traffic happens to contain "crazy=1" header (not the host-header, I think, but just the regular HTTP header), then it should be routed to a different set of tasks (which are similar to other tasks, but dedicated to handle this crazy traffic). This seems a bit complicated to do with Copilot.

**Comment by imaginarynik** [comment]
@bvtujo Would you be able to help add custom-headers to this? I would really appreciate it ^_^

**Comment by Lou1415926** [comment]
@imaginarynik  In general, you can use yaml patch to do this. For example, you could have ⬇️
```yaml
- op: add
  path: Resources/HTTPListenerRuleByHttpHeader
  value: 
      Metadata: 'aws:copilot:description': 'An HTTP listener rule for path `/` that forwards HTTP traffic to your tasks'
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
          - TargetGroupArn:# The target group for XYZ 
          Type: forward
        Conditions:
          - Field: 'http-header'
            HttpHeaderConfig: #... your config
      ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
      Priority: !GetAtt HTTPRulePriorityAction.Priority
```
