### ISSUE TITLE
Docker build args sourced from Shell environment variables

### ISSUE THREAD

**Issue by flyinprogrammer** [aws/copilot-cli#1599]
So we'd like to have copilot source environment variables from the shell that copilot is run in as build arguments into the docker build command. And it either already does this, and I am dumb, or it does not.

In my mind some form of the following might work:

manifest.yml:
```yaml
image:
  build:
    dockerfile: path/to/dockerfile
    context: context/dir
    args:
      SECRET_PASSWORD: {{ .Env.SECRET_PASSWORD_IN_SHELL_ENV }}
```

In my shell:

```bash
export SECRET_PASSWORD_IN_SHELL_ENV="ssshthisissecret"
copilot deploy
# at some point this would happen:  docker build -f Dockerfile --build-arg SECRET_PASSWORD=ssshthisissecret
```

I thought maybe, perhaps, we were clever and ran the manifest file through go template before shoving it into a struct, but i'm either stupid, or we aren't doing this? Happy to provide a PR and shame on me for not running this in a debugger before opening this issue, but alas here we are.

**Comment by bvtujo** [comment]
Hey @flyinprogrammer, you're right that Copilot doesn't do this currently. This is a super interesting use case though, so thank you so much for bringing it to our attention. 

Also, you're right that we run `docker build` under the hood and it's not great to require that you expose your secrets in the manifest if you have to pass them in as build args.

Depending on your use case, though I can think of a couple of workarounds of varying complexity that will allow you to keep using Copilot for infrastructure management 😄 

##### If you need secrets inside your deployed container:
We recommend you use SSM and the [`secrets` section of the manifest](https://aws.github.io/copilot-cli/docs/developing/secrets/) to specify credentials that you need to access from inside your running containers. 

##### If you need secrets from the terminal environment as build arguments
You can run `docker build` manually using whatever environment variables suit you, then use the [`image.location` field of the manifest](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location) to specify an external repository (Dockerhub or ECR, both work 😄 ) from which to grab the built secret-containing image. 

HUGE CAVEAT that if you do this, be really careful not to specify any secrets in the `variables` section of the manifest as they'll be exposed as plaintext in the Environment Variables section of the Container Definition inside the Task Definition on the AWS console. 

Do either of those work for you?

**Comment by flyinprogrammer** [comment]
> This is a super interesting use case though, so thank you so much for bringing it to our attention.

Yah, the primary use case is that we have private python/java repos that tools like pip and gradle need access to at build time, as we build our code in the container. Building our image outside of Copilot seems reasonable for now.

>  image.location

So this would require us to manage the version in the manifest.yaml file - which is fine, but it still might be nice to have a way to make that dynamic since most of our use cases already have CI tools providing Git hashes and Tag names as environment variables. At some point it might be nice to have copilot acknowledge these ideas as Default Environment variables, but perhaps it's out of scope.

I'll close this for now as your backlog of issues will either force this requirement naturally, or it will be able to be delayed indefinitely, which is no problem either way.

**Comment by aaroncarlucci** [comment]
I would also like to see this feature.

**Comment by perevernihata** [comment]
bump on this one, things like nextjs require build time env vars, hence deploying from local using `copilot deploy` becomes impossible

**Comment by zackdotcomputer** [comment]
Same here and could love to see this issue reopened @flyinprogrammer since, backlog or no, this is a real issue for anyone who needs a secret build arg (such as an access token to a private package repo).

**Comment by tsingh2k15** [comment]
same here, I was looking to be able to pass ARTIFACT_VERSION (not a secret) as build args. The point here is that ARTIFACT_VERSION has to be read from a source of truth and could not be hardcoded in the manifest file. I am looking to be able to specify something like below:

```
image:
  build:
    dockerfile: path/to/dockerfile
    context: context/dir
    args:
      ARTIFACT_VERSION: {{ get_artifact_version() }} // invocation to a specific script -  shell, python, groovy...
```

Could this be supported? or is it already supported?

**Comment by iamhopaul123** [comment]
Hello @tsingh2k15 it is not supported yet. Reopen this issue as it gains more popularity.

**Comment by tsingh2k15** [comment]
@iamhopaul123 thank you for considering this! 

On another note, it would also be easier if `copilot svc deploy` could allow me to pass build-args. What do you think about that as another alternative? Specifying args in the manifest file and having the values assigned programmatically might not be always that easy for every user.

**Comment by iamhopaul123** [comment]
@tsingh2k15 Good question. Normally we don't want to spam our flag set by adding any field that's already available in our manifest. However, if there does exist loads of users wanting to add the flag we'll reconsider about it!

**Comment by iamhopaul123** [comment]
Hello friends! We have a proposal for supporting manifest env vars in #2912. Feel free to check it out and leave your thought on it. Appreciate for your input on this features 🙇

**Comment by efekarakus** [comment]
Hi all! The feature is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳

To learn more: https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/

**Comment by tsingh2k15** [comment]
> Hi all! The feature is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳
> 
> To learn more: https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/

awesome! I tried it and it works like charm.

**Comment by afgallo** [comment]
Hi @efekarakus and @iamhopaul123 ,

I've been struggling with an issue that I can't really tell exactly why it is happening but will try to explain below:

1. I have a front-end service which is a React SPA app
2. I can deploy this service on my local computer via `copilo svc deploy`
3. My manifest file contains build args that are passed in to docker which in turn uses them to build the front-end application (see an extract below). These build args are env variables set in my shell with `export VAR_X = value`
4. When I take the same approach in my CI/CD tool of choice (Github Actions), copilot deploys my service successfully (i.e it doesn't complain the env variables are missing), however, my React front-end app is built with no env variables available. This means things like `process.env.VAR_X` have no values at all!

This is super strange and I can't tell what is wrong. Your help would be very much appreciated. Please let me know if this can be expedited by raising support tickets as we have access to AWS Business Support.

Thanks!

```
image:
  build:
    dockerfile: packages/app/Dockerfile
    context: packages/app
    args:
      VAR_X ${VAR_X}
      VAR_Y: ${VAR_Y}
```

**Comment by Lou1415926** [comment]
Hello @afgallo ! Am I correct that in your Github Actions CICD environment,  you are also using `copilot svc deploy`?

**Comment by afgallo** [comment]
> Hello @afgallo ! Am I correct that in your Github Actions CICD environment, you are also using `copilot svc deploy`?

Yes, @Lou1415926

**Comment by Lou1415926** [comment]
Gotcha! Yeah totally agree that it's weird... Normally, Copilot would complain if `VAR_X` isn't found as an environment variable 🤔 

Is `copilot svc deploy` executed in a bash script in your GitHub Actions?

**Comment by afgallo** [comment]
> 

No, straight from my workflow file @Lou1415926 :

```
      - name: 🛠 Build & Deploy Api
        run: copilot svc deploy -e env_name -n service_name -a app_name
```

Are there any alternatives to the way I'm currently deploying? Is this best practice? Are there other commands? Should I build the docker image manually? We are very stuck with this issue and would like help please 🙏🏻

**Comment by Lou1415926** [comment]
> Are there any alternatives to the way I'm currently deploying? 

I don't see an issue with your current approach - using GitHub Actions for CICD, and running `copilot svc deploy` as a step. 

To add environment variable to your container though, you can use [`variables`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#variables) section or [`secrets`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#secrets) section if it's sensitive information. That is, if you write
```
image:
  build: 
     dockerfile: Dockerfile
variables:
  VAR_X: ${VAR_X}
```
your React front-end should be able to access `VAR_X` via. `process.env.VAR_X`.

I think this will be the best thing to try right now!

---
> copilot deploys my service successfully (i.e it doesn't complain the env variables are missing)

Regarding this issue - that Copilot doesn't complain the env var being missing when interpolating your manifest with shell variables - I am not able to reproduce it. I can share my attempt here:

I tried setting up a GitHub Action on my own repo like this
```yaml

# env: no environment variables

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup AWS Copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.19.0/copilot-linux && \
          chmod +x copilot-linux && \
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Deploy
        run: copilot svc deploy --name api
```
where the manifest for `api` contains:
```yaml
image:
  build:
    dockerfile: Dockerfile
    args:
      VAR_X: ${VAR_X}
      VAR_Y: ${VAR_Y}
```

The result of this GitHub Actions execution is (as expected):
```
Run copilot svc deploy --name api
Only found one environment, defaulting to: test
Environment test is already on the latest version v1.10.1, skip upgrade.
✘ interpolate environment variables for api manifest: environment variable "VAR_X" is not defined
```

**Comment by afgallo** [comment]
Hi @Lou1415926 thanks for your reply. That is interesting. I was under the impression I only need `args` as the react app only needs those variables at _build time_ as opposed to _run time_. 

In your example above, I cannot see you setting `VAR_X` and `VAR_Y` in your script before calling copilot. That's why you are not able to repro the behaviour I have.

**Comment by Lou1415926** [comment]
I see. Sorry I misunderstood your ask. I thought you needed them at run time. In this case, indeed you don't need `variables` section in the manifest. My apologies. 

I updated my GitHub Actions to include `env` section:
```yaml
env: # <- this is what changed
  VAR_X: myvarx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup AWS Copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.19.0/copilot-linux && \
          chmod +x copilot-linux && \
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Deploy
        run: copilot svc deploy --name api

```

where the `image` part of `api`'s manifest looks like this:
```yaml
image:
  build:
    dockerfile: web/Dockerfile
    args:
      VAR_X: ${VAR_X}
  port: 8080
```
and for the `Deploy` stage, I have this output
```
> Run copilot svc deploy --name api
Only found one environment, defaulting to: test
Environment test is already on the latest version v1.10.1, skip upgrade.
Building your container image: docker build -t <my account ID>.dkr.ecr.us-east-1.amazonaws.com/gh-actions-expr/api --platform linux/amd64 --progress plain --build-arg VAR_X=myvarx /home/runner/work/example/example/web -f /home/runner/work/example/example/web/Dockerfile
```

The build arg is indeed passed as a flag `--build-arg VAR_X=myvarx`.

Does this sound contradictory to what you experienced? If possible, could you check the output of your `🛠 Build & Deploy Api` and see if the build args are passed in?

**Comment by afgallo** [comment]
Thanks, @Lou1415926. I don't get to see the same output in my logs. See below:

```
2022-06-15T05:08:47.8373134Z ##[group]Run copilot svc deploy -e xxx -n yyy -a zzz
2022-06-15T05:08:47.8373616Z [copilot svc deploy -e xxx -n yyy -a zzz [0m
2022-06-15T05:08:47.8435118Z shell: /usr/bin/bash -e {0}
2022-06-15T05:08:47.8435466Z env:
2022-06-15T05:08:47.8435779Z   REACT_APP_DEBUG_CONFIG: yes
2022-06-15T05:08:47.8437708Z   REACT_APP_COGNITO_USER_POOL_ID: ***
2022-06-15T05:08:47.8442396Z   AWS_REGION: ap-southeast-1
2022-06-15T05:08:47.8442803Z   AWS_ACCESS_KEY_ID: ***
2022-06-15T05:08:47.8443258Z   AWS_SECRET_ACCESS_KEY: ***
2022-06-15T05:08:47.8447057Z   AWS_SESSION_TOKEN: ***
2022-06-15T05:08:47.8447350Z ##[endgroup]
2022-06-15T05:08:53.7145892Z Environment dev is already on the latest version v1.10.1, skip upgrade.
2022-06-15T05:08:54.7892014Z Sending build context to Docker daemon  3.161MB
```

How can I tell copilot to output the docker build command? How did you get to print this out `Building your container image`?

**Comment by Lou1415926** [comment]
> How can I tell copilot to output the docker build command? How did you get to print this out Building your container image?

Ah my bad! I realized this was logged only when you have `platform` in manifest. If it's acceptable, you could add a `platform` field in the manifest, for example, `platform: linux/x86_64` which is the default value if you don't specify it!

I'm sorry for the churn 🙇🏼

**Comment by afgallo** [comment]
Hi @Lou1415926 I have finally found the issue ... it was to do with my docker file having multistage builds and `ARG` not being correctly used in the right scope. I hope this thread helps other people in the future 🙏🏻

**Comment by lokeshsipani** [comment]
Hi @efekarakus and @iamhopaul123,

I am struggling with a similar issue mentioned above. I am trying to build a react app which needs build time secrets.
My secrets are stored in AWS Systems Manager.

What would be the right way to pass secrets from AWS Systems Manager as build time arguments? I was trying this, but didn't work.
```
image:
  build:
    dockerfile: Dockerfile
    args:
      REACT_APP_SECRET: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/SECRET
```

How to I specify the location of my secrets to **REACT_APP_SECRET**?

Am I supposed to build an image locally and upload it to ECR and follow [Environment Variables in the Manifest](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/)?

**Comment by aaroncarlucci** [comment]
@lokeshsipani Did you make sure the SSM parameters were also tagged with `copilot-application: ${COPILOT_APPLICATION_NAME}` and `copilot-environment: ${COPILOT_ENVIRONMENT_NAME}`. When I have issues with this it's usually that.

https://aws.github.io/copilot-cli/docs/developing/secrets/

Edit: After a more careful re-read, I don't have any experience with build-time secrets, but I'm interested in the answer. My suggestion probably is not of much help.

**Comment by lokeshsipani** [comment]
Yes, I used `copilot secret init` to store secrets for different environments in my application. When I log `process.env.SECRET`, this raw text '/copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/SECRET' prints out instead of the referenced secret in the Systems Manager.

**Comment by aaroncarlucci** [comment]
@lokeshsipani Well, I haven't looked into this issue in a long time, so I hope there is a better solution someone from the team might recommend. But I solved this for our organization with a nasty hack. Here is a snippet from our pipeline's CICD task:

```
deploy-to-aws: &deploy-to-aws
  name: Build and Publish to AWS
  script:
    # insert build arguments dynamically into copilot configuration from environment variables
    - yq e '.image.build.args.SECRET_1 = env(SECRET_1)' -i copilot/app/manifest.yml
    - yq e '.image.build.args.SECRET_2 = env(SECRET_2)' -i copilot/app/manifest.yml
    # deploy
    - copilot svc deploy --name app --env $DEPLOYMENT_ENVIRONMENT
```

We are essentially re-writing the `manifest.yml` file just before the build and replacing it with environment variables set up in the CICD administration tools. It's nasty and a bit embarassing to share, but it works "alright" so far. If you find a more integrated solution, please do drop the answer here.

**Comment by lokeshsipani** [comment]
Thanks @acarlton, I am not sure if this would work for me. But, I want to avoid an additional script to insert build arguments and deploy the service.

I want copilot to read secrets from AWS Systems Manager and pass it on to docker which uses them to build the application. Eventually, I want to read it from `process.env.SECRET` from my React app.

**Comment by iamhopaul123** [comment]
Hello @lokeshsipani. We only support reading runtime secrets rather than build for now. The feature request can be tracked here https://github.com/aws/copilot-cli/issues/4230. Thank you for providing the use case and feel free to +1 for that feature request issue. And thanks @acarlton for clarifying and providing the pipeline workaround!

**Comment by lokeshsipani** [comment]
Thanks for letting me know @iamhopaul123. Does that mean the current workaround for this is I `export SECRET=abc` on the shell and add the below to manifest.yml:
```
build:
    dockerfile: Dockerfile
    args:
      SECRET: ${SECRET}
```
This in turn passes on **SECRET** to my docker which uses them to build the application.
If yes, why does [Environment Variables in the Manifest](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/) mention using `image.location`?
