### ISSUE TITLE
Ability to import docker-compose defintion and convert them as Copilot app and services

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1612]
Docker compose is commonly used for local development and testing. We need an ability for Copilot to import Docker Compose files and convert them as Copilot native app and svc objects, in a guide way. This will be a big boost for developers.

**Comment by mikelhamer** [comment]
Pretty please

**Comment by efekarakus** [comment]
Hi @mikelhamer and everyone!

Would it make sense to you if we took each service defined in the Compose file and then create a separate Copilot service with `copilot svc init`? In this scenario there would be no sidecars for any of your Copilot services.  

For images such as `postgres` would you expect it to translated into an Aurora Serverless PostgreSQL database addon or instead get an ECS service with postgres?

Thanks!

**Comment by mikelhamer** [comment]
> Would it make sense to you if we took each service defined in the Compose file and then create a separate Copilot service with `copilot svc init`? In this scenario there would be no sidecars for any of your Copilot services.

Yes that would be awesome. I don't even really understand what a sidecar is at this point so I don't have an issue with that (yet) lol.

> For images such as `postgres` would you expect it to translated into an Aurora Serverless PostgreSQL database addon or instead get an ECS service with postgres?

I would expect it to just make an ECS service with postgres. The option to turn it into an RDS cluster could be cool, but I'd rather see that effort go towards expanding the 'storage' functionality :P

This team is awesome!

**Comment by srsridharan** [comment]
> Hi @mikelhamer and everyone!
> 
> Would it make sense to you if we took each service defined in the Compose file and then create a separate Copilot service with `copilot svc init`? In this scenario there would be no sidecars for any of your Copilot services.

Yes that would work well. 


> For images such as `postgres` would you expect it to translated into an Aurora Serverless PostgreSQL database addon or instead get an ECS service with postgres?

1.  ECS service with postgres  to keep it simple.  In addition see (2) below for alternative needs that arise. 
2. if our dev ops team has setup / maintains the data ware house (e.g. using redshift, or snowflake) would it be possible to specify/map it from the docker file?

Also could we specify the VPC/subnet into which it should be launched? 

Ideally for me the goal is to move easily from dev to deployment without needing to take up a lot of dev-ops support.

Thanks for the amazing work on this.

**Comment by pharindoko** [comment]
@efekarakus  any update on this topic ?

**Comment by Lou1415926** [comment]
Hi @pharindoko! :wave: Thanks for reaching out, we unfortunately don't have a short term plan to progress on this feature request at this moment. Currently, we're working on these features on our [sprint board](https://github.com/aws/copilot-cli/projects/1). 

Meanwhile, could you tell us more how you'd like this feature to be implemented? For example, would you expect each service in the Compose file to be transformed into an ECS service or would you expect some of them to be a sidecar? 

Thanks!

**Comment by pharindoko** [comment]
Hey @Lou1415926 

I would expect them to be sidecars.
Otherwise service discovery needs to be enabled.

**Comment by piotr-szewczyk** [comment]
Is there any news about this issue? Support for docker-compose in aws copilot would really be a big deal, as running docker-compose in AWS leaves a lot to be desired

**Comment by huanjani** [comment]
Thanks, @Piotrek98, for the nudge! 

Can you give us more details on what you're hoping for? As asked above, for a Docker Compose file like
```
version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
```
would you expect `web` (and any other similar listed services) to automatically become a Copilot service? Would you want `db` to become an ECS Service with postgres or an Aurora Serverless PostgreSQL database [add-on](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) under `web`? Would you want Copilot to guess at the service type (Load Balanced Web Service, Backend, etc.) or would you rather specify it?

This would be a really cool feature; we hope to build it in a way that suits folks' needs!
