### ISSUE TITLE
Support private registry auth

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1667]
Copilot currently does not support private image repositories: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html. This is a request to add an additional field in our manifest to allow customers to provide their repository credentials.

From a customer ask on gitter:
> Hey, I checked the issues and docs - do I get it correctly Copilot doesn't support private registry authentication?

**Comment by bpottier** [comment]
Any near-future plans for implementing private registry authentication?

**Comment by efekarakus** [comment]
Hi @bpottier, we haven't started working on this task yet. Would you mind giving it a 👍 to help us prioritize the issue? Thanks!

**Comment by efekarakus** [comment]
This feature should now be possible using `taskdef_overrides` in the manifest: https://aws.github.io/copilot-cli/en/docs/developing/taskdef-overrides/

For example,
```yaml
taskdef_overrides:
- path: ContainerDefinitions[0].Image
  value: "private-repo/private-image"
- path: ContainerDefinitions[0].RepositoryCredentials
   value: { "CredentialsParameter: "arn:aws:secretsmanager:region:aws_account_id:secret:secret_name" }
```
and ensuring that arn:aws:secretsmanager:region:aws_account_id:secret:secret_name` is tagged with `copilot-application` and `copilot-environment`.
