### ISSUE TITLE
Healthcheck path not present

### ISSUE THREAD

**Issue by danieloldberg** [aws/copilot-cli#1685]
On Copilot 0.7.0.

My target group healthcheck path is empty (just '/') when deploying the following manifest:
```
http:
  healthcheck: 
    path: '/custom-path-to/healthcheck'
    healthy_threshold: 3
    unhealthy_threshold: 4
    interval: 30s
    timeout: 10s
```
The following works:
```
healthcheck: '/custom-path-to/healthcheck'
```
But I need to adjust healthcheck thresholds in order to allow my app to come online.

Have I misinterpreted the syntax or make a mistake?

Thanks!
