### ISSUE TITLE
Supply custom task role arn in service manifest conf

### ISSUE THREAD

**Issue by nikolasten** [aws/copilot-cli#1732]
What is the appropriate way to supply task role for a service definition?

I can see we have an option to do that for `copilot task run`

**Comment by efekarakus** [comment]
Heya @nikolasten !

You can add additional permissions to the task role by leveraging the [additional AWS resouces](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) feature.
For example, if you have a service named "frontend", you can add attach any `"AWS::IAM::ManagedPolicy"` to your service by creating a template at `copilot/frontend/addons/taskrole.yaml`:
```yaml
# in copilot/frontend/addons/taskrole.yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  # Define your managed policy!
  MyTableAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: my-table
Outputs:
  MyTableAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MyTableAccessPolicy
```
When you Output an IAM ManagedPolicy in your addon template Copilot automatically adds it to your task role :)

Hope this helps!
