### ISSUE TITLE
Ability to Disable Scheduled Job?

### ISSUE THREAD

**Issue by sachinahj** [aws/copilot-cli#1823]
Is there a way to disable the schedule for a scheduled job? I just want to call a fargate function from a lambda so don't need a schedule for it

**Comment by bvtujo** [comment]
Hi @sachinahj, the easiest way would be to set the [`schedule` field](https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/#on-schedule) in the manifest to a date in the past so it will never run. You can do this by using the [AWS Events native syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions), which includes an extra "year" field. For example, your manifest might look like:

```yaml
name: fargate-worker
type: Scheduled Job

image:
  build: ./worker/Dockerfile

cpu: 256
memory: 512

on:
  schedule: cron(0 0 1 1 ? 2021) # Run at midnight on January 1, 2021
                                 # This will never occur again so the job will never run
```
