### ISSUE TITLE
Adding Cloudfront addon fails 

### ISSUE THREAD

**Issue by vbarba** [aws/copilot-cli#1848]
Hi,

I am using the following template to add Cloudfront CDN in front of `Load Balanced Web Service`:

```
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName:
            Fn::ImportValue:
              !Sub "${App}-${Env}-PublicLoadBalancerDNS"       
          Id: myCustomOrigin          
          CustomOriginConfig:
            HTTPPort: 80
            OriginProtocolPolicy: http-only
        Enabled: true
        Comment: !Sub "{$App}-${Env}-${Name}"
        DefaultCacheBehavior:
          TargetOriginId: myCustomOrigin
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
```

This works when the service was deployed before, but fails if this is deployed together for the first time because the
``` 
           Fn::ImportValue:
              !Sub "${App}-${Env}-PublicLoadBalancerDNS" 
```
Is not available until de Load Balanced Service is deployed.

Do you have any advice with this situation?

Thanks

**Comment by efekarakus** [comment]
Hi @vbarba 👋 

Thanks for the issue! One way that might help mitigate the issue is possible to `sleep` in the cloudformation template before the `myDistribution` resource is created. We might be able to leverage the new [`CommandRunner`](https://aws.amazon.com/blogs/mt/running-bash-commands-in-aws-cloudformation-templates/) resource type to do this.

1. Install CommandRunner to the CloudFormation registry: https://aws.amazon.com/blogs/mt/running-bash-commands-in-aws-cloudformation-templates/

2. Add a timer resource:
```yaml
Resources:
  Waiter:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command: 'sleep 4m'

  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn: Waiter
    Properties: ...
```

3. If that works, we might be able to refine the Command to loop only until the load balancer is created. 

We'll investigate in the mean time on our end if there is a simpler solution. Sorry for the inconvenience 🙇

**Comment by kohidave** [comment]
Another option is, rather than import the DNS name, just re-construct it:
```yaml
        - DomainName:
            Fn::ImportValue:
              !Sub "${App}-${Env}-PublicLoadBalancerDNS"       
          Id: myCustomOrigin          
          CustomOriginConfig:
            HTTPPort: 80
            OriginProtocolPolicy: http-only
        Enabled: true
        Comment: !Sub "{$App}-${Env}-${Name}"
```

becomes

```yaml
        - DomainName:
            !Join
            - '.'
            - - !Ref Name
              - Fn::ImportValue:
                  !Sub "${App}-${Env}-SubDomain"
              - ""
          Id: myCustomOrigin          
          CustomOriginConfig:
            HTTPPort: 80
            OriginProtocolPolicy: http-only
        Enabled: true
        Comment: !Sub "{$App}-${Env}-${Name}"
```
