### ISSUE TITLE
Setting arbitrary attributes from SSM

### ISSUE THREAD

**Issue by kahirul** [aws/copilot-cli#1867]
Hi, I'm trying to ship log from my container to Datadog with logging sidecars
Here is how my manifest.yml look like

```
logging:
  image: amazon/aws-for-fluent-bit:latest
  destination:
    Name: datadog
    TLS: on
    apikey: <DD_API_KEY>
  enableMetadata: true
  configFilePath: /fluent-bit/configs/parse-json.conf
```  
Is it possible to set this `apikey` from `SSM`?

**Comment by iamhopaul123** [comment]
Hey @kahirul, unfortunately it is not possible yet. We'll be working on this feature to make it available.

**Comment by iamhopaul123** [comment]
Hello @kahirul,

Sorry for the previous misleading. It is actually available now because ECS has secret integration with Firelens. You can simply do sth like
```yaml
logging:
  image: amazon/aws-for-fluent-bit:latest
  destination:
    Name: datadog
    TLS: on
  enableMetadata: true
  secretOptions:
    apikey: arn:${Partition}:secretsmanager:${Region}:${Account}:secret:${SecretId}
  configFilePath: /fluent-bit/configs/parse-json.conf
```
Then store the secret in SSM before deploying the service. Let me know if it works. Thank you!
