### ISSUE TITLE
"path" is being ignored

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#1888]
I'm provisioning a load-balanced service and I have "/hook" in the manifest for the path but it creates the load balancer with just "Requests otherwise not routed", so "/" I think. I should mention that at the time of provisioning there is no service I have answering at "/".

**Comment by efekarakus** [comment]
Hi @bpottier ! 

I tried re-producing the issue but couldn't :(. I created an app, with a single load balanced web service, here is my manifest file:
```yaml
name: frontend
type: Load Balanced Web Service

image:
  build: ./Dockerfile
  port: 8080

http:
  path: 'hello'
  healthcheck: '/hello'
cpu: 256
memory: 512
count: 1
```

Note that I have updated the healthcheck setting as well to point to a valid path as I don't have a handler for `/` in my service code:
```js
'use strict';
const express = require('express');

const PORT = 8080;
const HOST = '0.0.0.0';

const app = express();
app.get('/hello', (req, res) => {
  res.send('Hello World');
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);
```

Is your setup different than this?
