### ISSUE TITLE
Exporting non default target group

### ISSUE THREAD

**Issue by perevernihata** [aws/copilot-cli#1913]
Hey guys, is there any reason to not export the non-default target group per application? I'm trying to set up a custom https listener (do not want to use a build-in one, as it autogenerates URL and SSL cert which I do not want to use). All I want is to have 
api.mywebsite.com
but if I use build-in https it will append application, environment, and (or) service name, do not remember as the last time I tried a few weeks ago.
As a simple solution I could add an addon: 
```
Resources:
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: 
        Fn::ImportValue: !Sub "${App}-${Env}-EnvironmentManagerRoleARN"
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !FindInMap [EnvironmentsMap, !Ref "Env", AcmCertificateArn]
      SslPolicy: !Ref SslPolicy
      DefaultActions:
        - Type: forward
          TargetGroupArn: ????
```
But there is no way I can get the non-default target group arn. I suspect the problem might be that on the first deployment it may not yet exist, but generally, I'm fine with it, as reprovisioning happens quite rarely, so I could add conditions to the addon
