### ISSUE TITLE
Pipeline DeployTo-prod failing with: Template format error: Unresolved resource dependencies [AddonsStack]

### ISSUE THREAD

**Issue by fuji97** [aws/copilot-cli#1966]
# Issue
I have an ECS cluster with two Load Balanced Web Services and two environments, test and prod, with a pipeline generated from copilot that deploys the application on the two environments, first on test and after on prod. When I deploy the service with two addons directly from the copilot CLI, the deploy is successful, but when I try to deploy using the pipeline, the deploy on test is successful, but the deploy on prod fails with the error:
 `Template format error: Unresolved resource dependencies [AddonsStack] in the Resources block of the template (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: xxx)`.
Only by removing all the addons seems to fix the error and let the pipeline deploy to prod successfully.

# Environment
- ECS Cluster on Fargate
- Copilot CLI v1.2.0
- Node.js v14.x
- manifest.yml
```yaml
name: backend
type: Load Balanced Web Service

image:
  build: backend/Dockerfile
  port: 80

http:
  path: 'api'
  healthcheck: '/api/v1/healthcheck'

cpu: 256
memory: 512
count: 2
```
- pipeline.yml
```yaml
name: pipeline-name

version: 1

source:
  provider: GitHub
  properties:
    access_token_secret: github-token-aws-ecs-node-demo-aws-ecs-node-demo
    branch: main
    repository: https://github.com/user/repo

stages:
    - name: test
      requires_approval: true
      test_commands:
        - echo 'running tests'
        - cd backend/
        - npm ci
        - npm run test
        - echo 'test completed'
    - name: prod
      requires_approval: true
```
- addons/dynamodb.yml
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  DynamoDbAccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the demo-ecs db'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grants CRUD access to DynamoDB
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: !Sub arn:aws:dynamodb:eu-central-1:user-id:table/ecs-${App}-${Env}-${Name}-*
          - Sid: DDBLSIActions
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource: !Sub arn:aws:dynamodb:eu-central-1:user-id:table/ecs-${App}-${Env}-${Name}-*/Index/*

Outputs:
  DynamoDbAccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role."
    Value: !Ref DynamoDbAccessPolicy
```
I've removed personal information like User ID and repository's URL.

**Comment by huanjani** [comment]
Hello, @fuji97! 

Hmm 🤔 , that's odd. Thanks for all of the info you included; are your `test` and `prod` environments in the same or different AWS accounts? We are going to try to reproduce the issue-- what region(s) are your envs in?

Thanks!

**Comment by fuji97** [comment]
Hi, @huanjani
Yes, both the clusters are under the same AWS account (sub-account with administrator rights) and everything is in the eu-central-1 region.

**Comment by huanjani** [comment]
@fuji97, where is your DynamoDB resource created? (I don't see it in the above addons template.)
https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/

**Comment by huanjani** [comment]
@fuji97,
Okay, a couple more things to check:
Is your service deployed to both environments? 
When you look at your CloudFormation stacks in the AWS console, are both addons stacks nested?

**Comment by huanjani** [comment]
From https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-template-validation/
Validate logical and physical IDs
1.    Confirm that resource logical IDs are defined in your template.
2.    Confirm that resource physical IDs exist in your environment.

For example, test is referenced for the ImageId property in the following JSON template and for the ImageID property in the following YAML template. Neither template includes a resource logical ID or parameter named test.

The resource ID isn't correctly defined in the following JSON and YAML templates. These templates return the following error: "Unresolved resource dependencies [test] in the Resources block of the template.” For more information on resource definitions and their syntax, see Resources.
```
JSON:

{
  "Parameters" : { ... },
  "Resources" : {
    "EC2Instance01" : {
      "Type" : "AWS::EC2::Instance",
      "Properties" : {
        "ImageId" : {"Ref": "test"},
        ...
      }
    }
  }
}
```
```
YAML:

Parameters:
Resources:
  EC2Instance01:
    Type: AWS::EC2::Instance
    Properties:
      ImageID: !Ref: test
```
