### ISSUE TITLE
Add load balancer configuration: security groups, auth

### ISSUE THREAD

**Issue by sharepointoscar** [aws/copilot-cli#1982]
**Scenario**

I provision a new environment via copilot.  This provisions a Load Balancer as usual. However, I want to be able to customize the LB either at provisioning time, or after provisioning it.  In this scenario, we want to configured OICD to authenticate users.

**Comment by us3r5pac3** [comment]
The customer use case would be to offload single sign-on using OpenID Connect on the Application Load Balancer: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

**Comment by us3r5pac3** [comment]
I think we'd need:
1. the `authenticate-oidc` and `redirect` action types for listener rules
2. the [fields that enable `AuthenticateOidcActionConfig`](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_AuthenticateOidcActionConfig.html)

**Comment by h5aaimtron** [comment]
Bumping this request since it is for UCLA and Oscar was requesting on our behalf at the time. We're focused on making copilot a major tool within our toolbox for aws migration, however; there are still gaps where we must manually update resources (this being one). As you know, once we update, we lose the level of management copilot generated stacks afford us.

**Comment by Lou1415926** [comment]
The request makes a lot of sense. Thank you @us3r5pac3 and @h5aaimtron for the customer use cases and for clarifying the need!

**Comment by sekamaneka** [comment]
any updates on this?

**Comment by Lou1415926** [comment]
Apologies - this integration isn't on our short-term sprint board yet. In the meantime, I wonder if it's possible to create a ListenerRule with OIDC configured using [addons](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#what-does-an-addon-template-look-like)?

```yaml
Resources:
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties: 
    Actions: 
      - Type: authenticate-oidc
        AuthenticateOidcConfig: 
          AuthorizationEndpoint: # Your endpoint.
          ClientId:  # Your client-id.
          ClientSecret: # Your client-secret.
          Issuer: # The issuer.
        Order: 1
      - Type: forward
        TargetGroupArn: # Your target group ARN.
        Order: 2
    Conditions: 
      - RuleCondition # Your rule conditions, e.g. path being `"/authenticate"`.
    ListenerArn: # The listner ARN
    Priority: Integer
```



You can take advantage of customized Parameters section in addons to atttach the addon listener rule to your the ALB listener, for example, you can create `addons/addons.parameters.yml` and write
```yaml
Parameters:
  ListenerARN: !GetAtt EnvControllerAction.HTTPListenerArn
```
and then refer to it in your addon template by `!Ref ListenerARN`.
