### ISSUE TITLE
Support for utilizing environment variables in manifest.yml

### ISSUE THREAD

**Issue by filipgolonka** [aws/copilot-cli#1992]
My current manifest:
```
name: my-service
type: Load Balanced Web Service
image:
  location: {COPILOT_IMAGE}
  port: 3333
# ...
```

Before running deploy, I need to build my docker image and then replace `{COPILOT_IMAGE}` in manifest, like this:
`sed -e "s~{COPILOT_IMAGE}~$COPILOT_IMAGE~g" copilot/my-service/manifest.bak.yml > copilot/my-service/manifest.yml

Proposed change:

```
name: my-service
type: Load Balanced Web Service
image:
  location: {env:COPILOT_IMAGE}
  port: 3333
# ...
```

before deploy, manifest is parsed and evaluated, so `{env:COPILOT_IMAGE}` will become replaced with `$COPILOT_IMAGE` environment variable value.

Thanks!
