### ISSUE TITLE
Dynamic services created and destroyed in custom pipelines

### ISSUE THREAD

**Issue by aaroncarlucci** [aws/copilot-cli#2005]
Just getting my feet wet with Copilot here and its looking very promising for us. I'm trying to fulfill a "review app" requirement. Currently using Bitbucket pipelines and when a new pull request is created, the pipeline needs to spin up a new version of the application for review. When the PR is merged back in, the review application is destroyed. I've managed to accomplish this using a custom solution with a hybrid of Terraform and CloudFormation template, but it looks my solution has a lot of overlap with Copilot so trying to migrate.

Basically, I want to run `copilot svc init` and `copilot svc deploy` in my pipeline to dynamically create new services, let them hang out for a while and then destroy them during later pipeline runs. I've been playing with the following pipeline code and have managed to get something that feels close:

```
# create review app                                                                                                 
- NEW_APP_NAME="app--pr-${BITBUCKET_PR_ID}"
- copilot svc init --name ${NEW_APP_NAME} --svc-type "Load Balanced Web Service" --dockerfile ./Dockerfile
- cp -R copilot/app/manifest.yml copilot/$NEW_APP_NAME/manifest.yml
- yq e ".name = \"$NEW_APP_NAME\"" -i copilot/$NEW_APP_NAME/manifest.yml
- cat copilot/$NEW_APP_NAME/manifest.yml
- copilot svc deploy --name $NEW_APP_NAME --env dev
```

I need to copy the manifest because it has some important customization for environment variables and secrets that I don't see flag support for.

I'm running into an error because the ECR repository never got created. Sounds like something with the state management that is being handled in CloudFormation infrastructure by Copilot versus the manifest.yml file is missing a link.

I know I'm pushing the limits of the prescribed use case for Copilot, but should something like this be possible with the tool design? If yes, do you see an issue with my approach? If no, are something like dynamic services created during build processes, or "review apps", worthy of the feature roadmap?

Perhaps there is a trickier way to do this by submitting a CloudFormation template?

**Comment by efekarakus** [comment]
OOhhh this is very interesting, thanks for sharing with us!

For the ECR repository creation, I think you'd need to run the following commands outside of your Bitbucket pipeline:
```bash
# Create an application (a logical name for a collection of services)
# https://aws.github.io/copilot-cli/docs/concepts/applications/
$ copilot app init 

# Create an environment, such as "prod-review"
# https://aws.github.io/copilot-cli/docs/concepts/environments/
$ copilot env init
```
Once your environment is created, we'll create an ECR bucket for your services in the environment!
These commands don't create resources that cost money, so I think it'd be okay to have them linger around in between review service runs.

An alternative solution might also be the `copilot task run` command (https://aws.github.io/copilot-cli/docs/commands/task-run/) if you don't need a service to maintain your tasks alive and a load balancer fronting your service. This command does take `--env-vars` as a flag and will create an ECR repository, but we don't have a flag for secrets yet.

**Comment by bvtujo** [comment]
To clarify a few things, can you answer some questions for us?
1. Have you committed the entire copilot directory, including the `copilot/.workspace` file that registers the repo to your application? 
2. To be clear, you're okay with initializing these review apps in your existing application? Does your pipeline not deploy to the `dev` environment, so it's reserved for the review apps? 
3. Could you paste the output of that set of commands? That will help us understand maybe what's going wrong.

**Comment by aaroncarlucci** [comment]
@efekarakus I have indeed run those commands outside of my pipeline. I will look into using a task, but I do need a descriptive URL endpoint by which the team can preview the PR application code.

@bvtujo here are some quick answers to your questions:

> Have you committed the entire copilot directory, including the copilot/.workspace file that registers the repo to your application?

Yes I have.
> To be clear, you're okay with initializing these review apps in your existing application? Does your pipeline not deploy to the dev environment, so it's reserved for the review apps?

Right now I am comfortable with keeping the review apps as services within the "dev" app. My use case is that we have two AWS accounts, one for `dev` and one for `prod`. The applications are really simple frontend nodejs sites built with Docker and I'm grouping them into a `www` application. In the `dev` AWS account I am using two environments, one for dev and one for staging, putting each in a different region. Then I will create another app in the prod account. The idea is to run the apps as sibling services in the same cluster in the `dev` environment. This seems ok for now, but if I can fix my issues, I am open to making them full-fledged apps. Are you suggesting that?
> Could you paste the output of that set of commands? That will help us understand maybe what's going wrong.

Here is the output from the `copilot svc deploy` command:
```
initiate image builder pusher: get repository URI: ecr describe repository www/momento-cam--pr-4: InvalidParameterException: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
```

I have since been looking at this issue ALL DAY today and last night, and I am convinced that there is an issue with validating the service names. As you can see, my service name includes a double-dash `app--pr-${PR_ID}`. This naming convention does not appear to be compatible with the naming requirements for an ECR repository. I tried to delete my services, environments and applications from copilot one-by-one, then all together and start over, but the application name I submitted is somehow getting stuck in the application state stored by some of the CloudFormation resources. I did some digging and tried to manually remove the SSM parameters defining my services and applications, and eventually manually removed all the CloudFormation stacks created by Copilot, trying to make my account a fresh slate. Eventually I got the copilot commands to report no services. However, when I spin up my app (with the same name), and then spin up a new environment targeting the us-west-2 region, the process fails with:
```
acarlton@ubuntu:~/project$ aws-vault exec -n <account> -- copilot env init --region us-west-2
What is your environment's name? dev
Which credentials would you like to use to create dev? Enter temporary credentials
What's your AWS Access Key ID? ********************
What's your AWS Secret Access Key? ********************
What's your AWS Session Token? 
Would you like to use the default configuration for a new environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services and jobs in your environment
 No, I'd like to import existing resources (VPC, subnets).
Which VPC would you like to use? vpc-**** (dev1)
Which public subnets would you like to use? subnet-****, subnet-****, subnet-****
Which private subnets would you like to use? subnet-****, subnet-****, subnet-****
✔ Proposing infrastructure changes for the www-dev environment.
- Creating the infrastructure for the www-dev environment.           [create complete]  [140.2s]
  - An IAM Role for AWS CloudFormation to manage resources           [create complete]  [18.8s]
  - An ECS cluster to group your services                            [create complete]  [11.3s]
  - An IAM Role to describe resources in your environment            [create complete]  [18.6s]
  - A security group to allow your containers to talk to each other  [create complete]  [7.2s]
✘ Failed to link account 741267758119 and region us-west-2 to application www.

✘ deploy env dev to application www: adding dev environment resources to application: operation 23 for stack set www-infrastructure failed
```

I've been looking into the CloudFormation stacks and the application code and I'm seeing that a list of services exists in the `StackSet-*-infrastructure` which has entries naming old services that I failed to add or remove using the copilot commands, which failed because the ECR repo was not able to be created and/or deleted. I've been searching all over various AWS services and the copilot code for where that Metadata state gets stored or populated but I can't find it.

When I look at the CloudFormation event log for this stack (oddly running in us-east-1), I see the ECR repository for these antiquated services is still trying to be created, failing and then rolling the stack back.
`Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])`

This is a pretty big validation issue -- it looks like you can't name a copilot service with a string that violates ECR repository requirements, but there is no checking, and in my case it has borked my account, at least for the namespaces I am interested in.

Can you PLEASE tell me how to clear or wipe the service list that is getting pulled into the infrastructure StackSet's Metadata section?

**Comment by aaroncarlucci** [comment]
Update: I managed to fix my environment by manually editing the StackSet in CloudFormation, copying the template, removing the old resources and metadata entries for the services and re-uploading it with a new version number in the metadata. I was then able to delete my environments and app, hopefully clearing out my account of copilot resources.

Time to start over. It seems to me that that managing metadata and resources in StackSet template is at least very brittle. I'm still pretty sure that missing validation against the requirements for the ECR repository name led my StackSet to get into an unmanageable state. That whole thing probably belongs in a separate issue. I'll continue with my pipeline integration and report back.

**Comment by aaroncarlucci** [comment]
Update: I took a step back and attempted to try completely new applications for the review apps using `copilot app init` followed by `copilot env init` as @efekarakus suggested. The pipeline took a really long time due to creating all the CloudFormation stacks for app infrastructure and environments. There were also some pipeline hang ups. I had to create an empty /root/.aws/config file in my pipeline to fake out the credential lookup and I had to remember to pass my VPC and subnets in via repository variables to the command line arguments. Eventually, I abandoned this approach because when it came time to deploy, the service was not able to access my secrets because the tags for app name and environment didn't match what I was copying from the original config. Bummer.

Going back to deploying a sibling service within the same app and environment, I finally got a small prototype to work. Here is the relevant pipeline code in case it helps anyone else or inspires improvements for this feature:
```
    # install copilot
    - curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x /usr/local/bin/copilot && copilot --help
    # install yq
    - wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    # create review app
    - APP_NAME="app-name"
    - NEW_SERVICE_NAME="pr-${BITBUCKET_PR_ID}"
    - copilot svc init --name ${NEW_SERVICE_NAME} --svc-type "Load Balanced Web Service" --dockerfile ./Dockerfile
    - cp -R copilot/app/manifest.yml copilot/$NEW_SERVICE_NAME/manifest.yml
    - yq e ".name = \"$NEW_SERVICE_NAME\"" -i copilot/$NEW_SERVICE_NAME/manifest.yml
    - cat copilot/$NEW_SERVICE_NAME/manifest.yml
    - copilot svc deploy --app $APP_NAME --name $NEW_SERVICE_NAME --env dev
```

**Comment by bvtujo** [comment]
Oh my goodness, I am so sorry you had to fight with this as long as you did! If the ECR repository name is indeed the issue, it looks like you've hit an undocumented edge case--ECR certainly doesn't say anything in their docs about multiple hyphens being disallowed. If I can repro this issue, we'll add some more substantial validation to stop other folks from falling into this unmanageable trap that caught you. 

Thanks SO much also for posting your results and the code that worked for you. So this is now creating services on each push in the `dev` environment so you can review them? How do you handle the deletion workflow? Is that also automated, or do you tear it down manually after you approve the changes to get deployed to prod?

**Comment by aaroncarlucci** [comment]
@bvtujo Thanks for the reply. Happy to see it addressed in the PR :)

In terms of the deletion workflow, I have another pipeline running for the target branch. When the PR gets merged, that pipeline runs something like this:
```
clean-up-review-app-from-aws: &clean-up-review-app-from-aws
  image: alpine:3.12.3
  name: Cleanup Review App from AWS
  script:
    - apk add --no-cache curl git jq make openssh python3
    - python3 -m ensurepip
    - "pip3 install git+git://github.com/aws/aws-cli.git#2.0.55"
    # install copilot                                                                                                   
    - curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x /usr/local/bin/copilot && copilot --help
    # Pull the commit that triggered this script, which for a pull request will be the merge commit.                    
    # Retrieve the associated pull-request to get the review id number so we can delete the review app                  
    - PR_NUMBER=$(curl -X GET -G "https://${BITBUCKET_API_USERNAME}:${BITBUCKET_API_TOKEN}@api.bitbucket.org/2.0/repositories/[bitbucket-account-name]/[bitbucket-repo]/pullrequests" --data-urlencode 'q=merge_commit.hash="'"$BITBUCKET_COMMIT"'"' | python3\
 -c "import json,sys;obj=json.loads(sys.stdin.read());value=obj.get('values', [{}])[0].get('id', '');print(value)") || true
    - echo $PR_NUMBER
    - APP_NAME="[app-name]"
    - SERVICE_NAME="pr-${PR_NUMBER}"
    - cp -R copilot/app copilot/$SERVICE_NAME
    - yq e ".name = \"$SERVICE_NAME\"" -i copilot/$SERVICE_NAME/manifest.yml
    - cat copilot/$SERVICE_NAME/manifest.yml
    - copilot svc delete --app $APP_NAME --env dev --name $SERVICE_NAME --yes
```

This specific code hasn't been tested with my copilot implementation yet, but the general approach has been working for a custom implementation which deleted CloudFormation stacks.

The remaining item is the use case for PRs that get declined. In my prior implementation, I had an AWS API Gateway and Lambda function that was called by Bitbucket webooks which deleted the custom review app CloudFormation template using naming conventions. With copilot, I'm currently trying to scrap that and create a copilot "scheduled job" which runs a python script to query the Bitbucket API for declined PRs, then runs `copilot svc ls --json` in a subprocess to get a list of the available services for the apps and matches them up by the `pr-[id]` naming convention and then calls `copilot svc delete` if there is a match. Another thought was to look into a container-image-supported Lambda, but I don't think I have my head wrapped around that feature properly yet.

Any comments or suggestions welcome.

**Comment by acarlton** [comment]
@bvtujo Thanks for the reply. Happy to see it addressed in the PR :)

In terms of the deletion workflow, I have another pipeline running for the target branch. When the PR gets merged, that pipeline runs something like this:
```
clean-up-review-app-from-aws: &clean-up-review-app-from-aws
  image: alpine:3.12.3
  name: Cleanup Review App from AWS
  script:
    - apk add --no-cache curl git jq make openssh python3
    - python3 -m ensurepip
    - "pip3 install git+git://github.com/aws/aws-cli.git#2.0.55"
    # install copilot                                                                                                   
    - curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x /usr/local/bin/copilot && copilot --help
    # Pull the commit that triggered this script, which for a pull request will be the merge commit.                    
    # Retrieve the associated pull-request to get the review id number so we can delete the review app                  
    - PR_NUMBER=$(curl -X GET -G "https://${BITBUCKET_API_USERNAME}:${BITBUCKET_API_TOKEN}@api.bitbucket.org/2.0/repositories/[bitbucket-account-name]/[bitbucket-repo]/pullrequests" --data-urlencode 'q=merge_commit.hash="'"$BITBUCKET_COMMIT"'"' | python3\
 -c "import json,sys;obj=json.loads(sys.stdin.read());value=obj.get('values', [{}])[0].get('id', '');print(value)") || true
    - echo $PR_NUMBER
    - APP_NAME="[app-name]"
    - SERVICE_NAME="pr-${PR_NUMBER}"
    - cp -R copilot/app copilot/$SERVICE_NAME
    - yq e ".name = \"$SERVICE_NAME\"" -i copilot/$SERVICE_NAME/manifest.yml
    - cat copilot/$SERVICE_NAME/manifest.yml
    - copilot svc delete --app $APP_NAME --env dev --name $SERVICE_NAME --yes
```

This specific code hasn't been tested with my copilot implementation yet, but the general approach has been working for a custom implementation which deleted CloudFormation stacks.

The remaining item is the use case for PRs that get declined. In my prior implementation, I had an AWS API Gateway and Lambda function that was called by Bitbucket webooks which deleted the custom review app CloudFormation template using naming conventions. With copilot, I'm currently trying to scrap that and create a copilot "scheduled job" which runs a python script to query the Bitbucket API for declined PRs, then runs `copilot svc ls --json` in a subprocess to get a list of the available services for the apps and matches them up by the `pr-[id]` naming convention and then calls `copilot svc delete` if there is a match. Another thought was to look into a container-image-supported Lambda, but I don't think I have my head wrapped around that feature properly yet.

Any comments or suggestions welcome.
