### ISSUE TITLE
Support APIGW as ingress for Backend Services

### ISSUE THREAD

**Issue by rmarapp-dio** [aws/copilot-cli#2050]
Hello,

Is there any guidance or support to implement API gateway to - 'Backend Service' integration. Does copilot have any support to integrate with API Gateway for backend services?

**Comment by efekarakus** [comment]
Hi @rmarapp-prisidio ! We don't have an integration with APIGW available at the moment.

> API Gateway for backend services?

Do you want the APIGW to be private?  so that the APIGW is accessible only within the VPC or do you want it to be a public endpoint? At the moment the APIGW would need to be created outside of copilot unfortunately

**Comment by rmarapp-dio** [comment]
I think the use case is pretty simple (and common one IMHO)

  *   Have apgw public endpoint that fronts the backend services.

Please let me know if you would like me to put in a feature request.

Thankyou efe


  *   Ram

From: Efe Karakus ***@***.***>
Date: Monday, March 15, 2021 at 6:22 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram Marappan ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Integration with API Gateway and Backend Services (#2050)

Hi @rmarapp-prisidio<https://github.com/rmarapp-prisidio> ! We don't have an integration with APIGW available at the moment.

API Gateway for backend services?

Do you want the APIGW to be private? so that the APIGW is accessible only within the VPC or do you want it to be a public endpoint? At the moment the APIGW would need to be created outside of copilot unfortunately

**Comment by efekarakus** [comment]
> Please let me know if you would like me to put in a feature request.

I updated this issue to be a feature request (renamed it!)

Would you mind sharing with us what features of APIGW you'd like to use with Copilot? 🙏 
Any reason why you'd prefer to use APIGW over the existing "Load Balanced Web Service" pattern?

**Comment by rmarapp-dio** [comment]
Absolutely. We are build an product that has extra security requirements and by proxying it through API gateway we can govern access to the service and not expose the REST service to WWW and thus reducing the blast radius.

For most of the financial institutions this is a popular pattern. Pleas let me know if it makes sense.

Thanks
Ram
________________________________

**Comment by efekarakus** [comment]
I think so, thanks! Is there a particular feature of APIGW that allows the RESTful service not to be accessible to the internet?  Something like [API Keys](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-setup-api-key-with-console.html)? 

I'm trying to understand which particular features of APIGW we could expose in our manifest files to make it easier for you to integrate with it.

**Comment by rmarapp-dio** [comment]
Let me think about this.. give me a day or 2, please..

Thanks
Ram
________________________________

**Comment by rmarapp-dio** [comment]
Efe,

Here are my thoughts

  *   Start with Public REST API that integrates with a “back-end service”, that provides HTTP Proxy support along with CORS support
***@***.***D71AB4.928C4260]

  *   Expose properties for a list of stages and ability to pass an encryption key per stage.



  *   Part of the recipe would be to tie usage plan with api-key and stage

Attaching 2 yaml files that does this. First is an svc that creates all the API GW stuff. Second is a web app that creates an API key and attaches to usage plan. Hope that helps.

Please let me know if you need anything more.


From: Ram ***@***.***>
Date: Monday, March 15, 2021 at 6:54 PM
To: aws/copilot-cli ***@***.***>, aws/copilot-cli ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)
Let me think about this.. give me a day or 2, please..

______________________

**Comment by efekarakus** [comment]
Thanks Ram! This is great :D

**Comment by rmarapp-dio** [comment]
Aboslutely, would be terrific for us if it get implemented! If there is something that we could do to help you guys out please let me know.

Thanks
Ram

From: Efe Karakus ***@***.***>
Date: Wednesday, March 17, 2021 at 12:53 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

Thanks Ram! This is great :D

**Comment by ceagan** [comment]
I think the key is https://aws.amazon.com/blogs/architecture/field-notes-integrating-http-apis-with-aws-cloud-map-and-amazon-ecs-services/ with routes secured by Cognito.

**Comment by rmarapp-dio** [comment]
Hello,

Any chance that this would get implemented near-term. We were going to start to implement it, but wanted check with the co-pilot team and see whether there are any plans for co-pilot support.

Any thoughts would be greatly appreciated.

From: Ram ***@***.***>
Date: Wednesday, March 17, 2021 at 3:37 PM
To: aws/copilot-cli ***@***.***>, aws/copilot-cli ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)
Aboslutely, would be terrific for us if it get implemented! If there is something that we could do to help you guys out please let me know.

Thanks
Ram

From: Efe Karakus ***@***.***>
Date: Wednesday, March 17, 2021 at 12:53 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram Marappan ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

Thanks Ram! This is great :D

**Comment by efekarakus** [comment]
> I think the key is https://aws.amazon.com/blogs/architecture/field-notes-integrating-http-apis-with-aws-cloud-map-and-amazon-ecs-services/ with routes secured by Cognito.

Application Load Balancers also [support integration](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) with Cognito would that be something you'd be interested in to configure for existing "Load Balanced Web Services"?

How do y'all use Cognito today? I wonder if we can add a `copilot auth init` command to create an Amazon Cognito user pool via CloudFormation and attach it to your existing ALB 🤔 

> Any chance that this would get implemented near-term. We were going to start to implement it, but wanted check with the co-pilot team and see whether there are any plans for co-pilot support.

We really want to integrate with APIGW just like in the post from @ceagan but there is no short term plan for it. 
My first thought was that APIGW would instead be an option for "Load Balanced Web Services" if the APIGW is going to be publicly accessible:
```yaml
type: "Load Balanced Web Service"
api:
   openapi: ./api-definition.json
```
How would you like this field to be surfaced in the manifest? What options would you like to see?

**Comment by rmarapp-dio** [comment]
Efe,

Apart from open-api I would like to pass in an

  *   array of API-keys and stage-name,
  *   Enable CORS support (Boolean)
  *   domainName – Or this could be elmiated and use the domain name that was defined as part of the co-pilot app. This might be handy if we want vanity URL for the API-GW and external customers. This is more like “would like to have”
Input

api:



   openapi: ./api-definition.json

   apiKeyStage:

-    Dsdskdjs, dev

   enableCors: true|false

   domainName:


Output:

  *   Would be an API GW ID as an environment variable

Part of the recipe would be to tie api-key and stage with the api gateway instance something like this.
***@***.***D7256B.7D2823F0]

From: Efe Karakus ***@***.***>
Date: Tuesday, March 30, 2021 at 1:07 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

I think the key is https://aws.amazon.com/blogs/architecture/field-notes-integrating-http-apis-with-aws-cloud-map-and-amazon-ecs-services/ with routes secured by Cognito.

Application Load Balancers also support integration<https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html> with Cognito would that be something you'd be interested in to configure for existing "Load Balanced Web Services"?

How do y'all use Cognito today? I wonder if we can add a copilot auth init command to create an Amazon Cognito user pool via CloudFormation and attach it to your existing ALB 🤔

Any chance that this would get implemented near-term. We were going to start to implement it, but wanted check with the co-pilot team and see whether there are any plans for co-pilot support.

We really want to integrate with APIGW just like in the post from @ceagan<https://github.com/ceagan> but there is no short term plan for it.
My first thought was that APIGW would instead be an option for "Load Balanced Web Services" if the APIGW is going to be publicly accessible:

type: "Load Balanced Web Service"



api:



   openapi: ./api-definition.json

How would you like this field to be surfaced in the manifest? What options would you like to see?

**Comment by rmarapp-dio** [comment]
I’m sure it is true, but just confirming that the actually service will not be publicly accessible but only through API-GW.

From: Ram ***@***.***>
Date: Tuesday, March 30, 2021 at 1:49 PM
To: aws/copilot-cli ***@***.***>, aws/copilot-cli ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)
Efe,

Apart from open-api I would like to pass in an

  *   array of API-keys and stage-name,
  *   Enable CORS support (Boolean)
  *   domainName – Or this could be elmiated and use the domain name that was defined as part of the co-pilot app. This might be handy if we want vanity URL for the API-GW and external customers. This is more like “would like to have”
Input

api:



   openapi: ./api-definition.json

   apiKeyStage:

-    Dsdskdjs, dev

   enableCors: true|false

   domainName:


Output:

  *   Would be an API GW ID as an environment variable

Part of the recipe would be to tie api-key and stage with the api gateway instance something like this.
***@***.***D72581.E09B6C10]

From: Efe Karakus ***@***.***>
Date: Tuesday, March 30, 2021 at 1:07 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

I think the key is https://aws.amazon.com/blogs/architecture/field-notes-integrating-http-apis-with-aws-cloud-map-and-amazon-ecs-services/ with routes secured by Cognito.

Application Load Balancers also support integration<https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html> with Cognito would that be something you'd be interested in configuring for existing "Load Balanced Web Services"?

How do y'all use Cognito today? I wonder if we can add a copilot auth init command to create an Amazon Cognito user pool via CloudFormation and attach it to your existing ALB 🤔

Any chance that this would get implemented near-term. We were going to start to implement it, but wanted check with the co-pilot team and see whether there are any plans for co-pilot support.

We really want to integrate with APIGW just like in the post from @ceagan<https://github.com/ceagan> but there is no short-term plan for it.
My first thought was that APIGW would instead be an option for "Load Balanced Web Services" if the APIGW is going to be publicly accessible:

type: "Load Balanced Web Service"



api:



   openapi: ./api-definition.json

How would you like this field to be surfaced in the manifest? What options would you like to see?

**Comment by efekarakus** [comment]
Yup that's right! Copilot never creates security groups that allow ingress from the internet. For Load Balanced Web Services, only through the ALB or other containers in the cluster and it would be similar with the APIGW integration.

**Comment by rmarapp-dio** [comment]
So in case the ALB will not be visible publicly Correct?


From: Efe Karakus ***@***.***>
Date: Tuesday, March 30, 2021 at 5:07 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

Yup that's right! Copilot never creates security groups that allow ingress from the internet. For Load Balanced Web Services, only through the ALB or other containers in the cluster and it would be similar to the APIGW integration.

**Comment by efekarakus** [comment]
Right now the ALB is visible publicly for "Load Balanced Web Services", however if we do enable APIGW or ALB for "Backend Services" then they wouldn't be publicly visible.

**Comment by rmarapp-dio** [comment]
Perfect.

From: Efe Karakus ***@***.***>
Date: Tuesday, March 30, 2021 at 7:46 PM
To: aws/copilot-cli ***@***.***>
Cc: Ram ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/copilot-cli] Support APIGW as ingress for Backend Services (#2050)

Right now the ALB is visible publicly for "Load Balanced Web Services", however, if we do enable APIGW or ALB for "Backend Services" then they wouldn't be publicly visible.

**Comment by ceagan** [comment]
I think it is important to support authenticated routes with the deployed API Gateway too. They could be configured to use Amazon Cognito for authentication.

It would be great if there was an option to automatically deploy a Swagger-UI for the Copilot-deployed API as well. The Swagger-UI would be configured automatically to support in-browser testing of authenticated routes and allow developers/users of the API to access documentation of the deployed APIs.

**Comment by rmarapp-dio** [comment]
@efekarakus Any timeframe on when you think the team might be able to implement this feature, we have a need, and if it takes longer we might have to look at other options. Please let me know your thoughts.

**Comment by efekarakus** [comment]
Hi @rmarapp-prisidio ! 

> Any timeframe on when you think the team might be able to implement this feature

We don't have currently bandwidth to start on the implementation for this feature any time soon unfortunately. Our near-term roadmap is available here: https://github.com/aws/copilot-cli/projects/2

> We were going to start to implement it

If y'all are still available to do it, we would love to have it as a contribution! But before implementation it would great to have a UX design discussion first such as https://github.com/aws/copilot-cli/issues/1154

However, in the mean time, I think it's possible to build this integration outside of Copilot with CloudFormation today although  it won't be managed by Copilot.

In the service stack's we are exporting `DiscoveryServiceARN` and we also export the subnets and security groups created in the environment stack. So I think it should be possible to deploy a stack with APIGatewayV2:
```yaml
PParameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  SvcName:
    Type: String
Resources:
  CloudMapHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: HTTP

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref CloudMapHttpApi
      RouteKey: 'ANY /'
      Target: !Join
        - /
        - - integrations
          - !Ref APIIntegration

  PrivateAPIGWvpcLink:  
    Type: AWS::ApiGatewayV2::VpcLink
    Properties: 
      Name: private-apigw-vpclink
      SubnetIds:
      - Fn::Select:
        - 0
        - Fn::Split:
          - ','
          - Fn::ImportValue: !Sub '${AppName}-${EnvName}-PublicSubnets'
      - Fn::Select:
        - 1
        - Fn::Split:
          - ','
          - Fn::ImportValue: !Sub '${AppName}-${EnvName}-PublicSubnets'
      SecurityGroupIds:
      - Fn::ImportValue: !Sub '${AppName}-${EnvName}-EnvironmentSecurityGroup'

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref CloudMapHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref PrivateAPIGWvpcLink
      IntegrationUri: 
      - Fn::ImportValue: !Sub '${AppName}-${EnvName}-${SvcName}-DiscoveryServiceARN'
      PayloadFormatVersion: '1.0'  
  
  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      AutoDeploy: true
      ApiId: !Ref CloudMapHttpApi

Outputs:
  APIURL:
    Description: Invoke URL
    Value: !Sub https://${CloudMapHttpApi}.execute-api.${AWS::Region}.amazonaws.com/        

```
Hope this helps!
