### ISSUE TITLE
Feature request: nonpersistent empty storage

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#2065]
I have a scenario where I would like to run a sidecar that is responsible for pulling down and configuring some files. It could be useful to be able to define a shared volume for the task. Maybe something like the following:

```yaml
volumes:
  source_volume: scratch
  path: /var/scratch
```

This is already possible with Fargate. See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

Also, it might be useful to be able to mark a sidecar as not essential so that it can exit after doing its work. Maybe this is a bad approach though. I'm not sure.

**Comment by bvtujo** [comment]
Ohh, thanks os much for the feature request. This is a neat use case that we hadn't necessarily considered. It should be possible for us to do with our current volumes feature. 

Once we enable passing in empty volumes, we can do the following:

```yml
storage:
  volumes:
    scratch:
      path: /var/scratch

sidecars:
  downloader:
    image: ${SIDECAR_IMAGE_URI}
    mount_points:
      - path: /var/scratch
        source_volume: scratch
```
    
  
```
