### ISSUE TITLE
Feature request: allow sidecars to be marked as non-essential

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#2066]
As described in #2065, we should allow customers to mark sidecars as non-essential so that their exiting doesn't cause the task to become unhealthy. 

To do this, we should add an optional field to our `sidecars` map:

```yaml
sidecars:
  nonessentialSidecar:
    image: ecr.aws/image
    essential: false
```

This will cause the `Essential` property of the [container definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-essential) to be rendered in the task definition.
