### ISSUE TITLE
upload pipeline template to S3 bucket to handle larger capacities

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#2068]
Hello,
I added another environment to my pipeline and got the following error "'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200".
For my understanding this is a CFN limitation, how can i avoid that?

**Comment by efekarakus** [comment]
Oh this is very interesting! Would you mind sharing the change in the `pipeline.yml` file that cause the template size to be greater than 51200?

Maybe we can help trim the size, there is no short term fix that I can think of for this 🤔 until we upload the template to an S3 bucket

**Comment by niros1** [comment]
Just added the prod section (which is currently comment out )

my pipeline.yml
```
source:
  # The name of the provider that is used to store the source artifacts.
  provider: Bitbucket
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:
    branch: master
    repository: url to repository

# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:
  - # The name of the environment to deploy to.
    name: dev
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

  - # The name of the environment to deploy to.
    name: test
    # Optional: flag for manual approval action before deployment.
    requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

  # - # The name of the environment to deploy to.
  #   name: prod
  #   # Optional: flag for manual approval action before deployment.
  #   requires_approval: true
  #   # Optional: use test commands to validate this stage of your build.
  #   # test_commands: [echo 'running tests', make test]
```
