### ISSUE TITLE
Deploying Load Balanced Web Service doesn't pick up changes

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2069]
So I have a simple web service, it's an Angular app. I deployed it using:

`copilot svc deploy --name frontend-service --env test `

This worked, however subsequent deploys don't seem to apply changes. I mean, I changed the code (Angular), then redeployed the service. It says everything was successful, but I still see the old UI when I open the URL copilot generated, which looks something like this:

http://something-other-blah-blah.me-south-1.elb.amazonaws.com/

No matter what I change, it seems the old version is getting deployed over and over again.

Am I missing something here? How can I force copilot to deploy the latest changes?

My manifest:

```
# The manifest for the "frontend-service" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: frontend-service
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: ../frontend/Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.

variables:                    # Pass environment variables as key value pairs.
  NODE_ENV: test
  
# secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.


# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.

```

Btw, I even tried to run `docker system prune` to force rebuild of the image, and I can see that the next deploy rebuilding everything from scratch. But the end result is still the old app.
