### ISSUE TITLE
Automatically round up to nearest Fargate cpu/mem

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#2081]
We should just automatically round up to the valid cpu and mem values in Fargate so even if someone enters an invalid mem/cpu combo it doesn't stop them from building and deploying.

**Comment by camilosantana** [comment]
in user-experience spirit, this may be related to https://github.com/aws/copilot-cli/issues/1625

**Comment by camilosantana** [comment]
to comment further on user experience, i ran into this vague error via:

```shell
copilot job init
# edit manifest
copilot job deploy
```

The manifest edit was where I introduced illegal values for fargate `cpu` units.

```yaml
name: conntest
type: Scheduled Job

on:
  schedule: "@every 25m"
timeout: 30m

image:
  build: Dockerfile-conntest

cpu: 128 # Number of CPU units for the task.
memory: 256 # Amount of memory in MiB used by the task.

entrypoint: "./run-my-tests.py"
```

I was using tiny values because this is all that's in my Dockerfile

```dockerfile
FROM alpine:3.2 AS builder

RUN apk update && apk upgrade && apk add curl wget bash jq netcat-openbsd

FROM builder AS deploy

COPY --from=builder /bin /bin
COPY --from=builder /usr /usr
COPY --from=builder /sbin /sbin

CMD ["/bin/ash"]
```

the subsequent `deploy` command yields this error:

```java
Invalid request provided: Create TaskDefinition: 
No Fargate configuration exists for given values. 
(Service: AmazonECS; Status Code: 400;
Error Code: ClientException; 
Request ID: 3d7530c5-bfb4-6a4e-8a2a-53a3561b8f74;
Proxy: null)
```
