### ISSUE TITLE
Setup Copilot GH Action

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#2174]
We should create a GH action for setting up Copilot like SAM: https://github.com/aws-actions/setup-sam

**Comment by guyschlider** [comment]
So if I want to automate deployment using copilot-cli using Github actions it's not possible right now?

**Comment by kohidave** [comment]
You can do it now, you just have to manage downloading Copilot in your GH Action. The Action we're thinking of building is just a shortcut for that :)

**Comment by efekarakus** [comment]
I haven't tried it myself but checkout this action: https://github.com/softprops/setup-aws-copilot! That might help you get started.

If using AWS CodePipeline is an okay alternative, you can use the `copilot pipeline` commands to create a cd pipeline to release your services :)

**Comment by josefaidt** [comment]
Hey everyone here's a small GitHub Actions snippet (for Linux-based runners) to download a specific version of the CLI and add it to the PATH. 

```yml
jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Install copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.8.3/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      # sample use
      - run: copilot help
```
