### ISSUE TITLE
How to use secrets in multiple environments ?

### ISSUE THREAD

**Issue by nicolas-b12** [aws/copilot-cli#2275]
Hello there,

I would like to add secrets for multiple environments when deploying. For example `DJANGO_SECRET_KEY` for `staging` and `production` environment. Those 2 environments should be running on the same AWS account. The issue I'm facing there is that I can't create two parameters with the same name and I would like to avoid patching manifests at runtime to switch between `staging/DJANGO_SECRET_KEY` and `production/DJANGO_SECRET_KEY`.

Could you help me with that ?

Thanks

**Comment by Lou1415926** [comment]
Hello @nicolas-b12! Thanks for reaching out!

If I am understanding correctly, you have created two secrets,`staging/DJANGO_SECRET_KEY` and `production/DJANGO_SECRET_KEY`, and you'd like `DJANGO_SECRET_KEY` to refer to `staging/DJANGO_SECRET_KEY` when the service is deployed to `staging` environment, and `production/DJANGO_SECRET_KEY` when it's deployed to `production` environment. Is this correct?

You can do this by specifying environment overrides in your manifest file. That is, in your manifest file, you can write
```yaml
environments:
   staging:
      secrets:
         DJANGO_SECRET_KEY: staging/DJANGO_SECRET_KEY
   production:
      secrets:
         DJANGO_SECRET_KEY: production/DJANGO_SECRET_KEY
```
This way, the value of `DJANGO_SECRET_KEY` will be versioned by your environments.

On our [doc site's sample manifest file](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/), we only included `count` as an example override, but in fact most of the configurations - such as `count`, `memory`, `variables`, and of course `secrets` - can all be versioned in the same way. 

Hope this solves your problem!!

(By the way, we are currently working on [`secret init`](https://github.com/aws/copilot-cli/issues/1920) that helps you create secrets through Copilot. Stay tuned if you're interested!)

**Comment by nicolas-b12** [comment]
Oh, right, this makes much more sense 🙂  Thank you !

**Comment by gabrieljoelc** [comment]
[This comment](https://github.com/aws/copilot-cli/issues/2275#issuecomment-833646845) was very helpful in understanding how to specify environment-specific secrets. However, it took me a while to find this and the documentation doesn't make it clear you can do stuff like this:
```yaml
environments:
  dev:
    secrets:
      DB_URL:
        secretsmanager: db_url_secrets_manager_name
```
