### ISSUE TITLE
Support for CodeBuild Test Reports

### ISSUE THREAD

**Issue by patnolanireland** [aws/copilot-cli#2289]
In order to support the CodeBuild Test Reports feature which allows viewing test results in the AWS Console it appears that the `templates/cicdf/pipeline_cfn.yml` file needs to be modified expanding the `BuildProjectPolicy` to include the following statement.

```
- Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Resource: !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/pipeline-{{$.AppName}}-*

```

I have made these changes on my own fork and have successfully been able to view test reports in CodeBuild as a result.  At this point I'm happy to submit a PR however I believe I need to update the end-to-end tests in order for the PR to be accepted.  From what I can tell this may just require adding the necessary cf to the `internal/pkg/deploy/cloudformation/stack/testdata/pipeline/bb_template.yml`?  

I'm new to golang and this project so any direction would be greatly appreciated.
