### ISSUE TITLE
Are default environment variables available in Dockerfiles?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2302]
For instance, could I do something like `RUN npm run build -- -c $COPILOT_ENVIRONMENT_NAME` in a service Dockerfile?

Forgive my laziness please, but perhaps this will also help some future traveler.

**Comment by bvtujo** [comment]
Whoops! Just saw the ongoing conversation on #2304

<details>
<summary>Old comment</summary>
Hi Mike! Unfortunately we don't inject anything by default into the dockerfile, but you could add it as a build arg in the manifest using environment overrides:

```yaml
image:
  build:
    dockerfile: ./Dockerfile

environments:
  test:
    image:
      build:
        args:
          ENV: test
  prod:
    image:
      build:
        args:
          ENV: prod
```

Then in your dockerfile you can do:
```Dockerfile
ARG ENV
FROM node:16
RUN npm run build -- -c $ENV
 ```
</details>
