### ISSUE TITLE
Make health check relative to path

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2303]
Current behavior: the http path in a service manifest has to be repeated in the health check path

``` yaml
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: 'my-api'
  # You can specify a custom health check path. The default is "/".
  healthcheck: '/my-api/actuator/health'
```

Desired behavior: The http path is only specified once, and the health check path is relative to it.

``` yaml
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: 'my-api'
  # You can specify a custom health check path. The default is "/".
  healthcheck: '/actuator/health'
```

No idea how feasible this is and perhaps there are factors that make this undesirable. Just my experience with it at the moment :)
