### ISSUE TITLE
args not being passed to Dockerfile

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2304]
I have the following in my service manifest

``` yaml
# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: apps\frontend\Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80
  args:
    ENVIRONMENT: COPILOT_ENVIRONMENT_NAME
```

and in my Dockerfile for this service
``` yaml
ARG ENVIRONMENT
RUN npm run build -- --prod -c $ENVIRONMENT
```

But when I deploy I see this in the logs
` => [builder 6/6] RUN npm run build -- --prod -c $ENVIRONMENT`

If I manually run `docker build --build-arg ENVIRONMENT=test .` then it works as expected.

What am I doing wrong here?

p.s.
I have no idea if passing COPILOT_ENVIRONMENT_NAME in the args like I am would even work or not, but I would expect that if it didn't I should at least be seeing the string literal of "COPILOT_ENVIRONMENT_NAME" in the Dockerfile output. So bonus question: if passing the env var like that wont work, how would one pass the COPILOT_ENVIRONMENT_NAME to a Dockerfile?

**Comment by efekarakus** [comment]
Hi @mikelhamer !

The `args` field needs to be under `build`: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build 😄 
Would you mind giving a shot to:
```yaml
image:
  port: 80
  build:
     dockerfile: apps\frontend\Dockerfile
     args:
       ENVIRONMENT: COPILOT_ENVIRONMENT_NAME
```

**Comment by mikelhamer** [comment]
@efekarakus OMG haha. Thank you!

But now I have another issue....since passing COPILOT_ENVIRONMENT_NAME isn't working (also tried ${COPILOT_ENVIRONMENT_NAME} and $COPILOT_ENVIRONMENT_NAME), I figure I need to just override in the environments section to make sure the passed value matches the environment like so:

``` yml
environments:
  test:
    image:
      build:
        dockerfile: apps\frontend\Dockerfile
        args:
          ENVIRONMENT: test
```

But this doesn't seem to be working. Nothing is actually being overridden when I deploy to test environment with `copilot svc deploy -n frontend -e test`. Hopefully I'm just making another dumb mistake?
