### ISSUE TITLE
Application Auto-Scaling on Schedule

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#2310]
We want to create a schedule for our non-production environments such that we can shut off containers during non-business hours. We would then adhoc start them if they're needed outside of the schedule. I was directed to the link below as a reference.

https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-scheduled-scaling.html

**Comment by efekarakus** [comment]
Thanks Scott! The feature request makes a lot of sense.

I wonder if using the new `spot` field in [Copilot v1.6.0](https://github.com/aws/copilot-cli/releases/tag/v1.6.0) can help here for your non-production environments: https://aws.github.io/copilot-cli/docs/manifest/backend-service/#count-spot

```yaml
count:
  spot: 1
```

Spot tasks can be up to 70% cheaper: https://aws.amazon.com/fargate/pricing/

**Comment by h5aaimtron** [comment]
@efekarakus as I understand it, spot instances (even a minimum of 1) still run 24/7. Our use-case is really wanting these systems to be up during business hours for development (or adhoc if needed), but generally would be down. The other added benefit of them being down is that you don't incur cost from wrongly configured integrations/jobs/etc. that might accidentally get kicked off during these off periods that somehow cause an issue. If we had an integration partner that accidentally triggered a performance test against a non-prod environment, we don't want to incur a cost in that event, but rather their process fail.

**Comment by bvtujo** [comment]
Could you use a scheduled job to accomplish this? If you set up a scheduled job using 
```bash
copilot job init \
  --name autoscaler \
  --dockerfile ./Dockerfile_autoscaler \
  --schedule "30 8,17 * * MON-FRI"
  # --retries 2 # Optional
```

Then, in your Dockerfile, you could wrap a shell script using the AWS CLI to scale the service down to 0 at 5:30pm and up again at 8:30am.

The last piece here is to create an `addons` directory at `copilot/autoscaler/addons` and add a CloudFormation template containing a managed policy with the permissions you'll need to scale the ECS service. You can read more in our website at (https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/). 

Something like this: 

```yaml
# You can use any of these parameters to create conditions or mappings in your template.
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  ServiceScalingAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ECSServiceScaling
            Effect: Allow
            Action:
              - ecs:UpdateService
            Resource: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${App}-${Env}-${REPLACE_ME_SERVICE_NAME}-Service-*

Outputs:
  ServiceScalingAccessPolicyARN:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref ServiceScalingAccessPolicy
```
