### ISSUE TITLE
How can  connect service container from Sidecar?

### ISSUE THREAD

**Issue by shgtkshruch** [aws/copilot-cli#2370]
Hi, there.
I have one service container (Rails), it's export 3000 port. And I have one Sidercar container (Nginx) to proxy request to Rails container.
I tried to connect to Rails from Sidecar using [service discovery](https://aws.github.io/copilot-cli/en/docs/developing/service-discovery/) of copilot, but I could not connect.

My `.workspace` and manifest file is here.

```
application: chronos
```

```yaml
name: rails
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck:
    path: '/'
    healthy_threshold: 2
    unhealthy_threshold: 2
    interval: 5s
    timeout: 2s
  targetContainer: 'nginx'

image:
  build:
    dockerfile: ./Dockerfile.prod
    args:
      RUBY_VERSION: 3.0.1
      BUNDLER_VERSION: 2.2.16
  port: 3000

cpu: 256 
memory: 512
count: 1

exec: true

sidecars:
  nginx:
    image: aws_account_id.dkr.ecr.ap-northeast-1.amazonaws.com/chronos/nginx:latest
    port: 80
    variables:
      RAILS_HOST: http://rails.chronos.local:3000

variables: 
 RAILS_LOG_TO_STDOUT: true

environments:
  dev:
    secrets:
      RAILS_MASTER_KEY: /copilot/chronos/dev/secrets/RAILS_MASTER_KEY
  staging:
    secrets:
      RAILS_MASTER_KEY: /copilot/chronos/staging/secrets/RAILS_MASTER_KEY.
```

My Nginx configuration (`/etc/nginx/conf.d/default.conf`) here.

```
server {
   listen      80;
   server_name localhost;

   root  /home;
   index index.html;

   access_log /var/log/nginx.access.log;
   error_log  /var/log/nginx.error.log;

   location @rails {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_redirect   off;
      proxy_pass       http://rails.chronos.local:3000; # proxy request to Rails container
   }
}
```

I get error message in CloudWatch.

```
nginx: [emerg] host not found in upstream "rails.chronos.local" in /etc/nginx/conf.d/default.conf:29
```

How can I connect from Sidecar container to Rails container? Or, Should I create new Nginx service to proxy request to Rails?
