### ISSUE TITLE
COMMAND_EXECUTION_ERROR Message: Error while executing command: for workload in $WORKLOADS; do

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2371]
I have created a new pipeline for a project with three services. After running `copilot pipeline update` the build fails with

`COMMAND_EXECUTION_ERROR Message: Error while executing command: for workload in $WORKLOADS; do`

See attached log from the failed build. Sorry for the weird spacing, an artifact of the copy/paste for some reason

[buildlog.log](https://github.com/aws/copilot-cli/files/6532397/buildlog.log)

**Comment by iamhopaul123** [comment]
Hello @mikelhamer. It seems like the codebuild was not able to find the dockerfile for your services. For example:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /codebuild/output/src141988787/src/apps\\main-api\\Dockerfile: no such file or directory
```
Can you try to set up the correct dockerfile path to see if it works? Thank you!

**Comment by mikelhamer** [comment]
Hi @iamhopaul123 . I have correct Dockerfile paths set up for all three services. Deploying with `copilot svc deploy` works just fine.

My directory structure is like
- apps
worker-api
frontend
main-api
- copilot 
worker-api
frontend
main-api

With all Dockerfiles located at apps/\<directory\>/Dockerfile

and in the manifests defined like

``` yaml
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: apps\main-api\Dockerfile
```
