### ISSUE TITLE
Deploy failure after adding http.alias

### ISSUE THREAD

**Issue by oldsj** [aws/copilot-cli#2390]
## Copilot version version: v1.7.1, built for darwin

Adding a custom http.alias DNS after a service had already deployed successfully led to a deploy failure and seemed to leave my service in an unrecoverable state. I deleted the service and recreated it with http.alias already set.

`copilot svc deploy --name preview-proxy --env production`

## Error seen:

- Updating the infrastructure for stack the-people-app-production-preview-proxy    [update rollback complete]  [402.3s]  The following resource(s) failed to update: [HTTPListenerRuleWithDomain, HTTPSListenerRule, TaskDefinition].   

More info from the CloudFormation console:

HTTPListenerRuleWithDomain
CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-east-1:myaccountid:stack/the-people-app-production-preview-proxy/68e57530-be88-11eb-b424-0e5c31da0605|HTTPSRulePriorityAction|296e4f97-2f5d-45e7-9660-61e01a618527 in S3 bucket cloudformation-custom-resource-storage-useast1

HTTPSListenerRule
CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-east-1:myaccountid:stack/the-people-app-production-preview-proxy/68e57530-be88-11eb-b424-0e5c31da0605|HTTPSRulePriorityAction|296e4f97-2f5d-45e7-9660-61e01a618527 in S3 bucket cloudformation-custom-resource-storage-useast1

## manifest.yml

```
# The manifest for the "preview-proxy" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: preview-proxy
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  alias: 'people-preview.example.com'

  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  healthcheck: '/healthz/preview-proxy'

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: copilot/preview-proxy/Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

# Optional fields for more advanced use-cases.
#
#variables:                    # Pass environment variables as key value pairs.
#  LOG_LEVEL: info

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
```
