### ISSUE TITLE
Support s3 config-file-type in FireLens Sidecar

### ISSUE THREAD

**Issue by kokuyouwind** [aws/copilot-cli#2392]
I want to use my FluentBit configuration file, original FireLens configuration supports `config-file-type` with `s3`, but copilot sidecar is hard-corded with `file`.
Ref: 
  * [Specifying a custom configuration file](https://docs.aws.amazon.com/AmazonECS/latest/userguide/firelens-taskdef.html)
  * [copilot-cli/templates/workloads/partials/cf/sidecars.yml](https://github.com/aws/copilot-cli/blob/mainline/templates/workloads/partials/cf/sidecars.yml#L8)

Workaround:

Build `fluentd` image with my configuration file and use `configFilePath` opiton.

Proposal:

Add `configFileType` option to `logging` key.

```yaml
logging:
  configFileType: s3 | file
  configFilePath: <config file s3 path> | <config file local path>
```
