### ISSUE TITLE
Performance of ECS cluster deployed using Copilot is slow using default VPC

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2407]
We have successfully deployed our app to ECS using copilot. We have a test and a prod environment and everything works fine.

However, the performance of the endpoints seems to be strangely low.

Here is a simple load test example:

ab -n 500 -c 100 http://[::1]:5000/api/user/health

Requests per second:    459.59 [#/sec] (mean)

This is localhost, using local MongoDB.

The same test in our prod env produces much worse results:

Requests per second:    69.40 [#/sec] (mean)

The prod env uses a MongoDB Atlas M10 cluster and the following Copilot config:

```
    cpu: 1024
    memory: 3072
    count:
      range:
        min: 1
        max: 4
        spot_from: 3
      cpu_percentage: 70
      memory_percentage: 80
      response_time: 2s
```
This endpoint doesn't perform DB requests, it just checks if a DB connection is exists.
Other endpoints performing actual queries produce similar results.

In my opinion, the performance should much higher, isn't that correct? Our prod env should be able to scale up to 4 instances, it is load balanced etc. It should be able to do a lot more than 60 req / sec.

My question is, how could I improve the performance? What AWS resources / docs should I look into?

We created these environments using the default network config and VPC Copilot installs. No customisation there. Maybe this is the problem?

Any suggestion would be appreciated!

Thanks in advance!
