### ISSUE TITLE
RDS: Specifying environment specific configurations in RDS addon template

### ISSUE THREAD

**Issue by paulca** [aws/copilot-cli#2432]
I have an RDS cluster set up for my app, with the following default configuration:

```teamtitoclusterDBAutoPauseSeconds:
    Type: Number
    Description: The duration in seconds before the cluster pauses.
    Default: 1000
```
    
However, I'd like to have a much longer time before autopausing the production environment.

Is it possible to split out the setting for different environments?

I tried adding the autopause setting to the `mappings` section, but that didn't work.

(I've looked further down the file and now I see that `mappings` is used within the spec ... is it as simple as doing the same there?)

**Comment by Lou1415926** [comment]
Hi pualca!

Yes! You can add a new name-value pair to the `Mappings` section:
```yaml
  <workload name>EnvScalingConfigurationMap: 
   <env1>:
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 8 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBAutoPauseSeconds": 3000 # <- 
      
    <env2>:
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 8 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBAutoPauseSeconds": 1000 # <- 
      
    All:
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 8 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBAutoPauseSeconds": 1000 # <- 
```
and then for the cluster resource,
```yaml
        # Replace "All" below with "!Ref Env" to set different autoscaling limits per environment.
        MinCapacity: !FindInMap [backendclusterEnvScalingConfigurationMap, All, DBMinCapacity]
        MaxCapacity: !FindInMap [backendclusterEnvScalingConfigurationMap, All, DBMaxCapacity]
        SecondsUntilAutoPause: !FindInMap [backendclusterEnvScalingConfigurationMap, All, DBAutoPauseSeconds] # <- 
``` 
Feel free to remove DBAutoPauceSeconds from your `Parameter` sections if you no longer need it!
