### ISSUE TITLE
Expose AWS account ID in test stage

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#2445]
Test commands execution in pipeline stage doesn't have access to AWS::AccountId variable.
As a result, when running a docker image in tests section, we have to hardcode account number as below:
```
stages:
    - name: gautam
      test_commands:
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789000.dkr.ecr.us-east-1.amazonaws.com
        - docker run 123456789000.dkr.ecr.us-east-1.amazonaws.com/vault/jasper-e2e:cicdtest
```

Can we expose this variable in test specific code build?
