### ISSUE TITLE
Cannot create DynamoDB table with Partition key less than 3 characters

### ISSUE THREAD

**Issue by asquithea** [aws/copilot-cli#2475]
I am trying to `storage init` for DynamoDB to match an existing schema (see below).
When prompted for the Partition key, CoPilot refused to accept `Id`, which is the key used in existing deployment.

Error message: `Sorry, your reply was invalid: value must be between 3 and 255 characters in length`

I have read https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-naming-rules and I see that names for tables and secondary indexes must be at least 3 characters long, but there is no such limitation on the key attributes if I've read it correctly, and my current scheme has caused no issues so far in either the API or console.

Would be great if this check were adjusted to match.

The workaround is to add a dummy key and patch the manifest afterwards. 

Current schema:
```yaml
Table:
  AttributeDefinitions:
  - AttributeName: Id
    AttributeType: S
  - AttributeName: Te
    AttributeType: N
  - AttributeName: Tsx_Sid
    AttributeType: S
  TableName: eaha-rta-demo-indexes
  KeySchema:
  - AttributeName: Id
    KeyType: HASH
  - AttributeName: Tsx_Sid
    KeyType: RANGE
  TableStatus: ACTIVE
  CreationDateTime: '2021-06-16T23:52:19.503000+01:00'
  ProvisionedThroughput:
    NumberOfDecreasesToday: 0
    ReadCapacityUnits: 0
    WriteCapacityUnits: 0
  TableSizeBytes: 0
  ItemCount: 0
  TableArn: arn:aws:dynamodb:eu-west-2:xxxxxx:table/aaaaaa
  TableId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  BillingModeSummary:
    BillingMode: PAY_PER_REQUEST
    LastUpdateToPayPerRequestDateTime: '2021-06-16T23:52:19.503000+01:00'
  LocalSecondaryIndexes:
  - IndexName: Key_Te_index
    KeySchema:
    - AttributeName: Id
      KeyType: HASH
    - AttributeName: Te
      KeyType: RANGE
    Projection:
      ProjectionType: INCLUDE
      NonKeyAttributes:
      - Ts
      - S01
      - S00
      - S03
      - Sid
      - S02
    IndexSizeBytes: 0
    ItemCount: 0
    IndexArn: arn:aws:dynamodb:eu-west-2:xxxxxx:table/aaaaaa/index/Key_Te_index
```
