### ISSUE TITLE
entrypoint and command not applied with environment specific configuration

### ISSUE THREAD

**Issue by MiLk** [aws/copilot-cli#2481]
I've just started to use ECS/Fargate yesterday, and thanks to Copilot it has almost been painless.
However, I encountered an issue.

I'm deploying a python application, where each service I want to deploy to ECS is using a different module of the said app.
So I have a common docker image with `ENTRYPOINT ["pythom", "-m"]` in my Dockerfile.
And then for each service, I want to override `command`.

I've seen it has been added a couple of months ago through #1999 and #2009.

I've created a manifest like this:
```yaml
name: service1
type: Backend Service
command: ["app.service1"]
image:
  build: Dockerfile

...

environments:
    production:
      variables:
        ...
```

If I run `copilot svc package`, I get the `command` read and I get a `Command` parameter in the cloudformation template, and no custom environment variables.
Now, if I run `copilot svc package -e production`, I get the environment variables, but no `Command` parameter.

As a workaround, I've put my `command` under `environments.production`, but I was not expecting to have to do that.

I'm thinking something is wrong in the substitution after resolving environment specific configuration.
