### ISSUE TITLE
How to share RDS resource between services

### ISSUE THREAD

**Issue by myorbitmg** [aws/copilot-cli#2495]
Hi

I'm really liking the new tool. One issue I'm having is granting access to a MySQL DB between several services within the same application.

Is this possible using the CLI? My only work around is assigning security groups after deploying a service, which is far from ideal.

Trying to create a new add on RDS with the same details creates a new DB, rather than pickup the existing instance.

Thanks

**Comment by Lou1415926** [comment]
Hi myorbitmg! 

There is a `<App>-<Env>-EnvironmentSecurityGroup` that's assigned to all services. After copilot generates the addon template for you, you can modify the template and add this security group to the ingress rule of the cluster's security group. Here is a snippet that may work for you:
```yaml
  <clusterName>DBClusterSecurityGroup: # replace <clusterName> 
    Metadata:
      'aws:copilot:description': 'A security group for your DB cluster <cluster>' # replace <clusterName> 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the database cluster.
      SecurityGroupIngress:
        - ToPort: 5432
          FromPort: 5432
          IpProtocol: tcp
          Description: !Sub 'From the Aurora Security Group of the workload ${Name}.'
          SourceSecurityGroupId: !Ref backendclusterSecurityGroup
        - ToPort: 5432 # The additional ingress rule that you can add for other service to access the cluster
          FromPort: 5432
          IpProtocol: tcp
          Description: From Environment Security Group
          SourceSecurityGroupId: 
            Fn::ImportValue: 
              !Sub '${App}-${Env}-EnvironmentSecurityGroup'
```
With this ingress, the cluster's security group will allow access from all services deployed in the environment. 

---

> Edit: I can see how the following section can be a little confusing to readers with the sudden introduction of "second". Here I meant any services that need to access the DB & is not the service that the DB deployed with. For example, if the DB is an addon for service `orders`, then if service `cart` also need to access the DB, it will need the following snippet in `cart`'s manifest.

You probably have had your own solutions for accessing the db credentials from a second service 🥳 , but here is a suggestion for folks with the same ask:
1. Note down the ARN of the db credential secret that we've created and outputed for you from the CloudFormation stack.
2. Inject the secret by specifying 
```yaml
secrets:
  DBCREDENTIAL: <secret ARN>
```
in the service's manifest. Then you can access the secret via the environment variable `DBCREDENTIAL` from your code.

**Comment by myorbitmg** [comment]
Thanks for the feedback. This looks to work 👍

**Comment by coopsmoss** [comment]
Thank you for that explanation @Lou1415926. As a follow up, I'm struggling to set up the secrets for two environments.
This works fine when `secrets` is at the root level.
```
secrets:
  MYRDSCLUSTER_SECRET: arn:aws:secretsmanager:us-east-.....testsecretarn
```
But the follow does not.

```
environments:
  prod:
    secrets:
      MYRDSCLUSTER_SECRET: arn:aws:secretsmanager:us-east-.....prodsecretarn
  test:
    secrets:
      MYRDSCLUSTER_SECRET: arn:aws:secretsmanager:us-east-.....testsecretarn
```
