### ISSUE TITLE
Unable to deploy shared load balancer on different paths in same domain

### ISSUE THREAD

**Issue by ds29** [aws/copilot-cli#2527]
Hi, first and foremost, thank you to the Copilot Team. This CLI is amazing and has saved me weeks worth of learning the in/outs of deploying a modern container based stack.

That said, I'm encountering a few issues when trying to deploy a load balancer on two different paths. My application is a simple Rails API backed by Postgres and uses a Next JS frontend. I have one environment in copilot: `staging`. I have two services defined, `backend` (the Rails API with Aurora add-on) and `frontend` (the Next JS app).

I'm using version 1.8.1 of copilot so that I could make use of the custom domain alias. My use case is to have my application served from `app.example.com`, so my manifest defines the `http.alias` as `app.example.com` for both services.

Following recommendations I read on the gitter.im room, I deployed `backend` service listening on the `/api/v1` path. Upon deployment, my service says it's available at `https://app.example.com//api/v1`. Note the extra double `//`, it seems that copilot is adding this extra `/` on it's own. When I attempted to correct that by using only `api/v1' for the path in my manifest, copilot alerted that this was invalid configuration and required the leading `/`. 🤷‍♂️

That issue aside, I then proceeded to deploy my `frontend` service listening on the root path `/` using the `http.alias` of `app.example.com`. That produces an error when it attempts to add `A-record` to the hosted zone.

Removing the `http.alias` allows the `frontend` service to be deployed to the default `frontend.staging.{app}.{domain}` path but doesn't allow me to run my application as desired.

For reference, I'm sharing my two service manifests (sanitized) below. Any help/guidance you could provide is GREATLY appreciated.

```yaml
# backend/manifest.yml
name: backend
type: Load Balanced Web Service

http:
  path: '/api/v1'
  healthcheck: '/api/v1/health_check'

build
  build: api/Dockerfile
  port: 3000

cpu: 256
memory: 512
count: 1
exec: true

secrets:
  RAILS_MASTER_KEY: RAILS_MASTER_KEY

environments:
  staging:
    count: 1
    http:
      alias: app.example.com
    secrets:
      RAILS_MASTER_KEY: /copilot/myapp/staging/secrets/RAILS_MASTER_KEY
    variables:
      RAILS_ENV: 'staging'
```

```yaml
# frontend/manifest.yml
name: frontend
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck: '/api/health'

image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: app/Dockerfile
  port: 3001

cpu: 256
memory: 512
count: 1
exec: true

environments:
  staging:
    count: 1
    http:
      alias: app.example.com
```

**Comment by iamhopaul123** [comment]
Hello @ds29. Sorry for the churn. I tried to reproduce the steps but it worked well for me. Here's what I did:

1. I created an app using domain `archercopilot.com` with the app name to be `demo` and an env named `test` and an LB service named `frontend`.
2. Part of the LB service manifest is shown as below:
``` yaml
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: 'frontend'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'
  alias: archercopilot.com
```
Then after the deployment, it showed ```✔ Deployed frontend, you can access it at https://archercopilot.com/frontend.```

Technically you should have the path to be `api/v1` without the leading "/", and I'm not sure why it shows `api/v1' for the path in my manifest, copilot alerted that this was invalid configuration and required the leading /`. Can you paste the whole error message we throw here?

Also for the other issue, is `example.com` the same domain when you created the app? If not then Copilot is not allowed to automatically help you to validate the certificate as described [here](https://github.com/aws/copilot-cli/pull/2482/files#diff-cfa49eb43e38e53f634441c85263ef902825531e7ba7e2f773cfa997b4c3ef9aR15-R25) (sorry we'll release this doc change  showing this limitation as well as manifest alias validation in our next release!) However, hopefully after https://github.com/aws/copilot-cli/pull/2413 we'll allow users to import any validated certificate so as to workaround this limitation. Thank you!
