### ISSUE TITLE
How can I deploy multiple copilot services simultaneously

### ISSUE THREAD

**Issue by shgtkshruch** [aws/copilot-cli#2528]
Hi, there. I create my deployment pipeline by GitHub Actions to customize db migration timing and with maintenance or without maintenance.

![スクリーンショット 2021-06-26 21 01 22](https://user-images.githubusercontent.com/5207601/123512301-b0e8a180-d6c1-11eb-91b5-de51ca334fc8.png)

I do parallel deploy copilot services using [`matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) feature in GitHub Actions to reduce deployment time  because of Load Balanced Web Service deployment take time 5 ~ 10 minutes.
GitHub Actions definition: https://github.com/shgtkshruch/chronos/blob/main/.github/workflows/deploy.yml
```yml
...
deploy-services:
  runs-on: ubuntu-latest
  timeout-minutes: 15
  strategy:
    matrix:
      # copilot service list
      service: [rails, admin-rails]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
  - name: Setup AWS Copilot
     run: ...
  - name: Deploy Rails service
    run: |
      copilot svc deploy \
        --app chronos \
        --env ${{ github.event.inputs.env }} \
        --name ${{ matrix.service }}
...
```

But some deployments that create/update environment level resources same time was failed. For example, initial deployment of Load Balanced Web Service could not simultaneously.
How can I deploy multiple copilot services simultaneously without errors?
