### ISSUE TITLE
proposal: add Task Definition Overrides

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#2588]
## Background
As more customers are using Copilot, our current manifest might not meet all their needs. For example in #2101, customers want `http.credential` to be configurable so as to support private repositories. Also as stated in one of our top issues with the most thumb-ups #948, it would be very helpful if they could overwrite arbitrary fields in their task definitions.

## Example Related Issues
- #948
- #1919 
- #1783 
- #2101

## UX Design
For specific fields to override, please refer to https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html
```yaml
taskdef_override:
  - path: ContainerDefinitions[0].Ulimits.HardLimit
    value: 1024
  - ContainerDefinitions[0].Ulimits.Name: some limit
  - ContainerDefinitions[0].Ulimits.SoftLimit: 512
  - RequiresCompatibilities: [FARGATE]
```

## Restriction
Users will not be allowed to modify the following fields in the task definition
- Family
- ContainerDefinition.Name (our main container name)

## Override Behaviors
- For *single-value* options like `bool`, `string`, or `int`, the new value replaces the old value.
- For *multi-value* options like `list` or `map`, Copilot concatenates both sets of values.

## Milestones
- [x] new `override` package (subject to future changes), which
  - [x] validate the override rule
  - [x] translates the override rule
  - [x] applies override rules to the unmarshalled CFN template
  - [x] unmarshals and marshals the CFN template correctly
- [x] read the override section in the `manifest` package
- [x] apply the template override in `stack` pkg
- [ ] add docs and integ tests
