### ISSUE TITLE
Proposal: Input $env into the secrets

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [aws/copilot-cli#2590]
Hi there,
This is how to use secret regarding of the guideline
```
#secrets: # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.
# You can override any of the values defined above by environment.
environments:
    prod:
      secrets: 
        DB_PASSWORD: /copilot/my-app/prod/secrets/db_password
    dev:
      secrets:
        DB_PASSWORD: /copilot/my-app/dev/secrets/db_password
```

But, as you may know that, we often have many ENV, it makes manifest duplicate code when we have many environment
```
environments:
    prod:
      secrets: 
        DB_PASSWORD: /copilot/my-app/prod/secrets/db_password
        ...
        <50 lines for 50 environments of prod>
    dev:
      secrets:
        DB_PASSWORD: /copilot/my-app/dev/secrets/db_password
        ...
        <50 lines for 50 environments of dev>
```

So, why don't we use the global secrets for the case with env like this:
```
secrets:
   DB_PASSWORD: /copilot/my-app/$env/secrets/db_password
   <50 lines for 50 environments of $env>
environments:
    prod:
      secrets: 
          <specific environment variable for prod>
    dev:
      secrets:
          <specific environment variable for dev>
```

Now, our manifest will be shorter and clear!

**Comment by efekarakus** [comment]
Hi @mvn-bachhuynh-dn ! The requests makes a lot of sense :D 

We could parse the manifest files always first with the `{{.Env}}` and `{{.App}}` data, so the slight change to the existing proposal would be:
```yaml
secrets:
   DB_PASSWORD: '/copilot/my-app/{{.Env}}/secrets/db_password'
   <50 lines for 50 environments of $env>
```
First parse, and then invoke `UnmarshalWorkload`.
