### ISSUE TITLE
Issue with overwriting environment variables in manifest

### ISSUE THREAD

**Issue by dannysteenman** [aws/copilot-cli#2613]
I have the following issue, I have a test and prod environment and use copilot pipelines to deploy to each environment. For test and prod I use different values for the secrets. So I use the following to overwrite the existing (default) variables in the manifest:

```
variables:
  MYSQL_HOST: aurora-mysql.mydbinstance.tst.aws.customer.lan
  MYSQL_PORT: 3306
  MYSQL_DB_NAME: mydbname
  ProductionTier: false
  AllowedEmails: ''
secrets:
  MYSQL_PASSWORD: "'arn:aws:secretsmanager:eu-central-1:0123456789012:secret:secret-tst-hCLUIH:password::'"

environments:
  test:
    variables:
      MYSQL_HOST: aurora-mysql.mydbinstance.tst.aws.customer.lan
  prod:
    variables:
      MYSQL_HOST: aurora-mysql.mydbinstance.prd.aws.customer.lan
    secrets:
      MYSQL_PASSWORD: "'arn:aws:secretsmanager:eu-central-1:2109876543210:secret:secrets-prd-64r8gz:password::'"
```

When I validate the cloudformation template with the command:
```
copilot svc package --name <servicename> --env prod
```

I see the right secret in the template (`arn:aws:secretsmanager:eu-central-1:2109876543210:secret:secrets-prd-64r8gz:password::`). When I deploy the change with the pipeline and check the template in cloudformation I see the secret from test `arn:aws:secretsmanager:eu-central-1:0123456789012:secret:secret-tst-hCLUIH:password::`

Did I do something wrong in the setup of the manifest? 

Edit: I'm running app version: v1.0.1. I have some other copilot pipelines running for other containers and there the environment vars are set correctly.

**Comment by dannysteenman** [comment]
Update:
The pipeline was running copilot v1.8.0 in the buildspec. Once I updated to v1.8.3 the issue was immediately fixed and now prod has the correct environment variables.

Now I see it in the build release update:
https://github.com/aws/copilot-cli/releases/tag/v1.8.1
```
Apply environment overrides when running svc package and job deploy (#2476)
This ensures that the appropriate variables and secrets are applied to each environment with pipeline deployments
```
Is it possible to introduce a command or github action automation to update the copilot version in our deployed copilot pipeline? Otherwise when people do an initial deploy of the copilot pipeline, they'll be stuck with that specific version that they deployed unless they manuelly check and update the version in the buildpec in the copilot folder of your repository.

**Comment by efekarakus** [comment]
Hi @dannysteenman 👋 

I'm glad you got it working! 

> Is it possible to introduce a command or github action automation to update the copilot version in our deployed copilot pipeline? 

This makes a lot of sense, @adamjkeller's proposal in #1583 is related where we can hide the buildspec.  
Perhaps, a related solution might be defining some rules for which copilot binary to use in `pipeline.yaml`:
```yaml
build:
  copilot_version:  1.8.x # always upgrades the patch releases
  # copilot_version: 1.x # always upgrades minor releases.
```
