### ISSUE TITLE
Service update taking a long time

### ISSUE THREAD

**Issue by buddhike** [aws/copilot-cli#2619]
Hey, 
I have a very basic app that I deploy as a `Backend Service` using the manifest below.

```
name: idgen
type: Backend Service

image:
  build: Dockerfile
  port: 8080
  healthcheck:
    command: [ "CMD-SHELL", "curl -f http://localhost:8080/healthcheck || exit 1" ]
    interval: 10s
    retries: 2
    timeout: 5s
    start_period: 0s

cpu: 1024
memory: 2048
count: 2
exec: true
entrypoint: [ gopi, idgen, --port, 8080 ]

network:
  vpc:
    placement: private
```

As you can see in the log snippet below, when I run `copilot svc deploy` to update the service, it takes a long time (218.8s).

```
✔ Proposing infrastructure changes for stack gopi-team-demo-idgen
- Updating the infrastructure for stack gopi-team-demo-idgen                  [update complete]  [218.8s]
  - An ECS service to run and maintain your tasks in the environment cluster  [update complete]  [195.3s]
    Deployments
               Revision  Rollout      Desired  Running  Failed  Pending
      PRIMARY  6         [completed]  2        2        0       0
  - An ECS task definition to group your containers and run them on ECS       [delete complete]  [0.0s]
✔ Deployed idgen, its service discovery endpoint is idgen.gopi.local:8080.
```

Is there anything I should do to make it quicker?
