### ISSUE TITLE
Add ability to override log retention period for ECS logs

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#2622]
Hi All,
Firstly, Thank you for such an awesome open-source product.
Creating this new feature request to add flexibility in log retention period.

Currently copilot sets 30 days log retention period for ECS task logs.
Can we add a flag to ensure we can modify log retention period for these logs per environment?
This may be useful for cases where logs in PROD environment need to be retained for auditing purposes.

Proposal for changes in manifest:
```
log_retention: 30  # Default log retention period in days
environments:
  prod:
    log_retention: 90               # Number of days to retain logs for prod environment
```
