### ISSUE TITLE
Assign multiple domains to single Load Balanced Web Service

### ISSUE THREAD

**Issue by shgtkshruch** [aws/copilot-cli#2628]
Hi, there. AWS Copilot can create multiple Load Balanced Web Services those are set one custom domain.
My application handle multiple domain request to single web application, so I would like to configure multiple custom domain to single Load Balanced Web Service to reduce container services count and running cost.

Proposal for changes in manifest: `http.alias` accept array of domain strings.

```yml
http:
  alias:
    - example.com
    - admin.example.com
    - blog.example.com
    - shop.example.com
```

Or Any good ideas for assigning multiple domains to single Load Balanced Web Service?
