### ISSUE TITLE
bug: Creating app runner services from ARM machines

### ISSUE THREAD

**Issue by jsagorin** [aws/copilot-cli#2640]
Hi, 

I'm following through the basic first app https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/. Everything goes along smoothly, but the ECS Service won't deploy. I receive this message: 

 Resource handler returned message: "Error occurred during operation `ECS Deployment Circuit Breaker was triggered'." (RequestToken: XXXXXXXXXXX, HandlerErrorCode: GeneralServiceException)`        

Would anyone know where I can review deployment logs? I checked on both `copilot svc logs` and on AWS CloudWatch.

Here's a full log output
```Proposing infrastructure changes for the example-app-test environment. 
- Creating the infrastructure for the example-app-test environment.      [create complete]  [81.7s]
  - An IAM Role for AWS CloudFormation to manage resources               [create complete]  [24.6s]
  - An ECS cluster to group your services                                [create complete]  [6.4s]
  - Enable long ARN formats for the authenticated AWS principal          [create complete]  [0.0s]
  - An IAM Role to describe resources in your environment                [create complete]  [24.4s]
  - A security group to allow your containers to talk to each other      [create complete]  [5.7s]
  - An Internet Gateway to connect to the public internet                [create complete]  [13.9s]
  - Private subnet 1 for resources with no internet access               [create complete]  [16.8s]
  - Private subnet 2 for resources with no internet access               [create complete]  [16.8s]
  - Public subnet 1 for resources that can access the internet           [create complete]  [16.8s]
  - Public subnet 2 for resources that can access the internet           [create complete]  [16.8s]
  - A Virtual Private Cloud to control networking of your AWS resources  [create complete]  [13.9s]
✔ Created environment test in region ap-southeast-2 under application example-app.
Environment test is already on the latest version v1.4.1, skip upgrade.
✔ Proposing infrastructure changes for stack example-app-test-front-end 
- Creating the infrastructure for stack example-app-test-front-end                   [rollback complete]  [866.2s]
  The following resource(s) failed to create: [Service]. Rollback reques                                  
  ted by user.                                                                                            
  - Service discovery for your services to communicate within the VPC                [delete complete]    [0.0s]
  - Update your environment's shared resources                                       [update complete]    [114.2s]
    - A security group for your load balancer allowing HTTP and HTTPS traffic        [create complete]    [5.0s]
    - An Application Load Balancer to distribute public traffic to your services     [create complete]    [92.5s]
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf           [delete complete]    [2.4s]
  - A CloudWatch log group to hold your service logs                                 [delete complete]    [2.4s]
  - An ECS service to run and maintain your tasks in the environment cluster         [delete complete]    [57.8s]
    Resource handler returned message: "Error occurred during operation 'E                                
    CS Deployment Circuit Breaker was triggered'." (RequestToken: XXXXXXXXXXX, HandlerErrorCode: GeneralServiceExceptio                                
    n)                                                                                                    
    Deployments                                                                                            
               Revision  Rollout   Desired  Running  Failed  Pending                                               
      PRIMARY  4         [failed]  1        0        9       1                                                     
  - A target group to connect the load balancer to your service                      [delete complete]    [2.4s]
  - An ECS task definition to group your containers and run them on ECS              [delete complete]    [0.0s]
  - An IAM role to control permissions for the containers in your tasks              [delete complete]    [2.4s]
```

**Comment by bvtujo** [comment]
Hey @jsagorin, the circuit breaker is triggered by 9 failures in task launch. Usually that's due to failing health checks or a container which can't come up properly. Can you share your manifest and Dockerfile? 

In addition, you can find stopped task information in the ECS console for your service. If you navigate to your copilot cluster, then Services, then the Stopped Tasks tab, you can see the stopped reason for tasks that didn't come up. Can you also share the most common failure reasons for this deployment?

**Comment by jsagorin** [comment]
HI @bvtujo - sure. I can't get to the ECS logs, because the tasks aren't deployed.

Here's the Dockerfile
```
FROM public.ecr.aws/nginx/nginx:1.19
EXPOSE 80
COPY index.html /usr/share/nginx/html
```

Manifest - Manifest file is generated as part of copilot init. I've tried entries for both Dockerfile and ./Dockerfile, but both fail.
```
# The manifest for the "front-end" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: front-end
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'

# Configuration for your containers and service.
image:
  location: ./Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

# Optional fields for more advanced use-cases.
#
#variables:                    # Pass environment variables as key value pairs.
#  LOG_LEVEL: info

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.

```
