### ISSUE TITLE
Use cases for each method of injecting secrets

### ISSUE THREAD

**Issue by TillaTheHun0** [aws/copilot-cli#2651]
Heya Copilot team. This is a question about Secrets injection, not so much how to do it, but what is the use case for each method of doing it, as it seems that there are a couple prescribed ways of getting secrets securely injected into the container runtime. I want to make sure I understand the use cases of each approach, or it's really just a case of "developers choice, just be consistent".

### Approaches

First, is the CLI via `copilot secret init` which creates a secret in SSM. One can then reference this secret, by _name_, in the `manifest.yml` and Copilot will resolve the secret from SSM and inject it into the container environment.

---

Second is the approach described [here in the docs](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/):
> If you'd like to inject a secret, you can define a Secret in your template, and then add it as an Output. The secret will be injected into your container and can be accessed as an environment variable as capital SNAKE_CASE.

So I could create a secret in Cloudformation `addon` like so:

```
Resources:
  DoucmentDbClusterSecret:
    Metadata:
      'aws:copilot:description': 'A a generated secret stored in SecretsManager to use as DocumentDB Cluster Credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub "A secret to use for ${App}-${Env}-${Name} DocumentDb credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "foodbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: copilot-application
          Value: !Ref App
        - Key: copilot-environment
          Value: !Ref Env
        - Key: copilot-service
          Value: !Ref Name
Outputs:
  DoucmentDbClusterSecret:
    Description: The credentials used to access the DocumentDB cluster
    Value: !Ref DoucmentDbClusterSecret
```

and Copilot will inject the secret into the container runtime, resolving it from Secrets Manager.

---

Lastly, similar to the 2nd approach, is an approach I saw in an example [here](https://github.com/aws/copilot-cli/discussions/2011#discussioncomment-651417) where an SSM secret is created directly in Cloudformation `addon` and then referenced in the `manifest.yml`.

```
Resources:
  # Redis endpoint stored in SSM so that other services can retrieve the endpoint.
  RedisEndpointAddressParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${App}/${Env}/${Name}/redis'
      Type: String
      Value: !GetAtt 'Redis.RedisEndpoint.Address'
```

So **TL;DR**:
1. `copilot secret init` and update `manifest.yml`
2. Create `AWS::SecretsManager::Secret` and add as `Output` to Cloudformation `addon`
3. Create `AWS::SSM::Parameter` and update `manifest.yml`

### My Question Is

What is the intended use case for each of these different approaches? Are any of these obsolete given new Copilot features/approaches?

Seems to me that 1 is for if I just need a secret value, that my service uses at runtime, but no other resources need.

Seems to me that 2 is for if you need to pass a secret into another CF resource and so need the secret, right then, in CF.

Seems to me that 3 is for if you want to store an output of a CF resource as a secret and automate it via CF.

This is all speculation on the use cases, but assuming i'm correct, all of these approaches can be used to accomplish the use case of another approach, with some tweaking. I assume i'm not the only one asking this question, so figured i'd consult the source! Thanks everyone.
