### ISSUE TITLE
Logs appear to be delayed until container shutdown

### ISSUE THREAD

**Issue by jlucas91** [aws/copilot-cli#2679]
Hi! On a trivial scheduled job setup, I'm seeing - what appears to be - my logs being delayed until the container shuts down.

I setup a python scheduled job that every minute:
1) Prints the current time.
2) Sleeps for 30 seconds.
3) Prints end of job. 
4) Terminates.

When viewing the logs in ECS it appears that the logs are only forwarded off the container when the container is shutdown. The log timestamps are all are at the same time, roughly correlating when the task completed, but the time in the print statements reflect the _actual_ time they were created. See an example below:

<img width="711" alt="Screen Shot 2021-07-30 at 12 45 58 PM" src="https://user-images.githubusercontent.com/3912019/127685400-49b70689-e282-4abf-b221-1afc1beddb98.png">

FWIW I'm also seeing a similar issue using a copilot logging config forwarding to datadog in the primary application container. In that case, it appears the logs are forwarded on container shut down or roughly every 30 minutes. There are more moving parts there though, so I'm hoping the simple periodic job is easier to debug. 

Here's the copilot config for the job:

```
name: test
type: Scheduled Job

on:
  schedule: "@every 1m"

image:
  build:
    dockerfile: ./Dockerfile
    context: .
    target: deployed

command: ["python", "test.py"]

cpu: 256
memory: 512
```

Any advice or guidance would be appreciated! I'm not sure if this is a copilot specific problem - I'd appreciate being pointed in the right direction if it's not.

**Comment by bvtujo** [comment]
Hey @jlucas91, so sorry you're experiencing this. At first glance it looks like this may be an artifact of how we create resilient scheduling with [Step Functions State Machines](https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html). I think that this may be how step functions works--unfortunately, the logs may only be written to CloudWatch after the state containing the job terminates. I will try to investigate and reproduce and get back to you, though.

**Comment by jlucas91** [comment]
Got it - thanks @bvtujo ! Appreciate the context. Probably not the end of the world for my use case and good to know it's not an issue on our end. Curious if y'all see it as a problem for copilot's users more broadly? I could imagine that being inconvenient for longer running jobs.

In other news - while doing some testing I converted the job to a service and am seeing a similar issue. I'm running the same print statements in a `while True:` loop and now am seeing no logs at all. I would expect to see logs in cloudwatch based on the ECS screenshot below. Is there anything obvious I'm missing?

<img width="364" alt="Screen Shot 2021-07-30 at 6 16 48 PM" src="https://user-images.githubusercontent.com/3912019/127716806-7344257f-2701-4f06-9a6f-8f458167d454.png">


Here's my copilot config:
```
name: test
type: Backend Service

# Your service does not allow any traffic.

# Configuration for your containers and service.
image:
  build:
    dockerfile: ./Dockerfile
    context: .
    target: deployed

command: ["python", "test.py"]

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
```
