### ISSUE TITLE
Copilot unable to find/retrieve project in GitHub Actions

### ISSUE THREAD

**Issue by josefaidt** [aws/copilot-cli#2680]
Hello team :wave: I'm trying to deploy my service from GitHub Actions and have been able to install the binary, execute with credentials, etc.. However, I'm receiving a few odd errors depending on what command I run and I'm not sure where to begin debugging. It does appears to properly authenticate.

There are two envs, `main` and `next`, which have both been deployed manually and confirmed running. I've replaced the app name and service name with something readable for this example.

My action:

```yml
# .github/workflows/deploy-next.yml
name: Deploy
on:
  push:
    branches:
      - next
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - name: Install copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.9.0/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Deploy service
        run: copilot deploy --env next
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

If I run `copilot env ls` in the action I get the following error:

```
✘ couldn't find an application named MyApplication in account xxx and region us-east-1
```

When running `copilot deploy --env next` I receive:

```
✘ select service or job: no jobs or services found
```

When running `copilot svc deploy --env next` I receive:

```
✘ get environment next configuration: couldn't find environment next in the application MyApplication
```

Finally if I run `copilot deploy --name MyApplication --env next`

```
retrieve MyApplication from application MyService: get workload: couldn't find MyService in the application MyApplication
```

This last error is interesting because the first half seems backwards(?).

Locally I've confirmed the services are in fact part of this account and region, so I'm unsure if I'm supplying sufficient credentials/information. The env vars _seem_ sufficient since it's able to log my account ID and region, but appears to fail fetching regardless. I'm not sure if this is a bug so much as a misconfiguration on my part, though I'm having trouble identifying the missing piece(s).

**Comment by kohidave** [comment]
Hiya!!! One question - are the credentials you're passing for the environment account? Copilot expects them to be for the application account 😄 I'll take a deeper look later but if you could let me know I'd appreciate it!!

**Comment by josefaidt** [comment]
Hey @kohidave it's an IAM user with full admin access but it is not the user I initially deployed with. I'm not sure if that answers your question 😕

**Comment by kohidave** [comment]
Are all your environments in the same aws account? Also make sure the region in your gh action is the same as in your local environment. 

You can run `aws configure get region ` to determine the region running on your computer. 

Can you also call `aws get-caller-identity` to ensure that the account returned there is the same as the one running in your GH action?

**Comment by josefaidt** [comment]
Hi @kohidave yes all environments are under the same account. Oddly enough, if I switch the local AWS profile in use to my deploy user I can list the AppRunner services with `aws apprunner list-services` and they show the correct account, but I am unable to run `copilot` commands similar to what I was experiencing in the GH action. `copilot` commands were working before, however it might have been using my default profile which is under a different account (same region, though), but I do still see the service in the correct account.

**Comment by Lou1415926** [comment]
Hello @josefaidt!

You mentioned that your application might have been deployed to a different account, is that correct?

For commands like `copilot env ls`, Copilot will try to access to your application resources. If your application is deployed in a different account than the account you specified via
```yaml
...
AWS_REGION: us-east-1
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
...
```
then you will need the credentials for the account that your application was deployed with, instead of this one that your environments are deployed with.

For more, [here](https://aws.github.io/copilot-cli/docs/credentials/) is the recommended way to set up your credentials!
