### ISSUE TITLE
Import and use an existing certificate for my domain.

### ISSUE THREAD

**Issue by makies** [aws/copilot-cli#2694]
I have a wildcard SSL certificate on AWS ACM.  When deploying, copilot does not use this certificate, creates another certificate and attempts DNS authentication, but it is not authenticated.

We want to import and use an existing certificate for my domain.

(Japanese)
AWSのACMでワイルドカードのSSL証明書を保持しています。デプロイする時に、copilotは、この証明書を使わずに、別な証明書を作成し、DNS認証を試みますが、それは認証されません。

独自ドメインの既存の証明書をインポートして使いたいです。

**Comment by efekarakus** [comment]
Hi @makies ! Thank you for the feature request, it makes a lot of sense.

@iamhopaul123 on the team had started on this feature before 😬 https://github.com/aws/copilot-cli/pull/2413
We should be able to resurrect the changes 🧟  and continue from there!

**Comment by heyheman11** [comment]
+1 on this issue, seems very hacky to get containers running over https if your domain isn't currently hosted on AWS

**Comment by chriskuech** [comment]
@heyheman11 , were you ever able to get https containers running without hosting the domain on AWS?  I'm desperate for a solution.  It seems as though we cannot use a reverse proxy container as the healthchecks are http and only one port is supported.

**Comment by heyheman11** [comment]
@chriskuech I followed the instructions from a previous reply from the team at AWS but here is a brief overview of what I did:

**1.** Ensure manifest.yml looks something like this (ensure container only exposes port 80):

```yml
http:
  path: "/"
  healthcheck:
    path: "/health_check/"
    success_codes: "200"

image:
  build:
    context: ./project
    dockerfile: ./project/Dockerfile
  port: 80
```

**2.** Create a certificate in ACM or import an exisiting one for the desired domain

**3.** Create a new listener rule on the existing load balancer that listens on port 443, use the certificate from step 2 and copy all rules from the existing rule.

**4.** Go to your DNS provider and create a new `CNAME` record to point to the ELB address

Essentially the https connection is terminated at the listener, and my server in the container only listens for http traffic on port 80.

**Comment by chriskuech** [comment]
This seems to be a valid template snippet for what you are describing and it passes a linter, but fails in cloudformation with a "AWS::ElasticLoadBalancingV2::ListenerRule Validation exception", but doesn't seem to show anywhere what the actual validation issue is.

Any idea what I'm doing wrong?

```yaml
  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !FindInMap [EnvMap, !Ref Env, CertificateArn]
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroupStickinessConfig:
              Enabled: false
            TargetGroups:
              - TargetGroupArn:
                  !FindInMap [EnvMap, !Ref Env, LoadBalancerDefaultTargetArn]
                Weight: 1
          TargetGroupArn:
            !FindInMap [EnvMap, !Ref Env, LoadBalancerDefaultTargetArn]
      LoadBalancerArn: !FindInMap [EnvMap, !Ref Env, LoadBalancerArn]
      Port: 443
      Protocol: HTTPS

  HttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroupStickinessConfig:
              Enabled: false
            TargetGroups:
              - TargetGroupArn:
                  !FindInMap [EnvMap, !Ref Env, LoadBalancerRouteTargetArn]
                Weight: 1
          TargetGroupArn:
            !FindInMap [EnvMap, !Ref Env, LoadBalancerRouteTargetArn]
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /*
          Values:
            - /*
      ListenerArn: !Ref HttpsListener
      Priority: 50000
```
