### ISSUE TITLE
Dependency ordering being ignored

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#2723]
I'm using version 1.9.0 and am trying to have a dependency condition of "HEALTHY" for my main container on a sidecar container (for a scheduled job). The task definition being generated doesn't include any dependency ordering. Is there something I'm missing?

mainfiest for main container:
```yaml
depends_on:
  content: HEALTHY

sidecars:
  content:
    image: ...
```

**Comment by iamhopaul123** [comment]
Hello @bpottier. It seems like the manifest is not configured properly. Could you refer to [this example](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-depends-on)?

**Comment by efekarakus** [comment]
Hi @bpottier 👋 

Is it possible to modify the manifest like this to see if the dependency works?
```yaml
image:
  depends_on:
     content: HEALTHY
```

Thanks!
