### ISSUE TITLE
Feature request: Enable VPC connectivity when running tests in CICD

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#2739]
When running tests in CICD, they do not have access to resources in VPC.
This access would be helpful in some scenarios. (Running integration tests against DB deployed in VPC OR hitting internal APIs of services which are not exposed outside VPC).

Can we add option to provide connectivity between VPC and code build test stage?
I am thinking of something like below:
```
stages:
    - name: dev
      test:
        config:
          vpc_connectivity: true
        commands:
          - echo "Tests!"

    - name: test
      test:
        commands:
          - echo "Tests!"
```

**Comment by efekarakus** [comment]
This is cool idea thanks for creating the issue! 

I assume that means that the test commands build project needs to be created in the same region and account as where the environments are 🤔 
I don't think we do that today, we're creating the build projects in the same account and region as the pipeline. We'd need to think of a way around that I think

**Comment by gautam-nutalapati** [comment]
In case anyone else needs this feature, I followed the approach in https://docs.aws.amazon.com/codebuild/latest/userguide/vpc-support.html
Based on this, Code build will need to be deployed in private subnets in VPC. They have access to internet via NAT (Internet GateWay is not supported). They need a no-ingress security group which we linked to copilot EnvironmentSG.
 
Above infrastructure (public and private subnets, RTs, SGs, CodeBuild role etc.): https://gist.github.com/gautam-nutalapati/32476596a5b01708550444438a244810. This is deployed via add-ons of a startup service that gets deployed in each new ENV. This infrastructure gets created per ENV in respective accounts.

For each service deployment, we added add-on that creates code builds: https://gist.github.com/gautam-nutalapati/f7cde2f44c562eba3959535f41750c44

And I [modified copilot pipeline](https://github.com/gautam-nutalapati/copilot-cli/tree/prisidio-1.9.0) to below, when these keys are included, copilot adds these CBs in pipeline stages.
```
      name: dev-local
      # Optional: use pre_deploy_code_builds or post_deploy_code_builds to link code builds in pipelines stages
      #                 code_builds_service_role is common service role used by specified code builds that should trusts this pipeline.
      #                 Ensure below code build pipelines and roles deployed before running 'pipelin update' command
      pre_deploy_code_builds:
        - vault-ENV-SVC-PreDeployIT
      post_deploy_code_builds:
        - vault-ENV-SVC-PostDeployIT
      code_builds_service_role: arn:aws:iam::***:role/vault-ENV-IT-CodeBuildRole
```
