### ISSUE TITLE
Feature request: build project role addon policies

### ISSUE THREAD

**Issue by joshgoodson** [aws/copilot-cli#2755]
It is well documented that you can create an addon with a ManagedPolicy resource and an Output definition and this policy will be injected into the ECS Task Role. As documented on this page: https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#what-does-an-addon-template-look-like

> If you need to add additional policies to your ECS task role, you can define an IAM ManagedPolicy resource in your template that holds the permissions for your task, and then add it as an Output. The permission will be injected into your ECS Task Role.

I am working with pipelines and wish to add permissions to the CodeBuild Build Project Role so I can grant, for example, cross-account CodeArtifact access and allow the Build Project Role to perform a login similar to:

`aws codeartifact login --tool pip --repository artifacts --domain <domain> --domain-owner <owner>`

I asked about this in the the project discussion: https://github.com/aws/copilot-cli/discussions/2535

It seems this is not something that is currently supported.

Proposal:
Offer a way to configure Outputs for addon templates that can attach to the Build Project Role and continue to support Task Role injection as well.

**Comment by efekarakus** [comment]
Hi @joshgoodson 👋 

The feature request makes total sense!
Would an interface like this also solve your feature request?  

1. We can add a new field to the pipeline manifest under `build` like this:
```yaml
build:
   additional_policy: # New field 'additional policy'
     document:       # Write cloudformation policy document.
       Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: '*'
```

2. This will result in the creation of a new IAM Policy resource `BuildProjectAdditionalPolicy` with the permissions provided in the manifest.
