### ISSUE TITLE
Feature Request: Allow specifying of OutputArtifactFormat in pipeline.yml

### ISSUE THREAD

**Issue by jsutton** [aws/copilot-cli#2799]
Currently, copilot doesn't specify OutputArtifactFormat, so it defaults to CODE_ZIP, not CODEBUILD_CLONE_REF. This causes problems when trying to build a project that uses submodules. If this method is chosen, it would be nice to include an option to add a full clone including submodules to the buildspec.yml.

The other option would be to add a source to the codebuild project for the repository that has "Use Git submodules" selected. This has the benefit of reducing complexity on the user but increases complexity in that there are then two source checkouts.

**Comment by jsutton** [comment]
For option1, it would be helpful to update the docs/templates for buildspec.yml to include the following:
```yaml
env:
  git-credential-helper: yes
```
and
```yaml
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # If your submodule does not use https, you may need to change it with a command like this
      - git config --file=.gitmodules submodule.<SubModulePath>.url https://git-codecommit.us-east-1.amazonaws.com/v1/repos/SubmoduleRepoName
      - git submodule update --init
```

Also, the pipeline policy and codebuild policy have to be updated:
```yaml
  BuildProjectPolicy:
    Type: AWS::IAM::Policy
    DependsOn: BuildProjectRole
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodeBuildPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        #...omitted...
          - Effect: Allow
            Action:
              - codecommit:GitPull # Needs to be added for CODEBUILD_CLONE_REF
              - codecommit:GetBranch # Needs to be added for submodules?
              - codecommit:GetCommit # Needs to be added for submodules?
              - codecommit:GetRepository # Needs to be added for submodules?
            Resource:
              - "*"
  PipelineRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodepipelinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:*
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:UploadArchive
              - codecommit:GetUploadArchiveStatus
              - codecommit:CancelUploadArchive
              - codecommit:GetRepository # Needs to be added
            #...omitted...
            Resource:
              - "*"
            #...omitted...
```

After running through a workaround implementation of this, I think option1 is probably the best way and seems to follow existing idioms.
