### ISSUE TITLE
Unmarshal error on `copilot deploy` in a fresh project

### ISSUE THREAD

**Issue by rorybyrne** [aws/copilot-cli#2823]
Hi, here's a screenshot of the steps taken to reproduce the error:

![image](https://user-images.githubusercontent.com/9436784/133063999-931e061d-c31b-4fff-a47e-7c6a0e09ed9f.png)

And here's the manifest:

```
# The manifest for the "api" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: api
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  path: '/'
  healthcheck: '/health'
  alias: api.letsmatchmums.com

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

variables:
  LETSHELP_DB_URL = "xxx"
  LETSHELP_API_KEY = "xxx"
  LETSHELP_TYPEFORM_SECRET = "xxx"
  LETSHELP_MAILCHIMP_SERVER = "xxx"
  LETSHELP_MAILCHIMP_API_KEY = "xxx"
  LETSHELP_MAILCHIMP_AUDIENCE_ID = "xxx"
  LETSHELP_MAILCHIMP_TAG_NEW_MEMBER = "xxx"
  LETSHELP_MAILCHIMP_TAG_MATCH_FOUND = "xxx"

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
```
