### ISSUE TITLE
Add host based routing for HTTP Load Balanced Web Services

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#2871]
## Ask
Customers would like to serve multiple multiple domains such as `example1.com` and `example2.com` (managed outside of route53) by the same ALB.

The goal is to have `example1.com/` route to `service1` and `example2.com/` route to `service2`.

### Programming model
I believe the way to achieve this is to modify our `HTTPListenerRule` like this:
```yaml
- Field: 'host-header' # New config that we can add.
  HostHeaderConfig:
    Values: 'example1.com'
- Field: 'path-pattern'
  PathPatternConfig:
    Values: '/*'
```

A possible way that we can surface it in the manifest is by re-using `alias` even if the application wasn't initialized with a `--domain`:
```
http:
  alias: 'example1.com'
  path: '/'
```

### Original request thread

https://twitter.com/VicVijayakumar/status/1440818181099048979
