### ISSUE TITLE
Feature Request: Custom InstanceRole permissions on manifest of Request-Driven Web Service (App Runner)

### ISSUE THREAD

**Issue by dharada1** [aws/copilot-cli#2909]
Currently we can't customize InstanceRole of Request-Driven Web Service (App Runner), so we can't let the app talk to other aws services. (e.g. dynamodb, ssm parameter store. )
If we can specify iam policies of InstanceRole on manifest file, it would be great.

https://aws.github.io/copilot-cli/en/docs/manifest/rd-web-service/
https://aws.github.io/copilot-cli/ja/docs/manifest/rd-web-service/

**Comment by dharada1** [comment]
As a workaround, we can attach policy to the instance role directory on aws console. 
It won't be removed when you do `copilot svc deploy`.

(( This is not preferable because it's not declarative on manifest.

**Comment by efekarakus** [comment]
Hi @dharada1 ! 👋 

There is a way today to do it with Copilot today and it's through the [addons/](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) feature!

For example, if you have a Request-Driven Web Service named "api". You can define additional permissions and AWS resources under the "addons" directory:
```
.
└── copilot
    └── api
        ├── manifest.yml
        └── addons/
            └── template.yml # 🆕  Create an "addons" directory and CFN template.
```
Then in the `template.yml` file if you define an IAM ManagedPolicy your instance role will be augmented with it for example:

```yaml
Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
Resources:
  MyTableAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: <ARN> # Add your Table ARN
Outputs:
  MyTableAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MyTableAccessPolicy
```

Copilot will automatically detect that the output `MyTableAccessPolicyArn` refers to an `AWS::IAM::ManagedPolicy` and will augment your InstanceRole with the additional permissions.

Hope this helps!
To learn more: 
- https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/
- https://aws.github.io/copilot-cli/ja/docs/developing/additional-aws-resources/

Alternatively, if you'd like to define the DDB Table with copilot you can also run `copilot storage init` which will automatically generate this template for you!
