### ISSUE TITLE
Allow multiple volumes with managed EFS for a single service

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#2921]
We should enable more than one `storage.volumes` with managed EFS for a single service.

## Ask
Original ask: https://github.com/aws/copilot-cli/issues/1559#issuecomment-942496804

Today users are limited to a single EFS access point per service:
```yaml
storage:
  volumes:
    frontend:
      efs:
        uid: 123
        gid: 123
      path: /var/data
```
If they try to use the same EFS filesystem for multiple volumes like this:
```yaml
storage:
  volumes:
    v1:
      efs:
        uid: 123
        gid: 123
      path: /etc/mount1
    v2:
      efs:
        uid: 456
        gid: 456
      path: /etc/mount2
```
We return the following error:
```
validate "storage": cannot specify more than one managed volume per service
```

## Programming model

1. In order to support multiple access points for a single service we need to transform the following resource into a list:
https://github.com/aws/copilot-cli/blob/2cc2403b5f69e63c4f4d61f2b8065cc45b2097b9/internal/pkg/template/templates/workloads/partials/cf/efs-access-point.yml#L2-L3
2. We need to assign a new `RootDirectory.Path` for the additional access points. Today, we hard-code it to the service name like "frontend". The proposal is to do `<svcName>-<volumeName>`.
https://github.com/aws/copilot-cli/blob/2cc2403b5f69e63c4f4d61f2b8065cc45b2097b9/internal/pkg/template/templates/workloads/partials/cf/efs-access-point.yml#L13-L14
3. Update the IAM policy in the TaskRole to grant access to multiple access points:
https://github.com/aws/copilot-cli/blob/2cc2403b5f69e63c4f4d61f2b8065cc45b2097b9/internal/pkg/template/templates/workloads/partials/cf/taskrole.yml#L72-L74

**Comment by FraserThompson** [comment]
Just in case this helps prioritize this... Multiple access points is essential for running CMSs like Drupal (probably others) which save user files in multiple locations. For example:

Public filesystem in /opt/drupal/web/sites/default/files
Private fileystem /opt/drupal/private

A single access point couldn't meet this use case. It's possible with externally managed filesystems, but having all this managed by Copilot would be much more convenient.

**Comment by efekarakus** [comment]
Hi @FraserThompson ! out of curiosity wouldn't this scenario be satisfied with:
```
storage:
  volumes:
    frontend:
      efs: true
      path: /opt/drupal
```
Or am I misunderstanding a step?
