### ISSUE TITLE
Manifest validation does not take into account final evaluated manifest

### ISSUE THREAD

**Issue by zackdotcomputer** [aws/copilot-cli#2923]
Manifest validation was introduced by PR #2881 in version 1.11.0.

However, this caused an error in my build because of the following situation. I think this setup is valid, though let me know if you disagree. Assuming it should be valid, this form of validation is too strict.

```yaml
image:
  # All configurations share this port value
  port: 3000

environments:
  staging:
    image:
      location: # some ecs URL
```

After combining settings for staging deploy, `image` is completely defined. However, the new version of copilot complains that `image` requires `location` or `build` because it validated the manifest before applying the environment-specific settings.
