### ISSUE TITLE
✘ validate manifest against environment test: validate "on": "schedule" must be specified

### ISSUE THREAD

**Issue by dannysteenman** [aws/copilot-cli#2962]
I upgraded the copilot-cli in the pipeline from: v1.8.2 to v1.11.0 and suddenly my cronjobs won't deploy anymore (on 1.8.2 it worked)

The pipeline exits on the error message:
```
✘ validate manifest against environment test: validate "on": "schedule" must be specified
✘ validate manifest against environment prod: validate "on": "schedule" must be specified
```

This is what the schedule in the manifest looks like of a typical cronjob:
```
environments:
  test:
    on:
      schedule: cron(0 0 1 1 ? 2021) # Run at midnight on January 1, 2021 # This will never occur again so the job will never run
  prod:
    on:
      schedule: "24 6 * * *" # At 06:24
```

Basically, the cronjobs have different schedules for each environment.
