### ISSUE TITLE
Question: Working with submodules

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#2989]
Hi, thanks for the useful project. It's made working with AWS a lot less overwhelming for me. 😄

I do have a question around adding a pipeline when my project includes a submodule.

I followed the instructions in #2799 about this issue, but I think im missing something.

1) Updated my `pipeline.yml` file to add output_artifact_format: CODEBUILD_CLONE_REF
```
  properties:
    branch: main
    repository: MY_REPO_URL
    output_artifact_format: CODEBUILD_CLONE_REF
```

2) Ran `copilot pipeline update`

3) Adjusted `buildspec.yml`  to add env git-credential-helper: yes AND added the submodule commands for my submodule (named shared)

```
version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      docker: 18
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - git config --file=.gitmodules submodule.shared.url https://git-codecommit.us-west-2.amazonaws.com/v1/repos/shared
      - cat .gitmodules
      - git submodule update --init
```

I'm running into a 403 forbidden error that makes me think that `https://git-codecommit.us-west-2.amazonaws.com/v1/repos/shared` isn't the right url to add there, I've tried some different combination but not sure what I'm supposed to add to that line.

Thanks for you help!

**Comment by Lou1415926** [comment]
Hello @dmathewwws!

Your `buildspec.yml` looks good to me. This is likely because the `BuildProjectRole` lacks permissions to achieve what you want. 

The CodeBuild project assumes the `BuildProjectRole` and makes request on your behalf. If it doesn't have the permission required - which is `codecommit:GitPull` - in order to add a CodeCommit repository as a submodule, you will see the 403 error.

To add the additional permission, you can:
#### Go to the CodeBuild console
1. Look for the project named `pipeline-<app name>-<pipeline name>-BuildProject`. 
2. Go to the "Build details" tab. 
3. Under the "Environment" section, look for "Service role", there should be a link to the service role, which is exactly the `BuildProjectRole` that I've mentioned above. 
#### After clicking the link, you are brought to the IAM console
1. Select "Add inline policy"
2. Select "JSON" tab
3. Copy and paste the following snippet:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "codecommit:GitPull",
            "Resource": <Replace this with the ARN for your CodeCommit repository>
        }
    ]
}
```
After this, you can trigger another build and see if it works!

**Comment by Lou1415926** [comment]
This issue so far could be possibly related to #1689 and #2755. We might need to develop a good way to natively support customizing `BuildProjectRole`.

If the above solution works for you, would you please give those two issues a thumb-up? This would help us prioritize the task!

**Comment by dmathewwws** [comment]
Thanks Wanxian!

I was able to follow your instructions, go to the IAM console and add the `codecommit:GitPull` permission. 

However I still do see the below error when I look at my build logs:
```Error retrieving Git credentials.no error: GITHUB Git credential unavailable.```

I was wonder if:
- it mattered that I am not using CodeCommit to host my repository, I am hosting the submodule on GitHub. Does that mean I need to set a different permission?

- I've added this line inside my `buildspec.yml`
```
git config --file=.gitmodules submodule.${SUBMODULE_NAME}.url https://git-codecommit.us-west-2.amazonaws.com/v1/repos/${GITHUB_USERNAME}/${SUBMODULE_NAME}
```

I guessed the url structure based on the comment in #2799. I am wondering if you think that line needed or accurate?

this is the whole first part of the `buildspec.yml` for context:
```
version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      docker: 18
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - git config --file=.gitmodules submodule.${SUBMODULE_NAME}.url https://git-codecommit.us-west-2.amazonaws.com/v1/repos/${GITHUB_USERNAME}/${SUBMODULE_NAME}
      - cat .gitmodules
      - git submodule update --init
```
