### ISSUE TITLE
Environmental variables in logging Firelens sidecar

### ISSUE THREAD

**Issue by sekamaneka** [aws/copilot-cli#2997]
Hello,

is this supported? I could find only references to the normal/storage sidecar. My Firelens sidecar doesn't have any ENV variables.. The COPILOT* ones are missing and the TEST one defined below is also missing.

```
logging:
  image: <>.dkr.ecr.eu-central-1.amazonaws.com/fluentbit:latest
  configFilePath: /extra.conf
  enableMetadata: false
  variables:
    TEST: "TEST"
```
