### ISSUE TITLE
Generate Manifest

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#3]
### Story
As a user that ran `ecs init`,   
I want to see a configuration file that captures my application configuration,   
So that I can modify the file in the future to make changes to my app's infrastructure.  

### Acceptance Criteria
The prompts should ask the user for:
1. Project name
2. Dockerfile location
3. Application type

The Manifest file should be written under `{project dir}/ecs/{app-name}-app.yml`

The spec looks like: 
```yaml

version: 1.0
# First is the Project name. The Project is the grouping of the
# environments related to each other.
project: DavidsLemons

# This is the application specific to whatever code
# is in the same Directory as this file. Optionaly, you can
# model multiple applications in one template file. They'll
# all be released together. 
applications:
    # The name of the Application. This will be used to
    # prepend resources, name tasks, name log groups, etc.
    DavidsLemonsFrontend:
      # The "Type" of the application we're running. Currently we support
      #   LoadBalancedEc2Service
      #   LoadBalancedFargateService
      #   QueueProcessingEc2Service
      #   QueueProcessingFargateService
      #   ScheduledEc2Task
      #   ScheduledFargateTask
      type: LoadBalancedFargateService
      # The port exposed through your container. We need to know
      # this so that we can route traffic to it.
      containerPort: 80
      # This specifies the location of the Dockerfile for this application.
      # We'll use ./Dockerfile by default.
      # dockerfile: ./Dockerfile
      # Size of CPU
      cpu: '256'
      # Size of memory (all these params are stollen from the construct)
      memory: '512'
      # Logging is enabled by default. We'll create a loggroup that is
      # the Project/Application/Stage
      logging: true
      # Determines whether the application will have a public IP or not.
      public: true
      # You can also pass in environment variables as key/value pairs
      environment-variables:
       dog: 'Clyde'
       cute: 'hekya'
      #
      # You can also specify the loadbalancer configuration
      # you'd like. The LB is an environment configuration, so
      # we'll look it up from the ENV stack. You can tell
      # us which rules you'd like to route to our app.
      loadbalancer:
        name: 'DavidsLemons'
        rule:
          path: '/'
      # Additional Sidecar apps that can run along side your main application
      # We won't include the sidecars section by default.
      # The shape of the sidecar structure is a subset of the
      # container definition above.
      sidecars:
        fluentbit:
            containerPort: 80
            image: 'amazon/aws-for-fluent-bit:1.2.0'
            memory: '512'

# The stages section defines, esentially, the deployment stages of
# the Pipeline, while also giving us a place to store stage specific
# configuration.
stages:
  # Test and Production are the two default stages.
  # In every stage, you can override application wide parameters by
  # overwriting values. This will be used to generate stage specific taskdefs
  - test:
      # The "environment" (cluster/vpc/lb) to contain this service.
      env: test
      # The number of tasks that we want, at minimum.
      desiredCount: 2
      # Secrets are the same as environment variables, but the name
      # is a little more clear. We can also help out by making
      # sure non-arns aren't stored here? Also, default to secretsmanager
      # because SSM is no bueno.
      secrets:
        # The individual secrets can be added here, programatically.
        # archer app add-secret
        # secret name? lemonaidpassword
        # secret value for test stage? ***
        # secret value for prod stage? ***
        lemonaidpassword: arn:aws:secretsmanager:us-west-2:902697171733:secret:DavidsLemons/DavidsFrontEnd/lemonaidpaw-jcXNEY
  - prod:
      # Again, the environment. You can put the CloudFormation stack
      # ARN instead of the short name. This allows for x-region, x-account
      # environments. Otherwise, it's realative to the Pipeline.s
      env: prod
      # Tagging a stage as production (or naming it prod) will trigger safe guards.
      # Safeguards like delete protection on CloudFormation, our own commands
      # will be more paranoid, etc. This may be an environment configuration, rather than a stage config in the future.
      production: true
      desiredCount: 2
      secrets:
        lemonaidpassword: arn:aws:secretsmanager:us-west-2:902697171733:secret:DavidsLemons/DavidsFrontEnd/lemonaidpaw-jcXNEY
```
