### ISSUE TITLE
[Design] Pipeline manifest new source pattern

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#3021]
## Problem

Right now our pipeline manifest repo field is as follow:

```yaml
source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/iamhopaul123/copilot-xray-example
```

Problem is there are all kinds of repo format given that we now support GitHub, Bitbucket, and CodeCommit (or more in future). If the user never changes the default repository we write to the manifest, it is probably fine. However, since the repository we accept for now is actually usually the repo console url, if they put a repo URL in different format (for example `ssh://` or `codecommit::`), `pipeline update` would fail because we can't parse the info we need from the URL and use it in the CFN template.

## Proposal

Instead of writing the URL to the manifest, what we can do is to provide different field set for different provider type, which would be more intuitive to users and less error prone to us. We can utilize our manifest validation to make sure their manifest is configured correctly.

### GitHub && BitBucket

```yaml
source:
  provider: GitHub
  properties:
    branch: main
    owner: <owner>
    repo: <repo name>
```

### CodeCommit

```yaml
source:
  provider: CodeCommit
  properties:
    branch: main
    repo: <repo name>
    region: <region>
```

For backward compatibility concern, we can still keep the same behavior for `repository` field, but stop writing to the new manifest to transit to the new manifest format. Also for visibility concern, we can move the repo console url to our `pipeline show`, instead of showing the URL in the manifest.
