### ISSUE TITLE
[Feature Request] Support SSM as Manifest environment variables

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#3031]
### Currently supported in copilot:
Shell environment variables and predefined variables are supported in [Manifest Environment Variables](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/)

### Requested feature:
Support SSM parameters as [Manifest Environment Variables](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/)

### Use Case:
Copilot manifest can contain attributes that are common per environment. For example, Task count per environment (services run with count of 1 in development clusters and more than 1 in PROD), Custom [security group](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#network-vpc-security-groups) for ECS tasks, [exec](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#exec) enabled in non-prod environments , [alias](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) etc.  
and a few can be common for all services like [healthcheck](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-healthcheck) attributes, LOG_LEVEL environment variable that can be used to control log level in specific environment

It will be a repetitive task to update a properties like the ones mentioned above as we need to update manifest file in all services, and need to maintain these per new service and environment, especially when we have large number of micro services under an app.

Providing a way for manifest to read the properties from SSM would automate this process.

### Proposal:
If manifest file contains cloudformation syntax `!Sub "XXX"`, copilot can pass it on to cloudformation template without intercepting it.
This is supported for keys that are directly passed on to cloudformation today. 
e.g. value provided to `image.healthcheck.interval`, `cpu`,  `environments.dev.variables` are forwarded to cloudformation template today, and hence support SSM variables. And `type` key which is used by copilot to do some processing rather than forwarding it to cloudformation is not supported.

Example manifest:
```
name: prisidio-svc-v1
type: Backend Service

image:
  build: Dockerfile
  port: 8060
  healthcheck:
    command: [ "CMD-SHELL", "curl -f http://localhost:8060/hc || exit 1" ]
    interval: 10s
    retries: 5
    timeout: 10s
    start_period: 60s

cpu: 1024 
memory: 3072
count: !Sub "{{resolve:ssm:/copilot/${App}/${Env}/service-X-task-count}}"
exec: true

variables:
  LOG_LEVEL:  !Sub "{{resolve:ssm:/copilot/${App}/${Env}/log-level}}"
  
environments:
  dev:
    variables:
      LOG_LEVEL: INFO  # Preference is still given to overrides
```
