### ISSUE TITLE
Main container can not `depends_on` logging container(firelens_log_router)

### ISSUE THREAD

**Issue by rluisr** [aws/copilot-cli#3053]
I would like to depend on `firelens_log_router` on the main container. But current copilot does not support this.
```
$ copilot deploy
✘ execute svc deploy: validate manifest against environment sbx: validate container dependencies: container firelens_log_router does not exist
```

manifest
--------
```yml
image:
  depends_on:
    firelens_log_router: HEALTHY # I think `logging stanza` does not support `healthcehck` so please ignore `HEALTHY`.

logging:
  ...
```
