### ISSUE TITLE
[Question] Is it possible to attach different security groups to different environments?

### ISSUE THREAD

**Issue by george-silva** [aws/copilot-cli#3111]
Hello all!

Here's my scenario:

* We have 1 VPC per environment.
* Each VPC can have it's own resources, like RDS databases
* Each VPC has dedicated security group that allows for database access
* These resources are managed by terraform.

In my manifest, I have 3 envs: prod, stag, qa. Since each security group is in a different VPC, we need to attach different security groups for different environments.

Example manifest today:

```
name: myservice
type: Load Balanced Web Service
network:
  vpc:
    security_groups:
      - 'sg-xxxxxxxxxxx'
http:
  ...
```

Is it possible to configure the security groups per env?

```
name: myservice
type: Load Balanced Web Service
http:
  ...
environments:
  qa:
    network:
     vpc:
      security_groups:
        - 'sg-xxxxxxxxxxx'
```

If it's not possible, what are the workarounds in this situation?
