### ISSUE TITLE
Export dead letter queue name in worker service 

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#3147]
I want to create cloud watch alarm for dead letter queue via add-ons.
Exporting dead letter queue name would help reference it in CFN template for Cloudwatch alarm.
CFN alarm for reference:
```
Resources:
  deadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${App}/${Env}/alerts/sns-topic-arn}}"
      AlarmDescription: 'Messages in dead letter queue.'
      AlarmName: !Sub "${App}-${Env}-${Name}-DLQ-count"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value: <Dead letter queue name> #<------------
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Average
      Threshold: 1.0
      TreatMissingData: breaching
      ~``

**Comment by efekarakus** [comment]
Hi @gautam-nutalapati !

I wonder if this new customizable addon parameters feature would help in this situation: https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#customizing-the-parameters-section

You can drop this new special file `addons.parameters.yml` under the `addons/` directory, where you can specify additional parameters to pass down to your addons stack

For example,
```yaml
# Contents of the addons.parameters.yml file
Parameters:
  DLQName: !GetAtt DeadLetterQueue.QueueName
```
then in your `addons/template.yml` file you can add the new parameter:
```yaml
Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  DLQName: # 🆕
    Type: String
```
