### ISSUE TITLE
Circular depenceny with !Ref `Service` in addons.parameters.yml.

### ISSUE THREAD

**Issue by thenav56** [aws/copilot-cli#3149]
Hello there, thanks for this awesome project.

I was trying to use **[ServiceName](https://github.com/aws/copilot-cli/issues/2968)** to define AutoScaling resources using custom metrics through [addons](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#customizing-the-parameters-section). Due to the dependency of Service to Task and Task to addons (due to roles, parameters, secrets), I am getting circular dependency error.
```
Circular dependency between resources: [TaskDefinition, AddonsStack, Service, TaskRole]
```

Can we define Service Name something like `'${AWS::StackName}-${Env}-${Name}-Service'` so that we can use that instead of Ref?

**Comment by efekarakus** [comment]
Hi @thenav56 !

Thank you for the detailed issue description, that makes a lot of sense and apologies for the inconvenience 🙇 

I think one downside of fixing the service name is that updating fields such as [`LoadBalancers`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html) will fail because the update requires a "Replacement".

The request makes a lot of sense 🤔 and seems to be related to #3147.
In the long term, it'd be cool if we could have a way of creating multiple `addons/` stacks for a service, perhaps something like this? Let me know what you think:
```
service-name/
   manifest.yml
   addons/ 
      template.yml              # Existing addons stack.
      addons.parameters.yml
      asg/                       # New ASG addons stack.
        template.yml
        addons.parameters.yml
      dashboard/                 # New Dashboard addons stack.
        template.yml
        addons.parameters.yml
```

-------

I've a terrible workaround that I think allows mitigating this problem until we have a longer term solution: leveraging [AWS Lambda-backed custom resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources-lambda.html) in the addons stack. The solution is really complex, so I totally understand if it's not desirable.

1. Define your custom resource to describe any resource that you want:
```yaml
ResourceDescriberFunction:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      ZipFile: >
  const response = require('cfn-response');
  const AWS = require('aws-sdk');
  exports.handler = async function(event, context) {
    const {cluster, appName, envName, serviceName} = event.ResourceProperties;
    
    // Query for the service name.
    try {
      const rgt = new AWS.ResourceGroupsTaggingAPI();
      const resp = await rgt.getResources({ResourceTypeFilters: ["ecs:service"], TagFilters: [
          {Key: "copilot-application", Values: [appName]},
          {Key: "copilot-environment", Values: [envName]},
          {Key: "copilot-service", Values: [serviceName]},
        ],
      }).promise();
      const resources = resp.ResourceTagMappingList;
      if (resources.length !== 1) { throw new Error("unexpected resource length size: " + resources.length); }
      
      const ecs = new AWS.ECS();
      const services = await ecs
        .describeServices({ cluster: cluster, services: [resources[0].ResourceARN] }).promise();
      const { serviceName } = services[0];
      response.send(event, context, response.SUCCESS, {ServiceName: serviceName});
    } catch(err) {
       response.send(event, context, response.FAILED, null, `${err.message}`);
    }
  };
    Handler: "index.handler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt ResourceDescriberRole.Arn
    Runtime: nodejs12.x
```

2. Create the `ResourceDescriberRole`:
```yaml
ResourceDescriberRole:
  Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: "DescribeResources"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: ECS
            Effect: Allow
            Action:
              - ecs:DescribeServices
            Resource: "*"
            Condition: 
              ArnEquals: 
                'ecs:cluster':
                  Fn::Sub:
                    - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}
                    - ClusterName:
                        Fn::ImportValue:
                          !Sub '${AppName}-${EnvName}-ClusterId'
          - Sid: ResourceGroups
            Effect: Allow
            Action:
              - resource-groups:GetResources
            Resource: "*"
          - Sid: Tags
            Effect: Allow
            Action:
              - "tag:GetResources"
            Resource: "*"
```

3. Create the action to trigger the Lambda function:
```yaml
ResourceDescriberAction:
  Type: Custom::ResourceDescriberFunction
  Properties:
    ServiceToken: !GetAtt ResourceDescriberFunction.Arn
    cluster:
      Fn::ImportValue:
        !Sub '${AppName}-${EnvName}-ClusterId'
    appName: !Ref AppName
    envName: !Ref EnvName
    serviceName: !Ref WorkloadNametypes
```

Then within the rest of your template you refer to the responseData from the triggered action:
```yaml
ServiceName: !GetAtt ResourceDescriberAction.ServiceName
```

**Comment by thenav56** [comment]
@efekarakus Thanks for the reply and workaround.

> In the long term, it'd be cool if we could have a way of creating multiple addons/ stacks for a service, perhaps something like this? Let me know what you think:
> 
> service-name/
>    manifest.yml
>    addons/ 
>       template.yml              # Existing addons stack.
>       addons.parameters.yml
>       asg/                       # New ASG addons stack.
>         template.yml
>         addons.parameters.yml
>       dashboard/                 # New Dashboard addons stack.
>         template.yml
>         addons.parameters.yml
> 

This sounds perfect. Will make the addons more flexible to use.




> I've a terrible workaround that I think allows mitigating this problem until we have a longer term solution: leveraging AWS Lambda-backed custom resources in the addons stack. The solution is really complex, so I totally understand if it's not desirable.

For the workaround, `cfn-response` didn't work (shows the request data but doesn't exactly send them) so I used the basic requests. Leaving it here for others.

`<service1>/addons/resource-describer.yml`
```yml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  ResourceDescriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: "DescribeResources"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: ECS
            Effect: Allow
            Action:
              - ecs:DescribeServices
            Resource: "*"
            Condition:
              ArnEquals:
                'ecs:cluster':
                  Fn::Sub:
                    - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}
                    - ClusterName:
                        Fn::ImportValue:
                          !Sub '${App}-${Env}-ClusterId'
          - Sid: ResourceGroups
            Effect: Allow
            Action:
              - resource-groups:GetResources
            Resource: "*"
          - Sid: Tags
            Effect: Allow
            Action:
              - "tag:GetResources"
            Resource: "*"

  ResourceDescriberFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
            const AWS = require('aws-sdk');

            let report = function (
              event,
              context,
              responseStatus,
              responseData,
              reason,
              physicalResourceId,
            ) {
              return new Promise((resolve, reject) => {
                const https = require("https");
                const { URL } = require("url");
                let responseBody = JSON.stringify({
                  Status: responseStatus,
                  Reason: reason,
                  PhysicalResourceId: physicalResourceId || context.logStreamName,
                  StackId: event.StackId,
                  RequestId: event.RequestId,
                  LogicalResourceId: event.LogicalResourceId,
                  Data: responseData,
                });
                const parsedUrl = new URL(event.ResponseURL);
                const options = {
                  hostname: parsedUrl.hostname,
                  port: 443,
                  path: parsedUrl.pathname + parsedUrl.search,
                  method: "PUT",
                  headers: {
                    "Content-Type": "",
                    "Content-Length": responseBody.length,
                  },
                };
                console.log('ResponseBody:', responseBody);
                https
                  .request(options)
                  .on("error", reject)
                  .on("response", (res) => {
                    res.resume();
                    if (res.statusCode >= 400) {
                      reject(new Error(`Error ${res.statusCode}: ${res.statusMessage}`));
                    } else {
                      resolve();
                    }
                  })
                  .end(responseBody, "utf8");
              });
            };

            exports.handler = async function(event, context) {
                console.info('Event::', JSON.stringify(event, null, 2));
                // For Delete requests, immediately send a SUCCESS response.
                if (event.RequestType == "Delete") {
                    await report(event, context, "SUCCESS");
                    return;
                }
                // Query for the service name. (RequestType: Create, Delete)
                try {
                    const {
                        cluster,
                        appName,
                        envName,
                        workloadName,
                    } = event.ResourceProperties;
                    const rgt = new AWS.ResourceGroupsTaggingAPI();
                    const resp = await rgt.getResources({
                        ResourceTypeFilters: ["ecs:service"],
                        TagFilters: [
                            {Key: "copilot-application", Values: [appName]},
                            {Key: "copilot-environment", Values: [envName]},
                            {Key: "copilot-service", Values: [workloadName]},
                        ],
                    }).promise();
                    const resources = resp.ResourceTagMappingList;
                    if (resources.length !== 1) {
                        throw new Error("unexpected resource length size:" + resources.length);
                    }
                    const ecs = new AWS.ECS();
                    const services = await ecs.describeServices({ cluster: cluster, services: [resources[0].ResourceARN] }).promise();
                    const { serviceName } = services.services[0];
                    // Send success
                    await report(event, context, "SUCCESS", {Cluster: cluster, ServiceName: serviceName});
                } catch(err) {
                    // Send error
                    await report(event, context, "FAILED", null, `${err.message}`);
                }
            };
      Handler: "index.handler"
      Timeout: 600
      MemorySize: 512
      Role: !GetAtt ResourceDescriberRole.Arn
      Runtime: nodejs12.x

  ResourceDescriberAction:
    Type: Custom::ResourceDescriberFunction
    Properties:
      ServiceToken: !GetAtt ResourceDescriberFunction.Arn
      cluster:
        Fn::ImportValue:
          !Sub '${App}-${Env}-ClusterId'
      appName: !Ref App
      envName: !Ref Env
      workloadName: !Ref Name
```

And then in any other addons for `<service1>`
`<service1>/addons/addon-1.yml`
```yml
.....
  Resource1:
    ....
    Properties:
      ...
      ResourceId:
        Fn::Join:
          - '/'
          - - 'service'
            - !GetAtt ResourceDescriberAction.Cluster  # From ./resource-describer.yml
            - !GetAtt ResourceDescriberAction.ServiceName  # From ./resource-describer.yml
      .....
```
