### ISSUE TITLE
Configuring scaling cooldown periods in the manifest

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#3165]
### Description

Discussed in https://github.com/aws/copilot-cli/discussions/3161

### Proposal

If the same values need to be applied to all scaling policies:
```yaml
count:
  range: 1-3
  cooldown:   # Optional.
    in: 3m        # Defaults to 2m
    out: 1m30s    # Defaults to 1m
  cpu_percentage: 40
  memory_percentage: 60
```
The `cooldown` field can only be specified if `range` is specified.

If individual policies need to be configured:
```yaml
count:
  range: 1-3
  cpu_percentage:
     value: 40   
     cooldown:
       in: 3m          
  memory_percentage: 60
```
The individual scaling in and out cooldowns take precedence over global ones
