### ISSUE TITLE
Proposal: per-environment overrides for addon parameters

### ISSUE THREAD

**Issue by codekitchen** [aws/copilot-cli#3209]
Right now you can define new parameters for your addon templates in `addons.parameters.yml`, but those parameter values are the same across all environments. I would like to propose allowing per-environment overrides using the same pattern that is supported in the manifest files. Something like:

```yaml
Parameters:
  DBInstanceClass: db.t3.medium
production:
  Parameters:
    DBInstanceClass: db.t3.xlarge
```

I believe this would be a pretty localized change to [the Parameters method](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/addon/addons.go#L110) for addons, using the same mergo dependency used in merging the manifest overrides. We would need to pass the environment name in as well.

There is already a way to implement this same functionality by using mappings inside the CF addon template, see for example [this issue](https://github.com/aws/copilot-cli/issues/2432). But I think explicit support is still worthwhile for a few reasons:

1. It is more straightfoward to reason about and (I believe) removes more complexity from the addon templates than it adds to `addons.parameters.yml`.
2. It is an existing pattern used in the manifest files, so copilot users will already be familiar with the idea.
3. It makes it easier to share addon templates between copilot applications, since they don't need environment-specific logic and values in them. This is the biggest driver for my team wanting this feature.

I am happy to implement this feature myself if the copilot team agrees with the idea. Thanks.

**Comment by efekarakus** [comment]
Hi @codekitchen 👋 

Thank you for the feature request ! The description and proposal is clear to us. 
However, I'm a bit reluctant to accept an implementation at the moment because as you mentioned CloudFormation's [`Mappings`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) functionality mitigates the feature request. The proposal would make defining parameters more convenient but it would increase complexity in the codebase while the usecase can be satisfied with `Mappings`.

For now, I'm leaning towards keeping the feature request open and waiting to hear more from others and collecting 👍  before jumping into implementation.  
Does that sound reasonable with you?

**Comment by codekitchen** [comment]
Hi @efekarakus I totally understand. Hopefully others will feel this would be useful too. My only comment would be that I don't really feel that Mappings fully satisfies our need for this feature for the reason I stated -- if you use Mappings you have to hard-code the possible values inside the CF template, which makes it much more difficult to share standardized copilot addon templates between different copilot projects. Our company is using copilot in quite a few projects so we're trying really hard to have standardized addon templates for things such as RDS, ElastiCache, CW alarms, etc.

**Comment by matthewhembree** [comment]
Adding my use case is:

- 4 environments.
- Addon database.
- I want to restore one environment's database from a snapshot with `DBSnapshotIdentifier`.

Workaround (one of):
1. Using `addon-template.yml`: Create a map in the template and add the snapshot ID for the environment. Fallback to `AWS::NoValue`.
2. Maybe a manual edit of the `addon-template.yml` and manual `copilot svc deploy -e <environment>` (I can't remember what happens when you set the field to `AWS:NoValue` after creating from snapshot... which you would have to do for other environments and/or pipeline deployment.) Edit: Restoring from snapshot and then setting the value to `AWS:NoValue` will cause CF to recreate an empty CF instance. So this will not work.
3. Maybe fetch the snapshot ID from a `resolve:ssm` call, but that's a bit weird to have configuration in different places. I'd also need to have that SSM parameter present in all environments; populated or blank.
4. Restore snapshot to a temp instance, and pgdump/pgrestore.
5. Using `addons.parameters.yml`: Create 4 conditionally created resource sets, based on a `Conditions:` block of ${Env} in the `addon-template.yml`. Have environment specific parameters for snapshot ID. e.g.: 

```yaml
# addons.parameters.yml
Parameters:
  ProdDBSnapshotIdentifier: arn:aws:rds:us-west-2:695301472178:cluster-snapshot:rds:myProdSnapshotId
  UatDBSnapshotIdentifier: AWS::NoValue
  ...
```

I'd prefer OPs solution, but will probably try **(1)** the mapping option. I think environment level overrides is the most Copilot conventional option, but I do understand there are codebase tradeoffs. Coming from AWS SAM, I appreciate its config-env `parameter_overrides`.
.
.
Thanks!

Edit:
I am already doing something similar to option **(5)** as I am creating an Aurora Global DB for prod and not for lower environments. I found it easier/only-possible to do this by duplicating the entire DB stack resources and making them conditional for each set.

e.g:
```yaml
Conditions:
  IsNotProd: !Not
    - !Condition IsProd
  IsProd: !Equals [ !Ref Env, prod ]
```

**Comment by matthewhembree** [comment]
Now I remember why I don't like `Mappings:`:

You cannot have a default value to fallback to. For me, this makes it difficult to have feature environments.

Where environment name might be:
- Developer's handle
- GH-Issue/Jira-Task ID
- Arbitrary feature/branch name

To accomodate a fallback, I'd have to create this elaborate `Fn:If` block.

Currently feature environments would be manually deployed, but we might leverage the new multi-pipeline functionality added in `v1.17.0`.

**Comment by codekitchen** [comment]
We went through this same thing a while back when we had to restore a db from snapshot. It re-affirmed for me how much nicer things would be if we had this feature. We ended up doing something similar to your option 1:

```yaml
  IsUseDBSnapshot: !Or
    - !And [Condition: IsStaging, !Not [!Equals ["", !Ref DBSnapshotNameStaging]]]
    - !And [Condition: IsProd, !Not [!Equals ["", !Ref DBSnapshotNameProduction]]]
# then inside the DBCluster resource:
      SnapshotIdentifier: !If [IsUseDBSnapshot, !If [IsStaging, !Ref DBSnapshotNameStaging, !Ref DBSnapshotNameProduction], !Ref "AWS::NoValue"]
```

But this is both really fiddly to get right, and really brittle since it requires hard-coding all the environment names.
