### ISSUE TITLE
Unable to pull secrets or registry auth.

### ISSUE THREAD

**Issue by mits87** [aws/copilot-cli#3240]
Hi guys!

First of all, thanks for an amazing tool! 

Currently I'm trying to setup my Fargate cluster using copilot-cli tool and I have one really big issue.

my manifest.yml:
```
name: blockchain-watcher
type: Backend Service

image:
  build: Dockerfile

cpu: 256
memory: 512
count: 1
exec: true

variables:
  LOG_LEVEL: info

secrets:
  REDIS_URL: /api/REDIS_URL

environments:
  test:
    count: 2

  production:
    count: 4
```

But whenever I'm trying to deploy that, I'm getting this error:

```ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): AccessDeniedException: User: ...```

My secrets are located in SSM as a SecureString. 
Do you have any solution for that?
