### ISSUE TITLE
Can not connect to external services.

### ISSUE THREAD

**Issue by mits87** [aws/copilot-cli#3245]
Hi guys!

I'm trying to deploy my application to Fargate through copilot-cli and almost everything works good except one thing. 
Currently I'm using "Backend Service" type for my application and from there I would like to:
- create a socket connection with external services (not hosted on AWS).
- send http request to external service (out of AWS as well).

I don't need and IP addresses to my service because it's a typical endless backend processing job there.
Eg. I would like to connect & subscribe to Redis which is hosted out of AWS.

How can I do that in an easy way?

**Comment by iamhopaul123** [comment]
Hello @mits87. Backend services should be able to connect to external endpoints on the internet. Would you mind sharing with us a sample code snipper and the error that you're seeing?

**Comment by mits87** [comment]
@iamhopaul123 of course here you are: 

```yml
name: worker
type: Backend Service

image:
  build: Dockerfile

cpu: 256
memory: 512
count: 1
exec: true 

variables:
  LOG_LEVEL: info

secrets:
  REDIS_URL: /api/REDIS_URL

environments:
  test:
    count: 2

  production:
    count: 4
```

and the JS script:

```ts
import Redis from 'ioredis';
 
(async () => {
  const redis = new Redis(process.env.REDIS_URL); // redis://....@eu1-strong-coral-34717.upstash.io:34717

  let n = 1;

  setInterval(() => {
    console.log(`interval: ${n}`);

    redis
      .smembers('data')
      .then((results) => console.log('Results', results))
      .catch((error) => console.error('Error', error));
 
     n++;
   }, 30000);
})();
```

this is my backend service which should get every 30s data from REDIS but currently I'm getting this error:
```
[ioredis] Unhandled error event: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
     at Socket.<anonymous> (/app/node_modules/ioredis/built/redis/event_handler.js:176:37)
     at Object.onceWrapper (node:events:510:26)
     at Socket.emit (node:events:390:28)
     at TCP.<anonymous> (node:net:687:12)
```

When I'm running my script locally then it works (REDIS endpoint is correct).
It looks like lack of connectivity from my code hosted on FARGATE.
