### ISSUE TITLE
Allow firelens container "logging" to have `essential` set to "false"

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#3255]
We recently had a job fail where the firelens container exited with a non-zero status and it took our main container with it. Is there a way to mark the firelens logging container as not essential? It obviously wouldn't be ideal but we want to avoid the job failing from any issues with firelens.

**Comment by efekarakus** [comment]
Hi @bpottier !

I think it might be possible to use the [task definition overrides](https://aws.github.io/copilot-cli/docs/developing/taskdef-overrides/) feature to "break the glass" and set the container as non-essential:
```yaml
taskdef_overrides:
- path: ContainerDefinitions[1].Essential
  value: false
```

Let me know if this works!
