### ISSUE TITLE
[Feature Request] EFS Storage Manipuration with CLI

### ISSUE THREAD

**Issue by MasaGon** [aws/copilot-cli#3270]
I would like to manipulate EFS storage with CLI without loging Fargate container in. Especially when the task was failed to boot caused by something wrong data on EFS.

Assuming that the manufest is like this,

```yml
storage:
  volumes:
    documentRoot:
      path: /var/www/html
      read_only: false
      efs:
        uid: 33
        gid: 33
```

These command like `aws s3` is very usefulf for me.

```bash
copilot storage ls documentRoot:/
copilot storage cp ./src.dir documentRoot:/dist.dir
copilot storage mv documentRoot:/src.dir documentRoot:/dist.dir
copilot storage sync ./src.dir documentRoot:/dist.dir
```
