### ISSUE TITLE
Ability to restrict TLS to v1.2 in a Load-Balanced Web Service

### ISSUE THREAD

**Issue by dimasusername** [aws/copilot-cli#3280]
When manually creating an HTTPS listener we're able to specify a security policy that can help us limit supported TLS versions. In particular, we're interested in limiting support to TLS 1.2 only.

Is there any way to specify this with copilot?

**Comment by huanjani** [comment]
Hello, @dimasusername! 

For HTTPS, specifying the security policy is not possible today with Copilot, unfortunately. 
If you are able to use a Network Load Balancer instead of an Application Load Balancer, you may specify the security policy with this field: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb-ssl-policy.

**Comment by FraserThompson** [comment]
TLSv1.0 and 1.1 are now considered insecure. Can we have an update to the default security policy to limit TLS 1.2 only?

edit: Oh I just checked the changelogs and it looks like this was solved with the `ssl_policy` parameter in the 1.23.0 release, which can be added to the environment manifest.

**Comment by tjhorner** [comment]
This doesn't seem to be possible for those using an Application Load Balancer. I've resorted to using a yaml patch at the environment level; here it is if it helps anyone else out:

```yaml
# Enforce a modern TLS policy for the Application Load Balancer
- op: add
  path: /Resources/HTTPSListener/Properties/SslPolicy
  value: ELBSecurityPolicy-TLS13-1-2-2021-06
```
