### ISSUE TITLE
Deploy not working after 9 months of no changes.

### ISSUE THREAD

**Issue by jaydlawrence** [aws/copilot-cli#3323]
I went to deploy to a service that was last deployed 9 months ago.

This is the error I get:
```
 The following resource(s) failed to update: [HTTPListenerRuleWithDomain, HTTPSListenerRule, TaskDefinition].                                                                     
  - An autoscaling target to scale your service's desired count               [not started]                  
  - Update your environment's shared resources                                [update complete]              [1.9s]
  - An ECS service to run and maintain your tasks in the environment cluster  [not started]                  
  - An ECS task definition to group your containers and run them on ECS       [update failed]                [0.0s]
    Resource creation cancelled                                                                              
```

We may have upgraded the up between the updates.

I have searched online and can't find anything to help debug the issue.

I have tried redeploying locally (instead of via our CI Pipeline).
I have backed out the code changes and it doesn't make a difference.
The change is just a package version bump, so nothing major anyway.

Any suggestions on what I could do to even start debugging this issue?

Here is our config, if that is helpful.

```
# The manifest for the "redirect-server" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: server-name
# The "architecture" of the service you're running.
type: Load Balanced Web Service

image:
  # Docker build arguments.
  # For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: ./app/Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 4280

http:
  # Requests to this path will be forwarded to your service. 
  # To match all requests you can use the / path. 
  path: '/'
  # You can specify a custom health check path. The default is /.
  # For additional configuration: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck
  healthcheck:
    path: '/healthcheck'
    # You can specify a custom health check path. The default is /.
    # For additional configuration: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck
    healthy_threshold: 3
    unhealthy_threshold: 2
    interval: 15s
    timeout: 10s

# Number of CPU units for the task.
cpu: 256
# Amount of memory in MiB used by the task.
memory: 512
# Number of tasks that should be running in your service.
count:
  range: 1-4
  cpu_percentage: 70
  memory_percentage: 80
  response_time: 2s

environments:
...
```
