### ISSUE TITLE
root_dir for efs volumes not working as expected

### ISSUE THREAD

**Issue by andaag** [aws/copilot-cli#3349]
Hi

With this storage set in a manifest:
```
storage:
  volumes:
    managedEFSVolume:
      efs:
        uid: 1000
        gid: 1000
      path: /var/efs
      read_only: true
      id: fs-xxxxxxxxxx
      root_dir: /updater
```

It produces this segment in the yaml:
```
  AccessPoint:
    Metadata:
      'aws:copilot:description': 'An EFS access point to handle POSIX permissions'
    Type: AWS::EFS::AccessPoint
    Properties:
      ClientToken: !Sub ${AppName}-${EnvName}-${WorkloadName}
      FileSystemId: !GetAtt EnvControllerAction.ManagedFileSystemID
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        Path: !Sub '/frontend'
        CreationInfo:
          OwnerUid: 1000
          OwnerGid: 1000
          Permissions: '0755'
```
(the service is creatively named frontend, matching the RootDirectory path above)

In addition according to the documentation https://aws.github.io/copilot-cli/docs/developing/storage/#managed-efs the root_dir is / by default, which doesn't seem to be the case.
