### ISSUE TITLE
EFS - sharing data across 2 services

### ISSUE THREAD

**Issue by andaag** [aws/copilot-cli#3350]
Hi

I'm trying to share data between two services, one produces some data on EFS, the other should have read only access.

Service one storage setup:
```
storage:
  volumes:
    managedEFSVolume:
      efs:
        uid: 1000
        gid: 1000
      path: /var/efs
      read_only: false
```
This works fine.

Service two:
```
storage:
  volumes:
    managedEFSVolume:
      efs:
        id: fs-1234
      path: /var/efs
      read_only: false
```
Does not work, stops with "ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32". 

```
storage:
  volumes:
    managedEFSVolume:
      efs:
        id: fs-1234
        auth:
          access_point_id: fsap-1234
      path: /var/efs
      read_only: false
```
Also does not work, stops with "ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32". 

Looking at the created cloudformation templates it looks like copilot is attempting to set this up to work? A "GrantEFSAccessfs" policy is created, but it doesn't seem to work.
