### ISSUE TITLE
Capacity Provider stategy is `FARGATE_SPOT` without a `spot_from` field

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#3351]
## Description

Today, when users write the following manifest:
```yaml
count:
  range:
    min: 1
    max: 10
  cpu_percentage: 70
```
Copilot sets the capacity provider strategy for the service to be `FARGATE_SPOT`:
```yaml
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
```
Instead, we should leave it as `FARGATE` and set the field only if the `spot_from` field is specified:
```yaml
count:
  range:
    min: 1
    max: 10
    spot_from: 1
```

### Fix
The issue seems to be because we're adding spot by default:
https://github.com/aws/copilot-cli/blob/14768fdb16b8969b6b07ca133872e15790f2528b/internal/pkg/deploy/cloudformation/stack/transformers.go#L144-L150
