### ISSUE TITLE
Deploying a request driven service fails when manifest contains 'command'

### ISSUE THREAD

**Issue by pchaganti** [aws/copilot-cli#3373]
Using a manifest file where we over-ride command. Trying to deploy a service results in the following error. I am running the latest release.

```
✘ unmarshal service testapp manifest: unmarshal manifest for Request-Driven Web Service: yaml: unmarshal errors:
  line 3: cannot unmarshal !!seq into string
```

Here is the manifest i tried to use. Removing 'command' from the manifest results in a successful deploy.

```
name: testapp
type: Request-Driven Web Service
command: ["app"]

http:
  path: '/'

image:
  build: Dockerfile
  port: 80


cpu: 2048
memory: 4096

network:
  vpc:
    placement: private

```
