### ISSUE TITLE
Worker service scaling from queue with a minimum range of 0

### ISSUE THREAD

**Issue by callikai** [aws/copilot-cli#3376]
I am having trouble with a worker service scaling up when items are added to the SQS queue:

Manifest example:

```
subscribe:
  topics:
    - name: serviceTopic
      service: servicename
  queue:
    retention: 96h
    timeout: 20m
    dead_letter:
      tries: 3
      
count:
  range:
    min: 0
    max: 10
    spot_from: 2
  queue_delay:
    acceptable_latency: 10m
    msg_processing_time: 10m
```
    
The alarm that is created only triggers to scale up if the queue is >1. My service at times is low usage and there is often 0 or 1 message in the queue. Am I doing something wrong? Feels like some logic is missing that there should be at least one worker running if there is something in the queue.

**Comment by huanjani** [comment]
Hello, @callikai!

Would you mind telling me more? Are you experiencing that your number of tasks is going down to 0 even when there is a message in the queue? Are you expecting more than 0 or 1 message in the queue?

Thanks!

**Comment by callikai** [comment]
Hi!

The number of tasks begins at 0. When one message is added to the queue, no worker task is added and the message is not processed.

**Comment by huanjani** [comment]
Ahh, thank you for clarifying, @callikai! 

Thanks for including your manifest-- I see that because `acceptable_latency` and `msg_processing_time` are equal, the  "[acceptable backlog per instance](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-using-sqs-queue.html#scale-sqs-queue-custom-metric)," which is calculated by `acceptable_latency`/`msg_processing_time`, is equal to 1. So you're right-- it's only launching a task if there is _more than one_ message in the queue.

Your use case seems like a common one, and we are trying to build in a way to make it possible (now that you have surfaced this-- thank you!). For now, though, could you make the `min` value for your `range` 1? We understand that you'd rather not have the one task running if there are no messages; maybe you could do `spot_from: 1` to minimize costs for now. 
```
count:
  range:
    min: 1
    max: 10
    spot_from: 1
```
Thank you!
