### ISSUE TITLE
Validation of environment variable in other environment causes error.

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#3415]
I want to use the container image which is already built in CI environment for the production environment.
The built container image URL is set to environment variable ${container_url}.
On the other hand, I want to use local Dockerfile for my own development environment.

```
environments:
  prod:
    image:
      location: ${container_url}

  local:
    image:
      build: Dockerfile
```

When I invoke `copilot svc deploy --name my-svc --env local` for my `local` environment, copilot validates the environment variable in `prod` environment, then error occurs.
 ```
? interpolate environment variables for my-svc manifest: environment variable "container_url" is not defined
```

It should not validate unused environment, or I want an option to ignore validation for missing environment variables.
