### ISSUE TITLE
Ability to specify additional security group to App Runner VPC Connector

### ISSUE THREAD

**Issue by toshitanian** [aws/copilot-cli#3504]
In [network section](https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/#network) of Request-Driven Web Service, we can enable VPC connection of App Runner. It adds App Runner service's security group by default as the cfn configuration as below. This is enough in most cases but I want to add extra security group to the network.

```yaml
  VpcConnector:
    Type: AWS::AppRunner::VpcConnector
    DependsOn: EnvControllerAction # Ensure NAT gateways are created before connecting to a VPC.
    Properties:
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub '${AppName}-${EnvName}-PrivateSubnets'
      SecurityGroups:
      - !Ref ServiceSecurityGroup
```

 The security group is copilot's environment wise security group ` ${App}-${Env}-EnvironmentSecurityGroup`. It's nice if we can add extra security group in the network section. Below is just one idea.

```yaml
network:
  vpc:
    placement: 'private'
  extra_security_group:
    - sg-xxxxxxxx
    - sg-yyyyyyyy
```
