### ISSUE TITLE
Datadog Agent Sidecar

### ISSUE THREAD

**Issue by SimonBerens** [aws/copilot-cli#3524]
I'm trying to use [datadog agent](https://docs.datadoghq.com/agent/) in my copilot application. I see they have datadog agent for [docker](https://docs.datadoghq.com/agent/docker), as well as for [ECS on Fargate](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=fluentbitandfirelens). The Fargate method seems involved and not in the spirit of copilot, so I'm trying to figure out how I can use the dockerized datadog agent by specifying the configuration in my `manifest.yml` files. It seems possible as it is mentioned in [this issue](https://github.com/aws/copilot-cli/issues/2699), but this is stretching the limits of my knowledge.

From what I've gleaned on the datadog agent for docker page, I need to run the equivalent of [this](https://docs.datadoghq.com/agent/docker/?tab=amazonlinux#:~:text=docker%20run%20%2Dd%20%2D%2Dcgroupns%20host%20%2D%2Dname%20dd%2Dagent%20%2Dv%20/var/run/docker.sock%3A/var/run/docker.sock%3Aro%20%2Dv%20/proc/%3A/host/proc/%3Aro%20%2Dv%20/sys/fs/cgroup/%3A/host/sys/fs/cgroup%3Aro%20%2De%20DD_API_KEY%3D%3CDATADOG_API_KEY%3E%20public.ecr.aws/datadog/agent%3A7) command.

It seems that copilot has [sidecars](https://aws.github.io/copilot-cli/docs/developing/sidecars/#general-sidecars) exactly for this use case. Here is my attempt:

```
storage:
  volumes:
    sock:
      efs: true
      path: '/var/run/docker.sock'
      read_only: true
    proc:
      efs: true
      path: '/proc/'
      read_only: true
    cgroup:
      efs: true
      path: '/sys/fs/cgroup/'
      read_only: true

sidecars:
  datadog:
    image: public.ecr.aws/datadog/agent
    mount_points:
      - source_volume: sock
        path: '/var/run/docker.sock'
      - source_volume: proc
        path: '/proc/'
      - source_volume: cgroup
        path: '/sys/fs/cgroup/'
    secrets:
      DD_API_KEY: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DATADOG_API_KEY
```

However, I'm not exactly sure how EFS/sidecars/Fargate work. Specificaly, should I have a different storage path for each service? What about if I have multiple instances of a service running?

**Comment by efekarakus** [comment]
Hi @SimonBerens !

From clicking through the docs, to me it looks like the [ECS on Fargate](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=fluentbitandfirelens) tutorial might be the easiest to model with copilot 😅 which seems to be similar to what you're building:

```yaml
sidecars:
  datadog:
    image: public.ecr.aws/datadog/agent:7
    variables:
      ECS_FARGATE: true
      DD_SITE: datadoghq.com
    secrets:
      DD_API_KEY: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DATADOG_API_KEY
```
From what I can tell that should do the trick. Would you mind giving this a shot?

**Comment by SimonBerens** [comment]
Yep that seemed to do it! 

I read something somewhere that datadog would persist container names (or smth similar) after restart with some extra config, but I can't seem to find it :/ I'll update if I do figure it out.

Appreciate the help!

**Comment by gabrieljoelc** [comment]
@SimonBerens hello, I am trying to do the same thing but am getting this error in the build:
```
validate "storage": cannot specify more than one managed volume per service
```
There is an open issue https://github.com/aws/copilot-cli/issues/2921 for this.

How did you get this working?

here's my manifest config:
```yaml
storage:
  volumes:
    sock:
      efs: true
      path: '/var/run/docker.sock'
      read_only: true
    proc:
      efs: true
      path: '/proc/'
      read_only: true
    cgroup:
      efs: true
      path: '/sys/fs/cgroup/'
      read_only: true

sidecars:
  datadog:
    image: public.ecr.aws/datadog/agent:7
    variables:
      ECS_FARGATE: true
      DD_SITE: us5.datadoghq.com
      DD_ENV: ${COPILOT_ENVIRONMENT_NAME}
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_CONTAINER_EXCLUDE: name:datadog-agent
    secrets:
      DD_API_KEY: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DATADOG_API_KEY
    mount_points:
      - source_volume: sock
        path: '/var/run/docker.sock'
      - source_volume: proc
        path: '/proc/'
      - source_volume: cgroup
        path: '/sys/fs/cgroup/'
```
