### ISSUE TITLE
access to addons in a task run command

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3525]
Hi,

I'm running a one off task with the command `copilot task run`

The task requires access to an IAM policy to access my SQS queues.

```
SQSAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: SQSActions
            Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueUrl
              - sqs:ChangeMessageVisibility
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:SetQueueAttributes
            Resource: !Sub ${SQSARN}
  ```

I would have added this as an addon if this was a service or scheduled job, but curious how I do this for a copilot task?
