### ISSUE TITLE
Expose private route table ID

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#3609]
To create VPC gateway endpoints for services deployed in private subnets, private route table ID is required. 
Expose private route table ID in environment cloudformation stack so we can associate gateway endpoint to private routing table.

**Comment by dannyrandall** [comment]
Hey @gautam-nutalapati! Thanks for the feature request, it makes sense to me.

**Comment by gautam-nutalapati** [comment]
For everyone's reference, below is sample template I am using 😃
```
  s3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds: !Split
        - ','
        - !Join
          - ','
          - - Fn::ImportValue: !Sub "${App}-${Env}-PublicRouteTableID"
            - Fn::ImportValue: !Sub "${App}-${Env}-PrivateRouteTableIDs"
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      VpcId:
        Fn::ImportValue: !Sub "${App}-${Env}-VpcId"
  dynamoDbVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:  !Split
        - ','
        - Fn::ImportValue: !Sub "${App}-${Env}-PrivateRouteTableIDs"
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcEndpointType: Gateway
      VpcId:
        Fn::ImportValue: !Sub "${App}-${Env}-VpcId"
```
