### ISSUE TITLE
[Feature] Use many aliases by service

### ISSUE THREAD

**Issue by rverpillot** [aws/copilot-cli#3627]
Could be possible to use many aliases by service ? Something like this:
```

http:
  path: '/'
  aliases:
    - alias: myapp.aws-private.com
      hosted_zone_id: Z0873220N255IR3MTNR4
    - alias: myapp.corp-private.com

```
The goal is to add listener rules for different domain names.

With this feature we could migrate applications and still using existing URLs by creating DNS CNAME (and importing existing certificates as well).

Today:
`myapp.corp-private.com (A)` --> `10.x.x.x`

Tomorrow:
`myapp.corp-private.com (CNAME)` --> `myapp.aws-private.com (A)` --> `ALB`
