### ISSUE TITLE
Ability to reference the EFS volume in Cloud Formation / addons

### ISSUE THREAD

**Issue by tomkerswill** [aws/copilot-cli#3641]
Hi,

I am provisioning an EFS volume using the following type of thing in manifest.yml

```
storage:
  volumes:
    wp-content:
      path: /test/efs
      read_only: false
      efs: true
```

I'd like to be able to reference this in the addons functionality.  As an example, we have a system that uses lambda to scale the IOPS of the EFS volume up and down, and so we'd like to write Cloud Formation templates in the addons directory to create CloudWatch alarms that reference the ID of the volume that CoPilot creates.

Is this possible? At the moment, we're struggling how we can reference those EFS volumes.
