### ISSUE TITLE
task run `env_file` support

### ISSUE THREAD

**Issue by cdunn** [aws/copilot-cli#3672]
Services have the ability to set env_file's
```
environments:
 production:
   env_file: production.env
...
```

Is there any way to translate this to `task run` besides enumerating them inline with `--env-vars`?
