### ISSUE TITLE
Allow setting `MapPublicIpOnLaunch` to false for public subnets

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#3720]
## Ask
For creating secure environments by default, clients might want to set the `MapPublicIpOnLaunch` field for public subnets to `false`.

### Sample manifest

For example, a sample manifest might be:
```yaml
name: test
type: Environment
network:
  vpc:
    subnets:
      public:
        ip_on_launch: false # default remains true.
````
