### ISSUE TITLE
CodePipeline deploy problem after upgrading to 1.20.0

### ISSUE THREAD

**Issue by hirro** [aws/copilot-cli#3825]
I was puzzled by a strange problem. 

I had a working copilot pipeline until 20220715, but after updating a README.md on 20220722 the deployment to my dev environment is now failing with the error:

```
[/Resources/DynamicDesiredCountFunction/Type/Code/S3Bucket] 'null' values are not allowed in templates (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: *******; Proxy: null)
```

The <service>-<env>-stack.yml file in the failing build that used to contain a proper:

```
  DynamicDesiredCountFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
           "...loads of JS skipped here...
```
Now instead (empty values in S3Bucket as the error message indicates):
```
  DynamicDesiredCountFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
        S3Key:
```

I noticed that my buildspec.yml downloads and unpacks the latest copilot-linux and that a new 1.20.0 version was released after the last successful build.

Once I changed fixed the copilot-linux to 1.19.0 things started working again.

There seems to be some breaking change to be aware of.
