### ISSUE TITLE
Scheduled job option Schedule: "None" not working

### ISSUE THREAD

**Issue by lennertcc** [aws/copilot-cli#3838]
I tried the option `Schedule: "None"` as described on https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/, but copilot is throwing an error:

`copilot job package -n jobname -e test --output-dir './infrastructure'`
✘ generate workload jobname template against environment test: generate stack template: convert schedule for job jobname: schedule is not valid cron, rate, or preset: expected exactly 5 fields, found 1: [None]

I tried:
```
on:
  schedule: none
```

```
on:
  schedule: "none"
```

```
on:
  schedule: 'none'
```

**Comment by iamhopaul123** [comment]
Hello @lennertcc. I was trying to reproduce the error and here's the manifest I've been using

```yaml
name: my-job

# The "architecture" of the job you're running.
type: Scheduled Job

image:
  # Docker build arguments. You can specify additional overrides here. Supported: dockerfile, context, args.
  build: schedule/Dockerfile

# Number of CPU units for the task.
cpu: 256
# Amount of memory in MiB used by the task.
memory: 512

on:
  # The trigger for your job. You can specify a cron schedule or keyword (@weekly) or a rate (2h, 1h30m, 15m)
  schedule: "none"
```

And then `copilot job package --output-dir infra` wasn't an issue for me. However, if I change to

```yaml
on:
  # The trigger for your job. You can specify a cron schedule or keyword (@weekly) or a rate (2h, 1h30m, 15m)
  schedule: "None"
```

It gave me the same error as 

```
✘ generate workload my-job template against environment test: generate stack template: convert schedule for job my-job: schedule is not valid cron, rate, or preset: expected exactly 5 fields, found 1: [None]
```

**Comment by hellolennert** [comment]
Thank you, it was indeed the capital N. Issue resolved, thanks again for your quick response.

**Comment by lennertcc** [comment]
Reopening because if I use 
```
on:
  schedule: "none"
```
and run it with the pipeline that was deployed using `copilot pipeline update`, it fails deployment in the CreateOrUpdate step with the error: 
Template configuration is not valid

If I revert to the suggestion at https://github.com/aws/copilot-cli/issues/1823, it runs fine again.
```
on:
  schedule: cron(0 0 1 1 ? 2021)
```
I could use the 2021 trick, but I like the `schedule: "none"` solution better.

**Comment by iamhopaul123** [comment]
Hello @lennertcc. Could you check which version of Copilot is your pipeline using? Because sometimes the Copilot version that pipelines use might not be updated for a while. You could easily find out in your pipeline buildspec. For example:

```yaml
phases:
  install:
    runtime-versions:
      docker: 19
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q xxxxxxxx.amazonaws.com/copilot-withsomeversion
      - mv ./copilot-withsomeversion ./copilot-linux
```
