### ISSUE TITLE
Trouble with aliases and environment subdomains

### ISSUE THREAD

**Issue by patkirts** [aws/copilot-cli#3883]
Hi Copilot team, fantastic product.

I'm having a problem and I think I've exhausted reading other issues and the documentation and I'm going to ask directly.

I have a copilot service running at (eg) `api.example.com`. It works great! `api.example.com` is a hosted zone on Route 53, and I've created several additional environments (successfully, with the same certificate), and deployed services and jobs with secrets to those environments (I can read the logs in CloudWatch), but I cannot get any additional subdomain aliases to work, eg, `test.api.example.com`, `staging.api.example.com`, and the copilot generated URLs don't seem to work either.

Here is my `manifest.yml`:

```
http:
  path: '/'
  alias: api.example.com

environments:
  staging:
    http:
      path: '/'
      alias: staging.api.example.com
```

When I run `copilot deploy`, it ends with the message: `You can access your service at https://staging.api.example.com over the internet.` But it cannot be reached. I've tried adding different records for it to Route 53, but without success.

Am I making a basic error? Or is what I'm attempting impossible, and I'm misunderstanding how aliases work?

Thanks for any clarity
