### ISSUE TITLE
Internal load balancer outbound rule allow traffic to 0.0.0.0/0 destination

### ISSUE THREAD

**Issue by craigjbass** [aws/copilot-cli#3934]
We're wondering what the design choice was around this, and if this makes sense?

**Comment by huanjani** [comment]
Hi, @craigjbass!

That's a good question. Would you like to see the equivalent of [this](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-private-security-groups-ingress) for egress?

**Comment by CorinWilkins** [comment]
Being able to specify the security group for a load balancer would give us the level of control we need. 
Something akin to [load balanced services](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-security-groups)

```
http:
  private:
    security_groups:
      groups: [sg_xyz890, sg_abc123]
      deny_default: true
```
