### ISSUE TITLE
Import an ALB or create dedicated ALB for services

### ISSUE THREAD

**Issue by CorinWilkins** [aws/copilot-cli#3936]
We have a number of internal load balanced services. We want to use security groups to restrict what can talk to our internal services. However, because the internal services all share an internal load balancer if something can reach that load balancer it can reach every service behind it. 

I'd like the ability to define the load balancer either to be created by copilot or to reference an already created. In my case this alb would ideally created outside of copilot.

```
http:
    alb:
        name: foobar
```

**Comment by huanjani** [comment]
Related: #1457, #3319.

**Comment by efekarakus** [comment]
1. A manifest proposal for creating separate Load Balancers per service could be (for import we can follow @CorinWilkins's proposal):
   ```yaml
   name: api
   type: Load Balanced Web Service # or 'Backend Service'
   
   http:
     dedicated: true
   ```

2. For configuring which other workloads should be allowed to connect to the load balancer:
   ```yaml
   http:
     dedicated: true
     ingress:
       names: 
         - other_service1
         - other_service2
         - other_job1
   ```
   This UX raises the question how can we have the ALB security group allow ingress from `other_service1`, `other_service2`, `other_job1` without having cross service or job-stack dependencies which would make deletions extremely complicated.
   I believe the solution is for us to define a separate security group per workload at the environment level as an environment addon. The security groups can be imported in workload stacks and an [EC2::SecurityGroupIngress](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html) resource can be created in the workload stack for the ALB to allow ingress from the workload sg.
