### ISSUE TITLE
Be able to specify the security group(s) for load balancer(s)

### ISSUE THREAD

**Issue by craigjbass** [aws/copilot-cli#3939]
Being able to specify the security group for a load balancer would give us the level of control we need. 
Something akin to [load balanced services](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-security-groups)

```
http:
  private:
    security_groups:
      groups: [sg_xyz890, sg_abc123]
      deny_default: true
```

_Originally posted by @CorinWilkins in https://github.com/aws/copilot-cli/issues/3934#issuecomment-1224800583_
