### ISSUE TITLE
Log retention config causes "Model validation failed... failed validation constraint for keyword [enum]"

### ISSUE THREAD

**Issue by glenswinfield** [aws/copilot-cli#3946]
Adding a `logging.retention` value to a manifest (seems consistent across load balanced web services and worker services) causes deployment to fail.

Example manifest:

```yaml
environments:
  development:
    cpu: 256
    memory: 512
    count: 1
    exec: true
    logging:
      retention: 2557
```
![Screenshot 2022-08-25 at 12 14 51](https://user-images.githubusercontent.com/1146295/186650319-5ae77ac0-1637-4104-9ac6-2a1389fb3e1e.png)

This is for a service that already exists - i.e. not a first deployment.

Documentation is limited, the error message suggests that the specified value is not valid, I tried several values specified in the CloudFormation docs for log retention periods with the same result. Changing the value via the AWS console works as expected.

I'm not sure if there's a subtlety around altering log retention periods that I'm missing.
