### ISSUE TITLE
Multiple Load Balanced Web Services in a same Environment

### ISSUE THREAD

**Issue by PierFio** [aws/copilot-cli#3963]
Hello 

Thank you for the great job with copilot.

I am experimenting with it and meet an issue when trying to deploy two Load Balanced Services in the same environment.
The first service is deploying fine and I have access to the exposed interface.
When I try to deploy the same service a second time (with different name, different port), everything seems to proceed correctly and I am provided with a connecting link of the format : name2.env.app.domain/name2

This link is not working though: accessing it produces a 404 error. I checked the load balancer which has a listener with the correct rule to manage the link. I do not understand where the problem comes from. Am I attempting something that is not possible ?

copilot version: v1.20.0
running on region canada-central-1

Thank you for your help.
Pierre ---

**Comment by paragbhingre** [comment]
@PierFio,
Could you please give me a little more information so that we can troubleshoot your problem. 
* Could you please paste in your manifest configuration for both the services here?
* Also, I would like to see the listener rules that are being set for your load balancer.

Can you check if one of the listener rules' path section contains a double slash "//", which might be the cause of this problem.

**Comment by PierFio** [comment]
Thank you for your concern @paragbhingre 

The manifests are the direct result of copilot generation:
For test1:
```
name: test1
type: Load Balanced Web Service

http:
  path: '/'
image:
  build: Dockerfile.test1
  port: 2000

cpu: 256      
memory: 512   
count: 1      
exec: true
```

For test2:
```
name: test2
type: Load Balanced Web Service

http:
  path: 'test2'
image:
  build: Dockerfile.test2
  port: 4000

cpu: 256      
memory: 512   
count: 1      
exec: true
```

The listener rules are:
```
1
IF
Path is/test2or/test2/*
THEN
Forward to
exper-Targe-3FZMXOJW1X90: 1 (100%)
Group-level stickiness: Off

2
IF
Path is/*
THEN
Forward to
exper-Targe-14XC84HA43LN6: 1 (100%)
Group-level stickiness: Off

last
HTTP 80: default action
This rule cannot be moved or deleted
IF
Requests otherwise not routed
THEN
Forward to
exper-Defau-E5AMXA3BU2AU: 1 (100%)
Group-level stickiness: Off
```
Target is healthy.
