### ISSUE TITLE
how to pass arguments to the entry point?

### ISSUE THREAD

**Issue by shunjizhan** [aws/copilot-cli#3989]
Hi, I was wondering what's the best way to pass arguments to the entry point? In docker compose way it would be `command` section like this:
```
  service-name:
    image: image-name
    command:
      - --arg1=aaa
      - --arg2=bbb
      - --boolean-arg3
```

I tried to use `image.args` but didn't seem to work:
```
image:
  build: xxx.Dockerfile
  args:
    arg1: aaa
    arg2: bbb
    boolean-arg3: 1
```

so currently I have to override to whole entry point in order to pass args:
```
entrypoint: [
  "original-entry-point",
  "--arg1=aaa",
  "--arg2=bbb",
  "--boolean-arg3",
]
```

Is there a better way to do it, so I can pass these args without overriding entry point? Thanks a lot for the help!
