### ISSUE TITLE
Can add some settings to the pipeline command.

### ISSUE THREAD

**Issue by harry-shopl** [aws/copilot-cli#4022]
ASk
---
There are some inconvenient things about using pipeline, so I would like to suggest it.

1. Source output artifact format

Finally, it would be nice to have an option to change the output artifact format to Git full clone in the source settings of the Codepipeline configuration.

**proposal**
```yml
source:
  provider: GitHub
  properties:
    branch: target-branch
    repository: https://github.com/my/repository
    output_artifact: full_clone
```

2. Trigger Codepipeline

Currently, I'm making a request to Codepipeline with a configuration that detects changes to a specific branch source on Github.
However, I want the Trigger to work even when I push a tag to git.
For example, it would be great if you could make it work through the following manifest.yml configuration.

```yml
source:
  provider: GitHub
  properties:
    repository: https://github.com/my/repository
    trigger_type: tag
```
