### ISSUE TITLE
Suggestion: ECR repositories need to separate between environments

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [aws/copilot-cli#4045]
Hi Copilot team,
When I tried to find workaround solution for this issue
https://github.com/aws/copilot-cli/issues/4044

Here is my batch job manifest :
```
# The manifest for the "event-change-status" job.
# Read the full specification for the "Scheduled Job" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/

# Your job name will be used in naming your resources like log groups, ECS Tasks, etc.
name: event-change-status
type: Scheduled Job

# Trigger for your task.
on:
  # The scheduled trigger for your job. You can specify a Unix cron schedule or keyword (@weekly) or a rate (@every 1h30m)
  # AWS Schedule Expressions are also accepted: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
  schedule: "30 18 * * *"
#retries: 3        # Optional. The number of times to retry the job before failing.
#timeout: 1h30m    # Optional. The timeout after which to stop the job if it's still running. You can use the units (h, m, s).

# Configuration for your container and task.
# image:
#   location: 443171139711.dkr.ecr.ap-south-1.amazonaws.com/quick/api:latest

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.

# Optional fields for more advanced use-cases.
#
#variables:                    # Pass environment variables as key value pairs.
#  LOG_LEVEL: info

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.
secrets:
  SERVER_ID: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/SERVER_ID
  APP_NAME: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/APP_NAME
  APP_PORT: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/APP_PORT
  APP_HOST: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/APP_HOST
  JWT_ACCESS_TOKEN_SECRET_KEY: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/JWT_ACCESS_TOKEN_SECRET_KEY
  JWT_ACCESS_TOKEN_EXPIRE_TIME: 

# Override command
command: ["npm", "run", "cron:event-change-status"]

# You can override any of the values defined above by environment.
environments:
#  prod:
#    cpu: 2048               # Larger CPU value for prod environment 
  dev:
    image:
      location: 443171139711.dkr.ecr.ap-south-1.amazonaws.com/quick/api:latest
```

I used `image.location` point directly to API service image for my batchjob, and it works well.

But, another problem I could get in the future, 
If I build many env with the same account and same region for a service, all images of the service of all env will be in a same ECR repository:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/16200158/192994577-c73bd340-e5eb-4d46-9023-8a4fd755c8dc.png">

As you see above the sceenshot, I create a service with 2 environments.

So, My suggest is we need to separate ECR repository between environments.

Then, we could use `latest` tag for my workaround solution.

Thank you!
