### ISSUE TITLE
Do we need copilot re-create certificate when config alias?

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [aws/copilot-cli#4079]
Hi all,
With a domain, Copilot will create certificate with domain and subdomain with wildcard already.

![image](https://user-images.githubusercontent.com/16200158/195252439-4ed8e7b0-c6db-4bf8-90a8-759bff101b85.png)

example for dev env:
- dev.example.com
- *.dev.example.com

it also implicit include: admin.dev.example.com or api.dev.example.com ...v.v

I raised this issue because when I tried to use `cert arn` in my add-on yml file,

```
Mappings:
  Cert:
    dev: 
      "arn": 'arn:aws:acm:us-east-1:44311111111:certificate/bddf7928-e96d-4355-8725-a264f2fcc4f3'
```
you could read here https://github.com/aws/copilot-cli/issues/4038 to find the reason why I used above mapping for add-on template

It works well, but after that, I create a new service with alias `admin2.dev.example.com`

Copilot will re-create a new cert and delete previous cert, it leads when redeploy the old service, it will be failed because could not find the old cert arn.

As you see: `admin2.dev.example.com` was implicit in `*.dev.example.com`

Please correct me if I'm wrong. Thank you!
