### ISSUE TITLE
Proposal: Support multiple ports

### ISSUE THREAD

**Issue by paragbhingre** [aws/copilot-cli#4170]
Proposal for #1783 , #3594,  #4445 
**Problem Statement**

Today in Copilot, a container can expose only one port. Below is an example manifest. Requests on “/” to the ALB  will be routed to the frontend main container’s port `8080`.
```yaml
name: 'frontend'
type: 'Load Balanced Web Service'
 
image:
  build: './frontend/Dockerfile'
  port: 8080
  
http:
  path: '/'
```

Copilot is adding support for multiple ports. This feature will enable exposing multiple ports from the containers, which can be opened to the application load balancer or the network load balancer. 

**Proposal**

To expose multiple ports, we will configure additional listener rules through a new field called `additional_rules` . 

For example, say we want to expand the above manifest such that it opens up port `8081` on the main service container, and `8082` on the sidecar container, in addition to the existing port `8080`.

```yaml
# Example 1
name: 'frontend'
type: 'Load Balanced Web Service'
 
image:
  build: './frontend/Dockerfile'
  port: 8080
  
http:
  path: '/'
  additional_rules: # The new field "additional_rules",
    - target_port: 8081
      path: '/customerdb'
    - target_port: 8082
      target_container: sidecarA
      path: '/admin'
```

With this manifest, requests to “/” will still be routed to the main container’s port 8080. Requests to "/customerdb" will be route to the main container’s `8081`, and "/admin" to “sidecarA”‘s port `8082`.

It is also possible to configure the container port that handles the requests to “/”:

```yaml
# Example 2
name: 'frontend'
type: 'Load Balanced Web Service'
 
image:
  build: './frontend/Dockerfile'
  port: 8080 # Some port that's exposed internally and may not handle public `http` traffic
  
http:
  path: '/'
  target_port: 8083  # Defaulted to `image.port` (8080) in "Example 1".
  additional_rules:
    - target_port: 8081
      path: '/customerdb'
    - target_port: 8082
      target_container: sidecarA 
      path: '/admin'
```

With this manifest, requests to “/” will now be routed to the main container’s port `8083`, instead of `8080`.

This feature will also allow us to expose multiple ports of the container through NLB ports. For example, say we want to expose `8080` and `8081` on the main service container and `8085` on the sidecar container.

```yaml
name: 'frontend'
type: 'Load Balanced Web Service'

image:
  build: Dockerfile
 
http: false
nlb:
  additional_listeners: 
    - port: 8081/tcp
    - port: 8082/tcp
      target_port: 8085.               # optional if the target_port is same as that of corresponding nlb port 
      target_container: sidecarA # default is set to the main container
  port: 8080/tcp
```

With this manifest, requests to NLB port `8080` will now be routed to the main container’s port `8080`. Requests to another NLB port `8081` will be routed to the port `8081` of the main service container. We need to notice here that the default value of the `target_port` will be the same as that of the corresponding NLB port. The requests to NLB port `8082` will be routed to port `8085` of the sidecar container.

Please do share your feedback on the multiple ports design.
