### ISSUE TITLE
[Bug] Command parameter is ignored in certain situations

### ISSUE THREAD

**Issue by FraserThompson** [aws/copilot-cli#4175]
I have a backend service which looks like this:

```
image:
  location: solr:8.11.2-slim
  port: 8983
  command: echo "test"
```

In this situation I would expect the task to just echo "test", and then quit, because the command in the image is being overriden in the manifest. But that doesn't happen.

When I change the command in the manifest file, it also doesn't detect any changes when I run svc deploy. So it feels like the command parameter is being completely ignored in this situation.

**Comment by huanjani** [comment]
Hello, @FraserThompson!

[`command`](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#command) is a top-level field, so please try again with:
```
image:
  location: solr:8.11.2-slim
  port: 8983
command: echo "test"
```
Let us know if that works!

(One other option is `command` [for a container health check](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-healthcheck-cmd).)
