### ISSUE TITLE
Docs is not clear about how to use addon credentials as variable in manifest

### ISSUE THREAD

**Issue by jericopulvera** [aws/copilot-cli#4176]
As it takes a long time to deploy a service It's preferrable to be clear on how to add addon credentials as variable in manifest.

The generated secret from my RDS addon is formatted like this in plaintext
```json
{"dbClusterIdentifier":"","password":"","dbname":"","engine":"","port":3306,"host":"","username":"admin"}
```

How would this be mapped into this using the example on this page this https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

```yaml
  DB_SECRET:
    secretsmanager: '${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/mysql'
 ```
 
 
If I want to get the username and password, would it look like this?
```yaml
 DB_USERNAME:
    secretsmanager: '${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/mysql/username'
 DB_PASSWORD:
    secretsmanager: '${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/mysql/password'
```
