### ISSUE TITLE
Question: Sidecar health check

### ISSUE THREAD

**Issue by raethlo** [aws/copilot-cli#4179]
Hey, so recently we've tried to add an otel sidecar to our load balanced services (to be able to push metrics to our grafana cloud instance) and we've run into a weird infinite loop deploy issue. The manifest is sth along these lines:

```yaml
sidecars:
  otel_sidecar:
    image: 'public.ecr.aws/aws-observability/aws-otel-collector:latest'
    secrets:
      AOT_CONFIG_CONTENT: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/AOT_CONFIG
    variables:
      ENVIRONMENT: ${COPILOT_ENV}
```

the problem was the config stored in ssm wasn't valid which made the sidecar crash in a loop, while at the same time the main container was healthy (but never ready because of the sidecar failing) and the circuit-breaker was never triggered to rollback the deploy - so in the end we had to manually set the ecs service desired count to 0 and revert the sidecar change. Might have missed it in the docs, but  is it possible to add a sidecar health-check? Do you have any recommendations as to how to approach this setup?

Thanks
