### ISSUE TITLE
Empty ELB access logs bucket on `env delete` before deleting the stack

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#4218]
## Background

As of copilot v1.23, if an environment has ELB access logs turned on with a Copilot managed bucket:
```yaml
http:
  public:
    access_logs: true
```
Or
```yaml
http:
  public:
    access_logs:
      prefix: access-logs
```

The environment deletion fails because:
```
The bucket you tried to delete is not empty. You must delete all versions in the bucket. (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: RD5KD2ZS7EH0S3C8; S3 Extended Request ID: p/Cor4OBBZT/ug6G1r7uTaM44SzVThbQ2tCzi4DYRwumA9MV8+uxp8zbTcOHYnhSGX02hYllGpo=; Proxy: null)
```

## Ask
Before deleting the environment, Copilot should empty the bucket *only if* the bucket is created by Copilot and not imported, prior to issue a `DeleteStack` call to CloudFormation.
