### ISSUE TITLE
Import Values From Other CFN Stacks in Workload Manifests

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4220]
### Proposal

Today, user can use [`from_tags`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement-subnets-from-tags) (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement-subnets-from-tags)  in a workload manifest under `network.vpc.placement.subnets` to specify external subnets for a service/job based on AWS tags. This proposal introduces `from_cfn`, an additional way to connect resources from other CFN stack outputs into a service/job.

We expect the `from_cfn` feature to be useful if you have existing AWS CloudFormation stacks that you’d like to connect with your Copilot workloads or if you’re using [environment addons #4219](https://github.com/aws/copilot-cli/issues/4219).

### Experience

To reference a value from another CFN stack, users should first export the output value from the source stack:
```yaml
# In a different stack, e.g. named "appmesh-stack".
Outputs:
  UserDBAccessSecurityGroup:
     Value: !GetAtt UserDBAccessSecurityGroup.Id
     Export: 
        Name: MyUserDBAccessSecurityGroup # <- Unique export name within the region.
```
Now, suppose I want to associate this security group with my `web` service, I will use `from_cfn`:
```yaml
Name: web
Type: Load Balanced Web Service

network:
  vpc:
    security_groups:
       - sg-1234
       - from_cfn: MyUserDBAccessSecurityGroup # <- Import the value from the other stack.
```
This will render `!ImportValue MyUserDBAccessSecurityGroup` into `web`’s service stack. Seeing `!ImportValue`, CloudFormation will try to fetch the value and use it as a security group ID for the web service. 

For now, `from_cfn` will be added to the following manifest fields only:

1. `network.vpc.security_groups`
2. `variables`
3. `secrets`

### Use `from_cfn` to reference a value from environment addons

This feature can work in conjunction with [environment addons #4219](https://github.com/aws/copilot-cli/issues/4219) to provide a full story of creating additional environment-level resources. After user exports a value from an environment, they can use that export name in a service manifest via `from_cfn`.

Following the example started in the [environment addons proposal #4219](https://github.com/aws/copilot-cli/issues/4219) - say we now want to inject `MyAppMeshName` into my `web` service as an environment variable, we can write:
```yaml
Name: web
Type: Load Balanced Web Service

variables:
  MY_APPMESH_NAME: 
    from_cfn: ${copilot-application}-${copilot-environment}-MyAppMeshName
  LOG_LEVEL: warning
```
After running `copilot svc deploy --name web --env test`, the name of the app mesh addon that is deployed to “test” environment will be added to the web’s main container.
