### ISSUE TITLE
How to communicate my Amazon RDS

### ISSUE THREAD

**Issue by gaoyusongcn** [aws/copilot-cli#4222]
Hi guys, I debugged for a long time, but I can't find a problem. Can you check my code for me? Thank you!

Questions: 

- My `backend-app` service can not communicate with the database
- I run `copilot svc deploy -n someservice` again with no need for update my `DB stack`

`~/myproject/copilot/backend-app/addons/rds.yaml`
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  dbName:
    Type: String
    Description: The name of the initial database to be created in the RDS instance.
    Default: myproject

Resources:
  workloadSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the RDS instance'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'The Security Group for ${Name} to access RDS instance ${dbName}.'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-${Name}-RDS'

  dbInstanceSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for RDS instance.
      SubnetIds:
        !Split [',', { 'Fn::ImportValue': !Sub '${App}-${Env}-PrivateSubnets' }]

  dbInstanceSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your RDS instance'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the RDS instance.
      SecurityGroupIngress:
        - ToPort: 3306
          FromPort: 3306
          IpProtocol: tcp
          Description: !Sub 'From the Security Group of the workload ${Name}.'
          SourceSecurityGroupId: !Ref workloadSecurityGroup
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
  
  dbInstanceSecret:
    Metadata:
      'aws:copilot:description': 'A Secrets Manager secret to store your DB credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub RDS main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "adminfate"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  
  dbInstance:
    Metadata:
      'aws:copilot:description': 'The RDS database instance'
    Type: 'AWS::RDS::DBInstance'
    DependsOn: dbInstanceSecret
    Properties:
      MasterUsername:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref dbInstanceSecret, ":SecretString:username}}" ]]
      MasterUserPassword:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref dbInstanceSecret, ":SecretString:password}}" ]]
      Engine: MySQL
      EngineVersion: 8.0.30
      Port: 3306
      DBName: !Ref dbName
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      VPCSecurityGroups:
        - !Ref dbInstanceSecurityGroup
      DBSubnetGroupName: !Ref dbInstanceSubnetGroup
  
  secretDbInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref dbInstanceSecret
      TargetId: !Ref dbInstance
      TargetType: AWS::RDS::DBInstance

Outputs:
  dbInstanceSecret: # injected as DB_INSTANCE_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password' and 'engine'"
    Value: !Ref dbInstanceSecret
  workloadSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref workloadSecurityGroup
```

Enter to my `backend-app` service and `ping` my Amazon RDS for MySQL
```shell
$ copilot svc exec -n backend-app
.
.
Starting session with SessionId: ecs-execute-command-012sdf1sdf649b
.
.

/app # ping  myproject-test-backend-app-addonsstack-1k-dbinstance-x6z6asdasdasdads2.us-east-1.rds.amazonaws.com 

 100% packet loss
```
