### ISSUE TITLE
`from_tags` should work with managed VPC subnets

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4227]
### What is the bug

Suppose I let Copilot created managed VPC (as opposed to imported), with two public subnets and two private subnets.
I tagged a public subnet with `"type: public"`, and a private subnet with tag `"type: private"`.

If my service has this manifest below:

```yaml
network:
  vpc:
    placement:
      subnets:
        from_tags:
          type: "private"
```
Copilot won't automatically create a NAT.

If my service has this manifest instead:

```yaml
network:
  vpc:
    placement:
      subnets:
        from_tags:
          type: "public"
```
Copilot will keep  `"AssignPublicIp"` disabled.

A result of both cases is that my service is not able to pull image from ECR.

### What is expected

Since the VPC is managed, even though they are introduced into the service via. `from_tags`, Copilot should be able to tell whether they are private/public and create NAT/enable public IP accordingly. The behavior should be consistent with `placement.type`.

Related: [Gitter](https://gitter.im/aws/copilot-cli?at=637e339c426f9311ffba7fbc)

**Comment by WilburJZHAO** [comment]
How to work around this issue for now? I am trying to use a specific public subnet as placement. My service is not able to pull image from ECR.

**Comment by huanjani** [comment]
Hi, @WilburJZHAO!

Apologies for the delayed response-- the Copilot team was exploring and discussing your question. 

Is the subnet you'd like to use in your environment?
```
network:
  vpc:
    subnets:
      public: 
```
If so, `AssignPublicIP` should be enabled. 

Also, is there a reason you don't want to just use the default setting, placing the service in public subnets? Is it because you'd like to use the subnets you already have? As an aside, you should have two subnets for Load Balanced Web Services.

With a little more information, hopefully we can help you get deployed asap! 

Thanks and again, sorry for the delay.

**Comment by WilburJZHAO** [comment]
Hi @huanjani,

Thanks for your reply.

What I did is like this:

`network:
  vpc:
    placement:
      subnets: [public-subnet-id]`

And the reason why I want to use only one subnet as the placement is because it is in the same availability zone with my RDS database, which provides the best performance. The service on different availability zones with my RDS database will be 3 time slower than the one in the same availability zone with my RDS database.

**Comment by huanjani** [comment]
Thanks!
Is that subnet that you're specifying one that you have imported into your Copilot environment?

**Comment by WilburJZHAO** [comment]
I tried import subnets from existing and create subnets by Copilot. Both have the same error.

**Comment by WilburJZHAO** [comment]
I can see from your codebase in /internal/pkg/deploy/cloudformation/stack/transformers.go, line 906-944, in convertNetworkConfig function. If a user set network.VPC.Placement, the AssignPublicIP option will be disabled.

**Comment by huanjani** [comment]
Do you have
```
network:
  vpc:
    subnets:
      public: 
        - [public-subnet-id]
```
in your env manifest?

**Comment by huanjani** [comment]
Okay, @WilburJZHAO-- thank you so much for your patience as we figure out how to best deal with this bug. Thanks for handling our confirmation questions.

We are working to fix this bug and hope to have it out in our next release early next week!

Again, apologies for the churn and back-and-forth. I know you were also working with a Cloud Support Engineer on this.

**Comment by huanjani** [comment]
Hi, @WilburJZHAO. 
In our next release, we will be introducing an overrides feature that will unblock you while we work toward a longer-term solution: https://github.com/aws/copilot-cli/issues/4208. 

With that, you will be able to:
1. run `copilot svc override` and select `yamlpatch`, which will cause Copilot to generate a `copilot/backend/override/cfn.patches.yml` file.
2. edit the created `cfn.patches.yml` file with:
```
- op: replace
  path: /Resources/Service/Properties/NetworkConfiguration/AwsvpcConfiguration/AssignPublicIp
  value: "ENABLED"
```
3. run `copilot svc deploy`

Stay tuned, and let us know how it goes once that feature is available! Thanks again for your patience.

**Comment by WilburJZHAO** [comment]
Thanks @huanjani

**Comment by WilburJZHAO** [comment]
Hi @huanjani , 

After using the updated version 1.27.0, I cannot update my service successfully. With the same manifest.yml (use default subnets settings) file, if I returned back to version 1.26.0, I can update the service.

![Screen Shot 2023-03-29 at 11 46 11 am](https://user-images.githubusercontent.com/56952171/228401417-fba54334-2daa-4e77-9847-68946d1d9030.png)

Here is my http in manifest.yml:

![Screen Shot 2023-03-29 at 1 53 54 pm](https://user-images.githubusercontent.com/56952171/228418633-caab18bb-87bc-425c-b194-d80009a79c01.png)

And in the ListenerRule, all http requests are Redirect to https.

Did I miss something?

**Comment by paragbhingre** [comment]
@WilburJZHAO could you please paste in your service manifest here? And could you please also explain what were you trying to do and how did you end up in this error?

**Comment by WilburJZHAO** [comment]
Hi @paragbhingre,

Here is my service manifest:

```# The manifest for the "backend" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: backend
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  healthcheck: '/aws-health-check'

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: ../Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 9001

cpu: 1024       # Number of CPU units for the task.
memory: 2048    # Amount of memory in MiB used by the task.
count:
  range: 1-3
  cooldown:
    in: 180s
    out: 60s
  cpu_percentage: 70
  response_time: 10s
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
```

I updated the package to the latest version 1.27.0 this morning. 

I were trying to update my service, so I run `copilot svc deploy` and the error came, which was not there when I use version 1.26.0. I do have a listener rule for http but all http requests are redirect to https. And https listener rule will forward requests to the service.

I downgrade the package to 1.26.0, run again `copilot svc deploy` with the same manifest file. Worked fine.

**Comment by paragbhingre** [comment]
Thank you for providing the manifest details to us. I tried following the same steps as you did, and I could successfully deploy the same service from v1.26.0 to v1.27.0.
To dig deeper into your issue, could you please also provide us with the following information -

1. Have you ever manually changed the listener rule created by Copilot?
2. What do you mean by http requests are redirected to https? In your case, we do not expect to have any redirection to HTTPS at all. Could you please paste the screenshot of your listener rule showing how it is redirecting the traffic to HTTPS?

**Comment by WilburJZHAO** [comment]
@paragbhingre Thanks for your reply.

1. Yes, I manually changed the listener rule to meet the requirements
2. You can see the screenshot below. How can I achieve this by using manifest file if I don't manually change listener rules? I have two services, different host header will point to different service.

![Screen Shot 2023-03-30 at 9 49 55 am](https://user-images.githubusercontent.com/56952171/228689763-2c4cc01c-9916-4409-a865-e210bb8e1ab6.png)


![Screen Shot 2023-03-30 at 9 55 46 am](https://user-images.githubusercontent.com/56952171/228690283-17362b23-a86d-4d43-b84e-445c25ba9f30.png)

![Screen Shot 2023-03-30 at 9 59 58 am](https://user-images.githubusercontent.com/56952171/228690485-805147c2-f957-420b-b7a0-7709545a86d9.png)

**Comment by paragbhingre** [comment]
@WilburJZHAO If I am understanding it correctly, then these screenshots are after you modified the listener rules manually. And these screen shots are what you want to achieve with Copilot without manually changing the listener rules. Am I correct?

**Comment by WilburJZHAO** [comment]
@paragbhingre Yes, you are correct.

**Comment by paragbhingre** [comment]
Oh, that should be easy with Copilot. Let us consider that you have **serviceA** and **serviceB**. Let's say we want **serviceA** to be reachable on _"v1.example.com"_ and serviceB on _"v2.eample.com"_. In this case, for **serviceA** we will set [`http.alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) field as _"v1.example.com"_. And for **serviceB** we will set [`http.alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) field as _"v2.example.com"_. This way, Copilot will create 2 listeners rules for serviceA, i.e., 1. An HTTP listener rule redirecting traffic to HTTPS listener and 2. An HTTPS listener rule will route this traffic to the desired target group. Similar things will happen with ServiceB as well. So here is your manifest for serviceA with an `http.alias` field added to it, which will do the needful. 
```
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: backend
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  alias: "v1.example.com" 
  # You can specify a custom health check path. The default is "/".
  healthcheck: '/aws-health-check'

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: ../Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 9001

cpu: 1024       # Number of CPU units for the task.
memory: 2048    # Amount of memory in MiB used by the task.
count:
  range: 1-3
  cooldown:
    in: 180s
    out: 60s
  cpu_percentage: 70
  response_time: 10s
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
```

So Copilot takes care of creating the certificates for the HTTPS listener rules if your app is created with `--domain`.

Please let us know how that goes. Here to help.
