### ISSUE TITLE
Ignore addon on specific Env

### ISSUE THREAD

**Issue by jericopulvera** [aws/copilot-cli#4229]
Is it possible to not deploy an addon based on env.

For example I want to not use Aurora V2 if it's staging and use a public MySQL instead.

**Comment by Lou1415926** [comment]
Hi @jericopulvera 👋🏼  You can use [`Conditions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) to do so. For example,
```yaml
Parameters:
  Env:
    Type: String
Conditions:
  IsTestEnv: !Equals [!Ref Env, "test"]
Resources:
  AuroraDB:
     Type: AWS::RDS::DBCluster
      Condition: IsTestEnv
      ...
```
The aurora db cluster will be created only if the service is getting deployed to the "test" environment.

**Comment by jericopulvera** [comment]
Does not work. I get Outputs issue.

**Comment by jericopulvera** [comment]
Thanks. I had to learn a bit of Cloudformation but I'm able to make out the missing parts.

```yml

...
Outputs:
  serviceclusterSecret: # injected as SERVICECLUSTER_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !If [IsProductionEnv, !Ref serviceclusterAuroraSecret, ""]

```
