### ISSUE TITLE
Support docker build-time secret

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4230]
Currently, to pass sensitive information to docker build while keeping it out of manifest, folks can use  ["shell environment variable interpretation"](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/):
```yaml
image:
  build:
    args:
      TOKEN: ${TOKEN}
```

However, even though the value of `TOKEN` is kept out of the manifest, it is still visible in `docker history`. This might not be a sufficient degree of security for some users. 

It'd be great if Copilot supports docker build-time secret: [`docker build --secret`](https://docs.docker.com/engine/reference/commandline/build/#options). Note that this requires docker buildkit, and users should be responsible for mounting the secret themselves in their `Dockerfile`s.

Related: https://github.com/aws/copilot-cli/issues/4224
---
**Edit(2023/11/15)** I'd like to append a second ask from this feature is to pass SSM/secretsmanager secret as docker build args. Related https://github.com/aws/copilot-cli/issues/2794#issuecomment-1691295150.

**Comment by lokeshsipani** [comment]
Hi @iamhopaul123, will this feature enable us to pull build time args (secrets) from AWS Systems Manager. I mean, will it support having different values of args depending upon the environment?
```
image:
  build:
    dockerfile: Dockerfile
    args:
      REACT_APP_SECRET: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/SECRET
```

**Comment by Lou1415926** [comment]
@lokeshsipani I'm afraid not from AWS Systems Manager, unfortunately 😞 

>  I mean, will it support having different values of args depending upon the environment?

This however is a different story and is totally doable already, using [environment overrides
](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#environments)

```yaml
image:
  build:
    dockerfile: Dockerfile
    args:
      REACT_APP_SECRET: ${MY_REACT_APP_SECRET}

environments:
  test:
    image:
      build:
        args:
          REACT_APP_SECRET: ${TEST_REACT_APP_SECRET}
  prod:
    image:
      build:
        args:
          REACT_APP_SECRET: ${PROD_REACT_APP_SECRET}
```

When you run `copilot svc deploy --env test`, the image will be built using `${TEST_REACT_APP_SECRET}`. Similarly, when running `copilot svc deploy --env prod`, the image will be built using ` ${PROD_REACT_APP_SECRET}`.
