### ISSUE TITLE
Modify `datapoint`(Evaluation Period, Datapoints) in cloudwatch alram.

### ISSUE THREAD

**Issue by housekorea** [aws/copilot-cli#4233]
Hi, 

I wonder how can i set `evaluation period`, `data points` in copilot manifest file. It seems that the default value is 3 data point within 3 minutes. 

I want to define 1 data point within 1 minute in copilot manifest file. But, I couldn't find any documentation or comment.

**Comment by Lou1415926** [comment]
Hello @housekorea ! Just a clarification question -  "CPUUtilization" and "MemoryUtilization" the metrics you have in mind? Or is it some other metrics/alarms that you'd like to customize?

**Comment by housekorea** [comment]
Hello, @Lou1415926 

I want set `auto-scaling` by  `cpu_percentage`,  `requests`, `response_time` metrics in manifest file. I watched this enabled alarm in cloudwatch alarm menu. In scale-out scenario they watched 3 data points while 3 minutes, and scale-in scenario they watched 15 data points while 15 minutes.

I want how to set these periods and data points. I hope to define desired count of tasks on `cpu_percentage`,  `requests`, `response_time` metrics execute scale-out `1 data point while 1 minute`.

**Comment by Lou1415926** [comment]
@housekorea I see! The alarm is unfortunately not configurable from the manifest :( 

I *think* the alarm is set up by target tracking, which is pretty much managed - meaning that this configuration isn't surfaced to Copilot either, yet. 

You could manually change it in the console though. However, you probably want to double check after each deployment that the configuration isn't overridden. 

Just curious, is this because the current 15/15 not responsive enough for you?

**Comment by housekorea** [comment]
@Lou1415926 Thanks, for your reply.

I think 3/3 is not enough in `scale-out` scenario in my case. 

I see, I can't configure data points and period time using manifest.yml. Copilot have any extra way to set these points and periods time using cloudformation or addon plugins? 

(* I prefer set these value in file, not AWS management console.)

I have a question about ECS Schedule Auto-scaling. Can I set specific desired_count on weekday 9:00 AM to 18:00 PM using copilot`s features?

**Comment by Lou1415926** [comment]
> Copilot have any extra way to set these points and periods time using cloudformation or addon plugins?

@housekorea  This *could* be probably achieved by [addons](https://aws.github.io/copilot-cli/docs/developing/addons/modeling/) by some extra work. I haven't tried out the solution yet, but here is a sketch that could helpfully be helpful to you 🤞🏼.


1. Define `copilot/<svc>/addons/addons.parameters.yml`
```yaml
Parameters:
  ServiceName: !GetAtt Service.Name
```

2. Define `copilot/<svc>/addons/cpu-scaling.yml`:
```yaml
Parameters:
  # Required parameters by AWS Copilot.
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  # Additional parameters defined in addons.parameters.yml
  ServiceName:
    Type: String

Resources:
  AutoScalingRole:
    Metadata:
      'aws:copilot:description': 'An IAM role for container auto scaling'
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'

  AutoScalingTarget:
    Metadata:
      'aws:copilot:description': "An autoscaling target to scale your service's desired count"
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 10
      ResourceId:
        Fn::Join:
          - '/'
          - - 'service'
            - Fn::ImportValue:
                 !Sub '${App}-${Env}-ClusterId'
            - !Ref ServiceName
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !GetAtt AutoScalingRole.Arn

  AutoScalingPolicyECSServiceAverageCPUUtilization:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: "ECSCustomScalingByCPUUtilization"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 120
        ScaleOutCooldown: 60
        TargetValue: 70

  MyCustomAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmActions: 
        - !Ref AutoScalingPolicyECSServiceAverageCPUUtilization
      AlarmDescription: "Custom alarm to trigger autoscaling of service ... by tracking CPUUtilization"
      AlarmName: "CustomizdECSCPUUtilizationTracking"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 12
      # Dimensions: 
      #   - Dimension
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 12
      # ExtendedStatistic: String
      # InsufficientDataActions: 
        # - String
      MetricName: CPUUtilization
      # Metrics: 
        # - MetricDataQuery
      Namespace: AWS/ECS
      # OKActions: 
        # - String
      Period: 30
      Statistic: Average
      Threshold: 70
      # ThresholdMetricId: String
      # TreatMissingData: String
      Unit: Percent


```



Another workaround I can think of right now is to use aws-cli. You need the name of the alarm that's created by autoscaling - for example, `TargetTracking-service/app-env-Cluster-<random>/app-env-svc-Service-<random>-AlarmHigh-<random>`. And then you can script it via
```console
aws cloudwatch put-metric-alarm \
--alarm-name TargetTracking-service/app-env-Cluster-<random>/app-env-svc-Service-<random>-AlarmHigh-<random>  \
--datapoints-to-alarm 13 \ 
--evaluation-periods 13 \
--comparison-operator LessThanThreshold \
--metric-name CPUUtilization \
--period 60 \
--namespace AWS/ECS \
--statistic Average \
--threshold 0.9
```


---

> I have a question about ECS Schedule Auto-scaling. Can I set specific desired_count on weekday 9:00 AM to 18:00 PM using copilot`s features?

Again, this could be *possibly* achieved using addons. I didn't test this solution either ⬇️  but I it gives you a good starting point!


1. Define `copilot/<svc>/addons/addons.parameters.yml`
```yaml
Parameters:
  ServiceName: !GetAtt Service.Name
```

2. Define `copilot/<svc>/addons/scheduled-scaling.yml`
```yaml
Parameters:
  # Required parameters by AWS Copilot.
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  # Additional parameters defined in addons.parameters.yml
  ServiceName:
    Type: String

Type: AWS::ApplicationAutoScaling::ScalableTarget
Properties: 
  MaxCapacity: 1
  MinCapacity: 1o
  ResourceId: !Ref ServiceName
  RoleARN: ...
  ScalableDimension: ecs:service:DesiredCount
  ScheduledActions: 
    - ScalableTargetAction:
        MinCapacity: 10 # Scale to 10
        MaxCapacity: 10
      Schedule: cron(...)
      ScheduledActionName: ScaleTo10EverySaturdayFrom9to18
  ServiceNamespace: ecs

```
