### ISSUE TITLE
Question: Is it possible to disable `AssignPublicIp` without specifying subnets?

### ISSUE THREAD

**Issue by EricHeitmuller-Addition** [aws/copilot-cli#4257]
Hello, 

I am deploying a backend service (https://aws.github.io/copilot-cli/docs/manifest/backend-service/) which is receiving warnings for `ECS.2 ECS services should not have public IP addresses assigned to them automatically`. Investigating network options, it seems the only way to toggle `AssignPublicIp` to disabled is to assign a private subnet:

```
network:
  vpc:
    subnets:
      private: ["sn-1", "sn-2"]
``` 

Is there a way to disable AssignPublicIp without specifying the subnets? We don't want to do set them in yaml as we use the same deploy across multiple environments.

**Comment by iamhopaul123** [comment]
Hello @EricHeitmuller-Addition. Without specifying a specific subnet IDs, I think you can do

```yaml
network:
  vpc:
    placement: private
```
or
```yaml
network:
  vpc:
    placement:
      subnets:
        from_tags:
          type: private
```
if you tag all your private subnets with "type: private".
