### ISSUE TITLE
Prefix Lists

### ISSUE THREAD

**Issue by Damon-Work** [aws/copilot-cli#4272]
Hi Team,

I've attempted to try to swap out an IP specification in a Load Balancer security group with a prefix list and I'm getting the following error.

» copilot env deploy --name test
✘ validate environment manifest for "test": validate "http config": validate "public": parse IPNet pl-xxxxxxxxxxxxxxxxx: invalid CIDR address: pl-xxxxxxxxxxxxxxxxx

Is there any way to achieve this in the current state or would this need to be a new feature?

Cheers,

Damon

**Comment by efekarakus** [comment]
Hi Damon!
Would you mind sharing your environment manifest? I think the feature you're asking for isn't supported yet with Copilot.
I see https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-ingress-source-ips but no way of specifying prefix lists themselves.

**Comment by Damon-Work** [comment]
Hi @efekarakus ,

Of course.  Here it is below.

```
# Your environment name will be used in naming your resources like VPC, cluster, etc.
name: test
type: Environment

# Import your own VPC and subnets or configure how they should be created.
network:
  vpc:
    id: vpc-XXXXXXXXXXXXXXXXX
    subnets:
      public:
        - id: subnet-AAAAAAAAAAAAAAAA
        - id: subnet-BBBBBBBBBBBBBBBB
      private:
        - id: subnet-CCCCCCCCCCCCCCCCC
        - id: subnet-DDDDDDDDDDDDDDDDDD

# Configure the load balancers in your environment, once created.
http:
  alias: verdaccio.some.domain.com
  path: '*'
  healthcheck: 
    path: '/#/'
  public:
    ingress:
      source_ips: ["pl-xxxxxxxxxxxxxxxxx", "pl-yyyyyyyyyyyyyyyyy"]


# Configure observability for your environment resources.
observability:
  container_insights: true

environments:
  test:
    http:
      alias:
        - name: 'verdaccio.some.domain.com'
          hosted_zone: Z0XXXXXXXXXXXXXXXXX

```

Thanks for your quick reply.

Cheers,

Damon

**Comment by efekarakus** [comment]
ah I see! yeah unfortunately `source_ips` assumes that the inputs are strictly CIDR ranges and do not accept prefix lists today. This would be a new feature requests for us!

**Comment by rickychew77** [comment]
hi there, think it would be a good idea to allow copilot managed load balancer's security group ingress rule with prefixed list especially for aws services like cloudfront.

**Comment by KollaAdithya** [comment]
Hello @rickychew77 !
I think there is a workaround for this issue. You can use [`yaml patches`](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) for `environment overrides` to add  customer managed prefix lists for the security group attached to ALB to allow ingress.

```
# This will replace the current ingress from anyone
# to allow ingress from custom managed prefix list for HTTP Load balancer SecurityGroup 
- op: replace
  path: /Resources/PublicHTTPLoadBalancerSecurityGroup/Properties/SecurityGroupIngress/0
  value:
    Description: Allow ingress from customer managed prefix list only
    SourcePrefixListId: pl-0b408ca015e3be33a
    IpProtocol: tcp
    FromPort: 80
    ToPort: 80

# This will replace the current ingress from anyone
# to allow ingress from custom managed prefix list for HTTPS Load balancer SecurityGroup 
- op: replace
  path: /Resources/PublicHTTPSLoadBalancerSecurityGroup/Properties/SecurityGroupIngress/0
  value:
    Description: Allow ingress from customer managed prefix list only
    SourcePrefixListId: pl-0b408ca015e3be33a
    IpProtocol: tcp
    FromPort: 443
    ToPort: 443
```
Feel free to ask if you have more questions on this!
