### ISSUE TITLE
svc deployment failure shouldn't cause stack rollback

### ISSUE THREAD

**Issue by lgarvey** [aws/copilot-cli#4276]
If i run `copilot svc deploy` and this fails because of a misconfiguration of the service, which could simply be a missing environment variable or incorrect health check configuration, it's frustrating that the entire stack including storage will roll back.

Is there to plan to separate these aspects of deployment so that the final ECS service and task definition can have errors without rolling back the other components of the service?

**Comment by efekarakus** [comment]
Hi @lgarvey !

Would the the `--no-rollback` flag with `svc deploy` help? https://aws.github.io/copilot-cli/docs/commands/svc-deploy/

This should result in the addon stack staying around until the service issue is fixed. Unfortunately, eventually the rollback itself needs to happen before a new version of the service gets deployed.

In the past the way I have worked is like this:
1. Do first a deployment with just the addon with an image that's guaranteed to succeed so that we don't have to wait for these long rollbacks. For example the following manifest and the `addons/` directory: 
   ```yaml
   image:
     location: public.ecr.aws/nginx/nginx:1.23
     port: 80
   ```

2. Then modify the manifest with your real service and re-deploy:
   ```yaml
   image:
     build: './Dockerfile'
   variables:
     hello: 'world'
   ```
