### ISSUE TITLE
Secrets Manager Access

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#4283]
This may be more guidance than a bug, but I'm having trouble access secrets using the aws sdk within my container. More specifically, I created an rds.yml in my addons folder to provision a mysql rds instance and create the secrets (credentials, host, port, etc.) I verified that the secret is tagged with the copilot-application and copilot-environment tags, however; my container throws an error that the [AppName]TaskRole does not have access to get the secret due to a missing IAM policy setup. or something along those lines. I can access the secrets via the environment variables, but as this db info and I may rotate the credentials, I'd like to use the sdk to update the credentials while running. Perhaps I'm missing something though.

**Comment by efekarakus** [comment]
Hi @h5aaimtron !

### Solution
I think the issue can be fixed by creating an addon of type`AWS::IAM::ManagedPolicy` that has the necessary permissions to your secret and outputing that:
```yaml
Resources:
  SecretAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SecretRotationAccess
            Effect: Allow
            Action:
              -  secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
              - secretsmanager:UpdateSecretVersionStage
            Resource: !Ref Secret # update to your secret logical ID

Outputs:
  SecretAccessPolicyArn:
    Value: !Ref SecretAccessPolicy
```
The above should attach the `SecretAccessPolicy` managed policy to the Task Role for the service and the containers in the task should now be able to access the secret.

### Context

The secret that shows up as an environment variable is through the ECS/Fargate Agent which gets its permissions from the [TaskExecutionRole](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html) and _not_ the TaskRole.
Here is the copilot template snippet:
https://github.com/aws/copilot-cli/blob/8aebf752746533fbdbbe0f64547c67aa52fd907e/internal/pkg/template/templates/workloads/partials/cf/executionrole.yml#L30-L38

The permissions associated with your containers instead come from the TaskRole which doesn't have permission to accessing any secrets by default.
