### ISSUE TITLE
Health check for a worker service

### ISSUE THREAD

**Issue by faisalil** [aws/copilot-cli#4284]
What is the best way to build a health check for a worker service? here is what I am trying but its not working, it keeps failing at the healthcheck. I look at the logs from the container but everything is working well. The issue is with how the check is happening.

```
# The manifest for the "workers" service.
# Read the full specification for the "Worker Service" type at:
# https://aws.github.io/copilot-cli/docs/manifest/worker-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: workers
type: Worker Service

# Configuration for your containers and service.
image:
  # Docker build arguments.
  build: 
    context: ./apps/temporal-workers/
    dockerfile: ./apps/temporal-workers/Dockerfile
  port: 3000
  healthcheck:
    command: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
    interval: 12s
    retries: 2
    timeout: 5s
    start_period: 3s

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
platform: linux/x86_64  # See https://aws.github.io/copilot-cli/docs/manifest/worker-service/#platform
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

# storage:
  # readonly_fs: true       # Limit to read-only access to mounted root filesystems.


# You can register to topics from other services.
# The events can be received from an SQS queue via the env var $COPILOT_QUEUE_URI.
# subscribe:
#   topics: 
#     - name: topic-from-another-service
#       service: another-service

# Optional fields for more advanced use-cases.
#
#variables:                    # Pass environment variables as key value pairs.
#  LOG_LEVEL: info

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
#    deployment:            # The deployment strategy for the "test" environment.
#       rolling: 'recreate' # Stops existing tasks before new ones are started for faster deployments.
```
