### ISSUE TITLE
Update existing VPC i.e. reduce number of AZs and subnets

### ISSUE THREAD

**Issue by nabilzhafri** [aws/copilot-cli#4285]
Hi, may I know if it's currently possible to update already created VPC?

Previously, I've created a new VPC using default configurations i.e. 2 AZs, 2 public subnets and 2 private subnets.

Would it be possible to reduce the number of AZs and subnets once its created?

**Comment by KollaAdithya** [comment]
Hi @nabilzhafri, Once the environment has services or jobs deployed, it's no longer possible to update the VPC configuration. This is because you have active workloads that depend on these subnets. On the other hand, if you delete your existing services and jobs then you can update the manifest with the appropriate configuration.

In case of Default Copilot generated VPC, It is not possible to reduce no of Subnets and the Availability Zones for a Default Copilot generated VPC. Your VPC must have at-least 2 AZ’s and 1 Public and 1 private subnet in each AZ.

But you can configure the CIDR range and the Availability zones of the Copilot generated VPC by updating the Environment manifest file
```yaml
network:
 vpc:
  cidr: ‘10.0.0.0/16’
  subnets:
   public:
    - cidr: ‘10.0.4.0/24’
     az: ‘us-west-2c’
    - cidr: ‘10.0.1.0/24’
     az: ‘us-west-2d’
   private:
    - cidr: ‘10.0.2.0/24’
     az: ‘us-west-2c’
    - cidr: ‘10.0.3.0/24’
     az: ‘us-west-2d’
```
In case If you want to configure the no of Subnets and the Availability Zones you can import a VPC by updating Environment Manifest with VPC ID and Subnet IDs
```yaml
network:
 vpc:
  id: ‘vpc-12345’
  public:
   - id: ‘subnet-11111’
   - id: ‘subnet-22222’
   - id: ‘subnet-33333’
   - id: ‘subnet-44444’
  ```
