### ISSUE TITLE
Copilot v1.21.0 multiple Target tracking scaling policies failed to scale in

### ISSUE THREAD

**Issue by ancheung01** [aws/copilot-cli#4298]
Hi,

I am currently using copilot v1.21.0 to test Load Balanced Web Service.

 This is the snippet from service manifest.yml

```
count:
#  range: 1-3
  range:
    min: 1
    max: 3
#    spot_from: 2
  cooldown:
    in: 60s
    out: 120s
  cpu_percentage: 20
  memory_percentage: 50
```
![Screenshot 2022-12-21 at 1 41 13 PM](https://user-images.githubusercontent.com/88743961/209007559-a6f7ee62-e49c-4fe1-9629-a427cc8ed5f3.png)

![Screenshot 2022-12-21 at 1 37 11 PM](https://user-images.githubusercontent.com/88743961/209006959-f13526c5-ad9d-4f0e-9227-2e16f117ccbb.png)

From what I understand, this should trigger a scale down / in.  But ECS does not do so.  When there is only cpu_percentage policy, then ECS scales up & down event happens.

Is there something I am missing?

**Comment by Lou1415926** [comment]
Hi @ancheung01 ! Just to clarify: do you mean the ECS service is able to scale up/down as expected when you have:
```yaml
count:
  range: 1-3
  cooldown:
    in: 60s
    out: 120s
  cpu_percentage: 20
```

(That is, for example, when the CPU percentage goes below 20, the ECS service indeed scales down.)

But the ECS service is not able to scale in when you have:
```yaml
count:
  range: 1-3
  cooldown:
    in: 60s
    out: 120s
  cpu_percentage: 20
  memory_percentage: 50
```
(That is, for example, when the CPU percentage goes below 20, the ECS service does not scale down)

**Comment by ancheung01** [comment]
Yes, that is what I am seeing.

**Comment by ancheung01** [comment]
Apologies for the 2nd message.  In the screenshot shown above, all AlarmLows were "in alarm".  But I did not see ECS scale down / in event.
![Screenshot 2022-12-21 at 2 11 09 PM](https://user-images.githubusercontent.com/88743961/209011915-84617b32-190a-4789-a9c8-a8d5bce8099b.png)

**Comment by Lou1415926** [comment]
Thank you @ancheung01 for sharing the screenshot!!

I did some testing myself! I used a manifest that looks like this:
```yaml
count:
  range: 1-3
  cooldown:
    in: 60s
    out: 120s
  cpu_percentage: 10
  memory_percentage: 50
```

The actual CPU and memory usage are both below 10% and 50%, so shortly after the deployment, both alarms are triggered:

*In this image, the CPU LOW alarm is triggered at 11:27am, and the MEMORY LOW alarm is triggered at 11:36am*
<img width="1656" alt="Screen Shot 2022-12-22 at 12 53 34 PM" src="https://user-images.githubusercontent.com/79273084/209223979-7a337db2-74dd-4f52-aab3-fb3101c10706.png">


Looking back at the `Events` tab of the ECS service:

<img width="2250" alt="Screen Shot 2022-12-22 at 12 53 11 PM" src="https://user-images.githubusercontent.com/79273084/209223922-e5777f3e-75cd-46ec-abb0-eba035157551.png">

1. The deployment finished at 11:36am
2. The scale down event was kicked off by autoscaling at 11:49am
3. The scale down event was kicked off again at 11:51am

Both events were kicked off a while after both scale-in alarms set in!

I was looking at your event log, and it seems like you made a new deploying at 1:52pm. When Copilot makes a new deployment, it will set the initial task count to the number of tasks that exist just before the deployment. If originally, you had 3 running, then Copilot will kick off a new deployment with initial count being 3. I have an unverified speculation: maybe what you saw was an edge case, where an autoscaling event was kicked of *while* the new deployment was being made, and this somehow causes the scheduler to ignore the autoscaling event 🤔.
