### ISSUE TITLE
Issue deploying: failed to update / one or more listeners not found

### ISSUE THREAD

**Issue by NickReisenauer** [aws/copilot-cli#4309]
Hey Copilot team. I've been deploying my service using CLI v1.19.0 and just recently tried to deploy using v.1.20.0 and I got a new issue on my production environment. 

I can deploy my dev and staging environments just fine. There's shouldn't be any differences in configuration between my 3 environments other than different domains assigned, but that hasn't caused any issues in the past. But when I try to deploy my prod environment using the command `copilot deploy --app opex-api --force --env prod` I get an error saying:

```txt
Received response status [FAILED] from custom resource. Message returned: One or more listeners not found (Log: /aws/lambda/***RulePriorityFunction-***/2022/12/29/[$LATEST]***) (RequestId: ***)

Resource creation cancelled

The following resource(s) failed to update: [TaskDefinition, HTTPRulePriorityAction].
```

![Screen Shot 2022-12-29 at 10 56 21 AM](https://user-images.githubusercontent.com/38516489/209991133-98a7ab02-6749-44a7-8ba8-f718d8e7ad62.png)

Here's my manifest file: 

<details>

```txt
# The manifest for the "opex-api" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

name: opex-api
type: Load Balanced Web Service

http:
  path: "/"
  healthcheck:
    path: "/healthcheck"
    success_codes: "200"
    interval: 1m
    timeout: 59s
    grace_period: 1m

image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build:
    dockerfile: Dockerfile
  port: 3000

cpu: 4096 # Number of CPU units for the task.
memory: 16384 # Amount of memory in MiB used by the task.
platform: linux/x86_64 # See https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform
count: 1 # Number of tasks that should be running in your service.
exec: true # Enable running commands in your container.

deployments:
  rolling: default

environments:
  prod:
    variables:
      stage: "prod"
      PORT: 3000
    secrets:
      DB:
        secretsmanager: "***"
  staging:
    variables:
      stage: "staging"
      PORT: 3000
    secrets:
      DB:
        secretsmanager: "***"
  dev:
    variables:
      stage: "dev"
      PORT: 3000
    secrets:
      DB:
        secretsmanager: "***"
```

</details>

I looked into my Load Balancer Listeners and their Rules and it seems as though they're set up correctly (they look the same as the other 2 environments that are deploying ok).

![Screen Shot 2022-12-29 at 11 12 24 AM](https://user-images.githubusercontent.com/38516489/209993140-28b81886-1fc6-450b-ab76-9efc7a97e3ec.png)

![Screen Shot 2022-12-29 at 11 14 00 AM](https://user-images.githubusercontent.com/38516489/209993165-4a126a0f-3c2f-4428-af7e-6361b0ce64a5.png)

![Screen Shot 2022-12-29 at 11 14 27 AM](https://user-images.githubusercontent.com/38516489/209993173-5d221fa4-5fba-4f87-b3d0-3aee38cec0dd.png)

I also looked at issue https://github.com/aws/copilot-cli/issues/3660 and it seems like there's some similarities but I was in a little bit different situation as nothing changed but the CLI version.

Thanks for any help on this.

**Comment by huanjani** [comment]
Hello, @NickReisenauer!

Thanks for the detailed documentation of this issue. It's puzzling that it's only happening for the one environment. I'll keep digging into this, but in the meantime: 

With v1.20.0, Copilot introduced environment manifests; did [migrate your existing environments](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments)?

Have you tried upgrading to our latest version (v1.24.0)? (If you have pipelines, you may want to regenerate the buildspec as well.)

Thanks!

**Comment by NickReisenauer** [comment]
Thanks for the tip on manifests @huanjani

I went ahead and ran `copilot env show -n ${env} --manifest > copilot/environments/${env}/manifest.yml` for my 3 environments and ended up with a minimal file containing vpc public/private subnets looking like this:

```yml
name: ${env}
type: Environment
network:
  {
    vpc:
      {
        id: vpc-***,
        subnets:
          {
            public:
              [
                { id: subnet-abc },
                { id: subnet-def },
              ],
            private:
              [
                { id: subnet-123 },
                { id: subnet-456 },
              ],
          },
      },
  }
observability: { container_insights: false }
```

The manifest files for dev and staging were identical minus the name field but when I pulled my prod env it came back without any vpc’s. When I look in the UI, it’s on the same vpc’s so I tried copy-pasting the same data into my prod env manifest. I haven’t run `env deploy` on prod with my changes because I’m not sure if that will cause any issues with my active deployment? It’s an active API endpoint so I’d have to try that at a low usage time if I need to redeploy. I don’t have any pipelines set up at the moment… would that be causing an issue?

Another thing I noticed was that in my prod CloudFormation Resources file, I don’t have an entry for `HTTPListenerRule`: `AWS::ElasticLoadBalancingV2::ListenerRule`, whereas in my staging and dev environments I have an entry pointing to an arn like `arn:aws:elasticloadbalancing:us-east-2:***:listener-rule/app/opex-Publi-***/***/***`.

I did try to mess with the prod template using the output of `copilot svc package -a opex-api -e prod --upload-assets > template.yml` as I saw others doing in #3660, but ended up getting the same error as before. I also got the “One or more listeners not found” error before looking at any of that so I’m not sure if the CloudFormation would be a part of the issue.

Lastly, I tried deploying using my same command with v1.24.0 and got the same error :/

**Comment by huanjani** [comment]
> ended up with a minimal file

Yup, they should be pretty lean.

> when I pulled my prod env it came back without any vpc’s

😮 

>  I don’t have any pipelines set up at the moment… would that be causing an issue?

No, not for this, but some people have had issues with their pipelines falling behind on updates.

Okay, this is maybe a long shot, but is it possible that there are multiple cooks in the kitchen and the different envs are being handled differently? See https://github.com/aws/copilot-cli/issues/3841, which has some similarities to your account.

**Comment by NickReisenauer** [comment]
It is definitely possible that it was deployed using a different Copilot version on another machine, however we have a GitHub Actions CI/CD set up to build and deploy and the first time I got this error I had just upgraded the version in the url string and then I followed the usual steps of pushing through branches and it failed on prod build. Here's an example of the file, it's the same for all 3 but just has the different environments based on the branch. I've since set all of them to v1.24.0 and 2/3 of the environments are ok with it. 

It's also possible that something in AWS (Load Balancer, Load Balancer Rules, Security Groups, etc) was manually changed by someone else and it caused an issue with some references in my CloudFormation template. I'm not sure how to validate that however. I'm not sure if I need to recreate the environment or if there's a way I can manually reference the arn of my Load Balancer Listener based on the output of my `copilot svc package` command or anything.

Regarding my empty prod environment/manifest file, would it be ok to input the correct vpc data and run `copilot env deploy` on that without any issues? and would that potentially be a part of the problem?

I'd be happy to run any helpful commands if there's any outputs you'd like to see, or outputs of template files etc. Ideally nothing that would cause any downtime 😅 

<details>

```yml
name: Deploy to Amazon ECS Fargate dev Environment

on:
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: "us-east-2"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Copilot
        run: |
          # make directory for installing
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.24.0/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Deploy with Copilot
        run: copilot deploy --app opex-api --force --env dev
```

</details>
