### ISSUE TITLE
Is it possible to restore(or create) environment's manifest.yml from exists copilot environment.

### ISSUE THREAD

**Issue by housekorea** [aws/copilot-cli#4310]
Hello, 

I have used copilot to run `service` and `environment` in production workload. Recently, I am looking to customize Environment settings. 

But, I can't find current exists environment's manifest.yml file in my repository( Service's manifest.yml exists, but any environment directory and manifest.yml didn't exist in my codes 😨)

I want to know how I can restore or make environment's manifest which exists environment. I looking for safety actions, because it is production workload. 

Thank you.

**Comment by efekarakus** [comment]
Hi @housekorea ! Does `copilot env show --manifest` work for you? https://aws.github.io/copilot-cli/docs/commands/env-show/

**Comment by housekorea** [comment]
@efekarakus 

Thank you! It works for me, I can create manifest.yml in environment using this command.

Can I ask another question about the existing `environment` re-deploy (with change)?

- I set some multiple ALB(ALB created by Copilot, exactly it is internet-facing PULIC ALB) listener rules which do not define in manifest.yml(copilot) using AWS web console.
- After updating environment's manifest.yml and re-deploy, Does copilot delete it(ALB's Listener rule which I set manually in AWS web console)

**Comment by efekarakus** [comment]
Apologies for the late response, we just got back from the holidays :) 

Updating the environment manifest or service manifests should result in **only** modifying the resources that were created by Copilot. So if you've created listener rules outside of Copilot they should not be deleted.

However, if you try to run `copilot env delete`, you'll now have to delete the manually created listener rules yourself as Copilot isn't aware of them.

* Does that make sense?
* If I may ask, why did you create listener rules via the Console? is there a usecase that's missing with Copilot?

**Comment by housekorea** [comment]
@efekarakus 

I appreciate the explanation! It makes sense.

`If I may ask, why did you create listener rules via the Console? is there a usecase that's missing with Copilot?`

- When I initially set up service and environment of copilot, I used only `http` protocol. At that time, I missed `environment` setup for ACM certificate, So, I created manually`HTTPS Listener` on ALB which created by copilot, and add ACM.
- In recent I find documentation  about `environment`'s manifest.yml and support ACM. I can restore the manifest.yml thanks to you.

Now I understand my problem,  I should set up some additional listener rules for `HTTPSListener` using `addon` features, And update manifest.yml(env) to insert ACM. I think exists HTTPS Listener will collide with `environment`'s HTTPS Listener. 

I think I would have to delete HTTPS Listener which I created manually, and `env` deploy to create HTTPS Listener and related rules(using addons)

May I ask am does my process right?

**Comment by efekarakus** [comment]
> May I ask am does my process right?

That process looks correct! However, just to be clear it will result in downtime (the service not being accessible) while you are replacing the HTTPS listener. If that's okay, then your steps look good to me.

>  I should set up some additional listener rules for HTTPSListener using addon features, 

I wonder if this is necessary 🤔 Is there a field that's missing under `http` (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) that you need that requires you to use `addons/`?

For example if your environment manifest looks like this:
```yaml
name: 'test'
type: 'Environment'
http:
http:
  public:
    certificates:
      - arn:aws:acm:${AWS_REGION}:${AWS_ACCOUNT_ID}:certificate/13245665-cv8f-adf3-j7gd-adf876af95
```
then in your service manifest you can set:
```yaml
name: 'frontend'
type: 'Load Balanced Web Service'
http:
  alias: example.com
  hosted_zone: Z0873220N255IR3MTNR4
  path: '/'
```

This way the 'frontend' service will have a listener rule that has host header routing for example.com. It will even insert the A-record to the hosted zone for you.

**Comment by housekorea** [comment]
@efekarakus 

Thank you for answer.

> I wonder if this is necessary 🤔 Is there a field that's missing under http (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) that you need that requires you to use addons/?

In my case I need more listener rules to forward&redirect to sub-domains.




Till now I can follow your instruction, But I faced another issue. I think I reach almost to final goal. 

After replace `HTTPSListener` which defined `env` manifest. I can deploy some services using `copilot svc deploy` command by manually it works.

But, In Code Pipeline step throw error which connect my github Repository.
In 'POST_BUILD' of CodeBuild step they failed with errors log😓.

Below is occured error logs.
```


✘ To use `http.alias`, your application must be:
--
1052 | * Associated with a domain:
1053 | `copilot app init --domain example.com`
1054 | * Or, using imported certificates to your environment:
1055 | `copilot env init --import-cert-arns arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012`
1056 | ✘ generate workload cm-api template against environment prod: cannot specify http.alias when application is not associated with a domain and env prod doesn't import one or more certificates
1057 | Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error.
1058 |  
1059 | [Container] 2023/01/07 05:39:58 Command did not exit successfully for env in $pl_envs; do
1060 | tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" \| rev \| cut -c 1-128 \| rev)
1061 | for svc in $svcs; do
1062 | ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
1063 | if [ $? -ne 0 ]; then
1064 | echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
1065 | exit 1;
1066 | fi
1067 | done;
1068 | for job in $jobs; do
1069 | ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
1070 | if [ $? -ne 0 ]; then
1071 | echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
1072 | exit 1;
1073 | fi
1074 | done;
1075 | done;
1076 | exit status 1
1077 | [Container] 2023/01/07 05:39:58 Phase complete: POST_BUILD State: FAILED
1078 | [Container] 2023/01/07 05:39:58 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: for env in $pl_envs; do

```

I hope that below summary of my work it would helpful to explain my problems.


1. (A year ago) I create env&app without import or set ACM certificate.
2. I have 3 services.
    1. Frontend App - (front)
    2. CMS API - (api)
    3. Search API - (search) 
3. I deployed `front`, `api` service which does not have `ACM`, `HTTPSListenerRule` in copilot(But, I created it)
4. Cloudformation stack only created HTTPListener. SO, I attached created HTTPSListener with ACM certificate in AWS console(manually) - it works.

5. In recent, I created `environment` manifest file and added ACM like below. And, delete `HTTPSListener` and attached `Rules` in console. then deploy `prod` env. (It succeed.)
```yaml
name: prod
type: Environment
network:
    vpc:
        id: vpc-01c8f2bb96555555
        subnets:
            public:
                - id: subnet-03dff5033dad555
                - id: subnet-0003d3455555
            private:
                - id: subnet-07fb47fac5555
                - id: subnet-015cf55555

http:
    private:
        ingress:
            vpc: true
        certificates:
            - arn:aws:acm:ap-northeast-2:00000000:certificate/0000-5f16-455d-a620-1944c4a60000

        subnets: ["subnet-07fb47fac0655555", "subnet-015cf5810fd55555"]
    public:
        certificates:
          - arn:aws:acm:ap-northeast-2:00000000:certificate/0000-5f16-455d-a620-1944c4a60000
observability:
    container_insights: true
```
6. I create addon each `front` , `api` services and add `alias`, `hostedzone` in manifest.yml ( I replaced some ARNs)
```yaml
name: api
type: Load Balanced Web Service
platform: linux/x86_64
# Distribute traffic to your service.
`api` manifest.yml
http:
    path: "/"
    targetContainer: nginx
    healthcheck:
        path: "/admin"
        success_codes: "200,301"
        healthy_threshold: 3
        unhealthy_threshold: 2
        interval: 20s
        timeout: 5s
        grace_period: 60s
    deregistraion_delay: 10s
    stickness: False
    allowed_source_ips: ["0.0.0.0/0"]
    alias:
        - name: api.example.com
          hosted_zone: Z08538512IT2JG000000

`api` addons.parameters.yml
Parameters:
    HTTPSListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
    CmApiTargetGroupArn: !Ref TargetGroup

`api` https_listener-ruls.yml
Parameters:
    App:
        Type: String
        Description: Your application's name.
    Env:
        Type: String
        Description: The environment name your service, job, or workflow is being deployed to.
    Name:
        Type: String
        Description: The name of the service, job, or workflow being deployed.
    HTTPSListenerArn:
        Type: String
    CmApiTargetGroupArn:
        Type: String
Resources:
    ListenerRuleForwardSitemap:
        Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
        Properties:
            Priority: 5
            ListenerArn: !Ref HTTPSListenerArn
            Conditions:
                - Field: "path-pattern"
                  Values:
                      - "/sitemap*.xml"
                - Field: "host-header"
                  Values:
                      - "www.example.com"
                      - "example.com"
            Actions:
                - Type: "forward"
                  TargetGroupArn: !Ref CmApiTargetGroupArn
                  Order: 1
                  ForwardConfig:
                      TargetGroups:
                          - TargetGroupArn: !Ref CmApiTargetGroupArn
                            Weight: 1
                      TargetGroupStickinessConfig:
                          Enabled: false
    ListenerRuleForwardCmAPI:
        Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
        Properties:
            Priority: 15
            ListenerArn: !Ref HTTPSListenerArn
            Conditions:
                - Field: "host-header"
                  Values:
                      - "api.example.com"
            Actions:
                - Type: "forward"
                  TargetGroupArn: !Ref CmApiTargetGroupArn
                  Order: 1
                  ForwardConfig:
                      TargetGroups:
                          - TargetGroupArn: !Ref CmApiTargetGroupArn
                            Weight: 1
                      TargetGroupStickinessConfig:
                          Enabled: false

```

```yaml
`front` manifest.yml
name: front
type: Load Balanced Web Service
platform: linux/x86_64
# Distribute traffic to your service.
http:
    # Requests to this path will be forwarded to your service.
    # To match all requests you can use the "/" path.
    path: "/"
    healthcheck:
        path: "/"
        success_codes: "200"
        healthy_threshold: 3
        unhealthy_threshold: 2
        interval: 20s
        timeout: 5s
        grace_period: 60s
    stickness: False
    allowed_source_ips: ["0.0.0.0/0"]
    alias:
        - name: web.example.com
          hosted_zone:  Z08538512IT2JG000000

`front` addon parameters
Parameters:
    HTTPSListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
    NextjsTargetGroupArn: !Ref TargetGroup

`front` addon yml
Parameters:
    App:
        Type: String
        Description: Your application's name.
    Env:
        Type: String
        Description: The environment name your service, job, or workflow is being deployed to.
    Name:
        Type: String
        Description: The name of the service, job, or workflow being deployed.
    HTTPSListenerArn:
        Type: String
    NextjsTargetGroupArn:
        Type: String
Resources:
    ListenerRuleForwardDomain:
        Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
        Properties:
            Priority: 7
            ListenerArn: !Ref HTTPSListenerArn
            Conditions:
                - Field: "host-header"
                  Values:
                      - "example.com"
                      - "www.example.com"
            Actions:
                - Type: "forward"
                  TargetGroupArn: !Ref NextjsTargetGroupArn
                  Order: 1
                  ForwardConfig:
                      TargetGroups:
                          - TargetGroupArn: !Ref NextjsTargetGroupArn
                            Weight: 1
                      TargetGroupStickinessConfig:
                          Enabled: false
    ListenerRuleForwardNocache:
        Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
        Properties:
            Priority: 10
            ListenerArn: !Ref HTTPSListenerArn
            Conditions:
                - Field: "host-header"
                  Values:
                      - "nocache.example.com"
            Actions:
                - Type: "forward"
                  TargetGroupArn: !Ref NextjsTargetGroupArn
                  Order: 1
                  ForwardConfig:
                      TargetGroups:
                          - TargetGroupArn: !Ref NextjsTargetGroupArn
                            Weight: 1
                      TargetGroupStickinessConfig:
                          Enabled: false
```
7. `front`, `api` service different codebase(github repo), first is typescript, second is python. Each connect to code pipeline which created copilot.
8. Both executed well without any collision or errors using `copilot svc deploy` command in my laptop and deployed well in production workload.
9. But when I commit&push to github repo, `api` service raised error in `POST_BUILD` of CodeBuild, But `front` doesn't have any error and succeed. I couldn't find which error caused.(During execution of entire process, I didn't edit any `pipelines` buildspec.yml or manifest.yml)
 

I want to know how to fix it. Is there difference between `copilot svc deploy` and deploy process of CodeBuild?


Please, Help me : )


Updated.

I should have read read about documentation which include creation app process.😱 (I read some issues(#3045, #1188))

I doubt causeness of these problems could related initial app create settings.

Because I didn't import ACM cert when created app. So, Is there only workable solution is re-create app?

**Comment by Lou1415926** [comment]
Hello @housekorea !! 

> I doubt causeness of these problems could related initial app create settings.

You don't have to have run `copilot app init --domain`. The way you import certificates into your `prod` environment looks fine to me! You only have to *either* run `app init --domain`, or import certificates (like you've done in your environment manifest) in order to use `http.alias` for your services.

To help you with the issue, I have a few questions:
1. Are both GH repo, the `front` and the `api`, connected to the same pipeline? 
2. Do you have any `copilot env deploy` command in your buildspec? 
3. What does the environment manifest for `prod` look like in your `api` repo?

I suspect that the environment manifest for `prod` in your `api` repo does not have `http.public.certificates`. It gets deployed via `copilot env deploy`, removing the certificates that you had. After that, when the pipeline runs `copilot svc package --name api`, it errors out.

**Comment by housekorea** [comment]
Hello, @Lou1415926 

Thank you reply and explanation.

 I didn't import ACM using this command `copilot app init --domain`. I did set certificate in `prod` environment manifest.yml. I explained before, It works when I using command `copilot svc deploy`. But, when It is executed in Code Pipeline triggered by Github Repository, It throws errors when CodeBuild.


>1. Are both GH repo, the front and the api, connected to the same pipeline?

Each github code repositories have different code pipeline. In my case, `front` service belongs independent Github repo and has their code pipeline. Also, `api` service has independent github repository and code pipeline. In addtion, `api` repository has `prod` environment manifest.


>2.Do you have any copilot env deploy command in your buildspec?

It would be no.  Because, I did not custom code in buildspec.yml file. I use only code which `copilot pipeline init` command generated.


>3.What does the environment manifest for prod look like in your api repo?

I attached code snippet below,  `prod` environment manifest.yml in `api` repository.
```yml
name: prod
type: Environment
network:
    vpc:
        id: vpc-01c8f2bb96555555
        subnets:
            public:
                - id: subnet-03dff5033dad555
                - id: subnet-0003d3455555
            private:
                - id: subnet-07fb47fac5555
                - id: subnet-015cf55555

http:
    private:
        ingress:
            vpc: true
        certificates:
            - arn:aws:acm:ap-northeast-2:00000000:certificate/0000-5f16-455d-a620-1944c4a60000

        subnets: ["subnet-07fb47fac0655555", "subnet-015cf5810fd55555"]
    public:
        certificates:
          - arn:aws:acm:ap-northeast-2:00000000:certificate/0000-5f16-455d-a620-1944c4a60000
observability:
    container_insights: true
```


Still now I can't figure out what is cause of problem. But, my production workload's CI/CD broken. 

Eventually, I removed `certificate` in `prod` manifest.yml and re-deployed copilot environment. And I created HTTPSListener and rules. 

I realized this is not best practice, but only works way to running my production workload 😨

**Comment by housekorea** [comment]
Hello, @Lou1415926 

May I ask another question? 

I didn't update pipeline which related service. Is there any possibility this error?

Should I have to re-deploy `copilot pipeline` after update `prod` environment manifest.yml?

**Comment by housekorea** [comment]
Hello, 

Sadly I face another issue. I afraid that if I missed some configuration or settings. 
Today, I added new service in environment, It works with command but  Code Pipeline Failed.


Svc name : `cm-celery-flower` 
1. `copilot svc init`
2. Customize cm-celery-flow/manifest.yml file
3. `copilot svc deploy --name cm-celery-flower --env prod`
4. It succeeded.
5. copilot pipeline deploy
6. pipeline update succeed
7. In my code base I commit and git push (To execute Code Pipeline which connected github repo)
8. `cm-celery-flower` cloud-formation failed(which executed by Code Pipeline)

**In CodePipeline Screen**
![image](https://user-images.githubusercontent.com/7610148/211803318-9296360a-8bb3-4809-bf46-5c918c02ae00.png)

**In CloudFormation Event Screen**
![image](https://user-images.githubusercontent.com/7610148/211803686-a5a547e4-0e14-4c2f-aaad-ef961b607040.png)
**In CloudFormation Resource Screen**
![image](https://user-images.githubusercontent.com/7610148/211805421-ec1f4248-e663-443f-891b-7feafab9e751.png)



>Resource handler returned message: "Resource of type 'AWS::ElasticLoadBalancingV2::ListenerRule' with identifier 'One or more rules not found (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: cf95595e-b0ea-4277-af7b-581f14b16928, Extended Request ID: null)' was not found." (RequestToken: 76e9e136-f0e5-1be0-cfd3-bf047c508ee1, HandlerErrorCode: NotFound)

I can't understand what error means. HTTPListener And Internal LoadBalancer exist and `HTTPListenerRule` defined well in Cloudformation Stack Template. 

Is there any starting point to trouble shooting this problem? (Is there any resource(documentation) to learn internal mechanism to debug this problem?)

**Comment by Lou1415926** [comment]
@housekorea So sorry I wasn't able to get to you earlier :(! I will address your question one by one!

I went back to https://github.com/aws/copilot-cli/issues/4310#issuecomment-1377250968, and had another hypothesis!

I suppose `prod` is not the only environment that you have, is this correct? Did you import certificates in the other environments as well?

If `prod` is the only environment that has certificates, then you should write your service manifest like this:
```yaml
http:
  # no alias field

environments:
  prod: # Specify `http.alias` for `prod` environment only.
    http:
      alias: <your alias>
```

This way, Copilot will deploy the service with `http.alias` only in the `prod` environment, which has the certificate.

If your service manifest looks like:
```yaml
http:
  alias: <your alias>
```
Copilot will deploy the service with `http.alias` in all our your environments, for example, `prod` and `dev`. If `dev` doesn't have certificates, Copilot will error out:
> ...cannot specify http.alias when application is not associated with a domain and env prod doesn't import one or more certificates
