### ISSUE TITLE
svc deploy blocked by "CreateServiceError:  SC service is already used" error

### ISSUE THREAD

**Issue by clifff** [aws/copilot-cli#4313]
I'm trying to deploy a Rails application using copilot, and started running into this issue after I deleted all the services, job and env I had initially created in order to import an ACM certificate. Whenever I deploy my `web` service, it fails like this:

```
Only found one environment, defaulting to: test
✔ Proposing infrastructure changes for stack shakedown-test-web
- Creating the infrastructure for stack shakedown-test-web                           [rollback complete]  [368.6s]
  The following resource(s) failed to create: [Service]. Rollback reques
  ted by user.
  - Service discovery for your services to communicate within the VPC                [delete complete]    [0.0s]
  - Update your environment's shared resources                                       [update complete]    [114.1s]
    - A security group for your load balancer allowing HTTP traffic                  [create complete]    [7.9s]
    - An Application Load Balancer to distribute public traffic to your services     [create complete]    [92.5s]
    - A load balancer listener to route HTTP traffic                                 [create complete]    [4.1s]
  - An IAM role to update your environment stack                                     [delete complete]    [2.7s]
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf           [delete complete]    [17.1s]
  - A HTTP listener rule for forwarding HTTP traffic                                 [delete complete]    [2.4s]
  - A custom resource assigning priority for HTTP listener rules                     [delete complete]    [0.7s]
  - A CloudWatch log group to hold your service logs                                 [delete complete]    [0.0s]
  - An IAM Role to describe load balancer rules for assigning a priority             [delete complete]    [17.2s]
  - An ECS service to run and maintain your tasks in the environment cluster         [delete complete]    [3.8s]
    Resource handler returned message: "Invalid request provided: CreateSe
    rvice error: SC service is already used by arn:aws:servicediscovery:us
    -east-2:349702889437:namespace/ns-pr4u3b73n7gkvm7z (Service: AmazonECS
    ; Status Code: 400; Error Code: InvalidParameterException; Request ID:
     99b1420d-ffc4-42cf-ba0f-ff091fca9c41; Proxy: null)" (RequestToken: d3
    36e5d1-29aa-6495-e9fd-719d516d10ba, HandlerErrorCode: InvalidRequest)
  - A target group to connect the load balancer to your service                      [delete complete]    [0.0s]
  - An ECS task definition to group your containers and run them on ECS              [delete complete]    [3.4s]
  - An IAM role to control permissions for the containers in your tasks              [delete complete]    [0.7s]
✘ deploy service web to environment test: deploy service: stack shakedown-test-web did not complete successfully and exited with status ROLLBACK_COMPLETE
```

Looking in Cloudformation in the AWS console, I can see the `Service` resource in the stack has a status of `CREATE_FAILED` with this status:

```
Resource handler returned message: "Invalid request provided: CreateService error: SC service is already used by arn:aws:servicediscovery:us-east-2:349702889437:namespace/ns-pr4u3b73n7gkvm7z (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 99b1420d-ffc4-42cf-ba0f-ff091fca9c41; Proxy: null)" (RequestToken: d336e5d1-29aa-6495-e9fd-719d516d10ba, HandlerErrorCode: InvalidRequest)
```

For context, this is the manifest for the `web` service:

```yaml
name: web
type: Load Balanced Web Service

http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  healthcheck: 
    path: '/health'

image:
  location: tootsuite/mastodon:v4.0.2
  port: 3000
  healthcheck:
    command: 
      - CMD
      - wget
      - -q
      - --method=HEAD
      - localhost:3000/health

command: bundle exec rails s -p 3000

cpu: 256
memory: 512
count: 1
exec: true
network:
  connect: true 

 
variables:                    # Pass environment variables as key value pairs.
  # omitted

secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
    AWS_ACCESS_KEY_ID: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/WASABI_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/WASABI_SECRET_ACCESS_KEY
    DB_HOST: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-postgres-PrivateDnsName

environments:
  test:
    variables:
      # omitted
```

When all stacks are deleted, there are no Route 53 or Cloud Map records that still exist, and when deploying this stack, there are no services listed in Cloud Map. Any ideas what is causing this and how I can fix it so I can deploy this service?
