### ISSUE TITLE
Create NAT Gateway for service

### ISSUE THREAD

**Issue by sodhi1981** [aws/copilot-cli#4327]
Hello,

I want to create a NAT gateway for a service so that it can access 3rd party APIs from a whitelisted IP
Followed the advice provided over here https://github.com/aws/copilot-cli/issues/3105

https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement

But for some reason I don't see any NAT gateway in the service VPC after deployment.

Here's the environment configuration:
```
environments:
  test:
    variables:
      ENV: test # env is test
    http:
      alias: apitest.xyz.com
    cpu: 1024
    memory: 2048
    network:
      vpc:
        placement: private
```
Please advise.
