### ISSUE TITLE
copilot-cli v1.24.0 causes AmazonECS ServerException when deploying

### ISSUE THREAD

**Issue by jryanmcc** [aws/copilot-cli#4353]
Running in *us-gov-west-1*, this command successfully deployed in copilot-cli v1.23.0:

`TAG=7dcd52058990a783e68906f0dba541fce373c2fc copilot deploy --env test --name web`

Now, with copilot-cli v1.24.0:

```
❯ TAG=7dcd52058990a783e68906f0dba541fce373c2fc copilot deploy --env test --name web
✔ Proposing infrastructure changes for stack [REDACTED]
- Updating the infrastructure for stack [REDACTED]                          [update rollback complete]  [26.6s]
  The following resource(s) failed to update: [Service].                                                         
  - An ECS service to run and maintain your tasks in the environment cluster         [update complete]           [1.8s]
    Resource handler returned message: "Service was unable to process this                                       
     request. (Service: AmazonECS; Status Code: 500; Error Code: ServerExc                                       
    eption; Request ID: 1157666c-74e1-4fe8-ba75-eb43fc9f0ff5; Proxy: null)                                       
    " (RequestToken: 6ca35636-d8cf-0fcc-13eb-b744abc4de41, HandlerErrorCod                                       
    e: GeneralServiceException)                                                                                  
    Deployments                                                                                                   
               Revision  Rollout      Desired  Running  Failed  Pending                                                   
      PRIMARY  11        [completed]  1        1        0       0                                                         
  - An ECS task definition to group your containers and run them on ECS              [delete complete]           [0.0s]
```

It's interesting that with v1.24.0 it doesn't even appear to advance the ECS task revision... it just shows the current version (in this case, 11, is already running).

web/manifest.yml
```
name: web
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck: '/health'

image:
  location: [REDACTED]:${TAG}
  port: 8000

cpu: 256
memory: 1024
platform: linux/x86_64
count:
  spot: 1
exec: true
entrypoint: ["gunicorn", "-b", "0.0.0.0:8000", "--workers", "4", [REDACTED], "--timeout", "120"]

environments:
  test:
    http:
      alias:
      [REDACTED]
    variables:
      [REDACTED]

    secrets:
      [REDACTED]
network:
  vpc:
    placement: 'private'
```

environments/test/manifest.yml
```
name: test
type: Environment

network:
  vpc:
    id: [REDACTED]
    subnets:
      public:
        - id: [REDACTED]
        - id: [REDACTED]
      private:
        - id: [REDACTED]
        - id: [REDACTED]

http:
  public:
    certificates:
      [REDACTED]

observability:
  container_insights: false
```
