### ISSUE TITLE
Unable to call api using Service connect or Service discovery

### ISSUE THREAD

**Issue by BaileyNepe** [aws/copilot-cli#4354]
I have deployed a simple frontend and backend using AWS copilot and have tried to make an api call from the frontend to the backend using service connect and service discovery and am unable to get a successful response.

copilot version: v1.24.0

client manifest:

```
name: client
type: Load Balanced Web Service

http:
  path: '/'

image:
  build: Dockerfile.client
  port: 5000

cpu: 256
memory: 512
platform: linux/x86_64
count:
  range: 1-10
  cooldown:
    in: 60s
    out: 30s
  cpu_percentage: 70
  requests: 30
  response_time: 2s
exec: true

network:
  connect: true

variables:
  LOG_LEVEL: info

environments:
  dev:
    http:
      alias: dev.ecomdev.link
    variables:
      LOCAL_SERVER_PORT: 4100
  prod:
    http:
      alias: prod.ecomdev.link
```

Client Manifest:

```
name: api
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck: '/status'

image:
  build: Dockerfile.server
  port: 4100

cpu: 256
memory: 512
platform: linux/x86_64
count:
  range: 1-10
  cooldown:
    in: 60s
    out: 30s
  cpu_percentage: 70
  requests: 30
  response_time: 2s
exec: true

network:
  connect: true

variables:
  LOG_LEVEL: info
  
environments:
  dev:
    http:
      alias: api.ecomdev.link
    variables:
      LOCAL_SERVER_PORT: 4100
  prod:
    http:
      alias: prodapi.ecomdev.link
```

When I make an api call to either http://api.dev.nww-dev.local:4100 or http://api-sc:4100 from the frontend it does not succeed. 

![Screenshot 2023-01-12 at 7 43 27 AM](https://user-images.githubusercontent.com/77417393/211893387-0cb8424b-ee0e-4dab-a77c-ee74d16e6189.png)
![Screenshot 2023-01-12 at 7 43 14 AM](https://user-images.githubusercontent.com/77417393/211893409-7931eda9-51d8-41b7-9a8b-2ef4deb67f88.png)

**Service Connect Logs**

![Screenshot 2023-01-12 at 7 49 29 AM](https://user-images.githubusercontent.com/77417393/211892592-0fdaf2ba-d39f-4410-bfc8-77664da2e4b3.png)

Both the api and client are accessible through the domain as expected

![Screenshot 2023-01-12 at 7 52 21 AM](https://user-images.githubusercontent.com/77417393/211893116-d30f27bf-2b64-4058-918c-158a18aa79d2.png)
