### ISSUE TITLE
What is the status of Type:fluentd support for Firelens sidecar?

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#4396]
Hello.

I checked FirelensConfiguration at the following URL and found that it supports other Fluentd types besides Fluentbit.

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_FirelensConfiguration.html

However, I checked the documentation for the Copilot Sidecars pattern and it seems that only the Fluentbit image can be used.

https://aws.github.io/copilot-cli/docs/developing/sidecars/

Is it possible to use Fluentd images?
And if not, do you plan to support it in the future?

**Comment by efekarakus** [comment]
Hi @icruwrks !

> Is it possible to use Fluentd images?

Unfortunately today this isn't possible. Would you mind elaborating why you prefer using `fluentd` over `fluentbit`? 

>  And if not, do you plan to support it in the future?

We can definitely expose this functionality, however today you can mitigate this concern by using the `taskdef_overrides` feature: https://aws.github.io/copilot-cli/en/docs/developing/taskdef-overrides/
Alternatively, we're actively working on #4208 which would provide an alternative way of setting this field.

For example, in your manifest you can set the following field:
```yaml
taskdef_overrides:
  - path: "ContainerDefinitions[1].FirelensConfiguration.Type"
    value: fluentd
```

Let us know if this helps resolve your feature request 🙏

**Comment by icruwrks** [comment]
> Unfortunately today this isn't possible. Would you mind elaborating why you prefer using fluentd over fluentbit?

Since another log management server was built with fluentd, the copilot application also wanted to forward logs with fluentd.

Also, thanks for the information about taskdef_overrides. I will give it a try as soon as possible.

**Comment by icruwrks** [comment]
I have confirmed that it works with the following settings.
Thank you very much!

```
logging:
  image: Amazon ECR URI (Built with Fluentd)
  configFilePath: /fluentd/conf/extra.conf (Embedded config file in the Fluentd container)

taskdef_overrides:
   - path: "ContainerDefinitions[1].FirelensConfiguration.Type"
     value: fluentd
```
