### ISSUE TITLE
Rabbit-MQ unable to take path prefix from environment variable.

### ISSUE THREAD

**Issue by daniyal4747** [aws/copilot-cli#4413]
Hi,
I am using AWS copilot to deploy rabbitmq as a load balanced service, and want to serve it on a path example /rabbitmq. But I am unable to use the path-prefix property in the menifest.yml file which AWS copilot use. RABBITMQ_CONFIG_FILE maybe this variable is not taking the correct path.

_menifest.yml_
```
name: rabbitmq
type: Load Balanced Web Service
# Distribute traffic to your service.
http:
  path: 'rabbitmq'
image:
  location: public.ecr.aws/docker/library/rabbitmq:3-management
  port: 15672
cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  vpc:
    placement: 'public'
variables:                    # Pass environment variables as key value pairs.
 RABBITMQ_DEFAULT_USER: user
 RABBITMQ_DEFAULT_PASS: pass
 RABBITMQ_DEFAULT_VHOST: /
 RABBITMQ_CONFIG_FILE: copilot/rabbitmq/rabbitmq.conf
```

_rabbitmq.conf_
`management.path_prefix = /rabbitmq`

**Comment by daniyal4747** [comment]
I have tried various iterations to give paths like
1. ./rabbitmq.conf
2. rabbitmq.conf

**Comment by efekarakus** [comment]
Hi @daniyal4747 !

I'm not familiar with RabbitMQ but I'll try my best to help you 💪 

When specifying,
```yaml
variables:                   
 RABBITMQ_CONFIG_FILE: copilot/rabbitmq/rabbitmq.conf
```
Just to clarify, this won't inject _the contents_ of the file under `copilot/rabbitmq/rabbitmq.conf` to the `RABBITMQ_CONFIG_FILE` variable.
Instead it just sets the following value for the environment variable `RABBITMQ_CONFIG_FILE=copilot/rabbitmq/rabbitmq.conf` 

My hypothesis is that we need to build a custom image here instead of using `public.ecr.aws/docker/library/rabbitmq:3-management` in order to add the `rabbitmq.conf` to the image.

1. Create a custom Dockerfile, for example under `src/rabbitmq/Dockerfile`:
   ```dockerfile
   FROM public.ecr.aws/docker/library/rabbitmq:3-management

   MKDIR rabbitmq
   COPY ./rabbitmq.conf rabbitmq

   EXPOSE 15672
   ```
   
   Note that this is assuming the following directory structure:
   ```
   copilot/
      rabbitmq/
         manifest.yml
   src/
     rabbitmq/
         Dockerfile
         rabbitmq.conf
   ```

2. Update your manifest at `copilot/rabbitmq/manifest.yml` as follows:
   ```yaml
   name: rabbitmq
   type: Load Balanced Web Service
   http:
     path: 'rabbitmq'
   image:
     build: 'src/rabbitmq/Dockerfile' # Updated
     port: 15672
   cpu: 256       
   memory: 512   
   count: 1       
   exec: true     
   network:
     connect: true 
     vpc:
       placement: 'public'
   variables:                    
     RABBITMQ_DEFAULT_USER: user
     RABBITMQ_DEFAULT_PASS: pass
     RABBITMQ_DEFAULT_VHOST: /
     RABBITMQ_CONFIG_FILE: /rabbitmq/rabbitmq.conf  # updated to the path in the Dockerfile.
   ```
   
I hope this helps!

Side note: I think the best way to test this is by building the container locally first using `docker build` and `docker run` to make sure that the environment variables passed and the file location all works correctly.
Once the container seems to behave correctly locally, then it should also work with the copilot manifest 👍
