### ISSUE TITLE
How to set memory utilization percentage in manifest file for autoscaling by copilot 

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4415]
Hi support,

  We are deploying our services in ecs by copilot with autoscaling help of [https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/](url) , we need  set the memory utililization percentage for autoscaling . can you help how to define memory utilization  percentage in manifest file  .
  
  
![image](https://user-images.githubusercontent.com/78138014/214575297-e860aea4-a12b-4711-93e1-c3614b6f2f63.png)

**Comment by efekarakus** [comment]
Hi @Dhina-test! 

You can achieve that by setting the [`count.memory_percentage`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count-memory-percentage) field.

For example,
```yaml
count:
  range: 1-10
  memory_percentage: 70
```

If you'd like more advanced configuration where you configure the scaling in and out cooldowns, the field can also take a `map` as input:
```yaml
count:
  range: 1-10
  memory_percentage:
    value: 70
    cooldown:
       in: 30s
       out: 60s
```

Hope this helps! I'll close the issue for now, but don't hesitate to reach out here if you have further questions.
