### ISSUE TITLE
"An ECS service to run and maintain your tasks in the environment cluster" fails on deploy

### ISSUE THREAD

**Issue by gusgordon** [aws/copilot-cli#4417]
I'm running `copilot deploy`, and my deploy continually fails on this step: `An ECS service to run and maintain your tasks in the environment cluster`. Here's what my full console log looks like:
```
...
a463dbda4664: Layer already exists 
a9099c3159f5: Layer already exists 
latest: digest: sha256:3f109bdc111654895fa69f5b4c02d85eb8e6aaf8cb15eff5a32aee5872d4deb2 size: 3686
✔ Proposing infrastructure changes for stack demo1-test-search
- Updating the infrastructure for stack demo1-test-search                     [update in progress]  [1072.6s]
  - An autoscaling target to scale your service's desired count               [not started]         
  - A custom resource returning the ECS service's running task count          [update complete]    [3.3s]
  - An ECS service to run and maintain your tasks in the environment cluster  [update in progress]  [1053.0s]
    Deployments                                                                                     
               Revision  Rollout        Desired  Running  Failed  Pending                                   
      PRIMARY  16        [in progress]  1        0        2       1                                         
      ACTIVE   11        [completed]    1        1        0       0                                         
  - An ECS task definition to group your containers and run them on ECS       [update complete]    [2.5s]
```

Eventually, this seems to error out with `search to environment test: deploy service: context deadline exceeded` but it hasn't been consistent.

My `manifest.yml` file looks like:
```
name: search
type: Load Balanced Web Service

http: false

image:
  build: Dockerfile
  port: 80

nlb:
  port: 80/tcp

cpu: 1024
memory: 4096
platform: linux/x86_64
count:
  range: 1-10
  cooldown:
    in: 60s
    out: 30s
  cpu_percentage: 70
network:
  connect: true
```
I have tried messing around with the settings here, but nothing I do seems to get it to consistently deploy.

What could be the issue here?
