### ISSUE TITLE
Default target group for each listener on the load balancer is forwarding on port 80 instead of 443

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4420]
Hi support,

we are deploying our services by copilot for our application. at the time of cluster creation alb also created by copilot .
Here by default **HTTP:80 listener were created  with target group**. due to this we are in complaince problem.
How to redirect listener from 80 to 443 by copilot , can you help.
![image](https://user-images.githubusercontent.com/78138014/214893820-ed8a0349-4b65-4939-833f-885b2ec6de45.png)

**Comment by efekarakus** [comment]
Hi @Dhina-test !

Once you deploy a `Load Balanced Web Service` with `http.alias` you should see that the listener rule under `HTTP:80` redirects the requests from http to https.
The rule will have the following action:
```
      - Type: redirect
        RedirectConfig:
          Protocol: HTTPS
          Port: 443
          Host: "#{host}"
          Path: "/#{path}"
          Query: "#{query}"
          StatusCode: HTTP_301
```

Therefore, it's done automatically and you shouldn't need to do anything.

Does that make sense?
