### ISSUE TITLE
Copilot Expose Multiple Ports (RabbitMQ)

### ISSUE THREAD

**Issue by sadeed7** [aws/copilot-cli#4432]
I have created a load balanced service for RabbitMQ using copilot, I have created custom dockerfile for image, I need to expose multiple ports:

- 15672 for management
- 5672 for amqp connection (For socket connection between services and RabbitMQ).

Below is code for docker file:

```
FROM public.ecr.aws/docker/library/rabbitmq:3-management

COPY ./copilot/rabbitmq/rabbitmq.conf /etc/rabbitmq/

EXPOSE 15672
EXPOSE 5672
```

Below is manifest file code:
```
name: rabbitmq
type: Load Balanced Web Service

http:
  path: 'rabbitmq'
  healthcheck: '/rabbitmq'

image:
  build: 
    dockerfile: copilot/rabbitmq/Dockerfile.local
    context: /
  port: 15672

cpu: 256
memory: 512
count: 1
exec: true
platform: linux/arm64 
network:
  connect: true
  vpc:
    placement: 'public'

variables:                    # Pass environment variables as key value pairs.
 RABBITMQ_DEFAULT_USER: user
 RABBITMQ_DEFAULT_PASS: pass
 RABBITMQ_DEFAULT_VHOST: /
```

I am able to successfully expose port 15672 and I have looked over the internet but could not find anyway to expose port 5672 using copilot and also am not able to find other approach for it.
