### ISSUE TITLE
 Error while executing command: for env in $pl_envs; do

### ISSUE THREAD

**Issue by fade2black** [aws/copilot-cli#4443]
Codepipeline is triggered by merge.

```
[Container] 2023/02/01 15:53:24 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: for env in $pl_envs; do

310 | tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env \| sed 's/:/-/g' \| rev \| cut -c 1-128 \| rev)
311 | for svc in $svcs; do
312 | ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
313 | if [ $? -ne 0 ]; then
314 | echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
315 | exit 1;
316 | fi
317 | done;
318 | for job in $jobs; do
319 | ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
320 | if [ $? -ne 0 ]; then
321 | echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
322 | exit 1;
323 | fi
324 | done;
325 | done;
326 | . Reason: exit status 1
```

My manifest:
```
name: myproject
version: 1
source:
  provider: GitHub
  properties:
    branch: development
    repository: https://github.com/mycompany/myproject
    connection_name: myconnection
stages:
    name: staging
```

My `buildspec.yml`
```
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.25.0
      - mv ./copilot-linux-v1.25.0 ./copilot-linux
      - chmod +x ./copilot-linux
      - rbenv install 3.1.2
      - rbenv global 3.1.2
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - aws s3 sync dist/. s3://mybucket --delete
      - cd ..
  post_build:
    commands:
      - ls -l
      - export COLOR="false"
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/myproject/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
      - echo "PIPELINE"
      - echo $pipeline
      - pl_envs=$(echo $pipeline | jq -r '.stages[].name')
      - echo "pl_env is "
      - echo $pl_envs
      # Find all the local services in the workspace.
      - svc_ls_result=$(./copilot-linux svc ls --local --json)
      - svc_list=$(echo $svc_ls_result | jq '.services')
      - >
        if [ ! "$svc_list" = null ]; then
          svcs=$(echo $svc_ls_result | jq -r '.services[].name');
        fi
      # Find all the local jobs in the workspace.
      - job_ls_result=$(./copilot-linux job ls --local --json)
      - job_list=$(echo $job_ls_result | jq '.jobs')
      - >
        if [ ! "$job_list" = null ]; then
          jobs=$(echo $job_ls_result | jq -r '.jobs[].name');
        fi
      # Raise error if no services or jobs are found.
      - >
        if [ "$svc_list" = null ] && [ "$job_list" = null ]; then
          echo "No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote." 1>&2;
          exit 1;
        fi
      # Generate the cloudformation templates.
      # The tag is the build ID but we replaced the colon ':' with a dash '-'.
      # We truncate the tag (from the front) to 128 characters, the limit for Docker tags
      # (https://docs.docker.com/engine/reference/commandline/tag/)
      # Check if the `svc package` commanded exited with a non-zero status. If so, echo error msg and exit.
      - >
        for env in $pl_envs; do
          tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)
          for svc in $svcs; do
          ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
          for job in $jobs; do
          ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
        done;
      - ls -lah ./infrastructure
artifacts:
  files:
    - "infrastructure/*"
```

**Comment by KollaAdithya** [comment]
Hi @fade2black !
Would you mind pasting your workload manifests.

**Comment by fade2black** [comment]
Hi @KollaAdithya, do you mean the manifest in `copilot/pipelines/myservice/manifest.yml`? If so, then I put it in my original post. Here it is:
```yml
name: myproject
version: 1
source:
  provider: GitHub
  properties:
    branch: development
    repository: https://github.com/mycompany/myproject
    connection_name: myconnection
stages:
    name: staging
```

**Comment by fade2black** [comment]
@KollaAdithya `copilot/myservice/manifest.yml`
```yml
name: my-service
type: Load Balanced Web Service


http:
  path: '/'
  healthcheck: '/myapp/api/health'

image:
  build: Dockerfile
  port: 3000

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
platform: linux/x86_64  # See https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.

secrets:                     
  POSTGRES_HOST:
    secretsmanager: '********'
  POSTGRES_DB:
    secretsmanager: '********'
  POSTGRES_USER:
    secretsmanager: '********'
  POSTGRES_PASSWORD:
    secretsmanager: '********'
  RAILS_MASTER_KEY:
    secretsmanager: '********'

environments:
  staging:
    variables:
      RAILS_ENV: staging
      RAILS_LOG_TO_STDOUT: ENABLE
```

<b>Environment manifest</b>
```yml
name: staging
type: Environment

observability:
  container_insights: false
```
