### ISSUE TITLE
Support for multiple ports, one for service container and other for sidecar

### ISSUE THREAD

**Issue by carlosaherrera** [aws/copilot-cli#4445]
I have a Django application that is running as the main service app. Traffic routes to it just fine. But I also want to configure a sidecar for [Celery Flower](https://flower.readthedocs.io/en/latest/) so that I can monitor the workers for my queue. I'd like to have the sidecar listen for internet traffic on port 5555. Is there a way to configure this in the manifest? I tried simply declaring the port on the sidecar via the [port](https://aws.github.io/copilot-cli/docs/developing/sidecars/#port) param, but I can't access it in the browser. The connection simply times out.

**Comment by carlosaherrera** [comment]
Or maybe alternatively, is there a way to configure routing to accomplish what I need? For example, if the path is "/" then forward the request to the main service container, elseif path is "/flower" then forward to the flower sidecar container.

**Comment by KollaAdithya** [comment]
Hello @carlosaherrera !
Unfortunately as of now, copilot exposes only one port to the internet traffic.
Currently we are working on supporting to expose multiple ports from a container. Here is the proposal https://github.com/aws/copilot-cli/issues/4170 for multiple ports.

> if the path is "/" then forward the request to the main service container, elseif path is "/flower" then forward to the flower sidecar container.

Indeed multiple ports design support routing based on the path. 
```yaml
image:
  build: './frontend/Dockerfile'
  port: 8080
  
http:
  path: '/'
  additional_rules: # The new field "additional_rules",
    - target_port: 5555
      target_container: sidecarA
      path: '/flower'
```
      
We will keep you posted about the release of this feature. Stay tuned!
