### ISSUE TITLE
Setting a build arg in a pipeline

### ISSUE THREAD

**Issue by chriscameron** [aws/copilot-cli#4498]
I need to set a secret to a build arg that ends up in an environment variable when building the docker image in the pipeline. Code Build has the option to access the parameter store where secrets are stored (https://docs.aws.amazon.com/codebuild/latest/APIReference/API_EnvironmentVariable.html), but I’m wondering if there is a way to accomplish this through the manifest.

**Comment by paragbhingre** [comment]
@chriscameron I think you can check out [variables](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#variables) from the manifest that will be passed to your service. Let us know if that's what you are looking for.

**Comment by chriscameron** [comment]
Could you give me an example? They are secrets instead of variables from the manifest, so this is the example from the docs: 

```
image:
  build:
    dockerfile: path/to/dockerfile
    context: context/dir
    target: build-stage
    cache_from:
      - image:tag
    args:
      key: value
```

I would need to set the key: value pairs from the secrets section in the manifest. I attempted various ways to try and set those and they are not getting into the build. The args appear to be blank.

**Comment by paragbhingre** [comment]
Ohh, so do you mean you are trying to set these [sercrets](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#secrets) in the manifest and they are not appearing as environment variables in your build?

**Comment by chriscameron** [comment]
Well my original question is that I need to get secrets from the parameter store and set them as args in the build section of the manifest so they are passed in to docker build. This is supported by Code Build, but it may not be by copilot as far as I can tell. Reposting this link: https://docs.aws.amazon.com/codebuild/latest/APIReference/API_EnvironmentVariable.html

**Comment by paragbhingre** [comment]
Okay, I think I get it now. 
I think following solution will help you use secrets as env variable when building docker image in pipeline. 

1. Update pipeline buildspec to use
```
env:
  secrets-manager:
    SECRET_1: "SECRET_1:FOO"
```

2. Update the pipeline manifest to allow codebuild to pull secret from secrets manager
```
build:
  additional_policy:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'
```

3. And then update the service manifest to set up build args
```
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build:
    dockerfile: frontend/Dockerfile
    args:
      SECRET_1: ${SECRET_1}
```
4. Finally in your dockerbuild use can use SECRET_1 like this
```
ARG SECRET_1
RUN echo "'Host geoserver\n\
User user\n\
HostName 38.191.191.111\n\
IdentityFile /root/${SECRET_1}'" >> /www/data/frontend/ssh_config
```
Let us know if this helps you.
