### ISSUE TITLE
AccessDeniedException for secrets created using `secret init`

### ISSUE THREAD

**Issue by tfrench** [aws/copilot-cli#4504]
Hi there, 

Thanks for your great work!

I'm having an issue deploying an app. The app is running fine currently, but I'm unable to deploy with new secrets. I added a few secrets using `copilot secret init` and I then add them to the manifest, as shown by the example in the manifest.

I.e.:
```
secrets:
    <env var name>: <name of secret>
```

The secrets are in AWS Systems Manager (SSM) Parameter Store with correct tags (`copilot-application` and `copilot-environment`). I did not add them manually.

The ECS cluster tasks are failing with (account id removed):
```
Stopped reason
Resourceinitializationerror: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): AccessDeniedException: User: arn:aws:sts::<account id>:assumed-role/aits-demo-app-test-demo-app-ExecutionRole-28VBAJL3T0YT/f83b93a4dc3442a18eaaf8c2a235cd37 is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:eu-west-2:<account id>:parameter/GOOGLE_CLIENT_ID because no identity-based policy allows the ssm:GetParameters action status code: 400, request id: 1adcb55f-f798-4503-b8a3-cd1533290001
```

It appears to be a permissions issue; however, I can see an IAM policy is setup with permissions for the Execution role mentioned in the error. 

The copilot autogenerated policy is (with account id removed):
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Condition": {
                "StringEquals": {
                    "ssm:ResourceTag/copilot-environment": "test",
                    "ssm:ResourceTag/copilot-application": "aits-demo-app"
                }
            },
            "Action": [
                "ssm:GetParameters"
            ],
            "Resource": [
                "arn:aws:ssm:eu-west-2:<account id>:parameter/*"
            ],
            "Effect": "Allow"
        },
        {
            "Condition": {
                "StringEquals": {
                    "secretsmanager:ResourceTag/copilot-application": "aits-demo-app",
                    "secretsmanager:ResourceTag/copilot-environment": "test"
                }
            },
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:secretsmanager:eu-west-2:<account id>:secret:*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "arn:aws:kms:eu-west-2:<account id>:key/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

Any ideas? What am I missing?

Many thanks in advance!

**Comment by paragbhingre** [comment]
Hi @tfrench, Actually, there could be multiple reasons why you could see this error:
1. Make sure you are deploying to the right AWS_PROFILE.
2. Make sure that Secrets doesn't have any typos in it. 
3. Secrets should be tagged with `copilot-application` and `copilot-environment` (I can see you already have it)

Would you mind pasting your manifest here just to figure out what's going on in here?

**Comment by tfrench** [comment]
Hi @paragbhingre. Thanks for the quick reply.

On your questions:
1. I haven't changed anything with profiles (AFAIK). I only use one profile for AWS at the moment. How can I verify this? 
2. I checked that there are no typos.
3. The secrets looked tagged - they were created using `copilot secret init`. I haven't changed anything there.

The manifest:
```
# The manifest for the "demo-app" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: demo-app
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.

secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID  # The key is the name of the environment variable, the value is the name of the SSM parameter.
  GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI: GOOGLE_REDIRECT_URI
  OS_DATAHUB_API_KEY: OS_DATAHUB_API_KEY
  MAPBOX_KEY: MAPBOX_KEY
```
