### ISSUE TITLE
Unable to add additional_policy to Load Balanced Web Service

### ISSUE THREAD

**Issue by fade2black** [aws/copilot-cli#4505]
I have a standard SQS which triggers a Lambda function.
Now I want to send a message to this SQS from my Load Balanced Web Service app.
However, this service by default doesn't have a permission to send a message to SQS. 
In the pipeline manifest we are able to add additional policies, however in case of the Load Balanced Web Service I am not able to add.
I add the following lines
```
image:
  build: 'Dockerfile'
  additional_policy:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: 'arn:aws:sqs:****'
```
to `my-service/manifest.yml` and run `copilot svc deploy`. It does not make any changes to my stack.
Is it bug or do I miss something?

Note: I don't think that existing Copilot Pub/Sub suites my case. I need a simple queue to where I send my job payloads and the SQS triggers "background Lambda jobs".
One possible solution is to use an addon, but wouldn't defining inside the manifest be better?
