### ISSUE TITLE
Sharing DbInstance across services via addon

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#4554]
I've borrowed from the following template found here: [addon template](https://github.com/aws/copilot-cli/issues/4222)
I then changed the dbInstanceSecurityGroup section like so:

```
 dbInstanceSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your RDS instance'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the RDS instance.
      SecurityGroupIngress:
        - ToPort: 3306
          FromPort: 3306
          IpProtocol: tcp
          Description: !Sub 'From the Security Group of the workload ${Name}.'
          SourceSecurityGroupId:
            Fn::ImportValue: 
              !Sub '${App}-${Env}-EnvironmentSecurityGroup'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
```

With the hope of allow all services deployed to access this particular database, but only the original service is able to connect. I looked at the security group for the DbInstance and it has an inbound rule for the environment security group, but other services timeout when trying to connect. Was hoping to get some insight.
