### ISSUE TITLE
use variables defined in secrets with variables.

### ISSUE THREAD

**Issue by 93-Kusaka** [aws/copilot-cli#4574]
I want to use variables created by secret init with variables.

The following description will result in an error.
secrets:
  PASS: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/TEST"`
variables:
  LOGIN: USER/${PASS}
↓
interpolate environment variables for service manifest: environment variable "PASS" is not defined

**Comment by efekarakus** [comment]
Hi @93-Kusaka ! 

oh that's really interesting 💭 

### Mitigation

Can this issue be mitigated if you run `secret init` and create a new secret with the name `LOGIN` that has `USER/<password>` as its value? For example:
```console
$ copilot secret init --name LOGIN 
  What is the value of secret LOGIN in environment test? USER/verySecretPassword 
```
Then you can update the manifest like this:
```yaml
secrets:
   LOGIN: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/LOGIN
```

####  Explanation

To give some context for the suggestion above, the following section in the manifest:
```yaml
secrets:
    PASS: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/TEST
```
Translates directly to an [ECS TaskDefinition field](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinition.html#cfn-ecs-taskdefinition-containerdefinition-secrets) such as:
```yaml
TaskDefinition:
  Type: AWS::ECS::TaskDefinition
  Properties:
     ContainerDefinitions:
       - Secrets:
             Name: PASS
             ValueFrom: '/copilot/myapp/test/secrets/TEST'
```
Unfortunately, as you can see from the API above there is no way today within the ECS task definition to use secret values in other environment variables. This is why I've recommended above to create a separate secret for the LOGIN and it will get injected as an environment variable.

Hope this helps!
