### ISSUE TITLE
Do I need target_port with target_container?

### ISSUE THREAD

**Issue by scble** [aws/copilot-cli#4589]
Until now, all I had to do was specify target_container and it would flow to the sidecar port beyond it.
```
name: example
type: 'Load Balanced Web Service'

image:
  build:
    dockerfile: example/docker/php/Dockerfile
    target: dev
    context: example
  port: 9000

http:
  path: '/'
  alias: example.com
  targetContainer: 'nginx'

sidecars:
  nginx:
    port: 80
    image: xxxxxxxxxxxxx
```
I think it is from the timing of raising copilot-cli from 1.24.0 to 1.26.0, but the main container (php-fpm:9000port) is now registered in the target group.

Fix
```
http:
  path: '/'
  alias: example.com
  targetContainer: 'nginx'
  target_port: 80    ------> Add
```
So, we resolved the issue by specifying target_port.
In the documentation, target_port is only introduced in the NLB section, is this a correct setting? 
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb-target-port

**Comment by efekarakus** [comment]
Hi @scble 👋 

Thanks for pointing out this bug! We recently made some code changes in anticipation of #4170 and you're right that we introduced a regression here:
https://github.com/aws/copilot-cli/blob/b8935ad97bb47280a86c645e50e7d23d6d125d90/internal/pkg/manifest/svc.go#L560

I believe this issue is happening because in the manifest you are using the legacy field name `targetContainer` instead of [`target_container`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-target-container).
We changed the field name a while back to be consistent with the rest of the fields (using underscore).

I've tested the manifest with:
```yaml
http:
  path: '/'
  alias: example.com
  target_container: 'nginx'
```
and it seems to work!

Let me know if this helps resolve your concern 🙇
