### ISSUE TITLE
Is there a way to specify an arbitrary S3 file in env_file?

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#4600]
Hello!

When I specify the env_file field in Manifest, it looks as if the copilot uploads a locally placed env file to S3 for referencing.

Is it possible to specify an arbitrary S3 location where this environment variable is placed?
For example: s3://my-app/my-service/env/log.env

I'm wondering if utilising taskdef_overrides would work, but it hasn't worked yet, so I have to ask!

**Comment by efekarakus** [comment]
Hi @icruwrks !!

You're right we don't support an S3 object URL directly today 😳 I've marked the issue as a feature request.

And your intuition is correct, I believe `taskdef_overrides` should work for example:
```yaml
taskdef_overrides:
- path: ContainerDefinitions[0].EnvironmentFiles
  value: [{ Type: "s3", Value: "s3://my-app/my-service/env/log.env" }]
```
My hypothesis on why it hasn't worked is because besides `taskdef_overrides` we would need to update the ECS Task Execution Role to give permission to get the object:
https://github.com/aws/copilot-cli/blob/6b22622915d2b0c7fd164f8983e30ff52947d933/internal/pkg/template/templates/workloads/partials/cf/executionrole.yml#L47-L67

There are two possible ways of achieving this today with copilot.
1. If you don't mind modifying the IAM role through the console or AWS CLI you can do that to add the S3 object permission.
2. Alternatively, you can define a new IAM role with the same permissions + the S3 object permission and write another taskdef_override to change the `ExecutionRoleArn` to the new value.

Hope this helps!

**Comment by icruwrks** [comment]
Thank you.

> Alternatively, you can define a new IAM role with the same permissions + the S3 object permission and write another taskdef_override to change the ExecutionRoleArn to the new value.

Regarding this method, is it possible to define and load MyExecutionRole in the addons/template.yaml file?

**Comment by efekarakus** [comment]
Yes! that's definitely possible 💭 . The only downside is that the original TaskExecutionRole created by Copilot will still exist in the account (although it will be unused)

For example:
```yaml
# In addons/template.yaml
Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

# In addons/template.yaml
Resources:
  CustomExecutionRole:
    Metadata:
      "aws:copilot:description": "Custom Execution Role"
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName:
            !Join ["", [!Ref App, "-", !Ref Env, "-", !Ref Name, SecretsPolicy]]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameters"
                Resource:
                  - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
                Condition:
                  StringEquals:
                    "ssm:ResourceTag/copilot-application": !Sub "${App}"
                    "ssm:ResourceTag/copilot-environment": !Sub "${Env}"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*"
                Condition:
                  StringEquals:
                    "secretsmanager:ResourceTag/copilot-application": !Sub "${App}"
                    "secretsmanager:ResourceTag/copilot-environment": !Sub "${Env}"
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource:
                  - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/*"

          # The policy for the env file!
        - PolicyName:
            !Join [
              "",
              [!Ref App, "-", !Ref Env, "-", !Ref Name, GetEnvFilePolicy],
            ]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - "arn:aws:s3:::examplebucket/folder_name/env_file_name"
              - Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                Resource:
                  - "arn:aws:s3:::examplebucket"

Outputs:
  CustomExecutionRoleArn:
    Value: !GetAtt CustomExecutionRole.Arn
```

And afterwards in the `manifest.yml` file we can write the following override:
```yaml
taskdef_overrides:
  - path: ContainerDefinitions[0].EnvironmentFiles
    value: [{ Type: "s3", Value: "s3://examplebucket/folder_name/env_file_name" }]
  - path: ExecutionRoleArn
    value: 
      Fn::GetAtt: [AddonsStack, Outputs.CustomExecutionRoleArn]
```

Hope that unblocks you!

**Comment by icruwrks** [comment]
Thank you.

I tried it and got the following error.
Any advice would be appreciated.

```
✘ Proposing infrastructure changes for stack stack-name
✘ deploy service my-service to environment my-env: deploy service: wait for creation of change set copilot-xxxxxxxx for stack stack-name: ResourceNotReady: failed waiting for successful resource state: [/Resources/CustomExecutionRole/Type/Policies/0/PolicyDocument] 'null' values are not allowed in templates
```

**Comment by efekarakus** [comment]
I had a tabbing issue in the template above 😭 I've fixed the typo and updated the comment. If you don't mind copy/pasting it again, it should work now!

**Comment by icruwrks** [comment]
I have successfully deployed by changing the S3 value part to arn as shown below. Thank you very much.

```
taskdef_overrides:
  - path: ContainerDefinitions[0].EnvironmentFiles
    value: [{ Type: "s3", Value: "arn:aws:s3:::examplebucket/folder_name/env_file_name" }]
  - path: ExecutionRoleArn
    value:
      Fn::GetAtt: [AddonsStack, Outputs.CustomExecutionRoleArn]
```
