### ISSUE TITLE
The use can specify the timezone of the schedule expression in Scheduled Job

### ISSUE THREAD

**Issue by RaffaeleSgarro** [aws/copilot-cli#4604]
In my workload `manifest.yml` I have the following cron schedule:

```yaml
name: morning-report
type: Scheduled Job

on:
  schedule: "cron(0 9 ? * MON-FRI *)"
```

But the time is assumed in UTC and the timezone can't be changed. It would be nice if the manifest could map the [EventBridge scheduler option](https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html):

```shell
aws scheduler create-schedule \
  --schedule-expression "at(2022-11-20T13:00:00)" \
  --name schedule-name \
  --schedule-expression-timezone "America/Los_Angeles"
```

**Comment by efekarakus** [comment]
Hi @RaffaeleSgarro !

Your feature request makes sense to me, if anything Copilot could translate the schedule expression from one timezone to another.

The manifest could be something like:
```yaml
on:
   schedule: "cron(0 9 ? * MON-FRI *)"
   schedule_timezone: "America/Los_Angeles"
```

**Comment by RaffaeleSgarro** [comment]
Great! How does it work now? Do you point me to some documentation to implement it myself and send a pull request, or is it so trivial that you prefer to fix it yourself?

**Comment by efekarakus** [comment]
> How does it work now? Do you point me to some documentation to implement it myself and send a pull request, or is it so trivial that you prefer to fix it yourself?

Typically, if it's going to be implemented by the AWS Copilot team we'll need to prioritize the feature request first. We update the GitHub issues saying that the team is now picking up the feature request so that users are aware of the progress.  
Unfortunately, I can't make a commitment today for a timeline for the feature. However, if you'd like to send a pull-request we'd be happy to review it!

If you'd like to contribute the feature, I believe the following changes need to happen:
1. Adding the `timezone` field to the manifest file:
https://github.com/aws/copilot-cli/blob/499bb1ca37b11a9955377594ac8c8826bb7d7ce8/internal/pkg/manifest/job.go#L45-L47

2. Adding validation for the new field to ensure that the string entered is a valid timezone:
https://github.com/aws/copilot-cli/blob/499bb1ca37b11a9955377594ac8c8826bb7d7ce8/internal/pkg/manifest/validate.go#L1550-L1557

3. Convert the cron job expression from one timezone to the next here: https://github.com/aws/copilot-cli/blob/499bb1ca37b11a9955377594ac8c8826bb7d7ce8/internal/pkg/deploy/cloudformation/stack/scheduled_job.go#L245
(although I think the last step isn't trivial)

**Comment by jas32096** [comment]
I'd also like to see this implemented. However, just translating the expressions, before passing it to the template engine is insufficient for reoccurring jobs. The advantage of being able to select timezone is daylight savings handling.

If someone were able to rewrite the template to use [AWS::Scheduler::Schedule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html), instead of the, currently used, [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html), we'd be able to have native timezone support.

The existing template is here: https://github.com/aws/copilot-cli/blob/4b8eccbe24a9e03ff1b35ae17163a287aa3062db/internal/pkg/template/templates/workloads/partials/cf/eventrule.yml#L1-L37

**Comment by jas32096** [comment]
I ended up using the following YAML patch overrides to support my use case. May follow up with a PR to do the work described in my comment above, if there is interest. If anyone knows, if there is a way to add support for grabbing the time zone value from the manifest yaml, please let me know.

```yaml
################################################################################################################
#########################################       Time zone Support      #########################################
################################################################################################################
##    Replaces AWS::Events::Rule with AWS::Scheduler::Schedule to take advtange of EventBridge Scheduler's    ##
##                                       time zone support. See TR-209                                        ##
################################################################################################################
# Update RuleRole to allow Scheduler
- op: replace
  path: /Resources/RuleRole/Properties/AssumeRolePolicyDocument/Statement/0/Principal/Service
  value: scheduler.amazonaws.com


# Use EventBridge Scheduler instead of CloudWatch Events
- op: replace
  path: /Resources/Rule/Type
  value: 'AWS::Scheduler::Schedule'

- op: add
  path: /Resources/Rule/Properties/FlexibleTimeWindow
  value:
    # Must have quotes
    Mode: "OFF"

- op: add
  path: /Resources/Rule/Properties/ScheduleExpressionTimezone
  # Set your timezone here as an IANA time zone
  value: "America/Chicago"

- op: remove
  path: /Resources/Rule/Properties/Targets
- op: add
  path: /Resources/Rule/Properties/Target
  value:
    Arn: !Ref StateMachine
    RoleArn: !GetAtt RuleRole.Arn
################################################################################################################
#########################################    End time zone Support     #########################################
################################################################################################################
```

**Comment by happysiro** [comment]
Hello!!!
I am interested in this, I am trying to see if I can solve this by employing EventBridge Scheduler.

**Comment by alquerci** [comment]
Hello there

I am interested in this too.

The YAML patch is good except that CloudFormation reject resource type modification.

In next days, I will submit a pull request with
- Full code coverage, from unit to integration
- EventBridge Schedule that replace CloudWatch Event Rule.
- UTC as default time zone
- Allowing expression like 'at(2022-11-20T13:00:00)'
- Resource `Rule` renamed to `Schedule`
- Resource `RuleRole` renamed to `ScheduleRole`
- Configurable on `manifest.yml` but not during `job init`
- Reference to the documentation

```yaml
# job manifest.yml

# Trigger for your task.
on:
  # The scheduled trigger for your job. You can specify a Unix cron schedule or keyword (@weekly) or a rate (@every 1h30m)
  # AWS Schedule Expressions are also accepted: https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html
  schedule: "rate(5 minutes)"

  # The timezone in which the scheduling expression is evaluated.
  # You can specify a time location like (America/New_York) or like (CET)
  # More details: https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html#time-zones
  timezone: "UTC"
```

cc @efekarakus
