### ISSUE TITLE
Allow setting of service connect namespace in service manifest.

### ISSUE THREAD

**Issue by CorinWilkins** [aws/copilot-cli#4623]
This would allow engineers to configure different app's services to talk to each other via service connect.

```
network:
  connect:
    alias: frontend.local
    namespace: my-namespace
```
