### ISSUE TITLE
Detect key of the `Json Secret` when appended to Output of `Addons`

### ISSUE THREAD

**Issue by KollaAdithya** [aws/copilot-cli#4625]
Issue from Gitter Conversation: https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$CDgSOReuex_f8kFLv5PFOTt68SR8B-UnWCPGsVGbyvE

Currently Copilot will create a secret and injects it as environment variable when using an addon to create a Database. 
```yaml
Outputs:
  MyDBSecret: # injected as MY_DB_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref MyDBAuroraSecret
```
But when we update the Output of an addon stack that have the keys appended as below
```yaml
Outputs:
  MyDBSecretPassword: 
    Value: Fn::Sub
        - ${secretARN}:password::
        - secretARN: !Ref MyDBAuroraSecret
 ```
 This will create a secret `MyDBSecretPassword` as plain string environment variable instead of accessing the value of `password` from the secrets manager.
 
 So it would be nice if Copilot should be able to detect if any of the key from `json secret` is appended to the value in Addons output.
