### ISSUE TITLE
Can't change to spot instances

### ISSUE THREAD

**Issue by bfeliano** [aws/copilot-cli#4651]
Hello team.

I have a service running on Fargate and I'm trying to change it to fargate_spot.

I changed my service manifest from 

```
environments:
  production:
    count: 1
``` 

to

``` 
environments:
  production:
    count: 
      range:
        min: 2
        max: 3
        spot_from: 2 
      memory_percentage: 80 
``` 

When trying to run a *copilot svc deploy* it returns an error when trying to update the service.

The following resource(s) failed to update: [Service]. 

Resource handler returned message: "Invalid request provided: CreateService error: SC service is already used by arn:aws:servicediscovery:us-east-1:ACCOUNT:namespace/ns-xxx (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 25213558-e374-4986-b4d2-a19eff2ae660; Proxy: null)" (RequestToken: xxxx, HandlerErrorCode: InvalidRequest)
