### ISSUE TITLE
Question: Is it possible to use a custom load balancer for a service?

### ISSUE THREAD

**Issue by ThunderGod77** [aws/copilot-cli#4669]
I want to use multiple application load balancers in a single environment, I have created a custom load balancer using copilot service add-ons, how can I associate the target group to my copilot service? The load balancer option is only present in the service definition, so is it possible to override the service definition and add the load balancer or add the custom load balancer config the manifest file

I have two applications on the same path, so I need two separate internet facing application load balancer

**Comment by huanjani** [comment]
Hello, @ThunderGod77! 

Great timing! We are about to release a new feature, probably early next week, that should help you do this. See https://github.com/aws/copilot-cli/issues/4208 for info. Do you think that will work for you? 

Thanks!

**Comment by ThunderGod77** [comment]
This will probably allow me to override the service definition ...so this will work for me

**Comment by ThunderGod77** [comment]
I am getting the following error when a custom load balancer(I have created a backend service, then created a load balancer addon which created an application load balancer,target group and listener)...when I am trying to add the load balancer to the service I am getting the following error:
<img width="224" alt="Screenshot 2023-04-03 at 4 00 19 PM" src="https://user-images.githubusercontent.com/56389741/229485126-9234e2a2-78fd-4d16-8c0a-d2ca1312dc73.png">
Here are my yml patches:
```yml
- op: add
  path: /Resources/Service/Properties
  value:
    LoadBalancers:
      - ContainerName: frontend-svc
        ContainerPort: 3301
        TargetGroupArn: 
          Fn::ImportValue:
            !Sub '${AppName}-${EnvName}-FrontendLoadBalancer'
- op: add
  path: /Resources/Service/Properties
  value:
    NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            Fn::Split:
              - ','
              - Fn::ImportValue: !Sub '${AppName}-${EnvName}-PrivateSubnets'
          SecurityGroups:
            - Fn::ImportValue: !Sub '${AppName}-${EnvName}-EnvironmentSecurityGroup'
            - Fn::ImportValue: !Sub '${AppName}-${EnvName}-FrontendALBSecurityGroup'
   ```

Is this a problem because a copilot does not have a role to attach the load balancer?
I have also exported a role with all load balancer permissions like in https://aws.github.io/copilot-cli/docs/developing/addons/workload/

Is there a way to resolve this error?
