### ISSUE TITLE
Use 'docker inspect' to populate some settings

### ISSUE THREAD

**Issue by clareliguori** [aws/copilot-cli#470]
One thing that has always bugged me is that I already set the container port (`EXPOSE`) and container health check (`HEALTHCHECK`) information in the Dockerfile, and then I have to duplicate it in my task definition.

It would be neat if the CLI would inspect my built image for an EXPOSE and a HEALTHCHECK command, and use that in the task definition.

So if I have in my Dockerfile:
```
HEALTHCHECK --interval=30s CMD node healthcheck.js
EXPOSE 3001
```

This would show up in my stack's task definition:
```
      ContainerDefinitions:
        - Name: !Ref AppName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 3001
            Command: 
          HealthCheck:
            Command:
              - node
              - healthcheck.js
            Interval: 30
```

`docker inspect` seems to give the information we want. There's probably a nice golang client that gives this information:
```
$ docker inspect 1c5ecf016668 # this is the image ID for a built image I have locally
...
        "ContainerConfig": {
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "node healthcheck.js"
                ],
                "Interval": 30000000000
            },
```
