### ISSUE TITLE
I am not able to create an efs on a service when using my custom vpc

### ISSUE THREAD

**Issue by ThunderGod77** [aws/copilot-cli#4705]
<img width="192" alt="Screenshot 2023-03-29 at 2 29 42 PM" src="https://user-images.githubusercontent.com/56389741/228482998-a99ce4da-ed24-4648-bff4-6ab159797f48.png">
I am getting an error in my environment cloud formation stack when deploying my service with an efs.

**Comment by ThunderGod77** [comment]
Is there a way to circumvent this...There is a similar issue in aws cdk  https://github.com/aws/aws-cdk/issues/10170

**Comment by paragbhingre** [comment]
Hi @ThunderGod77, I'm sorry to hear that you ran into this issue. Could you please paste in your service manifest here so that it can help us dig deeper into your problem? Also, did you use your own VPC or one that Copilot created for creating an environment?

**Comment by ThunderGod77** [comment]
I am using a fresh vpc with no other files system present...still I am getting this error
```yml
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: some-query-service #Do not edit this name , as it will be auto-replaced by the script.
type: Backend Service

# Distribute traffic to your service.


# Configuration for your containers and service.
image:
  build: some-path/Dockerfile
  port: 8080
  healthcheck:
    command: ["CMD-SHELL", "curl -f localhost:8080/api/v1/health || exit 1"]
    interval: 15s
    timeout: 10s
    grace_period: 60s

# in copilot/{service name}/manifest.yml

  
network:
  connect: true
  vpc:
    placement: 'private'


cpu: 256 # Number of CPU units for the task.
memory: 512 # Amount of memory in MiB used by the task.
count: 1 # Number of tasks that should be running in your service.
exec: true # Enable running commands in your container.

storage:
  volumes:
    signozDBVolume:
      efs: true
      path: /var/lib/signoz/
      read_only: false

taskdef_overrides:
  - path: "ContainerDefinitions[0].PortMappings[-].ContainerPort"
    value: 8085
  # PortMappings[1] gets the port mapping added by the previous rule, since by default Copilot creates a port mapping.
  - path: "ContainerDefinitions[0].PortMappings[1].Protocol"
    value: "tcp"
  - path: "ContainerDefinitions[0].PortMappings[1].HostPort"
    value: 8085  

```

Here is the manifest file and I am using my own vpc and subnets...it occurs when I use cloudformation to create my vpc and then use the outputs of that cloudformation template to create resources in that vpc and then use the same vpc for my copilot application


I got the following error in cloudformation
<img width="600" alt="Screenshot 2023-03-31 at 10 52 58 AM" src="https://user-images.githubusercontent.com/56389741/229030279-ec3fc46c-97c3-40f7-a429-deae71d37a4b.png">
