### ISSUE TITLE
Sidecar build with image URL broken after update

### ISSUE THREAD

**Issue by araujogo** [aws/copilot-cli#4708]
I'm not able to deploy the service after the 1.27 upgrade. Changelog did't specify any breaking changes and Documentation of the original sidecar patterns still alive. So this configurations:
```
sidecars:
  fluent-bit:
    port: 5170
    image: public.ecr.aws/calculato/custom-fluent-bit:v1.2
```
Shouldn't be failing with
`
 deploy service conta to environment test: deploy service: check if changeset is empty: create change set copilot-3161a968-20d4-42ef-a0b4-5c6719ea0372 for stack ommited: ValidationError: Template format error: Parameter name fluent-bitEnvFileARN is non alphanumeric.
`
