### ISSUE TITLE
How to set LoadBalancerAttribute

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#4719]
Hello.

I would like to configure a LoadBalancerAttribute for an Internal Application Load Balancer created in copilot.

The following is the part of the manual in CloudFormation.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html

This configuration allows us to change settings such as access_logs, idle_timeout, routing, and waf.

How do I accomplish this in copilot?

For example, changing the idle_timeout time to 30 seconds, etc.

![image](https://user-images.githubusercontent.com/57866285/229044063-c957d88e-09d4-4ca6-b3b5-561a6266e02a.PNG)

**Comment by paragbhingre** [comment]
@icruwrks You can use our newly released feature, [YAML Patch Overrides,](https://aws.github.io/copilot-cli/blogs/release-v127/#extend-copilot-generated-aws-cloudformation-templates) to configure LoadBalancerAttribute for an Internal Application Load Balancer created in copilot. .

**Comment by dannyrandall** [comment]
Hey @icruwrks - I wanted to share an example patch for you!
1. `copilot env override --tool yamlpatch`
2. Add the following patch to `copilot/environments/overrides/cfn.patches.yml`:
```yaml
- op: add
  path: /Resources/PublicLoadBalancer/Properties/LoadBalancerAttributes
  value:
    - Key: idle_timeout.timeout_seconds
      Value: 600 # 10 minutes
```
Hope that helps!

**Comment by icruwrks** [comment]
I was able to confirm that I can change the idle_timeout with InternalLoadBalancer using the above method.
Thank you very much.

However, when I try to configure access_logs, I get an permission error.

Is there any way to resolve this?

```
- op: add
  path: /Resources/InternalLoadBalancer/Properties/LoadBalancerAttributes
  value:
    - Key: access_logs.s3.enabled
      Value: true
    - Key: access_logs.s3.bucket
      Value: "my_bucket"
    - Key: access_logs.s3.prefix
      Value: "my_app/log/test/alb"
    - Key: idle_timeout.timeout_seconds
      Value: 30
```

```
      Access Denied for bucket: my_bucket. Please check S3bucket permission
       (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: I
      nvalidConfigurationRequest
```

In the environment manifest, it seems that access-logs can be specified only in the public case.
https://aws.github.io/copilot-cli/docs/manifest/environment/

**Comment by Lou1415926** [comment]
@icruwrks You are right - we should support this feature for internal ALB as well!

Until we have the support, you are correct to use the YAML patch to do so. The error you are seeing can be resolved by adding a bucket policy to your "my_bucket". You can check out https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html#attach-bucket-policy to determine what policies are needed for your "my_bucket"!

**Comment by icruwrks** [comment]
As you said, I added the policy to S3 and it worked. Thank you very much!

By the way, is it possible to separate the cfn.patches.yml used by YAML Patch Overrides by env?

For example, if I want to change the value of idle_timeout.timeout_seconds between the test and prod environments, what should I do?

**Comment by iamhopaul123** [comment]
Hello @icruwrks. You can use [CloudFormation mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) to do that. For example
```yaml
- op: add
  path: /Mappings
  value:
    TimeoutSeconds: 
      test:
        Name: 120
      prod:
        Name: 60
- op: add
  path: /Resources/InternalLoadBalancer/Properties/LoadBalancerAttributes
  value:
    - Key: access_logs.s3.enabled
      Value: true
    - Key: access_logs.s3.bucket
      Value: "my_bucket"
    - Key: access_logs.s3.prefix
      Value: "my_app/log/test/alb"
    - Key: idle_timeout.timeout_seconds
      Value: !FindInMap [TimeoutSeconds, !Ref EnvName]
```

**Comment by icruwrks** [comment]
I was able to achieve this by modifying EnvironmentName and FindInMap as follows.

```
- op: add
  path: /Mappings
  value:
    IdleTimeout: 
      test:
        TimeoutSeconds: 120
      prod:
        TimeoutSeconds: 60
- op: add
  path: /Resources/InternalLoadBalancer/Properties/LoadBalancerAttributes
  value:
    - Key: access_logs.s3.enabled
      Value: true
    - Key: access_logs.s3.bucket
      Value: "my_bucket"
    - Key: access_logs.s3.prefix
      Value: !Sub "my_app/log/${EnvironmentName}/alb"
    - Key: idle_timeout.timeout_seconds
      Value: !FindInMap [IdleTimeout, !Ref EnvironmentName, TimeoutSeconds]
 ```     

Looking at the template file, it seemed to use EnvironmentName for patches on env and EnvName for patches on svc.
The exchange in this issue has helped me understand YAML Patch Overrides better.

Thank you!

**Comment by efekarakus** [comment]
Resolving the issue now :)

**Comment by mebibou** [comment]
@dannyrandall when I use `copilot env override --tool yamlpatch` it is telling me:
```
list environments in the workspace: read directory [...]/copilot/environments: open [...]/copilot/environments: no such file or directory
```
I have never seen that folder or what's supposed to be inside. I deployed 3 environments without problems for the app but that folder doesn't exist
```
% copilot env ls    
production
staging
test
```

**Comment by Lou1415926** [comment]
@mebibou ah were the environments deployed using an old version of Copilot? We introduced environment manifests in v1.20.0, and documented ways to "port" your existing manifest-less environment to having manifests in the [blog post](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments). You shouldn't need to recreate the environment or anything; just creating a few files should do the trick.

After v1.20.0, Copilot will expect the existence of `copilot/environments/` for commands like `copilot env deploy`, `copilot env package` and `copilot env override`. You can refer to the blog post that I posted above to create the files that Copilot expects!

**Comment by mebibou** [comment]
@Lou1415926 thanks that worked

Is there any way to set the SSL certificates using this override method? I am currently doing this after deploying:
```
aws elbv2 create-listener \
    --load-balancer-arn $LB_ARN \
    --protocol HTTPS \
    --port 443 \
    --ssl-policy "ELBSecurityPolicy-TLS-1-2-Ext-2018-06" \
    --certificates CertificateArn=$CERT_ARN \
    --default-actions Type=forward,TargetGroupArn=$TG_ARN
```

**Comment by Lou1415926** [comment]
@mebibou Do you just need to change "SSLPolicy", or the certificates as well? Both can be done with environment manifest today (see [ssl_policy](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-sslpolicy) and [certificates](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-certificates))

In general, if you are just making small changes (e.g. changing the value of certain fields), you should go with YAML path. To use [YAML patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/):
```shell
$ copilot [svc/env] package --output-dir ./tmp
# Open CFN template in ./tmp, figure out the path to the configuration that you want to tweak, for example:
# /Resources/HTTPSListener/Properties/SslPolicy

$ copilot [svc/env] override 

# Open the overrides/cfn.patches.yml file
# Add the following content:
# - op: replce
#    path: /Resources/HTTPSListener/Properties/SslPolicy
#    value: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
```

**Comment by mebibou** [comment]
@Lou1415926 oh ok I see, this new environment contains all the things I needed to do manually before. Just to confirm, would just adding:
```yaml
http:
  public:
    ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    certificates:
      - arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
```
do exactly the same as:
```
aws elbv2 create-listener \
    --load-balancer-arn $LB_ARN \
    --protocol HTTPS \
    --port 443 \
    --ssl-policy "ELBSecurityPolicy-TLS-1-2-Ext-2018-06" \
    --certificates CertificateArn=$CERT_ARN \
    --default-actions Type=forward,TargetGroupArn=$TG_ARN
```

**Comment by Lou1415926** [comment]
I take that you had to create the listener via. aws-cli because you didn't have app domain, and wanted to enable HTTPS traffic for your services right?

If so, the ⬇️ manifest should do exactly that. 
```yaml
http:
  public.
     ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
     certificates: ${CERT_ARN}
```

---
To elaborate, the manifest should end up with ⬇️ CFN template (you could run `copilot env package --diff` to double check)

```yaml
  HTTPSListener:
    Metadata:
      'aws:copilot:description': 'A load balancer listener to route HTTPS traffic'
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: ExportHTTPSListener
    Properties:
      Certificates:
        - CertificateArn: <value of $CERT_ARN>
      DefaultActions:
        - TargetGroupArn: !Ref DefaultHTTPTargetGroup # Depending on what your $TG_ARN is, this might be slightly different
          # "DefaultHTTPTargetGroup" is a dummy target group that Copilot creates so that the listener has an action for its default rule.
          # Once you deploy new services, the service will add new `ListenerRule` with appropriate `Actions` (e.g. routing to a real target group) to the listener.
          Type: forward
      LoadBalancerArn: !Ref PublicLoadBalancer # Assuming that your $LB_ARN is the ARN of the same ALB.
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06

  HTTPSImportCertificate0:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Condition: ExportHTTPSListener
    Properties:
      ListenerArn: !Ref HTTPSListener
      Certificates:
        - CertificateArn: <value of $CERT_ARN>
   
  DefaultHTTPTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: CreateALB
    Properties:
      HealthCheckIntervalSeconds: 10 
      HealthyThresholdCount: 2  
      HealthCheckTimeoutSeconds: 5
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60                 
      TargetType: ip
      VpcId: !Ref VPC
```

Therefore, there are two places that might result in a "difference" between your previous aws-cli approach and the new manifest approach, depending on what your `$TG_ARN` and `$LB_ARN` are - and I guess most likely your `$LB_ARN` is the same LB? 

If your `$TG_ARN` is _not_ the ARN of `DefaultHTTPTargetGroup` (you could double check by looking at the `Resource` tab on the console; this target group should be there already), and is instead the ARN of a real target group from one your service stack - then you will need to deploy your service, so that the HTTPS listener has a rule that routes to that real target group.

Another thing that I'd like to note is that AWS doesn't allow you to have two listeners listening on the same port. You might have to delete your old 443 listener before Copilot can create & manage a new one for you.. 

Alternatively, if deleting & recreating does not work for you, we can explore how to import your existing listener into the environment stack that Copilot manages - instructed by https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html.
