### ISSUE TITLE
docker version 18 in buildspec of test_commands gives 'Unknown runtime version'

### ISSUE THREAD

**Issue by lennertcc** [aws/copilot-cli#4721]
Hello,

Today I upgraded from 1.20 to 1.27.0. 

I use test_commands for some post deployment steps and that started failing.

The buildspec that fails is
```
version: 0.2
phases:
  install:
      runtime-versions:
        docker: 18
  build:
    commands:
      - yum install -y sudo && yum install -y expect
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.27.0
      - mv ./copilot-linux-v1.27.0 ./copilot-linux
      - chmod +x ./copilot-linux
      - unbuffer ./copilot-linux svc exec -c "python manage.py collectstatic --no-input --skip-checks" -n app -e test --yes
      - unbuffer ./copilot-linux svc exec -c "python manage.py migrate" -n app -e test --yes
```

The error I'm getting with that:
```
[Container] 2023/03/31 18:53:17 Waiting for agent ping
--
2 | [Container] 2023/03/31 18:53:18 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2023/03/31 18:53:21 Phase is DOWNLOAD_SOURCE
4 | [Container] 2023/03/31 18:53:21 CODEBUILD_SRC_DIR=/codebuild/output/src759560563/src
5 | [Container] 2023/03/31 18:53:21 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2023/03/31 18:53:21 No commands found for phase name: install
7 | [Container] 2023/03/31 18:53:21 Setting HTTP client timeout to higher timeout for S3 source
8 | [Container] 2023/03/31 18:53:21 Processing environment variables
9 | [Container] 2023/03/31 18:53:21 Selecting 'docker' runtime version '18' based on manual selections...
10 | [Container] 2023/03/31 18:53:24 Phase complete: DOWNLOAD_SOURCE State: FAILED
11 | [Container] 2023/03/31 18:53:24 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '18' of docker. This build image has the following versions: 20
```

Seems like it sets docker version 18 in the buildspec whereas version 20 is available in the build image.

Comparing that to the generated buildspec for the build stage generated by v1.27.0 that also sets docker to 20 like so:
```
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      ruby: 3.1
      nodejs: 16
```

I did run `copilot pipeline update` and all the changes for updating to v1.27.0 are committed to main.

Manually changing the buildspec of the build project to use `docker: 20` solves the issue with logging:
```


[Container] 2023/03/31 20:13:20 Waiting for agent ping
--
2 | [Container] 2023/03/31 20:13:21 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2023/03/31 20:13:25 Phase is DOWNLOAD_SOURCE
4 | [Container] 2023/03/31 20:13:25 CODEBUILD_SRC_DIR=/codebuild/output/src591659411/src
5 | [Container] 2023/03/31 20:13:25 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2023/03/31 20:13:25 No commands found for phase name: install
7 | [Container] 2023/03/31 20:13:25 Setting HTTP client timeout to higher timeout for S3 source
8 | [Container] 2023/03/31 20:13:25 Processing environment variables
9 | [Container] 2023/03/31 20:13:25 Selecting 'docker' runtime version '20' based on manual selections...
10 | [Container] 2023/03/31 20:13:25 Running command echo "Specifying docker version in buildspec is deprecated. Using docker $DOCKER_VERSION"
11 | Specifying docker version in buildspec is deprecated. Using docker 20.10.22
```

**Comment by efekarakus** [comment]
Hi @lennertcc !!

Thank you so much for reporting this issue. It looks like we have to update this section of the CloudFormation template for the pipeline:
https://github.com/aws/copilot-cli/blob/e1afe3976229284a680ae59d6be4b6a6dd0478b5/internal/pkg/template/templates/cicd/pipeline_cfn.yml#L302-L304

and completely remove `docker` in `runtime-versions` as its no longer needed to specify

**Comment by lominming** [comment]
Getting this error right now. The lines https://github.com/aws/copilot-cli/blob/e1afe3976229284a680ae59d6be4b6a6dd0478b5/internal/pkg/template/templates/cicd/pipeline_cfn.yml#L302-L304 may need to bump the version to 20?

```
[Container] 2023/04/30 06:57:20 Processing environment variables
--
9 | [Container] 2023/04/30 06:57:20 Selecting 'docker' runtime version '18' based on manual selections...
10 | [Container] 2023/04/30 06:57:22 Phase complete: DOWNLOAD_SOURCE State: FAILED
11 | [Container] 2023/04/30 06:57:22 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '18' of docker. This build image has the following versions: 20
```

**Comment by Lou1415926** [comment]
@lominming Hey there! It's been fixed in #4723, but the fix isn't rolled out yet! We will try to release the fix ASAP. For the time being, to get around this bug you can try to modify the buildspec for the test command CodeBuild project and remove ⬇️  lines altogether
```yaml
install:
  runtime-versions:
    docker: 18
```
just like what https://github.com/aws/copilot-cli/pull/4723/files#diff-b23d8ebe6f7575eb66b41d872d02a08228ae1952ed3705bfb5b5ad4a8b27c403 did.
