### ISSUE TITLE
Copilot is not able to delete the app when I have added environment addons

### ISSUE THREAD

**Issue by ThunderGod77** [aws/copilot-cli#4730]
```
copilot app delete 
```

not able to delete the app, gets stuck after deleting the services - does not proceed to delete the environment and it's addons

console shows the delete has not even been initiated

![Screenshot 2023-04-04 at 6 38 34 PM](https://user-images.githubusercontent.com/56389741/229802213-c8e35ea6-078f-4f0e-94b3-e5d5f23009f7.png)
<img width="880" alt="Screenshot 2023-04-04 at 6 38 46 PM" src="https://user-images.githubusercontent.com/56389741/229802245-efbff84f-0254-4535-99f6-32da3707fbc0.png">

**Comment by iamhopaul123** [comment]
Hello @ThunderGod77. Would you mind running `copilot app delete` again?

**Comment by ThunderGod77** [comment]
Both of them are struck, and the deletion on the nested environment addons stack has not even been initiated
![Screenshot 2023-04-05 at 1 12 31 PM](https://user-images.githubusercontent.com/56389741/230014657-9db07aa8-89f8-430b-bf6e-35ecfdb83906.png)

I have to delete the stack manually from aws cloudformation console

**Comment by iamhopaul123** [comment]
I am not sure why it just stuck without returning any error 🤔 Could you run "drift detect" on CFN console against the "dev-signoz" environment. I wonder if it is because of some drift IAM roles causing this issue.

**Comment by gabelton** [comment]
I had a similar issue where the `copilot env delete` command was hanging. After running drift detect, I saw that the addons stack had drifted and the DBInstance had drift status: DELETED. I'd manually deleted the instance earlier via the RDS console, rather than copilot cli. Trying to manually delete the addons stack in cfn console, but delete fails because complaining that it couldn't delete the DBInstance, even though it's already deleted

**Comment by Lou1415926** [comment]
@gabelton I was not able to reproduce the issue either : ( Here is what I did:
1. Create an env addon with `copilot storage init`, selected RDS
2. Run `copilot env deploy --name test` (in us-east-1)
3. After the deployment finishes, delete the WriterInstance for the addons manually through console
4. Run `copilot env delete --name test`

Both of my addons stack and the environment stack were deleted, and the command didn't hang:
```
$ copilot env delete
Only found one environment, defaulting to: test
Sure? Yes
✔ Retained IAM roles for the "test" environment
✔ Delete environment stack app-test
✔ Deleted environment "test" from application "app".
```


Prior to seeing  ⬇️  and hang, 
```
✔ Retained IAM roles for the "test" environment
✔ Delete environment stack app-test
```
were you able to see any stack events rolling on you terminal? Like this:
<img width="1253" alt="Screenshot 2023-05-24 at 4 49 41 PM" src="https://github.com/aws/copilot-cli/assets/79273084/88174e99-1b60-4796-8cbf-dd4425abcfd6">

Or did the comment just went straight to ⬇️ ?
```
✔ Delete environment stack app-test
```

Do you happen to know if this has consistently happen to you, and specially for env addons, or is it transient? This will give me a bit clue on where the problem might be?

**Comment by WillGibson** [comment]
I experiencing what I expect to be a related issue, if not the same issue...

After running `copilot svc delete` I run `copilot svc delete` and it just hung.

Looking in the environment stack's events turns up this...

```
Export some-app-development-EnvironmentSecurityGroup cannot be deleted as it is in use by someapp--AddonsStack-JHG8765CUFV
```

I cannot find any information on what command to run to delete the addons 🤷

**Comment by iamhopaul123** [comment]
Hello @WillGibson. 

> After running copilot svc delete I run copilot svc delete and it just hung.

Did you mean you ran `svc delete` to delete one svc and then run the same command again to delete another service? Or it's actually `env delete` for the second command you ran.

> I cannot find any information on what command to run to delete the addons 🤷

It seems like in one of your services/environments' addons file, you referred to `some-app-development-EnvironmentSecurityGroup`. I think you would need to delete the service/environment that owns the addons before deleting this environment. Or remove the local addons file and run `svc/env deploy` for that addons owner again to "delete" the addons.

**Comment by WillGibson** [comment]
Hi @iamhopaul123. The app has one service. This was deleted with `copilot svc delete`. Then I tried to delete the environment with `copilot env delete` and get the error mentioned above.

The security group is mentioned in `copilot/environments/addons/postgres.yml`...

```
  # Enable ingress from other ECS services created within the environment.
  postgresEnvironmentIngress:
    Metadata:
      'aws:copilot:description': 'Allow ingress from containers in my application to the OpenSearch cluster'
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress Security Group from Fargate containers
      GroupId: !Ref 'postgresDBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: { 'Fn::ImportValue': !Sub '${App}-${Env}-EnvironmentSecurityGroup' }
```

So when I try to delete the environment it's saying it can't because of something in it's own specification?

**Comment by iamhopaul123** [comment]
Hello @WillGibson I think it's probably because you deployed your environment first and then deploy with the env addons. In that scenario, since in your addons stack you refer to the env security group, you would need to delete the addons (by deleting or moving the addons file locally and then run `env deploy`) and then run `env delete` to delete the environment.

Alternatively, in order to clearly specify the dependency for CloudFormation (instead of the `Fn::ImportValue`), you can use the [addons parameter file `addons.parameter.yaml`](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#customizing-the-parameters-section) to pass the env security group ARN to the addons stack as a parameter. For example: 

```yaml
# In "mysvc/addons/my-addon.yml"
Parameters:
  # Required parameters by AWS Copilot.
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  # Additional parameters defined in addons.parameters.yml
  EnvSG:
    Type: String
```

```yaml
# In "mysvc/addons/addons.parameters.yml"
Parameters:
    EnvSG: !Ref EnvironmentSecurityGroup
```

That way you can do the env deployment/deletion in one step. Hopefully this is helpful for you!

**Comment by WillGibson** [comment]
Hi @iamhopaul123 That sounds promising. Your example is for a service addon, whereas the app I am currently playing with only has an environment addon. Looks like this should work for an environment addon though as well.

**Comment by iamhopaul123** [comment]
Hello @WillGibson. Yes, you are right: env addons should work the same way as service addons.

**Comment by WillGibson** [comment]
Hi @iamhopaul123. I have tried your suggestion and now when trying to deploy I get errors like `No export named app-name-environment-VpcId found.`

I tried getting it in via the addons file as you suggested with the `EnvironmentSecurityGroup`, but that just results in `ValidationError: Template format error: Unresolved resource dependencies [Vpcid] in the Resources block of the template`.

Is there another way to ensure that the environment stack has been created before the addons stack and vice versa?

Have we found a bug?

**Comment by KollaAdithya** [comment]
Hello @WillGibson!

**Regarding the order on how CloudFormation handles the Creation of Parent Stack and its nested Stack**

In the Addons I am referencing using the intrinsic function `!Ref` for `VpcId` from the Parent stack in nested stack. CloudFormation creates the VPC first and then creates the nested stack only after the creation of VPC.

You can look at below screenshot for the Events when creating  Environment CloudFormation stack.

![Screenshot 2023-06-21 at 2 07 30 PM](https://github.com/aws/copilot-cli/assets/71282729/4f5dac91-0c21-4d0e-b09f-4ef08d478e3f)

After looking at the error can you answer this
1. Are you using copilot managed VPC or imported VPC?

For both scenarios you can look at this [issue comment](https://github.com/aws/copilot-cli/issues/4419#issuecomment-1404418778)

**Comment by KollaAdithya** [comment]
I was able to deploy with the following configurations with Copilot managed VPC.

In `addons.parameters.yml`

```
Parameters:
  VPCID: !Ref VPC
```
in my `addons.yml `

```
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.
  VPCID:
    Type: String
    Description: The ID of the VPC in which to create the Aurora Serverless v2 cluster.
    Default: ""
```
Can you also ensure that there no typos(Capital and small letters) in the template if any
