### ISSUE TITLE
Add additional permissions or policies to the task role created by AWS Copilot for frontend app

### ISSUE THREAD

**Issue by MaxOrelus** [aws/copilot-cli#4738]
## Description

I am currently deploying a frontend app using AWS Copilot, and I need to add additional permissions or policies to the task role created by AWS Copilot. My goal is to allow the task role to have access to invoke DynamoDB through the AWS SDK being used by my frontend app's container.

## Steps to reproduce

1. Deploy a frontend app with AWS Copilot.
2. Attempt to access DynamoDB from the frontend app's container using AWS SDK.

## Expected behavior

The task role created by AWS Copilot should have the necessary permissions or policies to allow the frontend app's container to invoke DynamoDB using the AWS SDK.

## Actual behavior

The task role created by AWS Copilot does not have the required permissions or policies, and the frontend app's container cannot access DynamoDB.

## Possible solution

Provide guidance on how to add additional permissions or policies to the task role created by AWS Copilot, specifically to allow access to DynamoDB using the AWS SDK from the frontend app's container.

**Comment by iamhopaul123** [comment]
Hello @MaxOrelus. In order to add extra permission to the DynamoDB. You could either run `copilot storage init` to create an [addon stack template](https://aws.github.io/copilot-cli/docs/developing/addons/workload/), and Copilot will configure the new DynamoDB along with necessary permission and injects into the ECS task role.

Alternatively, if you've already got a DynamoDB, you could still create an addon template on your own in order to inject additional permissions to the task role:

```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  myTableAccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the myTable db'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - { Table: ADD YOUR OWN }
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: ADD YOUR OWN
          - Sid: DDBLSIActions
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource: ADD YOUR OWN

Outputs:
  myTableAccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role."
    Value: !Ref myTableAccessPolicy
```

**Comment by pkit** [comment]
Doesn't work. The TaskRole does not include the permission.
How can I know why it's not picked?
Why so much magic??
Is there any way to add the permission directly without trying to debug for hours why it's not attached??

**Comment by dannyrandall** [comment]
Hey @pkit! Sorry you're having issues getting the permissions on your TaskRole. Would you mind sharing your addons file?

Alternatively, I wonder if using [YAML Patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) might be less "magic" for you. You can make direct modifications to the template that Copilot generates. For example, if you want to add a policy directly to your task role, you could do:
```
- op: add
  path: /Resources/TaskRole/Properties/Policies/-
  value:
    PolicyName: "myPolicy"
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Action: "dynamodb:Query"
          Resource: "<add your resource here>"
```

**Comment by pkit** [comment]
I've already deleted copilot integration. Just doing it manually for now.
The problem was: that AWS::IAM::ManagedPolicy was created by copilot, the output was there too. But the Role did not have that policy attached. If you have had any logging on why it was not picked, it would probably help me.
But looking at the copilot code I couldn't find any logs/debug prints anywhete the Output is processed.

**Comment by dannyrandall** [comment]
That's great feedback, it would be nice if we had some form of debug logs to help make it easier to understand what Copilot is doing! :+1: 

If you're curious, the logic for parsing your addons is here: https://github.com/aws/copilot-cli/blob/f4e2e578ba13b4ecbc8e88e45494b530e3b061ff/internal/pkg/deploy/cloudformation/stack/workload.go#L246-L270

And the `PolicyOutputs` from that ⬆️ function are put into your CloudFormation template `TaskRole` here: https://github.com/aws/copilot-cli/blob/f4e2e578ba13b4ecbc8e88e45494b530e3b061ff/internal/pkg/template/templates/workloads/partials/cf/taskrole.yml#L5-L7


I'm happy to dig more into it/your specific issue if you're interested!

**Comment by pcolazurdo** [comment]
I just run into a similar problem. I need my taskrole to have access to a few services like Bedrock, LakeFormation and S3. It would be very useful to have a place in the manifest where additional policies can be defined so TaskRole can use those when creating the role. 
The patch workaround it's much harder to understand and maintain

**Comment by Lou1415926** [comment]
Hi @pcolazurdo ! Patching is not the only way - what @iamhopaul123 described might be helpful for your case too. Basically, you'd want to create an addon, define an `IAM::ManagedPolicy`, and add that policy into the `Outputs` section.

```console
# Your file structure
.
├── copilot/
│   ├── web
│   │   ├── manifest.yml
│   │   └── addons/
│   │          └── additional_policy.yml # Where you will put your policies that grant the task role access to other services.
│   ├── other services...

```

```yaml
# Your additional_policy.yml
Parameters:
    App:
        Type: String
    Env:
        Type: String
    Name:
        Type: String

Resources:
  MyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AccessBedrock
            Effect: Allow
            Action:
              - ...
            Resource:...

Outputs:
  MyPolicyArn: # Result: "MyPolicy" will be added to the task role, granting it access to the said services.
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MyPolicy
```

The related doc if you want to read more: https://aws.github.io/copilot-cli/docs/developing/addons/workload/#writing-the-outputs-section
