### ISSUE TITLE
Unable to create a service that manages IAM groups

### ISSUE THREAD

**Issue by pcjun97** [aws/copilot-cli#4751]
I am trying to write a service that helps assign and remove IAM groups from IAM users as part of our internal tools. With the `DenyIAMExceptTaggedRoles` policy blocking all IAM access, is there any official workaround or suggestions to allow a service deployed with copilot to manage IAM groups?

**Comment by dannyrandall** [comment]
Hey @pcjun97, great question! There isn't a way to disable the `DenyIAMExceptTaggedRoles` policy that blocks IAM access for the Task Role. However, I can think of two workarounds for you:
1. Use [addons](https://aws.github.io/copilot-cli/docs/developing/addons/workload/) to create a new role `MyServiceIAMGroupManager`, tagged with:
```
iam:ResourceTag/copilot-application: <app name>
iam:ResourceTag/copilot-environment: <env name>
```
Add a policy to this role that gives you the IAM permissions that your service needs. Then, in your service code, [assume the `MyServiceIAMGroupManager` role](https://docs.aws.amazon.com/IAM/latest/UserGuide/example_sts_AssumeRole_section.html) and you should be able to make IAM calls using that role.

2. Use [YAML patch overrides](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) to modify the `DenyIAMExceptTaggedRoles` policy. Your patch would look something like:
```
- op: replace
  path: /Resources/TaskRole/Properties/Policies/0/PolicyDocument/Statement/0
  value:
    Effect: Allow
    Action:
      - iam:AddUserToGroup
      - iam:RemoveUserFromGroup
    Resource:
      - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:user/somePrefix"
```

Hopefully that helps!😊

**Comment by pcjun97** [comment]
Thanks @dannyrandall for the prompt reply! I went with the first solution and it is working great.

Reference if others bumped into the same issue:
```yaml
# addons.parameters.yml
Parameters:
  TaskRoleArn: !GetAtt TaskRole.Arn

# example-addon.yml
Parameters:
  App:
    Type: String
    Description: The application's name.
  Env:
    Type: String
    Description: The environment name the service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The workload's name.
  TaskRoleArn:
    Type: String
    Description: The ARN of the Task Role for the ECS service.
Resources:
  awsAccessRole:
    Metadata:
      "aws:copilot:description": "An IAM role to manage IAM groups"
    Type: AWS::IAM::Role
    Properties:
      RoleName: "example-aws-access"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref TaskRoleArn
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "iam"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:AddUserToGroup"
                  - "iam:RemoveUserFromGroup"
                  - "iam:ListGroupsForUser"
                  - "iam:ListGroups"
                Resource:
                  - "*"
      Tags:
        - Key: "iam:ResourceTag/copilot-application"
          Value: !Ref App
        - Key: "iam:ResourceTag/copilot-environment"
          Value: !Ref Env
Outputs:
  # this will be injected as AWS_ASSUME_ROLE_ARN
  awsAssumeRoleArn:
    Description: "The IAM::Role to assume"
    Value: !Sub ${ awsAccessRole.Arn }

```
