### ISSUE TITLE
increase `BUILD_TIMED_OUT` in the pipeline during `test_commands` phase

### ISSUE THREAD

**Issue by menbatisiunissart** [aws/copilot-cli#4752]
I am trying to increase the `BUILD_TIMED_OUT` value in the pipeline during `test_commands` stage.

Currently my pipeline `manifest.yml` includes an additional `test_commands` phase as follows:

```
stages:
    name: test
    test_commands:
      - echo 'running postman tests'
      - npm test
```

The tests are running fine, but are running longer than the default value of 45 min and therefore generating the following error message:
![Screenshot_2023-04-08_at_16 04 14](https://user-images.githubusercontent.com/15315568/231235454-b40bdbdf-ed98-4449-9792-0a352dc75c54.png)

Is there a way to increase the `BUILD_TIMED_OUT` default value either in the `manifest` or using `overrides` ?
