### ISSUE TITLE
depends_on but for build phase (chicken and egg problem for things like SNS topics)

### ISSUE THREAD

**Issue by gabrieljoelc** [aws/copilot-cli#4773]
I have 1 application and 2 services, one existing and one new one:
Existing service:
```yaml
# web/manifest.yml
name: web
type: Load Balanced Web Service

publish:
  topics:
    - name: mytopic
```
New service:
```yaml
# subs/manifest.yml
name: subs
type: Worker Service

subscribe:
  topics:
    - name: mytopic
      service: web
```

```yaml
# pipelines/myrepo-main/manifest.yml

stages:
  - name: dev
    deployments:
      web:
      subs:
        depends_on:
          - web
```

After merging these changes, the `subs` services fails in the build phase with this error:
```
generate workload subs template against environment dev: SNS topic myapp-dev-web-mytopic does not exist in environment dev
--
460 | Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error.
```

It dawned on me that the `stages.deployments.depends_on` is for the deployment phase but the `subs` build phase "depends on" the `web`'s deployment phase finishing first.

What have others been doing for these chicken-and-egg issues?
