### ISSUE TITLE
`--diff` should not show a diff between full/short form of CFN intrinsic functions

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4780]
Today, `--diff` shows a diff between these two snippets:
```yaml
# Short form
Subnets:
  - !Ref: PublicSubnet1

# Full form
Subnets:
  - Ref: PublicSubnet1
```

CFN templates generated by CDK uses full form everywhere, whereas Copilot uses the short form. Therefore, users running `--diff` for the first time after they applied CDK overrides will see a large amount of diff, while a majority of them are false alarm because of this.

It'd be great if `--diff` can tell that they are not really different. 

Doc on full/short form: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html
