### ISSUE TITLE
How do you access COPILOT_QUEUE_URI for a queue-per-topic Worker Service

### ISSUE THREAD

**Issue by gabrieljoelc** [aws/copilot-cli#4787]
I was exploring defining a queue-per-topic like the ["Separate queues" example from the docs](https://aws.github.io/copilot-cli/docs/manifest/worker-service/):
```
# Assign individual queues to each topic.
name: cost-analyzer
type: Worker Service

image:
  build: ./cost-analyzer/Dockerfile

subscribe:
  topics:
    - name: products
      service: orders
      queue:
        retention: 5d
        timeout: 1h
        dead_letter:
          tries: 3
    - name: inventory
      service: warehouse
      queue:
        retention: 1d
        timeout: 5m
count: 1
```

However, it looks like there is only one `COPILOT_QUEUE_URI` that is exposed (according to these [docs](https://aws.github.io/copilot-cli/docs/developing/publish-subscribe/)).

How do you expose the URI's for multiple queues?
