### ISSUE TITLE
Allow Memory Hard Limit setting.

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#4791]
Per the article:

https://aws.amazon.com/blogs/developer/configuring-net-garbage-collection-for-amazon-ecs-and-aws-lambda/

.NET GC sees the underlying hosts' total memory instead of the containers memory which can lead to OOM errors. The article states that you can specify the hard limit of the container which solves the issue, however; I haven't seen an easy to implement mechanism via manifest file. I'm not sure if this is implemented, but I could see it being very useful.

**Comment by bvtujo** [comment]
Hi there! You're right that there's not a native way to do this, but you can do it pretty easily using `copilot svc override --tool yamlpatch`

Then, in `copilot/web/overrides/cfn.patches.yml`, add the following code:

```yaml
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/0/Memory
  value: ${MEMORY_LIMIT}
```

A quick copilot deploy and you're done. You can supply the `--diff` flag to see the changes before you deploy.
