### ISSUE TITLE
Sidecar EnvFileARN causing ValidationError

### ISSUE THREAD

**Issue by benjaminpottier** [aws/copilot-cli#4821]
We just updated copilot cli in our pipeline and it started to throw the following error:

```
ValidationError: Template format error: Parameter name datadog-agentEnvFileARN is non alphanumeric.
```

This is what our sidecar looks like:

```
sidecars:
  datadog-agent:
    image: public.ecr.aws/datadog/agent:latest
    variables:
      ECS_FARGATE: true
      DD_APM_ENABLED: true
    secrets:
      DD_API_KEY: /path/to/secret
```

For now, we've just commented out the sidecar from the manifest in order to get back to deploying. Any idea?
