### ISSUE TITLE
Setting custom domain: prod to xyz.com and test to test.xyz.com

### ISSUE THREAD

**Issue by lominming** [aws/copilot-cli#4822]
I'm having difficulty setting this up for a `Load Balanced Web Service`.
- prod env ----> `xyz.com` and `www.xyz.com`
- test env ----> `test.xyz.com`

I have this setup:
```
http:
  path: '/'
  alias: ['xyz.com', 'www.xyz.com']
```

And I tried to override it in the environment section:
```
environments:
  test:
    http:
      path: '/'
      alias: ['test.xyz.com']
```

Now `xyz.com` does not route anymore, while `test.xyz.com` works. What should I be doing?
