### ISSUE TITLE
copilot svc override - fails to deploy using example

### ISSUE THREAD

**Issue by MJohnson459** [aws/copilot-cli#4828]
I have a working copilot setup with a `test` environment and a service configured. I can deploy the manifest and the service runs.

I now need to change the execution role so that I can use `boto3` from within the service and so I was looking at overrides to configure the role. Using the example from [YAML Patch Overrides](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) verbatim the service now fails to deploy.

cfn.patches.yml:
```yaml
- op: add
  path: /Resources/TaskRole/Properties/Policies/-
  value:
    PolicyDocument:
      PolicyName: DynamoDBReader
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action: 
            - dynamodb:Get*
          Resource: '*'
```

Error:
```
✔ Proposing infrastructure changes for stack sim-admin-test-sim-admin-api
- Updating the infrastructure for stack sim-admin-test-sim-admin-api          [update rollback complete]  [12.5s]
  The following resource(s) failed to update: [TaskRole].
  - An ECS service to run and maintain your tasks in the environment cluster  [not started]
  - An ECS task definition to group your containers and run them on ECS       [not started]
  - An IAM role to control permissions for the containers in your tasks       [update complete]           [0.0s]
    Property PolicyName cannot be empty.
✘ deploy service sim-admin-api to environment test: deploy service: stack sim-admin-test-sim-admin-api did not complete successfully and exited with status UPDATE_ROLLBACK_COMPLETE
```

Am I doing something wrong here or is there a bug in the example?

In addition to the above error, the documentation for the overrides has good links for the patch format but doesn't seem to have a reference for the cloud formation document being patched. Is the document stored locally so that I can reference it for the patches, or is there an online reference?

**Comment by MJohnson459** [comment]
I used `copilot svc package` to view the full cloud formation template and I found the correct format of the patch. I changed it to this and it deploys fine. This is with me using `copilot version: v1.27.0` which I believe is the latest so maybe the documentation just need updated.

```yaml
- op: add
  path: /Resources/TaskRole/Properties/Policies/-
  value:
    PolicyName: DynamoDBReader
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - dynamodb:Get*
          Resource: '*'
```
