### ISSUE TITLE
Ability to config Pipeline to source from ECR repository 

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [aws/copilot-cli#4904]
It would be great if there is a config like below.
```
source:
  # The name of the provider that is used to store the source artifacts.
  provider: ECR
  # Additional properties that further specify the location of the artifacts.
  properties:
    tag: latest
    repository: <erc-repository-url>
```

**Comment by Lou1415926** [comment]
Thanks for the feature request @ShanikaEdiriweera ! Makes a lot of sense to me 👍🏼 I have a few questions if you don't mind 👀 :

1. I guess your service manifests have `image.location: <erc-repository-url>:latest`, instead of `image.build`. Am I guessing right?
2. Are all of your services like that ⬆️ ?
3. For the services that have `image.location: <erc-repository-url>:latest`, is the behavior the same across all environments? i.e. do you have A or B:
```yaml
# A
environments:
  prod:
    image:
      location: <erc-repository-url>:latest
  test:
    image:
      build: Dockerfile # the `test` environment however builds from Dockerfile

# B
environments:
  prod:
    image:
      location: <erc-repository-url>:latest
  test:
    image:
      build:  <erc-repository-url>:latest # Both prod and test is grabbing an existing image.
```
4. Are you currently using `copilot svc deploy --force` to update your service?
5. Finally, if we support a pipeline that gets triggered on ECR push - do you expect the pipeline to be release application code change only? Say, if you have to change an infra config (say the `count` or `cpu` in manifest), you expect to deploy this change through another pipeline dedicated to infra, is this correct?
