### ISSUE TITLE
Pass on environment variables/secrets defined in service manifest to the build environment

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [aws/copilot-cli#4917]
Is it possible to pass on environment variables/secrets defined in service manifest to the build environment (CodeBuild in the pipeline)?

**Comment by Lou1415926** [comment]
Hello @ShanikaEdiriweera ! The env vars and secrets in the service manifest are not applied to the pipeline build stage. However, you can modify the `buildspec.yml` file that Copilot creates in your `copilot/pipelines/<pipelineName>/` dir to include the [`env` section](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env) and define the variables and secrets that you need there!

**Comment by ShanikaEdiriweera** [comment]
Thank you. Figured it out!
Btw is it possible to access Copilot env variables like ${COPILOT_APPLICATION_NAME} from the buildspec/ build env?

**Comment by Lou1415926** [comment]
@ShanikaEdiriweera The `${}` syntax - including the [predefined variables](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/#predefined-variables) `${COPILOT_APPLICATION_NAME}` and `${COPILOT_ENVIRONMENT_NAME}`, and basically any `${MY_ENV_VAR}`  - are strictly for service/environment manifest today and don't work for buildspec. Manifests are consumed by Copilot, which can understand and process `${}` correctly; whereas buildspecs are consumed by CodeBuild, who has no idea how to interpret `${}`.

However, if your manifest has `${COPILOT_APPLICATION_NAME}`, and you are writing `copilot svc package` or `copilot svc deploy` in the buildspec, then when Copilot processes the manifest during the build stage, it will be able to interpreted it correctly. If your manifest has `${MY_ENV_VAR}`, then you should make sure that `MY_ENV_VAR` is a defined env vars in your buildspec. 

##### This doesn't work
```yaml
# buildspec.yml
env:
  copilot_application: ${COPILOT_APPLICATION_NAME}

build:
  commands:
    - echo ${COPILOT_APPLICATION_NAME}
```
This doesn't work; however, since `buildspec.yml` is per pipeline, I guess you would have known in advance which app the buildspec is used for! So this hopefully won't become a problem for you.

##### This is okay
```yaml
# manifest.yml
secrets:
  mysecret: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-secret # Will get interpolated as "myapp-myenv-secret" during build stage, assuming the app name is "myapp", and the env name is "myenv".
```

##### This is also okay
```yaml
# buildspec.yml
env:
  variables:
    MY_ENV_VAR: "value-for-my-env-var"

# manifest.yml
secrets:
  mysecret: ${MY_ENV_VAR}-secret # Will get interpolated as "value-for-my-env-var-secret" during build stage.
```

##### This doesn't work however
```yaml
# buildspec.yml is not defining `MY_ENV_VAR`

# manifest.yml
secrets:
  mysecret: ${MY_ENV_VAR}-secret # Will throw an error "MY_ENV_VAR" not defined during build stagae.
```
