### ISSUE TITLE
Internal load balancer in public subnet

### ISSUE THREAD

**Issue by schm** [aws/copilot-cli#4918]
When trying to deploy a backend service to a public subnet, we're getting the following error message:

> At least two subnets in two different Availability Zones must be specified (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Cod: ValidationError; Request ID: 364bd33a-4c8d-4167-a287-ac3fa1062e93; Proxy: null)

<details>
<summary>Full output</summary>
<pre>
✔ Proposing infrastructure changes for stack tech-staging-back
- Creating the infrastructure for stack tech-staging-back                                                       [rollback complete]         [149.7s]
  The following resource(s) failed to create: [EnvControllerAction]. Rol
  lback requested by user.
  - Service discovery for your services to communicate within the VPC                                           [delete complete]           [3.8s]
  - Update your environment's shared resources                                                                  [update rollback complete]  [82.9s]
    The following resource(s) failed to create: [DefaultInternalHTTPTarget
    Group, InternalWorkloadsHostedZone, InternalLoadBalancer].
    - A security group for your internal load balancer allowing HTTP traffic from within the VPC                [delete complete]           [1.5s]
    - A hosted zone named staging.tech.internal for backends behind a private load balancer                     [delete complete]           [52.9s]
      Resource creation cancelled
    - An internal Application Load Balancer to distribute private traffic from within the VPC to your services  [delete complete]           [0.0s]
      At least two subnets in two different Availability Zones must be speci
      fied (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Cod
      e: ValidationError; Request ID: 364bd33a-4c8d-4167-a287-ac3fa1062e93;
      Proxy: null)
  - An IAM role to update your environment stack                                                                [delete complete]           [3.7s]
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf                                      [delete complete]           [3.3s]
  - An HTTP listener rule for path `/` that forwards HTTP traffic to your tasks                                 [not started]
  - A custom resource assigning priority for HTTP listener rules                                                [not started]
  - Alias for back.staging.tech.internal to the internal load balancer                                          [not started]
  - A CloudWatch log group to hold your service logs                                                            [delete complete]           [3.3s]
  - An IAM Role to describe load balancer rules for assigning a priority                                        [delete complete]           [2.6s]
  - An ECS service to run and maintain your tasks in the environment cluster                                    [not started]
  - A target group to connect the load balancer to your service on port 9292                                    [delete complete]           [15.6s]
  - An ECS task definition to group your containers and run them on ECS                                         [delete complete]           [4.1s]
  - An IAM role to control permissions for the containers in your tasks                                         [delete complete]           [3.3s]
</pre>
</details>

------

We have the following setup:

```yml
# copilot/environments/staging.yml
...
name: staging
type: Environment

network:
  vpc:
    id: vpc-z
    subnets:
      public:
        - id: subnet-a
        - id: subnet-b
        - id: subnet-c
```

```yml
# copilot/front/manifest.yml
name: front
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck: '/check'
```

```yml
# copilot/back/manifest.yml
name: back
type: Backend Service

# ...

http:
  path: '/'
  healthcheck: '/check'

network:
  connect: true
```

I.e. we have an environment which is importing/referencing a previously created vpc with a couple of public subnets (machines being able to access the internet). And I want to have two services, one `front` which is accessible via the external load balancer for the outside world and a second `back` which is in the public subnet, so that it can access external resources, but itself is only accessible via the interal load balancer, so that `front` can use it. Yet all of it is supposed to live in the public subnets so that it may have outbound traffic.

```
┌────────────────────┐
│                    │
│ external load b    │
│                    │
└──┬───────────────┬─┘
   │               │
┌──▼──────────┐    │
│             │    │
│  front      ├────▼─┐
│             │      │
│             │      │
└──┬─┬────────┘      │
   │ │               │
   │ └─────────────┬─┘
   │               │
   │               │
┌──▼───────────────▼─┐
│                    │
│ internal load b    │
│                    │
└───┬──────────────┬─┘
    │              │
┌───▼─────────┐    │
│             │    │
│  back       ├────▼─┐
│             │      │
│             │      │
└────┬────────┘      │
     │               │
     └───────────────┘
```

(I really hope that I don't confuse public and private vs. internal and external here.)

I can deploy the `staging` environment and the `front` service just fine. This also creates an external load balancer. 

But when I try to deploy the `back` service, I'm running into an error posted above.

It would be great if you could give me any pointers on how to resolve this issue.

**Comment by Lou1415926** [comment]
Today Copilot always puts the internal ALB in the private subnets. 

> Yet all of it is supposed to live in the public subnets so that it may have outbound traffic.

It sounds like the one that needs the outbound traffic is your `back` service, not your `internal load b`! If so, I think you should be able to put your internal ALB in private subnets while having your backend service in public subnet so that it can make outbound request.

**Comment by schm** [comment]
@Lou1415926 thanks for looking into this. This is very much appreciated.

Is there a way to let copilot create the additional private subnets? Because right now we don't have any in our infrastructure.

Or alternatively overwrite this default behaviour so that Copilot would put the internal ALB into the public subnet?

**Comment by Lou1415926** [comment]
> Is there a way to let copilot create the additional private subnets? Because right now we don't have any in our infrastructure.

@schm Your environment manifest only has `network.vpc.subnets.public`, and no `network.vpc.subnets.private` right? In this case, it should be possible to import <strike>two</strike> private subnets. You can:

1. Create the private subnets yourselves, outside of Copilot, in the same AZs as your public subnets
2. Import them into Copilot like this:
```yaml
# copilot/environments/staging.yml
name: staging
type: Environment

network:
  vpc:
    id: vpc-z
    subnets:
      public:
        - id: subnet-a
        - id: subnet-b
        - id: subnet-c
      private:
        - id: subnet-d # Same AZ as subnet-a
        - id: subnet-e # Same AZ as subnet-b
        - id: subnet-f # Same AZ as subnet-c
```

> Or alternatively overwrite this default behaviour so that Copilot would put the internal ALB into the public subnet?

You can try [CDK override](https://aws.github.io/copilot-cli/docs/developing/overrides/cdk/) or [YAML patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) to achieve this! I haven't tried it on your use case though, but I _think_ either of them will be able to help. But I think it's worth trying out the first option and put the internal ALB in the private subnet before we do the overrides!

**Comment by schm** [comment]
Thank you so much for your support. I'll try creating them outside of copilot and see how it goes.

**Comment by Lou1415926** [comment]
@schm There is a third option here (thanks @dannyrandall  for pointing that out)! You can create your private subnets, and instead of importing them to `network.vpc.subnets.private`, you can directly use them for your internal load balancer via. [`http.private.subnets`](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-private-subnets).

The difference here is that by importing the private subnets into `network.vpc.subnets.private`, you are basically saying _"the environment consists of a,b,c public subnets, and d,e,f private subnets"_, and this allows the services in the environment to use those private subnets. For example, if you write 
```yaml
name: back

network:
  vpc:
    placement: private
```
then `back` will be placed in the private subnets that you imported into `network.vpc.subnets.private`.

Whereas writing them under `http.private.subnets` is saying _"the environment still just has a,b,c public subnet, but the internal ALB is gonna be placed in d,e,f private subnets"_. The snippet for `back` ⬆️ won't work, because `back` can't find any private subnets in your environment.

**Comment by schm** [comment]
@Lou1415926 @dannyrandall thanks for the idea and the additional input. 

That allowed me to change the environment configuration like this:

```yml
# copilot/environments/staging.yml
...
name: staging
type: Environment

network:
  vpc:
    id: vpc-z
    subnets:
      public:
        - id: subnet-a
        - id: subnet-b
        - id: subnet-c
        
http:
  public:
  private:
    subnets:
      - subnet-a
      - subnet-b
      - subnet-c
```

to convince copilot to place the internal LB in the public subnet. I hope that won't bite me later. 😶
