### ISSUE TITLE
Pin ALB to the environment

### ISSUE THREAD

**Issue by vicpara** [aws/copilot-cli#4944]
Hi,
How can I keep the ALB pinned to the environment across multiple service deployments.
Very often the ALB gets recreated and I have a hard time keeping the DNS records fixed to other service dependencies, outside AWS can utilise the service.
Currently there is one single service attached to the ALB.

Alternatively, how can I attach a public/elastic IP address to the ALB so that at least I can always trust the IP is stable across repeated deployments?

my current env file:

```yml
name: rc
type: Environment

network:
  vpc:
    id: 'vpc-xxxxxxx'
    cidr: '10.0.0.0/16'
    subnets:
      public:
        - id: 'aaaaa-pub0'
          az: 'eu-west-1a'
          cidr: '1xxxx/24'
        - id: 'bbbbbb-pub1'
          az: 'eu-west-1b'
          cidr: '1xxxxx/24'
      private:
        - id: 'cccccc-priv0'
          az: 'eu-west-1a'
          cidr: '1xxxxxx/24'
        - id: 'ddddddd-priv1'
          az: 'eu-west-1b'
          cidr: '1xxxxxx/24'
```
