### ISSUE TITLE
Requesting guidance in troubleshooting missing role permission

### ISSUE THREAD

**Issue by mijolabs** [aws/copilot-cli#4965]
After deployment my service is getting a permission error when the code performs some SQS operations:

> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetQueueAttributes operation: User: arn:aws:sts::[ACCOUNT-ID]:assumed-role/my_app-dev-my_service-TaskRole-156CD4K40PPZT/b757b335a0074434834c664052d5db09 is not authorized to perform: sqs:getqueueattributes on resource: arn:aws:sqs:eu-north-1:[ACCOUNT-ID]:my_queue-dev because no identity-based policy allows the sqs:getqueueattributes action

Lacking access rights to view the organization's AWS policies makes it more difficult for me to troubleshoot, but I have confirmed that the user that was used to perform the deployment does have the `sqs:getqueueattributes` permission. The user has been granted the permission from a group policy.

I assumed that roles created by Copilot during deployment would inherit permissions from that user. Is my understanding of this correct, and if so, is there any possible reason for why the permission appears to not have propagated to the role used by the service?

**Comment by mijolabs** [comment]
I just realized this queue was not created by Copilot. Is it part of Copilot deployment to create queue resources and could this be the reason for the permission errors?

As the code uses a separate publish/subscribe framework (Celery), would it be possible to workaround the issue by specifying in the manifest that Copilot create the queues (different queues per env) in order to set their permissions so that the code can access them?

**Comment by mijolabs** [comment]
So I managed to resolve this with an addon policy:

```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  SQSAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SQSActions
            Effect: Allow
            Action:
              - sqs:*
            Resource: !Sub "arn:aws:sqs:eu-north-1:340856162020:my_queue-${Env}"

Outputs:
  SQSAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref SQSAccessPolicy

```
This got it working, but will need to scope down the allowed actions.

I didn't think this would be required as I haven't run into any permission issues before. As mentioned, I thought permissions would be inherited from the user during deployment.
