### ISSUE TITLE
Modified addon is not deployed on next service deploy

### ISSUE THREAD

**Issue by tjhorner** [aws/copilot-cli#4996]
I am running into an issue where, when an addon is modified, the resulting change is not deployed upon the next `svc deploy`.

As an example, I am attaching a Route53 record set to my service's NLB using an addon, and using `Mappings` to assign a unique domain to each environment:

```yaml
Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  LoadBalancerHostedZoneId:
    Type: String
  LoadBalancerDNSName:
    Type: String

Mappings:
  EnvironmentMap:
    staging:
      Domain: app-staging.example.com
    prod:
      Domain: app.example.com

Resources:
  LoadBalancerDNSAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: MyHostedZoneId
      RecordSets:
        - Name: !FindInMap [EnvironmentMap, !Ref Env, Domain]
          Type: A
          AliasTarget:
            HostedZoneId: !Ref LoadBalancerHostedZoneId
            DNSName: !Ref LoadBalancerDNSName
```

The addon deploys successfully, but if I later change one of the domains to something else and deploy the service with `svc deploy`, the addon does not get updated. The service's CloudFormation stack still points to the old addon template in S3.

I would expect Copilot to pick up on this change (e.g., by storing the hash in the S3 object's metadata or something) or provide an option to forcefully re-upload the addon template and deploy that one instead.
