### ISSUE TITLE
Adding new `path` without `port` doesn't update the LB

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5015]
I added a second path for the same port as follows:
```
    path: 'foo'
    additional_rules:
        path: 'bar'
```

I expected this to update the LB rules to add `bar` and `bar/*` on `copilot svc deploy` but no changes were made. Adding `bar` manually resulted in the desired effect.

**Comment by KollaAdithya** [comment]
Hi @ssyberg !

`http.additinal_rules` is an `Array of Maps` 
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-additional-rules.
can you modify the manifest like below ⬇️ 
```
http:
  path: "foo"
  additional_rules: 
    - path: "bar"
```
This will update the listener rules in CloudFormation template to add `bar` and `bar/*`

**Comment by ssyberg** [comment]
Ahh that makes sense! Is there a way to run a config test on the manifests?

**Comment by KollaAdithya** [comment]
After modifying the manifest. you can run `copilot svc package`. This will display the CloudFormation template that is going to get deployed. 
You can do `copilot svc package --diff` just to show the difference between the existing CloudFormation template and the newly generated template. 
Or you can also use `copilot svc deploy --diff` to show the diff just before deploying the service.

**Comment by ssyberg** [comment]
And will that error if the manifest is malformed?

**Comment by KollaAdithya** [comment]
> After modifying the manifest. you can run copilot svc package. This will display the CloudFormation template that is going to get deployed.
> You can do copilot svc package --diff just to show the difference between the existing CloudFormation template and the newly generated template.
> Or you can also use copilot svc deploy --diff to show the diff just before deploying the service.

All the ⏫ will help you to just see the CloudFormation template that will be deployed.

 we do have manifest validations and error out in some scenarios.

For example:
1. If you specify both `image.location` and `image.build` we do the validation on the manifest that you need to specify either `location` or `build` but not both.
2. If you specify `http.alias` with out creating an app with domain or importing a certificate in your environment then we will error out in this case well.

I mentioned only some of them here. Similar there are lot of validations on the service and environment manifests.

**Comment by ssyberg** [comment]
Thank you! I guess I'm still a little unsure how to directly trigger those errors? Is it only during an actual deploy? Is there anything on par with `terraform validate` or `terraform plan` that will "dry run" your changes just looking for issues?

**Comment by ssyberg** [comment]
Awesome, I was able to get an error running that package command! But now I need help debugging this error:
```
✘ generate workload backend template against environment staging: validate ALB runtime configuration for "http.additional_rule[0]": cannot deploy service backend without "alias" to environment staging with certificate imported
```

I have the paths defined at the top level:
```
# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: backend
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
    # Requests to this path will be forwarded to your service.
    # To match all requests you can use the "/" path.
    path: 'foo'
    additional_rules:
        - path: 'bar'
```

And then I have alias' per environment:

```
environments:
    develop:
        http:
            alias: develop.example.com
    staging:
        http:
            alias: staging.example.com
```

Any ideas?

**Comment by ssyberg** [comment]
I was able to get this working (well it passes validation, deploying now 🤞🏼 ), though feels like a not very DRY setup, appears that "alias" is required under path so I had to duplicate a lot of directives across envs, kinda brittle:

```
environments:
    develop:
        http:
            alias: develop.example.com
            path: 'foo'
            additional_rules:
                - path: 'bar'
                  alias: develop.example.com
    staging:
        http:
            alias: staging.example.com
            path: 'foo'
            additional_rules:
                - path: 'bar'
                  alias: staging.example.com
```

**Comment by ssyberg** [comment]
Hmm this is getting more complex actually, these additional rules also appear to be adding a new healthcheck that is failing

**Comment by ssyberg** [comment]
So yea I would suggest opening this back up as a bug or feature request, this is feeling pretty redundant

```
http:
     path: 'foo'
            additional_rules:
                - path: 'bar'
    healthcheck:
        path: '/foo/healthcheck'
        start_period: 60s
        protocol: http

....

environments:
    develop:
        http:
            alias: develop.example.com
            path: 'foo'
            additional_rules:
                - path: 'bar'
                  alias: develop.example.com
                  healthcheck:
                      path: '/foo/healthcheck'
                      start_period: 60s
                      protocol: http
    staging:
        http:
            alias: staging.example.com
            path: 'foo'
            additional_rules:
                - path: 'bar'
                  alias: staging.example.com
                  healthcheck:
                      path: '/foo/healthcheck'
                      start_period: 60s
                      protocol: http
```

**Comment by KollaAdithya** [comment]
For the same Container port  does it happen to have redundant health checks?
Currently we create a new target group and different health checks for each additional rules. 
But you need target group and its associated health check per container port. Is this the ask/request?

**Comment by ssyberg** [comment]
> But you need target group and its associated health check per container port. Is this the ask/request?

No the opposite I think, the only env specific directive is the alias, everything else should be inherited, but I haven't been able to get that to work. I want it to inherit everything from the top level http, here's what I would prefer:

```
http:
     path: 'foo'
            additional_rules:
                - path: 'bar'
    healthcheck:
        path: '/foo/healthcheck'
        start_period: 60s
        protocol: http

....

environments:
    develop:
        http:
            alias: develop.example.com
    staging:
        http:
            alias: staging.example.com
```

**Comment by KollaAdithya** [comment]
you can simplify the manifest by using `manifest interpolation ` for `Environmentname`.  You can remove the `environments` override section from the manifest.

```
http:
  path: "foo"
  alias: ${COPILOT_ENVIRONMENT_NAME}.example.com
  additional_rules:
    - path: 'bar'
      alias: ${COPILOT_ENVIRONMENT_NAME}.example.com
```
