### ISSUE TITLE
Service is attempting to use the incorrect imported certificate

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5020]
I'm attempting to deploy a service to a new environment and have successfully deployed the env itself, but when I go to deploy the service I'm getting variations on this error:

`✘ generate workload frontend template against environment develop: validate ALB runtime configuration for "http": cannot deploy service frontend without "alias" to environment develop with certificate imported`

Explicitly adding a certificate to the service manifest results in an even weirder error:
`✘ generate workload frontend template against environment develop: validate ALB runtime configuration for "http": validate aliases against the imported public ALB certificate for env develop: staging.example.com is not a valid domain against arn:aws:acm:us-east-1:*******50:certificate/****************04bd631`

As you can see I'm attempting to deploy to the `develop` environment, but it's complaining about the staging alias not being valid on that certificate - which it is not, because that is the `develop` certificate. 

```
enviornments:
    develop:
        http:
            alias: develop.example.com
```

I can't figure out why this is attempting to validate the certificate against the staging alias. I've tried reconfiguring this is a number of ways and nothing gets me passed that first error message. Additionally, this was all working perfectly before I added some `additional_rules` to a _different service_. Is there some sort of race condition here because this service is configured on `/` while the other services are configured on `/foo` and `/bar`?

**Comment by ssyberg** [comment]
In case it's useful

- copilot/environments/develop/manifest.yml
```
# The manifest for the "develop" environment.
# Read the full specification for the "Environment" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/environment/

# Your environment name will be used in naming your resources like VPC, cluster, etc.
name: develop
type: Environment

# Import your own VPC and subnets or configure how they should be created.
# network:
#   vpc:
#     id:

# Configure the load balancers in your environment, once created.
# http:
#   public:
#   private:
http:
    public:
        certificates: [arn:aws:acm:us-east-1:84********0:certificate/eaeb********d631]

# Configure observability for your environment resources.
observability:
    container_insights: false
```

**Comment by KollaAdithya** [comment]
Hey @ssyberg ! 

1. Do you have application with domain i.e did you run `copilot app init --domian example.com` or Did you import your certificate in the env manifest. I assume you imported your certificate in the environment.
2. Did you just import your certificate in only `develop` environment or any other environments
2. Can you also provide sample  service manifest as well.

**Comment by ssyberg** [comment]
So the `staging` application was already up and running with both services, this occurred when I attempted to add a `develop` environment. I successfully added `develop` backend service and hit these errors when I tried to add the `frontend`. I took down all the services and then deployed staging again, now I'm no longer getting errors on the develop `svc package` command so I'm really not sure what happened here... it's deploying now, will report back if I have more issues.

**Comment by ssyberg** [comment]
Very odd, that seems to have worked... seems like there's possibly some sort of race condition here but it's pretty hard to pinpoint.

**Comment by KollaAdithya** [comment]
Glad you had deployed your service. Feel free to reopen if you still face any issues !

**Comment by ssyberg** [comment]
I'll just add I think this still smells strongly of a bug but I guess we'll have to see if it resurfaces!

**Comment by KollaAdithya** [comment]
Hey @ssyberg !

I will reopen this issue!

You can help me to reproduce this issue. Can you answer these questions ⬇️ 
1. So you have three environments and then in each you imported three different certificates or the same certificate for all the environments.
2. Can you also provide your complete service manifest that will be really helpful

**Comment by KollaAdithya** [comment]
This will be an Enhancement request for us.

**Current Scenario**
Currently we validate on `addiitional_rules` if the alias is not specified and the certificate is imported in the environment with the below configuration ⬇️ 
```
http:
  alias: myalias.com
  path: '/'
  additional_rules:
     - path: '/admin'
```
This will error out `validate ALB runtime configuration for "http.additional_rule[0]": cannot deploy service fastapi without "alias" to environment test with certificate imported`

**Enhancement**

For each `additional_rule`:
1. If it has alias field, use its own alias
2. Otherwise, use `http.alias`  as its alias
