### ISSUE TITLE
Copilot Pipeline Build Steps?

### ISSUE THREAD

**Issue by jplock** [aws/copilot-cli#5022]
When generating a pipeline, the code examples have the build step as `copilot env deploy`. Shouldn't this instead be some form of `copilot svc deploy --env XXX` so that the code gets rebuilt but not deployed?

**Comment by KollaAdithya** [comment]
Hey @jplock  👋 
Where exactly do you see `copilot env deploy` in pipeline build steps. Can you paste a screenshot or point me to that examples.

**Comment by jplock** [comment]
This is what the stock `buildspec.yml` looks like after @waasi generated it using `copilot pipeline init`:

```yaml
# Buildspec runs in the build stage of your environment pipeline to generate the environment CloudFormation stack config.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary. You can update this version.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.27.0
      - mv ./copilot-linux-v1.27.0 ./copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - echo "Run your tests"
      - copilot env deploy --name staging    ### this doesn't build the container or push to ECR
      # - make test
  post_build:
    commands:
      - ls -l
      - export COLOR="false"
      - export CI="true"
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/staging-api/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
      - stages=$(echo $pipeline | jq -r '.stages[].name')
      # Generate the cloudformation templates.
      - >
        for env in $stages; do
          ./copilot-linux env package -n $env --output-dir './infrastructure' --upload-assets --force;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
        done;
      - ls -lah ./infrastructure
artifacts:
  files:
    - "infrastructure/*"
```

We're wondering what we should replace `copilot env deploy --name staging` with in the build steps so the latest source code is packaged into the container and pushed to ECR. Thank you for the help!
