### ISSUE TITLE
Static Site service should contain a "predeploy" command

### ISSUE THREAD

**Issue by yannickvr** [aws/copilot-cli#5026]
Many static site generators (i'm using Hugo atm) have a command to generate the static site content that the Copilot Static Site Service will upload to S3. Even though in CI we could easily run e.g. `hugo -d ../destinationdir` before running `copilot deploy`, my local workflow would really like a `preDeployCommand` that copilot runs before attempting to upload the source artifacts.

E.g.

```
name: static-site
type: Static Site
files:
  - source: public
    recursive: true
    preDeployCommand: hugo --cleanDestinationDir
```
