### ISSUE TITLE
How to use storage secret fields (host, password, ...) as environment variables?

### ISSUE THREAD

**Issue by ammerzon** [aws/copilot-cli#5041]
### Context

I am trying to deploy [Dagster](https://github.com/dagster-io/dagster/tree/1.3.13/examples/deploy_ecs) using AWS Copilot. The Dagster container expects the following environment variables to be set to connect to the Postgres database.

```yaml
DAGSTER_POSTGRES_DB: "mydb"
DAGSTER_POSTGRES_HOSTNAME: "host"
DAGSTER_POSTGRES_PASSWORD: "password"
DAGSTER_POSTGRES_PORT: "5432"
DAGSTER_POSTGRES_USER: "user"
```

### Current Approach

I added an Aurora cluster using the `storage` command.

```sh
copilot storage init -t Aurora
```

This creates the following addon in the environments folder.

<details>
  <summary>dagster-cluster.yml</summary>

  ```yaml
  Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.
  # Customize your Aurora Serverless cluster by setting the default value of the following parameters.
  dagsterclusterDBName:
    Type: String
    Description: The name of the initial database to be created in the Aurora Serverless v2 cluster.
    Default: dagster_db
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  VPCID:
    Type: String
    Description: The ID of the VPC in which to create the Aurora Serverless v2 cluster.
    Default: ""
  PrivateSubnets:
    Type: String
    Description: The IDs of the private subnets in which to create the Aurora Serverless v2 cluster.
    Default: ""

Mappings:
  dagsterclusterEnvScalingConfigurationMap: 
    prod:
      "DBMinCapacity": 0.5 # AllowedValues: from 0.5 through 128
      "DBMaxCapacity": 8   # AllowedValues: from 0.5 through 128
    
    All:
      "DBMinCapacity": 0.5 # AllowedValues: from 0.5 through 128
      "DBMaxCapacity": 8   # AllowedValues: from 0.5 through 128

Resources:
  dagsterclusterDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of private subnets for Aurora Serverless v2 cluster.
      SubnetIds:
        !Split [',', !Ref PrivateSubnets]
  
  dagsterclusterWorkloadSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for one or more workloads to access the Aurora Serverless v2 cluster dagstercluster'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'The Security Group to access Aurora Serverless v2 cluster dagstercluster.'
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-Aurora'

  dagsterclusterDBClusterSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your Aurora Serverless v2 cluster dagstercluster'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the Aurora Serverless v2 cluster.
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-Aurora'
  
  dagsterclusterDBClusterSecurityGroupIngressFromWorkload:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from one or more workloads in the environment.
      GroupId: !Ref dagsterclusterDBClusterSecurityGroup
      IpProtocol: tcp
      ToPort: 5432
      FromPort: 5432
      SourceSecurityGroupId: !Ref dagsterclusterWorkloadSecurityGroup
  
  dagsterclusterAuroraSecret:
    Metadata:
      'aws:copilot:description': 'A Secrets Manager secret to store your DB credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  dagsterclusterDBClusterParameterGroup:
    Metadata:
      'aws:copilot:description': 'A DB parameter group for engine configuration values'
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: 'aurora-postgresql14'
      Parameters:
        client_encoding: 'UTF8'
  
  dagsterclusterDBCluster:
    Metadata:
      'aws:copilot:description': 'The dagstercluster Aurora Serverless v2 database cluster'
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref dagsterclusterAuroraSecret, ":SecretString:username}}" ]]
      MasterUserPassword:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref dagsterclusterAuroraSecret, ":SecretString:password}}" ]]
      DatabaseName: !Ref dagsterclusterDBName
      Engine: 'aurora-postgresql'
      EngineVersion: '14.6'
      DBClusterParameterGroupName: !Ref dagsterclusterDBClusterParameterGroup
      DBSubnetGroupName: !Ref dagsterclusterDBSubnetGroup
      Port: 5432
      VpcSecurityGroupIds:
        - !Ref dagsterclusterDBClusterSecurityGroup
      ServerlessV2ScalingConfiguration:
        # Replace "All" below with "!Ref Env" to set different autoscaling limits per environment.
        MinCapacity: !FindInMap [dagsterclusterEnvScalingConfigurationMap, All, DBMinCapacity]
        MaxCapacity: !FindInMap [dagsterclusterEnvScalingConfigurationMap, All, DBMaxCapacity]
  
  dagsterclusterDBWriterInstance:
    Metadata:
      'aws:copilot:description': 'The dagstercluster Aurora Serverless v2 writer instance'
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBClusterIdentifier: !Ref dagsterclusterDBCluster
      DBInstanceClass: db.serverless
      Engine: 'aurora-postgresql'
      PromotionTier: 1
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region

  dagsterclusterSecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref dagsterclusterAuroraSecret
      TargetId: !Ref dagsterclusterDBCluster
      TargetType: AWS::RDS::DBCluster

Outputs:
  dagsterclusterSecret: # injected as DAGSTERCLUSTER_SECRET environment variable by Copilot
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterAuroraSecret
  dagsterclusterSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref dagsterclusterWorkloadSecurityGroup  
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterSecurityGroup
  ```
</details>

### Problem

As I understand from @huanjani reply (https://github.com/aws/copilot-cli/issues/4176#issuecomment-1317525605), Copilot automatically injects the `dagsterclusterSecret` as a `DAGSTERCLUSTER_SECRET` environment variable. Unfortunately, I can't parse this secret in the application code. 

I also tried using secrets, but this doesn't work either. Is there a way how I can pass the fields of `dagsterclusterSecret`, like `dbname`, `host`, `password`, etc., directly to the environment variables? 

```yaml
secrets:
  DAGSTER_POSTGRES_DB:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret:dbname::"
  DAGSTER_POSTGRES_HOSTNAME:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret:host::"
  DAGSTER_POSTGRES_PASSWORD:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret:password::"
  DAGSTER_POSTGRES_PORT:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret:port::"
  DAGSTER_POSTGRES_USER:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret:username::"
```

**Comment by Lou1415926** [comment]
@ammerzon From the template you shared, I see you are creating an environment-level Aurora cluster - the cluster is updated/deleted only when you run `env deploy/delete`. Is this what you are looking for?

The "auto injection" that @huanjani mentioned worked for service-level addon perfectly, but environment-level addon is different. Can you try adding the following to your service manifest:
```yaml
network:
  vpc:
    security_groups:
       - from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterSecurityGroup
secrets:
  DAGSTER_POSTGRES_SECRET:
    from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret"
```

**Comment by ammerzon** [comment]
Yes @Lou1415926, an environment-level Aurora cluster is what I want to achieve, and also the service manifest you shared works 😁

> @ammerzon From the template you shared, I see you are creating an environment-level Aurora cluster - the cluster is updated/deleted only when you run `env deploy/delete`. Is this what you are looking for?
> 
> The "auto injection" that @huanjani mentioned worked for service-level addon perfectly, but environment-level addon is different. Can you try adding the following to your service manifest:
> 
> ```yaml
> network:
>   vpc:
>     security_groups:
>        - from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterSecurityGroup
> secrets:
>   DAGSTER_POSTGRES_SECRET:
>     from_cfn: "${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterAuroraSecret"
> ```

The challenge is that I need, for instance, the hostname (`DAGSTER_POSTGRES_HOSTNAME`) or the password (`DAGSTER_POSTGRES_PASSWORD`) directly. As far as I am concerned, the `DAGSTERCLUSTER_SECRET` would contain a JSON object with different fields, right?

**Comment by Lou1415926** [comment]
@ammerzon I see! I think you can achieve this by:
1. Update your addon template to include the following outputs:
```yaml
Outputs:
  dagsterclusterDBName:
    Description: "The name of the initial database"
    Value: !Sub
      - "${Secret}:dbname::"
      - Secret: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterDBName
  dagsterclusterPort:
    Description: "The port of the cluster"
    Value: !Sub
      - "${Secret}:port::"
      - Secret: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterPort
 dagsterclusterHost:
    Description: "The host name of the cluster"
    Value: !Sub
      - "${Secret}:host::"
      - Secret: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterHost
  dagsterclusterUsername:
    Description: "The username to log into the cluster"
    Value: !Sub
      - "${Secret}:username::"
      - Secret: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterUser
  dagsterclusterPassword:
    Description: "The password to log into the cluster"
    Value: !Sub
      - "${Secret}:password::"
      - Secret: !Ref dagsterclusterAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dagsterclusterPassword
```
Then modify your service manifest:
```yaml
# This part stays the same
network:
  vpc:
    security_groups:
       - from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterSecurityGroup 

# Here are the changes
secrets:
  DAGSTER_POSTGRES_DB:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterDBName
  DAGSTER_POSTGRES_USER:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterUser
  DAGSTER_POSTGRES_HOSTNAME:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterHost
  DAGSTER_POSTGRES_PASSWORD:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterPassword
  DAGSTER_POSTGRES_PORT:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterPort
```

Related: https://github.com/aws/copilot-cli/issues/4625
