### ISSUE TITLE
iam:PassRole needed by Copilot service

### ISSUE THREAD

**Issue by mijolabs** [aws/copilot-cli#5054]
I have a service deployed by Copilot and some of its tasks involve work with EC2 e.g. bidding for EC2 spot instances. This operation requires Copilot's TaskRole to have the `iam:PassRole` permission. I tried creating an addon policy for it but it gets overridden by Copilot's `DenyIAMExceptTaggedRoles` inline policy that is automatically generated. This of course results in a permission error in our application.

It is basically the same problem described in [this issue](https://github.com/aws/copilot-cli/issues/1507). The author managed to solve it with a workaround which involves step functions, but that solution is not appropriate for our use case.

Are there any other known ways of circumventing this issue? We just want to add `iam:PassRole` to the Copilot instance's TaskRole.

**Comment by dannyrandall** [comment]
Hey @mijolabs! Great question. Would either of the workarounds mentioned in this issue https://github.com/aws/copilot-cli/issues/4751#issuecomment-1503750699 work for you?

**Comment by mijolabs** [comment]
Thanks @dannyrandall, this is excellent and exactly what I was looking for. I hadn't been able to find these methods in the docs.

The YAML patch override method would be most convenient, but then I'd need to overwrite the explicit DENY of `iam:*`. Adding `iam:PassRole` would still be denied by that explicit deny rule.

So I tried the assume-role method with addons instead, using the [example that was shared](https://github.com/aws/copilot-cli/issues/4751#issuecomment-1506573614) later in that thread. But I ran into circular dependency issues:
```
✘ Proposing infrastructure changes for stack myapp-dev-worker
✘ deploy service worker to environment dev: deploy service: check if changeset is empty: create change set copilot-92816b17-61c8-4a79-b1eb-9784af930397 for stack myapp-dev-worker: ValidationError: Circular dependency between resources: [TaskDefinition, AddonsStack, Service, TaskRole]
	status code: 400, request id: 8a5289c6-ebd6-4655-9090-239839a50963: describe change set copilot-92816b17-61c8-4a79-b1eb-9784af930397 for stack myapp-dev-worker: ValidationError: Stack [myapp-dev-worker] does not exist
```
These are my yamls:
```yaml
# addons.parameters.yml

Parameters:
  TaskRoleArn: !GetAtt TaskRole.Arn
```

```yaml
# iam-passrole.yml

Parameters:
  App:
    Type: String
    Description: The application's name.
  Env:
    Type: String
    Description: The environment name the service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  TaskRoleArn:
    Type: String
    Description: The ARN of the Task Role for the ECS service.

Resources:
  awsAccessRole:
    Metadata:
      "aws:copilot:description": "An IAM role to manage IAM groups"
    Type: AWS::IAM::Role
    Properties:
      RoleName: "example-aws-access"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref TaskRoleArn
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "iam"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource:
                  - "*"
      Tags:
        - Key: "iam:ResourceTag/copilot-application"
          Value: !Ref App
        - Key: "iam:ResourceTag/copilot-environment"
          Value: !Ref Env
Outputs:
  awsAssumeRoleArn:
    Description: "The IAM::Role to assume"
    Value: !Sub ${ awsAccessRole.Arn }

```
I'm puzzled why that would fail for me if it worked for the author. Any ideas?

**Comment by dannyrandall** [comment]
@mijolabs I'm not quite following the issue with YAML Patch? 🤔 In the example, the `op: replace` on the patch _replaces_ the IAM Policy Statement that contains the `iam:*` `Deny` with an `Allow` for the actions you want. For example, with this patch:
```
- op: replace
  path: /Resources/TaskRole/Properties/Policies/0/PolicyDocument/Statement/0
  value:
    Effect: Allow
    Action:
      - iam:PassRole
    Resource:
      - "*"
```
I got the following diff:
```
# copilot svc deploy --diff
~ Resources/TaskRole/Properties/Policies:
    ~ - (changed item)
      ~ PolicyDocument/Statement:
          ~ - (changed item)
            - Action: 'iam:*'
            + Action:
            +     - iam:PassRole
            ~ Effect: 'Deny' -> Allow
            - Resource: '*'
            + Resource:
            +     - "*"
          (1 unchanged item)
    (1 unchanged item)
```
effectively removing the explicit IAM deny and replacing it with an Allow for `iam:PassRole`.

---
As for the circular dependency issue using addons, I'm not sure why you're running into that issue when the original author didn't 🤔 I just deployed the same addons stack that you shared and didn't have the circular dependency issue either. Is this a _new_ service that you're deploying for the first time? Or are you updating an existing service?
