### ISSUE TITLE
How to attach policy from addon to an entity?

### ISSUE THREAD

**Issue by ammerzon** [aws/copilot-cli#5082]
## Context

I am trying to deploy [Dagster](https://github.com/dagster-io/dagster/tree/1.3.13/examples/deploy_ecs) using AWS Copilot. One of the services needs additional permissions to run. Therefore I created an addon in `copilot/environments/addons` like the following one:

<details>
  <summary>daemon-iam.yml</summary>

  ```yaml
  Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

  Resources:
    DagsterDaemonIAMPolicy:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "ec2:DescribeNetworkInterfaces"
                - "ecs:DescribeTaskDefinition"
                - "ecs:DescribeTasks"
                - "ecs:ListAccountSettings"
                - "ecs:RegisterTaskDefinition"
                - "ecs:RunTask"
                - "ecs:StopTask"
                - "ecs:TagResource"
                - "secretsmanager:DescribeSecret"
                - "secretsmanager:ListSecrets"
                - "secretsmanager:GetSecretValue"
              Resource:
                - "*"
            - Effect: "Allow"
              Action:
                - "iam:PassRole"
              Resource:
                - "*"
              Condition:
                StringLike:
                  iam:PassedToService: "ecs-tasks.amazonaws.com"

  Outputs:
  DagsterDaemonIAMPolicy:
    Description: "The ARN of the ManagedPolicy needed by the Dagster daemon to submit runs from schedules and sensors"
    Value: !Ref DagsterDaemonIAMPolicy
  ```
</details>

## Problem

I now want to attach this policy to the Copilot service called `daemon`. Is there an easy way to achieve that?

```yaml
name: daemon
type: Backend Service

image:
  build: src/data/Dockerfile.daemon

secrets:
  DAGSTER_POSTGRES_DB:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterDBName
  DAGSTER_POSTGRES_USER:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterUser
  DAGSTER_POSTGRES_HOSTNAME:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterHost
  DAGSTER_POSTGRES_PASSWORD:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterPassword
  DAGSTER_POSTGRES_PORT:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-dagsterclusterPort
```

**Comment by dannyrandall** [comment]
Hey @ammerzon! Copilot will automatically add managed policies to the ECS Task Role that are output from an Addon, like you're doing above (https://aws.github.io/copilot-cli/docs/developing/addons/workload/#writing-the-outputs-section).

However, Copilot _also_ creates a policy `DenyIAMExceptTaggedRoles` that blocks `iam:*`, other than `sts:AssumeRole` only roles tagged correctly.

To get around this, you can use YAML Patch overrides as discussed in https://github.com/aws/copilot-cli/issues/4751 and https://github.com/aws/copilot-cli/issues/5054. Feel free to follow up if you have any questions!

**Comment by ammerzon** [comment]
Hi @dannyrandall! Thank you for your answer. I tried the YAML Patch override approach by adding the following file to `copilot/daemon/overrides`.

```yaml
- op: replace
  path: /Resources/TaskRole/Properties/Policies/0/PolicyDocument/Statement/0
  value:
    Effect: Allow
    Action:
      - iam:PassRole
    Resource:
      - "*"
    Condition:
      StringLike:
        iam:PassedToService: "ecs-tasks.amazonaws.com"
```

Unfortunately, I am now receiving the following error:

- `ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm`
- `is not authorized to perform: ssm:GetParameters on resource`

I am also asking myself whether I can limit my managed policy to only apply to a specific service.
