### ISSUE TITLE
The correct way to create an EFS that can be mounted into a Copilot Environment as external dependency

### ISSUE THREAD

**Issue by vicpara** [aws/copilot-cli#5085]
I have a database service that needs persistent storage. 
I manually created an EFS as AWS account root, configured an AccessPoint and imported it in the service manifest file like below. (Or a different script that runs outside the copilot)
The service fails to start because it cannot mount the volume. 

When I define the requirement directly in the db's manifest file the EFS gets created automatically. 
My problem is that I don't want the copilot to manage the creation/deletion of the EFS directly based on code changes/pipelines or whimsy triggers. I create it and make it available to the services as a given dependency. It would be a disaster that the CloudFormation stack gets corrupted/cannot rollback some updates and I have to delete the FS in production.

What are the correct params + settings + permissions to use when creating an EFS that can be mounted and utilised by copilot services as externally managed file system?

```yaml
environments:
  rc:
    storage:
      volumes:
        dbData:
          path: /db-data
          read_only: false
          efs: true
          # This is how i tried to import the EFS, I created manually
          # efs:
          #   id: fs-0264cxxxx
          #   auth:
          #     access_point_id: fsap-0caxxxx

```

**Comment by dannyrandall** [comment]
Hey @vicpara! What errors did you run in to trying to import your manually created EFS volume? Did you follow this guide https://aws.github.io/copilot-cli/docs/developing/storage/#external-efs to importing a manually-created EFS volume?

**Comment by vicpara** [comment]
1. I created the FS using the web console and made sure it's created in the right region with the correct security group.
2. Create an access point. The POSIX users and groups were left blank (they were optional anyways). I have no idea how to populate them other than copying what the auto mountable drive has.
3. Populate the manifest and deploy the service.

`ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32`

**Comment by iamhopaul123** [comment]
Hello @vicpara.

> ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32

It's probably because the subnets you place externally created EFS volumes in are not the same as where ECS tasks are running in. Can you help me double check with that?

**Comment by vicpara** [comment]
## Private subnets
I created the EFS in private subnets of the environment's VPC.
The service manifest was set to:
```yaml
...
network:
  connect: true
  vpc:
    placement: 'private'
environments:
  rc:
    storage:
      volumes:
        dbData:
          path: /db-data
          read_only: false
          efs:
            id: fs-091xxx
            auth:
              access_point_id: fsap-096xxx
...
```
The error it produced was:
`    Task stopped at: 19/07/2023, 7:57:17 UTC
ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Failed to resolve "fs-0663525221ff8dc74.efs.eu-west-1.amazonaws.com" - check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. Attempting to lookup mount target ip address using botocore. Failed to import necessary dependency botocore, please install botocore first. : unsuccessful EFS utils command execution; code: 1`


## Public subnets
I placed the EFS in the public subnets in the VPC that corresponds to the environment. The service manifest was:
```yaml
...
network:
  connect: true

environments:
  rc:
    storage:
      volumes:
        dbData:
          path: /db-data
          read_only: false
          efs:
            id: fs-06exxx
            auth:
              access_point_id: fsap-012xxx
...
```
The error it produced was:
`Task stopped at: 19/07/2023, 11:17:27 UTC
ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Mount attempt 1/3 failed due to timeout after 15 sec, wait 0 sec before next attempt. Mount attempt 2/3 failed due to timeout after 15 sec, wait 0 sec before next attempt. b'mount.nfs4: mount system call failed' : unsuccessful EFS utils command execution; code: 32`
