### ISSUE TITLE
service & sidecar image/image.location is confusing

### ISSUE THREAD

**Issue by lgarvey** [aws/copilot-cli#5108]
According to the documentation, to point a main service to a docker registry we use `image.location` whilst sidecars expect just `image`. 

This difference in syntax is slightly confusing, but it's made worse because if you incorrectly use `image.location` in the sidecar config, it then tries to build a Dockerfile in the root of the project.

I questioned my sanity for awhile until I went back to look at the docs. 

It would be helpful if the configuration keys are consistent, and/or if sidecars fail with a loud error if missing both `image` and `image.build` instead of defaulting to looking for a Dockerfile in the root of the repo.

**Comment by bvtujo** [comment]
Hey @lgarvey, thanks for bringing this up. This *should* work whether you specify any of the following:
```yaml
image: nginx:stable
image:
  build: ./sidecar/Dockerfile
image:
  location: nginx:stable
```

At first, you had to manage your sidecar images yourself outside of copilot. That's why we allowed the short `image: repo` syntax. Later, we added the ability to have copilot build images for you, hence adding the full build config. But you're saying that you're specifying
```yaml
sidecars:
  mySidecar:
    image:
      location: nginx:stable
```
and Copilot is trying to build the image for you?

**Comment by lgarvey** [comment]
HI @bvtujo 

Hmm, that seems to work for me.  Unfortunately I don't have the original broken config to look at but I have a feeling I was actually trying to set: `image.location`, which maybe just isn't supported, e.g 

```
sidecars:
  envoy:
    image.location: ...
```

This results in copilot trying to build `{root}/Dockerfile`

However, this syntax works correctly:

```
sidecars:
  envoy:
    image:
        location: ...
```

Cheers,
L
