### ISSUE TITLE
Create an internal Network load balancer with AWS Copilot

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [aws/copilot-cli#5131]
I am trying to deploy `bitnami/openldap` container in ECS using AWS Copilot as a backend service with a internal NLB (Couldn't go with ALB since `bitnami/openldap` does not have a http healthcheck endpoint).

I have the following config in Copilot service manifest.

```
name: ldap2023
type: Backend Service

nlb:
  port: 1389/tcp
  healthcheck:
    healthy_threshold: 3
    unhealthy_threshold: 10
    grace_period: 120s
    interval: 15s
    timeout: 10s

network:
  vpc:
    placement: private
```

But when I deploy the service a NLB is not created. R53 dns record is directly pointing to the ECS task ip.

Is it not possible to use NLB with backend service? 

Can't find it in [docs][1] but it is not mentioned that it is [not possible as well][2]. For [Load balanced web service][3] it has examples for both ALB and NLB!

  [1]: https://aws.github.io/copilot-cli/docs/manifest/backend-service/
  [2]: https://aws.github.io/copilot-cli/docs/developing/internal-albs/
  [3]: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

**Comment by ghost** [comment]
@ShanikaEdiriweera I think you should use a Load Balanced Service, not a Backend Service with an nlb config:

```yaml
# copilot/<service>/manifest.yml
name: <service name>
type: Load Balanced Web Service
nlb:
  port: 80/tcp
```

Unfortunately, this will create a public NLB, AFAIK there is no official way to set it to internal.

Having said that, as a workaround you can create a [YAML patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) to fix this:

```yaml
# copilot/<service>/overrides/cfn.patches.yml
# Change the NLB to internal
- op: replace
  path: /Resources/PublicNetworkLoadBalancer/Properties/Scheme
  value: internal
# Add a Name to the NLB (otherwise the automatically generated name will contain 'public', which is confusing)
- op: add
  path: /Resources/PublicNetworkLoadBalancer/Properties/Name
  value: !Sub "${AppName}-${EnvName}-${WorkloadName}-NLB"
```
