### ISSUE TITLE
During service deployment: "more than one ECS service with tags"

### ISSUE THREAD

**Issue by mijolabs** [aws/copilot-cli#5144]
Lately I have been getting this output after deploying a particular service:

```bash
✘ deploy service myservice to environment dev: get the last updated deployment time for myservice: more than one ECS service with tags "copilot-application"="myapp","copilot-environment"="dev","copilot-service"="myservice"
```

The service appears to deploy fine at times, and sometimes it does not.

I'm curious to what this message means. Could this be due to a previous failed deployment? I have tried deleting the entire app and recreating everything again, but the message still appears. There is also a different service within this application that deploys successfully and does not show this message.

Here's the service manifest:
```yaml
name: myservice
type: Backend Service

image:
  build:
    dockerfile: services/myservice/Dockerfile
    context: services/

cpu: 1024
memory: 2048
platform: linux/x86_64
exec: true

network:
  vpc:
    placement: private

count: 1
```

Any ideas?
