### ISSUE TITLE
cannot unmarshal !!seq into string after upgrading to 1.29.0

### ISSUE THREAD

**Issue by NiclasLindqvist** [aws/copilot-cli#5155]
Hello! After upgrading copilot-cli 1.29.0 I'm getting an error message when deploying some services, here's a minimalistic manifest that works in versions `v1.28.0`

```
name: my-demo-service
type: Backend Service

image:
  location: bash:latest
  command: ["tail", "-f", "/dev/null"]
  labels:
    "my-label": |
      ["label-as-sequence"] # this is the issue part

cpu: 256
memory: 512
count: 1
exec: true
```
Deploying in `v1.28.0` works without problems, but in `v1.29.0` and above I get
```
copilot svc deploy
✘ unmarshal service my-demo-service manifest: unmarshal manifest for Backend Service: yaml: unmarshal errors:
  line 7: cannot unmarshal !!seq into string
```

I think the issue was possibly introduced in #4899 

I suppose it's a corner case, but we've been deploying images with labels to push prometheus metrics to datadog like this, is there another syntax I should be useing?:
```
[truncated for brevity]
  labels:
    "com.datadoghq.ad.check_names": |
      ["openmetrics"]
    "com.datadoghq.ad.init_configs": |
      [{}]
    "com.datadoghq.ad.instances": |
      [
        {
          "prometheus_url": "http://%%host%%:80/_/metrics",
          "namespace": "xyz",
          "metrics": ["*"],
          "send_distribution_buckets": true,
          "collect_counters_with_distributions": true,
          "collect_histogram_buckets": true
        }
      ]
```

Thanks in advance for any guidance or input!

**Comment by KollaAdithya** [comment]
Hello @NiclasLindqvist !
Thanks for reporting the bug! I can reproduce the issue. 
I think this is happening only in case of  having  a `pipe`  before `array of strings`.
As a workaround can you modify the manifest to have something like below
```yaml
labels:
    "com.datadoghq.ad.check_names": "openmetrics"
    "com.datadoghq.ad.init_configs": |
      [{}]
    "com.datadoghq.ad.instances": |
      [
        {
          "prometheus_url": "http://%%host%%:80/_/metrics",
          "namespace": "xyz",
          "metrics": ["*"],
          "send_distribution_buckets": true,
          "collect_counters_with_distributions": true,
          "collect_histogram_buckets": true
        }
      ]
 ```

**Comment by KollaAdithya** [comment]
Hello  @NiclasLindqvist 👋 

I just created a PR #5157. This will resolve the unmarshal error if you are using a `pipe`(`|`) with `array of strings`.

**Comment by NiclasLindqvist** [comment]
Thanks @KollaAdithya for looking into this!
I saw your PR, looks like a neat patch! I didn’t realize the pipe could be a factor, I thought I saw a similar error without it.. YAML isn’t my strong suit so I take your word for it!

Looking forward to a future release with your patch applied!

**Comment by KollaAdithya** [comment]
@NiclasLindqvist 

can you provide the manifest config that is giving an error with out `pipe`.

**Comment by dannyrandall** [comment]
Hey @NiclasLindqvist! We just released this fix [v1.30.0](https://github.com/aws/copilot-cli/releases/tag/v1.30.0)!🚀🎉 Thanks for reporting the issue!

**Comment by richardgavel-ordinaryexperts** [comment]
I think as a result of this change, something that is considered valid YAML by several different validators doesn't work anymore. This is a snippet.
 
Error: ✘ unmarshal service api manifest: unmarshal manifest for Load Balanced Web Service: unmarshal "variables": cannot unmarshal field to a string or into a map

```
environments:
  dev:
    http:
      healthcheck:
        timeout: 10s

    variables:
      STAFF_EMAILS: '["me@gmail.com"]'
```

**Comment by tmichalski** [comment]
I'm using v1.34 and I'm getting a similar error:

```
✘ unmarshal service my-app manifest: unmarshal manifest for Static Site: yaml: unmarshal errors:
  line 20: cannot unmarshal !!seq into string
```

and the manifest.yml is: 

```
name: my-app
type: Static Site

http:
  path: '/'

files:
  - source: apps/my-app/dist/
    recursive: true

environments:
  develop:
    http:
      alias: develop.not-a-real-domain-so-dont-try.com
  production:
    http:
      alias:
        - name: not-a-real-domain-so-dont-try.com
        - name: www.not-a-real-domain-so-dont-try.com
```

Line 20 is at `  production:`

When I remove `environments`, the script is processed correctly, or when I just remove "production" config it's fine. Appears that a Static Site cannot handle multiple aliases.

**Comment by cchen-ownit** [comment]
1.34 and also experiencing similar errors

```
✘ unmarshal service neo4j-db manifest: unmarshal manifest for Load Balanced Web Service: yaml: unmarshal errors:
  line 28: cannot unmarshal !!seq into map[string]manifest.Variable
```

My case, it is failing on `path`

```
storage:
  volumes:
    appDataVolume:
      efs: true
      path: /var/efs/app
      read_only: false
```
