### ISSUE TITLE
`copilot svc deploy` fails to retrieve secrets

### ISSUE THREAD

**Issue by gabelton** [aws/copilot-cli#5171]
I'm using 1.29.1. When I run `copilot svc deploy` it fails. I then run `copilot svc status --name web --env dev` and see:

```
 ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret {arn} from secrets manager: RequestCanceled: request context canceled caused by: context deadline exceeded. Please check your task network configuration.  
```

I can see that the arn in the error message does not match what I see in the aws console. The one in the error message ends `/copilot/fft/dev/secrets/POSTGRES` whereas the one in the console ends`/copilot/fft/dev/secrets/POSTGRES-1a2bc3` . I can see that the secret is tagged with the correct application and environment, so I would expect the deploy command to be able to find the secret from this and don't see where this other arn is coming from. My web service manifest looks like:

```
secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
  DATABASE_CREDENTIALS: 
    secretsmanager: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/POSTGRES
```

Any ideas where I'm going wrong here?

**Comment by huanjani** [comment]
Hi @gabelton!

Some quick questions:
1. How did you create the secret? SecretsManager console or `copilot secret init` or `copilot storage init`?
2. Which AWS console is showing your secret with the `-1a2bc3`? SecretsManager?

**Comment by gabelton** [comment]
Thanks for getting back to me @huanjani . 

1. Created the secret as part of the postgres addon template

```
postgresAuroraSecret:
    Metadata:
      'aws:copilot:description': 'A Secrets Manager secret to store your DB credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/copilot/${App}/${Env}/secrets/POSTGRES'
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
```

2. Yep, the SecretsManager console
