### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by daniyal4747** [aws/copilot-cli#5178]
OS: MacBook Pro 2020 M1

aws svc deploy gives error to pull base image from local machine, it is working fine on windows machine.

Manifest.yml
```

name: common
type: Backend Service
image:
  build:
    dockerfile: server/services/common/Dockerfile
    context: /
  # Port exposed through your container to route traffic to it.
  port: 8804

cpu: 256 # Number of CPU units for the task.
memory: 512 # Amount of memory in MiB used by the task.
platform: linux/x86_64 # See https://aws.github.io/copilot-cli/docs/manifest/backend-service/#platform
count: 1 # Number of tasks that should be running in your service.
exec: true # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.


```
Dockerfile
```
ROM grs-npm-dependencies

# define micro-service name
ARG micro_service=common

WORKDIR /usr/src/app

# Add service code
ADD ./server/services/$micro_service/ ./server/services/$micro_service
```

Error:
```
#3 [internal] load metadata for docker.io/library/grs-npm-dependencies:latest
     #3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
     
upload deploy resources for service common: build and push the image "common": build Dockerfile at /Users/daniyal.ahmad/projects/case-tracker/case-tracker/server/services/common/Dockerfile: building image: exit status 1
```
