### ISSUE TITLE
`copilot deploy` or `copilot svc deploy` ignores docker context attribute

### ISSUE THREAD

**Issue by emmanuelbuah** [aws/copilot-cli#5187]
Manifest looks like 

```
name: api
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  path: '/'
  healthcheck: '/graphql'

# Configuration for your containers and service.
image:
  build: ./deployment/docker/propa-platform-api.docker
  context: ./deployment/modules
  # Port exposed through your container to route traffic to it.
  port: 4000
```

But running `copilot deploye --name api --env beta` yields this output 

```sh
Building your container image "api": docker build -t 691244137259.dkr.ecr.us-east-2.amazonaws.com/propa-platform-api/api:latest --label com.aws.copilot.image.builder=copilot-cli --label com.aws.copilot.image.container.name=api --label com.aws.copilot.image.version=v1.29.1 /Users/masked/Projects/masked/foundation/deployment/docker -f /Users/masked/Projects/masked/foundation/deployment/docker/propa-platform-api.docker
```

Where the docker context path is `/Users/masked/Projects/masked/foundation/deployment/docker` instead of `/Users/masked/Projects/masked/foundation/deployment/modules`.

It looks like copilot is completely ignoring the context attribute and assuming the build context is the folder the dockerfile is in.

Using copilot version v1.29.1

**Comment by huanjani** [comment]
Hi, @emmanuelbuah!

`context` is a subfield of `image.build` (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build) so try indenting it two spaces.

```
image:
  build:
    dockerfile: ./deployment/docker/propa-platform-api.docker
    context: ./deployment/modules
  port: 4000
```

Let us know if that doesn't work!
