### ISSUE TITLE
How to use global defined secrets and variables when using sidecar.

### ISSUE THREAD

**Issue by interu** [aws/copilot-cli#5203]
I'm define as follows in copiot/service-name/manifest.yml

```
environments:
  production:
    variables:
      RAILS_ENV: production
    sidecars:
      job:
        variables:
          RAILS_ENV: production
  staging:
    variables:
      RAILS_ENV: staging
    sidecars:
      job:
        variables:
          RAILS_ENV: staging
variables:
  TZ: Asia/Tokyo
  XXXX: hoge
  YYYY:fuga
  ZZZZ:piyo
secrets:
  RDS_HOST:
    secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_HOST::'
  RDS_USERNAME:
    secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_USERNAME::'

sidecars:
  job:
    variables:
      TZ: Asia/Tokyo
      XXXX: hoge
      YYYY:fuga
      ZZZZ:piyo
    secrets:
      RDS_HOST:
        secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_HOST::'
      RDS_USERNAME:
        secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_USERNAME::'

```

The more environment variables handled by variables and secrets, the more duplicate definitions become cumbersome to manage and more prone to miss.

Is it possible to reflect global definitions of secrets and variables under sidecar definitions while avoiding duplicate definitions?

**Comment by interu** [comment]
Solved.
I used the following yaml functionality.

```
variables: &variables
  TZ: Asia/Tokyo
  XXXX: hoge
  YYYY:fuga
  ZZZZ:piyo
secrets: &secrets
  RDS_HOST:
    secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_HOST::'
  RDS_USERNAME:
    secretsmanager: 'copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/service-name:RDS_USERNAME::'
sidecars:
  job:
    variables:
      *variables
    secrets:
      *secrets
```
