### ISSUE TITLE
support `secrets_file` in the manifest

### ISSUE THREAD

**Issue by KollaAdithya** [aws/copilot-cli#5205]
conversation from gitter
https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$iWOLIz9DdgbThFO8oe4-x26Tk1IwT1rHxxoUxwAz9_c

**Current Scenario**

Say I have two services `serviceA` and `serviceB`

```
.
├── copilot                        (application directory)
│   ├── .workspace                 (workspace summary)
│   ├── serviceA
│   │   └── manifest.yml           (serviceA manifest)
│   ├── serviceB
│   │   └── manifest.yml           (serviceB manifest)

```

In order to specify secrets for `serviceA` and `serviceB`. 
In `ServiceA manifest`

```
secrets:
  GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
  DB:
    secretsmanager: 'demo/test/mysql'
  DB_PASSWORD:
    secretsmanager: 'demo/test/mysql:password::'
 
sidecars:
  nginx:
      GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
      DB:
        secretsmanager: 'demo/test/mysql'
      DB_PASSWORD:
        secretsmanager: 'demo/test/mysql:password::'
  nginx2:
      GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
      DB:
        secretsmanager: 'demo/test/mysql'
      DB_PASSWORD:
        secretsmanager: 'demo/test/mysql:password::'   
 ```
    
In `ServiceB manifest`
```
secrets:
  GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
  DB:
    secretsmanager: 'demo/test/mysql'
  DB_PASSWORD:
    secretsmanager: 'demo/test/mysql:password::'
 
sidecars:
  nginx:
      GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
      DB:
        secretsmanager: 'demo/test/mysql'
      DB_PASSWORD:
        secretsmanager: 'demo/test/mysql:password::'
  nginx2:
      GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
      DB:
        secretsmanager: 'demo/test/mysql'
      DB_PASSWORD:
        secretsmanager: 'demo/test/mysql:password::'   
 ```
 
 By looking at the manifest files, This feels redundant to specify same secrets across multiple services.
 
 **ASK**

Instead we can have specify `secrets_file`  in the manifests across services where `secrets_file` is path to a file from the root of your workspace. (This is similar to [`env_file`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#env_file) in the manifest)
```
.
├── copilot                        (application directory)
│   ├── .workspace                 (workspace summary)
│   ├── serviceA
│   │   └── manifest.yml           (serviceA manifest)
│   ├── serviceB
│   │   └── manifest.yml           (serviceB manifest)
│   ├── secretsdir
│   │   └── secrets.yml

```
Where `secrets.yml` contains all the secrets.
```
GITHUB_WEBHOOK_SECRET: GH_WEBHOOK_SECRET
DB:
  secretsmanager: 'demo/test/mysql'
DB_PASSWORD:
  secretsmanager: 'demo/test/mysql:password::'   
  ```
Copilot should be able to parse this `secrets.yml` file.

In manifest for serviceA will have

```
secrets_file: ./secretsdir/secrets.yml
```

In manifest for serviceB wil have
```
secrets_file: ./secretsdir/secrets.yml
```
