### ISSUE TITLE
Cannot update nodejs runtime version in buildspec.yml for code pipeline?

### ISSUE THREAD

**Issue by lominming** [aws/copilot-cli#5222]
I've a codepipeline setup: code from github >>> test env >>> run tests >>> prod env.
I also have tests to run which depends on the host nodejs version.

I am trying to change the nodejs version in `buildspec.yml`:
![image](https://github.com/aws/copilot-cli/assets/742933/dc0a4b15-ff58-4a52-b6f6-ddb5da9a2fce)

But it throws this error:
![image](https://github.com/aws/copilot-cli/assets/742933/935b627c-c38d-46ec-9296-52d526e67cdb)

My tests commands are in `pipelines/.../manifest.yml`:
![image](https://github.com/aws/copilot-cli/assets/742933/ac1b2508-d8c3-48d5-961a-ecfe7d41b833)

Question 1: How can I update the nodejs version for my build pipeline?

Question 2: Can I just install a higher version of nodejs runtime at the test_commands section? Like `apk add...`

**Comment by iamhopaul123** [comment]
Hello @lominming. It seems like for `aws/codebuild/amazonlinux2-x86_64-standard:4.0` which Copilot sets by default, only [nodejs 16 is supported](https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/4.0/runtimes.yml). You can get this around by installing a higher level version. For example:

```yaml
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
```

**Comment by lominming** [comment]
@iamhopaul123 Do I add it at line 10 in the `buildspec.yml`?

Doesn't seem to work. It somehow complained that it needs Docker 20 when I add the line. I will double check again, just making sure where I should put `n 18`.

![image](https://github.com/aws/copilot-cli/assets/742933/bf8f91ab-2ed6-4eca-91e9-c12f323a2336)

**Comment by iamhopaul123** [comment]
Here's my full example
```yaml
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 16
    commands:
      - n 18
      - echo "node -v" 
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.29.1 -O copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - echo "Run your tests"
      # - make test
```

**Comment by lominming** [comment]
@iamhopaul123 It doesn't appear to work. I added it in the commands like you have with `n 18`.
It still shows the `nodejs 16`

![image](https://github.com/aws/copilot-cli/assets/742933/3a0da9de-a9fa-46ca-bd59-1bbb3125e9c6)

Steps I took:
1. edit `copilot/pipelines/<pipeline-name>/buildspec.yml` to add `n 18`
2. `copilot pipeline deploy`
3. push code to github to trigger change
4. print `node -v` in my test commands (in `copilot/pipelines/<pipeline-name>/manifest.yml`
5. `node -v` still shows `nodejs v16`

**Comment by iamhopaul123** [comment]
Hello @lominming. Can you post your buildspec here? I use the buildspec below and in the log it shows node 18

```yaml
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 16
    commands:
      - n 18
      - node -v 
```

**Comment by lominming** [comment]
1. I copied the front part of your `buildspec.yml`
2. Then `copilot pipeline deploy`
3. push code to github to trigger change

```
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 16
    commands:
      - n 18
      - echo "node -v" 
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.29.1 -O copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - echo "Run your tests"
      # - make test
  post_build:
    commands:
      - ls -l
      - export COLOR="false"
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/xyzxyz/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
      - pl_envs=$(echo $pipeline | jq -r '.stages[].name')
      # Find all the local services in the workspace.
      - svc_ls_result=$(./copilot-linux svc ls --local --json)
      - svc_list=$(echo $svc_ls_result | jq '.services')
      - >
        if [ ! "$svc_list" = null ]; then
          svcs=$(echo $svc_ls_result | jq -r '.services[].name');
        fi
      # Find all the local jobs in the workspace.
      - job_ls_result=$(./copilot-linux job ls --local --json)
      - job_list=$(echo $job_ls_result | jq '.jobs')
      - >
        if [ ! "$job_list" = null ]; then
          jobs=$(echo $job_ls_result | jq -r '.jobs[].name');
        fi
      # Raise error if no services or jobs are found.
      - >
        if [ "$svc_list" = null ] && [ "$job_list" = null ]; then
          echo "No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote." 1>&2;
          exit 1;
        fi
      # Generate the cloudformation templates.
      # The tag is the build ID but we replaced the colon ':' with a dash '-'.
      # We truncate the tag (from the front) to 128 characters, the limit for Docker tags
      # (https://docs.docker.com/engine/reference/commandline/tag/)
      # Check if the `svc package` commanded exited with a non-zero status. If so, echo error msg and exit.
      - >
        for env in $pl_envs; do
          tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)
          for svc in $svcs; do
          ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
          for job in $jobs; do
          ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
        done;
      - ls -lah ./infrastructure
artifacts:
  files:
    - "infrastructure/*"
```

**Comment by iamhopaul123** [comment]
That's very interesting. This is what I got:
```
[Container] 2023/08/25 18:14:49 Running command n 18
--
27 | installing : node-v18.17.1
28 | mkdir : /usr/local/n/versions/node/18.17.1
29 | fetch : https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz
30 | copying : node/18.17.1
31 | node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
32 | node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```
<strike>Can you update your local Copilot version to the latest `v1.29.1` and run `copilot pipeline deploy` to update the pipeline?</strike>

**Comment by iamhopaul123** [comment]
Hello @lominming. So sorry about the confusion. Actually mine didn't work either because apparently according to https://github.com/aws/aws-codebuild-docker-images/issues/580, `aws/codebuild/amazonlinux2-x86_64-standard:4.0` can't work as well.

I am able to work it around by using [`build.image`](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#build-image) to use `aws/codebuild/amazonlinux2-x86_64-standard:5.0` in the manifest and you will be able to specify

```yaml
phases:
  install:
    runtime-versions:
      nodejs: 18
```
