### ISSUE TITLE
addons Parameter values specified for a template which does not require them

### ISSUE THREAD

**Issue by rmarops** [aws/copilot-cli#5229]
wanting to use addons to create and assign cloudwatch permissions to the taskrole as per example at the very end of this doc https://aws.github.io/copilot-cli/docs/developing/sidecars/

I created a file @ devops-prototyping/nginx/copilot/nginx/addons
```
Resources:
  FireLensPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:DescribeLogStreams
          - logs:PutLogEvents
          Resource: '*'
Outputs:
  FireLensPolicyArn:
    Description: An addon ManagedPolicy gets used by the ECS task role
    Value: !Ref FireLensPolicy
```

on deploy i get the following
```
$ copilot deploy
Only found one workload, defaulting to: nginx
Only found one environment, defaulting to: qa
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  13.82kB
Step 1/1 : FROM nginx:latest
 ---> 6efc10a0510f
Successfully built 6efc10a0510f
Successfully tagged *.dkr.ecr.us-east-1.amazonaws.com/devops-prototyping/nginx:latest
WARNING! Your password will be stored unencrypted in /home/rlm/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Using default tag: latest
The push refers to repository [*.dkr.ecr.us-east-1.amazonaws.com/devops-prototyping/nginx]
9d907f11dc74: Layer already exists 
79974a1a12aa: Layer already exists 
f12d4345b7f3: Layer already exists 
935b5bd454e1: Layer already exists 
fb6d57d46ad5: Layer already exists 
ed7b0ef3bf5b: Layer already exists 
latest: digest: sha256:f2fee5c7194cbbfb9d2711fa5de094c797a42a51aa42b0c8ee8ca31547c872b1 size: 1570
✘ Proposing infrastructure changes for stack devops-prototyping-qa-nginx
✘ execute svc deploy: deploy service nginx to environment qa: deploy service: wait for creation of change set copilot-b661e55a-c29e-4d68-856e-007245e1be4a for stack devops-prototyping-qa-nginx: ResourceNotReady: failed waiting for successful resource state: Parameter values specified for a template which does not require them.
```

I am skimming through https://aws.github.io/copilot-cli/docs/developing/addons/workload/ but not catching what I am missing.
