### ISSUE TITLE
Step Scaling

### ISSUE THREAD

**Issue by dannyrandall** [aws/copilot-cli#5241]
Making a dedicated issue for step scaling autoscaling, described in https://github.com/aws/copilot-cli/issues/1154 originally, as there has been recent interest in the feature. From @kohidave:

[Step scaling](https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-step-scaling-policies.html) allows you to scale up based on the magnitude of an alarm breach. You provide an alarm, and based on predefined ranges of how how far the alarm metric has been breached, determines how many tasks to increase. You can run a scale-in version which does the opposite. It’s kind of confusing to explain, but let me give you an example. 

Assume we have an alarm for service throttling exceptions. It triggers when the average number of throttles for our service is over 50/min. We could have a step scaling policy like:

|Throttle Range	|Number of tasks to increase	|
|---	|---	|
|50 - 60 throttles/min	|1	|
|60-100 throttles/min	|5	|
|100-1000 throttles/min	|10	|

Just for completeness, we’ll say our cooldown period (the time between scaling actions) is 60 seconds. 

In this example, as long as the alarm metric is between 50-60mins, we’ll keep spinning up 1 task per 60 seconds (the cooldown period). If the metric goes up even more, like all of our requests are getting throttled, then we might want to provision tasks faster (so maybe 10 tasks per cooldown period). 

You can do this with a negative version as well, for scaling in.

### Manifest Design
In general, we’ll assume that step scaling is more of an advanced feature so we’ll include less convenience methods around it. The real question here is about the alarm - where do customers generate it? They can add them via addons, but if the metric needs to reference the service at all, that won’t work. We’ll assume the alarm already exists in this example, but until we can figure out where/how to generate these alarms, we can’t effectively support step-scaling. 

```yaml
name: frontend
type: Load Balanced Web Service
image:
  build: ./Dockerfile
  port: 80
http:
  path: '/'
cpu: 256
memory: 512
count:
  range:1-100
  step-scaling:
    -
      alarm:alarm/OUTPUT_ALARM
      # By default the scale down is the opposite of steps
      #  unless disable-scale-in is set. 
      steps:
        -
          at:70
          adjust:5
        -
          at:90
          adjust:10
      scale-in-cooldown: 600
      scale-out-cooldown 1000
      disable-scale-in: true
```

**Comment by icruwrks** [comment]
Currently, we have the idea of using YAML Patch Overrides to achieve the following.

If you have any opinions on how to set this up, please let me know.

cfn.patches.yml

```YAML
- op: add
  path: /Resources/AutoScalingRole
  value:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'

- op: add
  path: /Resources/AutoScalingTarget
  value:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 100
      ResourceId:
        Fn::Join:
          - '/'
          - - 'service'
            - Fn::ImportValue: !Sub '${AppName}-${EnvName}-ClusterId'
            - !GetAtt Service.Name
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !GetAtt AutoScalingRole.Arn

- op: add
  path: /Resources/StepScalingInPolicy
  value:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Join ['-', [!Ref AppName, !Ref EnvName, ECSServiceAverageCPUUtilization, StepScalingInScalingPolicy]]
      PolicyType: 'StepScaling'
      ScalingTargetId: !Ref AutoScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: "ChangeInCapacity"
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -5
        Cooldown: 600
        MetricAggregationType: "Average"

- op: add
  path: /Resources/ServiceLowCPUAlarm
  value:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: !Join ['-', [!Ref AppName, !Ref EnvName, StepScaling, ServiceLowCPUAlarm]]
      MetricName: "CPUUtilization"
      Namespace: "AWS/ECS"
      Statistic: "Average"
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Threshold: 30
      ComparisonOperator: "LessThanThreshold"
      Dimensions:
        - Name: "ClusterName"
          Value:
            Fn::ImportValue: !Sub '${AppName}-${EnvName}-ClusterId'
        - Name: "ServiceName"
          Value: !GetAtt Service.Name
      AlarmActions:
        - !GetAtt StepScalingInPolicy.Arn

- op: add
  path: /Resources/StepScalingOutPolicy
  value:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Join ['-', [!Ref AppName, !Ref EnvName, ECSServiceAverageCPUUtilization, StepScalingOutPolicy]]
      PolicyType: 'StepScaling'
      ScalingTargetId: !Ref AutoScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: "ChangeInCapacity"
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 5
        Cooldown: 1000
        MetricAggregationType: "Average"

- op: add
  path: /Resources/ServiceHighCPUAlarm
  value:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: !Join ['-', [!Ref AppName, !Ref EnvName, StepScaling, ServiceHighCPUAlarm]]
      MetricName: "CPUUtilization"
      Namespace: "AWS/ECS"
      Statistic: "Average"
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: "ClusterName"
          Value: 
            Fn::ImportValue: !Sub '${AppName}-${EnvName}-ClusterId'
        - Name: "ServiceName"
          Value: !GetAtt Service.Name
      AlarmActions:
        - !GetAtt StepScalingOutPolicy.Arn
```

**Comment by alquerci** [comment]
Hello there,

This patch is a nice base for step scaling configuration.

For me, the main difference with target tracking is the latency of the alarm.

With custom patch.
```yaml
      Statistic: "Average"
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
```

Target tracking alarm have this and it cannot be changed.
```yaml
      Statistic: "Average"
      Period: 60
      DatapointsToAlarm: 3
      EvaluationPeriods: 3
```

With target tracking, the time to respond on pic is at least 5 minutes, it is very long.
The alarm trigger at the fourth minute.
And to start a new task is can take at least one minute or two.
Meanwhile, the app is down.

If that latency can be configurable on target tracking, then step scaling will be obsolete.
