### ISSUE TITLE
Defining ALB access by environment / ALB access service overrides

### ISSUE THREAD

**Issue by fgodino-milu** [aws/copilot-cli#5279]
Hi folks. I have a question regarding internal and external load balancers.

Is it possible to deploy a service that will be exposed to the interned through a public ALB in one environment and restricted to the public through an internal ALB for other environment?

We have an `alpha` environment whose services we would like to keep only accessible from within the VPC.

I'd appreciate any guidance. Thank you.

**Comment by iamhopaul123** [comment]
Hello @fgodino-milu. Just wanted to make sure I understand the question correctly: you have one service and you want to reuse the service to both public ALB and internal ALB for different purpose, instead of two identical services for these two ALBs respectively. Is the summary correct?

**Comment by fgodino-milu** [comment]
Hi @iamhopaul123, thanks for your help. I have a service(S1) that I want to deploy behind an internal ALB for the `alpha` environment, and behind a public ALB for `production` environment

**Comment by iamhopaul123** [comment]
Got it. I think right now we don't provide a native solution to create an internal load balancer for a Load Balanced Web Service. However, there are two workaround I can think of

1. Use env override to set the ALB in the `alpha` environment as internal
```yaml
# In copilot/environments/overrides/cfn.patches.yml
- op: add
  path: /Transform
  value: AWS::LanguageExtensions

- op: add
  path: /Mappings
  value:
    ALBScheme:
      alpha:
        Scheme: internal

- op: add
  path: /Resources/PublicLoadBalancer/Properties/Scheme
  value: !FindInMap 
    - ALBScheme
    - !Ref EnvironmentName
    - Scheme
    - DefaultValue: internet-facing
```
2. Create two identical services with one Load Balanced Web Service and the other one to be a Backend Service. So for the LBWS one you can use public ALB easily, whereas for the Backend Service one, you can set [`http`](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#http) to define an internal ALB.

Sorry for the inconvenience and let me know if you have more questions!

**Comment by fgodino-milu** [comment]
Thank you!, I think the first option will work just fine. I'll close the issue, feel free to reopen.

**Comment by Lou1415926** [comment]
Hi @fgodino-milu ! I know you've closed the issue, but the team has thought of another _potential_ option for you. You can try to use the [`allowed_source_ips`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-allowed-source-ips), and then use the [`environments`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-allowed-source-ips) section to write different `allowed_source_ips` per-environment for the service.
```yaml
http:
  allowed_source_ips: 0.0.0.0/0

environments:
  alpha:
     http:
        allowed_source_ips: <cidr of the subnets of the environment VPC>
```

Frankly, I am not entirely sure if the internet-facing ALB will be able to recognize the CIDR blocks of the public subnets. If it is not able to do so, this probably won't work for you... I just want to throw this out there, in case you want more creativity on this!
