### ISSUE TITLE
unmarshal "variables": cannot unmarshal field to a string or into a map

### ISSUE THREAD

**Issue by dickensdjj** [aws/copilot-cli#5288]
## Context
Repo: BitBucket
Secrets: AWS Secret Manager
CICD Pipeline: BitBucket Pipeline
Local: MacOS
Local Copilot Version(copilot-darwin): 1.28.0
Bitbucket Runner: atlassian/default-image (Ubuntu 22.0.4)
Runner Copilot Version(copilot-linux): 1.30.1

I am deploying a Load Balanced Web Service to the ECS cluster with Fargate via AWS copilot CLI. I am NOT using the AWS Copilot Pipeline as my CICD Pipeline because I would like to manage it via BitBucket.

## Issue
The BitBucket pipeline cannot deploy the svc due to the error shown below
Error: _unmarshal service xxx manifest: unmarshal manifest for Load Balanced Web Service: unmarshal "variables": cannot unmarshal field to a string or into a map_

This is my manifest.yml
```name: xxx
type: Load Balanced Web Service

# ALB configuration
http:
  path: '/'
  healthcheck:
    path: '/cicd_healthcheck'
    success_codes: '200'
    healthy_threshold: 3
    unhealthy_threshold: 2
    grace_period: 120s

image:
  build: app/Dockerfile
  port: 80

cpu: 2048
memory: 4096
exec: true
count: 1
deployment:
  rolling: 'default'
network:
  connect: true

variables:
  GC_EMAIL_SUBJECT: "xxx"
  GC_EMAIL_FROM_NAME: "xxx"
  GC_EMAIL_FROM_EMAIL: "xxx"

  ALERT_EMAIL_FROM_NAME: "xxx"
  ALERT_EMAIL_FROM_EMAIL: "xxx"
  PORT: "xxx"
```
This is my bitbucket.yml
```
image: atlassian/default-image:latest
options:
  docker: true

pipelines:
  branches:
    develop:
      - step:
          name: project image build, publish and deploy
          deployment: Staging
          size: 4x
          runs-on:
            - self.hosted
            - linux
          script:
            - echo "🚀🚀🚀Deploying to Staging ECS Cluster..."
            - curl -Lo aws-copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
            - chmod +x aws-copilot
            - ./aws-copilot -v
            - ./aws-copilot svc deploy --app xxx --env staging --name xxx
```

## Reference:
1. bitbucket pipeline failed
<img width="1003" alt="Screenshot 2023-09-07 at 2 17 51 pm" src="https://github.com/aws/copilot-cli/assets/8329895/ab16d488-bb46-4aa1-aae4-81ac5c77fc44">
