### ISSUE TITLE
Pipeline init for an environment deploy.  Generates a buildspec.yml with the wrong version of Ruby.  Copilot version: v1.30.1, built for darwin

### ISSUE THREAD

**Issue by gj02ib65** [aws/copilot-cli#5290]
I found today that creating a new pipeline for the environment creates the buildspec.yml file with ruby specified as 2.6. 
```
# Buildspec runs in the build stage of your environment pipeline to generate the environment CloudFormation stack config.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
...
```
I then see the following error in the logs.

```
[Container] 2023/09/07 21:22:59 YAML location is /codebuild/output/src3889428917/src/copilot/pipelines/env-prod/buildspec.yml
[Container] 2023/09/07 21:22:59 Setting HTTP client timeout to higher timeout for S3 source
[Container] 2023/09/07 21:22:59 Processing environment variables
[Container] 2023/09/07 21:22:59 Selecting 'ruby' runtime version '2.6' based on manual selections...
[Container] 2023/09/07 21:22:59 Phase complete: DOWNLOAD_SOURCE State: FAILED
[Container] 2023/09/07 21:22:59 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '2.6' of ruby. This build image has the following versions: 3.1
```
An easy workaround is to edit the buildspec.yml file and change the ruby version of 3.1.

**Comment by iamhopaul123** [comment]
Hello @gj02ib65. Did you specify the `image` field in your manifest to use a different codebuild image? seems like `ruby: 2.6` is not available since `amazonlinux2-x86_64-standard:4.0`

**Comment by gj02ib65** [comment]
I did not specify an `image` field.  Following is my manifest in full for my prod environment...

```
# The manifest for the "prod" environment.
# Read the full specification for the "Environment" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/environment/

# Your environment name will be used in naming your resources like VPC, cluster, etc.
name: prod
type: Environment

# Import your own VPC and subnets or configure how they should be created.
network:
  vpc:
    id: vpc-0586cfc02xxxxxx75
    subnets:
      public:
        - id: subnet-0fe8b5236xxxxxxec
        - id: subnet-0c1397466xxxxxx4e
      private:
        - id: subnet-0dc49209bxxxxx0b
        - id: subnet-0311ba64exxxxxx73

# Configure the load balancers in your environment, once created.
http:
  public:
    access_logs: true 
    ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
#   private:

# Configure observability for your environment resources.
observability:
  container_insights: true
```
