### ISSUE TITLE
copilot scheduled job unable call get_role

### ISSUE THREAD

**Issue by rickychew77** [aws/copilot-cli#5291]
After running my scheduled job in `copilot job deploy`, i am getting error below and i have even tried adding `iam:GetRole` to the execution role but getting same issue. What am i missing? 
```
Couldn't call 'get_role' to get Role ARN from role name <role_name> to get Role path.

**Comment by iamhopaul123** [comment]
Hello @rickychew77. Did you get this error from progress tracker when making the real deployment? Or it happens right after running the `job deploy` command?

**Comment by rickychew77** [comment]
It happens after 'copilot job deploy' is finished in my terminal. The error logs above are from ECS tasks cloudwatch.

**Comment by iamhopaul123** [comment]
I see. If it is from the task logs you probably need to add `iam:GetRole` to the task role instead of execution role (also just curious how did you add the permission to the execution role?). You can add permissions to the task role by using [addons](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#writing-the-outputs-section).

**Comment by rickychew77** [comment]
hi @iamhopaul123 , i have tried adding to task role using copilot addon, basically having another `addons` folder in the same directory and inside having a separate yml containing `iam:GetRole`. For execution role, i added manually on console in the meantime purely for troubleshooting.

On separate note, I notice in AWS console state machine, one of the execution shows errors logs here.
```
ECS was unable to assume the role <task_role_arn> that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role. 
```

Even i have granted the trust policy on task role still giving this error. will also continue to find out more.

**Comment by Lou1415926** [comment]
Hi @rickychew77 ! 

> ECS was unable to assume the role <task_role_arn> that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role. 

The ⬆️  error certainly seems unexpected to me - in the template that Copilot deploys for your job, the task role should already have allowed the ECS service to assume it, you shouldn't have had to grant the trust policy on your own:
```yaml
TaskRole:
  Metadata:
    'aws:copilot:description': 'An IAM role to control permissions for the containers in your tasks'
  Type: AWS::IAM::Role
  Properties:
    ManagedPolicyArns:
      - Fn::GetAtt: [iamAddons, Outputs.myIAMAddons]
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com # <- This should allow ECS to assume the task role.
          Action: 'sts:AssumeRole'
```

Is this error should showing up now? If so, can you please run `copilot job package` and let me know the following:
1. Under `Resources/TaskRole/Properties/AssumeRolePolicyDocument`, does it have the "ecs-tasks.amazonaws.com" that I mentioned above?
2. Under `Resources/TaskDefinition/Properties/TaskRoleArn`, does it have `!GetAtt TaskRole.Arn`?
3. Under `Resources/TaskDefinition/Properties/ExecutionRoleArn`, does it have `!GetAtt ExecutionRole.Arn`
4. Finally, do you have any yaml patch/cdk override?

> i have tried adding to task role using copilot addon

Is the `iam:GetRole` created as an [IAM::ManagedPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html) and added to the [Outputs](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#workload-addons-connecting-to-your-workloads)?

**Comment by rickychew77** [comment]
```
Is this error should showing up now? If so, can you please run copilot job package and let me know the following:

1. Under Resources/TaskRole/Properties/AssumeRolePolicyDocument, does it have the "ecs-tasks.amazonaws.com" that I mentioned above?
2. Under Resources/TaskDefinition/Properties/TaskRoleArn, does it have !GetAtt TaskRole.Arn?
3. Under Resources/TaskDefinition/Properties/ExecutionRoleArn, does it have !GetAtt ExecutionRole.Arn
```

Yup 1 to 3 i have it. 

For 4, I didn't do any overriding.

```
Is the iam:GetRole created as an IAM::ManagedPolicy and added to the Outputs?
```
Yup it was done like this but no added outputs

```
Resources:
  ECSTaskRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow ECS to invoke Lambda
      ManagedPolicyName: !Sub iam-policy-${Name}-${App}-${Env}-taskrole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - "<some_s3_arn>"
          - Sid: IAMGetRole
            Effect: Allow
            Action:
              - iam:GetRole
            Resource:
              - "<some_iam_role_arn>"

```

**Comment by rickychew77** [comment]
hi there, i think for this issue i figured out. 
the `iam:GetRole` action were blocked by `DenyIAMExceptTaggedRoles` with statement below explicitly denying all iam actions
```
       {
            "Action": "iam:*",
            "Resource": "*",
            "Effect": "Deny"
        }
``` 

This seems to be created by default, is it by design that it disallow task to perform iam related action?

**Comment by iamhopaul123** [comment]
Hello @rickychew77. 

> Yup it was done like this but no added outputs

I think in order to make it work (Copilot attaching the managed policy to the task role defined in the addons stack, see [here](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#writing-the-outputs-section)), you would need to output the arn of the managed policy you defined in the addons.

> the iam:GetRole action were blocked by DenyIAMExceptTaggedRoles with statement below explicitly denying all iam actions

Very good finding! `iam:GetRole` will be blocked even if you add the policy to the output. I wonder why you would need to perform `iam:GetRole` in the container. Is it possible for you to do `sts:AssumeRole` instead of directly using the task role to perform any `iam` action (note that the iam role to be assumed has to be tagged with `copilot-application` and `copilot-environment`)?

However, if you have to use `iam:GetRole`, after outputting the Arn of the managedPolicy, you can also run `copilot job override --tool yamlpatch` and use the following patch file to get rid of this explicit Deny logic in the task role.

```yaml
- op: replace
  path: /Resources/TaskRole/Properties/Policies/0/PolicyDocument/Statement/0/Effect
  value: 'Allow'
```
