### ISSUE TITLE
"ECS Deployment Circuit Breaker was triggered'." seemingly not possible to deploy again

### ISSUE THREAD

**Issue by hderms** [aws/copilot-cli#5296]
deploying like this:
```
copilot svc deploy --name upc-ner -e test
```

environments/app were created with the defaults
```yaml
name: test
type: Environment

# Import your own VPC and subnets or configure how they should be created.
# network:
#   vpc:
#     id:

# Configure the load balancers in your environment, once created.
# http:
#   public:
#   private:

# Configure observability for your environment resources.
observability:
  container_insights: false

```
svc I am deploying:
```yaml
deployment:
  rolling: 'default'

# storage:
  # readonly_fs: true       # Limit to read-only access to mounted root filesystems.
 
# Optional fields for more advanced use-cases.
#
variables:                    # Pass environment variables as key value pairs.
  LOG_LEVEL: info
  PG_USER: postgres
  PG_PASS: redacted
  PG_PORT: 5432

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
environments:
  production:
    count: 1
    variables:
      PG_HOST: redacted
  test:
    count: 1
    deployment:            # The deployment strategy for the "test" environment.
      rolling: 'default' # Stops existing tasks before new ones are started for faster deployments.
    variables:
      PG_HOST: redacted
````

Deploying a broken image that won't start causes the ECS deployment circuit breaker to trigger, and makes deploying again with a fixed image seemingly impossible.

Using the `--force` cli flag doesn't cause it to force the deploy, though I wasn't under the impression that would actually "force" it in the way I'd want, after reading some github issues.

"Cancel update stack" on the resulting cloudformation "stack" doesn't seem to have any effect, at least in the short term (15 minutes or so).

I don't want to turn the circuit breaker off, because I'd like to make it as difficult as possible to deploy broken code that won't stabilize. Similarly, I saw a workaround to turn the replicas down to 0 before deploying again, which is supposed to allow you to bypass the circuit breaker. This didn't seem to work to allow me to deploy, and I'd like to avoid it if at all possible because I don't want a failed deploy to cause an outage.

I'm trying to figure out if I'm doing something wrong because based on my experiences, I'd feel like there would be a lot more github issues/discussion around this behavior. It's very difficult to use copilot if deploying broken code causes deployments to fail for hours.

I know this is probably an issue with ECS, but I've read through everything I can find on Google and I simply can't figure out how to circumvent this issue, and the number of resources that even mention this ECS deployment circuit breaker are so scarce that I'm left scratching my head.

Related: [Gitter](https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$8qF4VRHqPPLvtWZINZg9yl3Qn5U7tQ9ni0Suf7z4Xvs)
