### ISSUE TITLE
Add from_cfn option to storage.volumes.<volume>.efs.auth.access_point_id

### ISSUE THREAD

**Issue by vc0sta** [aws/copilot-cli#5314]
# Problem statement
I have a very similar case on what was mentioned on  #5132, but with accesspoints.

First I created an `AWS::EFS::AccessPoint` using CloudFormation addon and exported it:
```yaml
Resources:
# ...
Outputs:
  AccessPointID:
    Value: !Ref AccessPoint
    Export:
      Name: !Sub ${App}-${Env}-AccessPointID
```

Then I would like to get the `access_point_id` from this exported value:
```yaml
storage:
  volumes:
    myEFSVolume: # This is a variable key and can be set to an arbitrary string.
      path: '/etc/mount1'
      efs:
        auth:
          access_point_id: fsap-0a0d2da318611cf5d # <-  I would like to get this value dynamically
          iam: true
        id:
          from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-PersistentEFSVolumeID # This is now possible thanks to #5156  
```

# Proposal

The proposal would be to use the very same approach implemented in #5156 with `AWS::EFS::AccessPoint`.

```yaml
storage:
  volumes:
    myEFSVolume: # This is a variable key and can be set to an arbitrary string.
      path: '/etc/mount1'
      efs:
        auth:
          access_point_id: ${App}-${Env}-AccessPointID # <-  I would like to get this value dynamically
          iam: true
        id:
          from_cfn: ${App}-${Env}-FilesystemID 
```

# Workaround
By now I'm defining manually the IDs for each environment:

```yaml
environments:
  myenv:
    storage:
      volumes:
        myEFSVolume:
          efs:
            auth:
              access_point_id: fsap-0a0d2da318611cf5d
```
