### ISSUE TITLE
import non-Copilot topics

### ISSUE THREAD

**Issue by nic-george** [aws/copilot-cli#5317]
I am attempting to create a worker service with a single queue that not associated to a copilot service topic. In doing so, I discovered that that the queue options retention, timeout and dead-letter retries are not being applied when a valid copilot topic is not included.

Example 1: This generates a single queue with the proper timeout and dead_letter retries
```
subscribe:
  topics:
    - name: inventory
      service: warehouse
  queue:
    retention: 96h
    timeout: 30s
    dead_letter:
      tries: 10 
```

Example 2: This generates a single queue but fails to provision the queue with the options provided (default queue options are utilized)
```
subscribe:
  queue:
    retention: 96h
    timeout: 30s
    dead_letter:
      tries: 10 
```

I would propose that these options still be applied when the topic property is absent. If there are no plans to support this functionality, I would recommend requiring the topics property.
