### ISSUE TITLE
Environment Variable to Add-On

### ISSUE THREAD

**Issue by HoosCoding** [aws/copilot-cli#5320]
Is there a way to pass an environment variable (from a machine) to an add on defined as a cloud formation template. For instance, we can reference from a workload manifest file a Github SHA or whatever environment variable is needed. However, can we do something similar in regards to an add-on at the environment level.

**Comment by Lou1415926** [comment]
Hi @HoosCoding 👋🏼 There is no native way to do this currently, and this feature request makes sense to me!

Just curious - would you be able to share a few examples of environment variables you'd like to use for addons? For example, are you storing security group IDs as environment variables, and reference it from the addons template?

**Comment by HoosCoding** [comment]
Thank you for the prompt response, @Lou1415926. Our primary use case involves dynamically referencing the image location for an AWS Batch job running on Fargate (defined as an addon). We would like to reference this based on the version or GitHub SHA, rather than having to harcode a value such as "latest" image.  


In our service manifest, we use the feature of passing environment variables when doing svc deploy in our CI/CD to use the location of the image published with the tag of the git commit.

**Comment by Lou1415926** [comment]
Thanks for sharing!! Yeah it wouldn't be nice if you have to update the image URL every time you push new codes : (.

Does it happen to be the same image URL as what the service is using?

**Comment by HoosCoding** [comment]
Agreed, it is really a struggle! For this use case, yes it is the same image URL.

**Comment by Lou1415926** [comment]
oh phew great! Then before we are able to support this feature request, you might have a nicer way to achieve your goal - [customized `Parameters` section](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#customizing-the-parameters-section).

Copilot passes the value of your image URL to the parameter [ContainerImage](https://github.com/aws/copilot-cli/blob/9e603256b49561fd894942040286d160ee4d70bb/internal/pkg/template/templates/workloads/services/lb-web/cf.yml#L18).

This means that you can do the following:
1. In the `Parameters` section of your addons file, add a parameter named `ImageURL`
```yaml
# In "webhook/addons/my-addon.yml"
Parameters:
  # Required parameters by AWS Copilot.
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  # ⬇️ New parameter!
  ImageURL:
    Type: String
```
2. Create an `addons.parameters.yml` file
3. In that file, write
```yaml
# In "svc/addons/addons.parameters.yml"
Parameters:
    ImageURL: !Ref ContainerImage
```

Then for your in the definition of your batch job, you can substitute the image url with `!Ref ImageURL`.

This way, you don't have to manually update the image url in the addons template every time. Copilot will pass whatever value it uses for `ContainerImage` to your addons' `ImageURL`.
