### ISSUE TITLE
Canary rollout

### ISSUE THREAD

**Issue by clay-risser** [aws/copilot-cli#5326]
How to do a canary rollout with copilot?

Is there a way to have the canary rollout automate the process based on health checks?

**Comment by Lou1415926** [comment]
Hi @clay-risser !

You can set up different environments, e.g. "test", "dev", etc. and create a [pipeline](https://aws.github.io/copilot-cli/docs/concepts/pipelines/) with these stages. Say you have a [pipeline manifest](https://aws.github.io/copilot-cli/docs/manifest/pipeline/) that looks like:
```yaml
# The "app-pipeline" will deploy all the services and jobs in the user/repo
# to the "test" and "prod" environments.
name: app-pipeline

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/user/repo
    # Optional: specify the name of an existing CodeStar Connections connection.
    # connection_name: a-connection

build:
  image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
  # additional_policy: # Add additional permissions while building your container images and templates.

stages: 
  - # By default all workloads are deployed concurrently within a stage.
    name: test
    pre_deployments:
      db_migration:
        buildspec: ./buildspec.yml
    test_commands:
      - make integ-test
      - echo "woo! Tests passed"
  -
    name: prod
    requires_approval: true
```

Then your application won't be deployed to `prod` unless the deployment to `test` is successful.

> automate the process based on health checks?

The ⬆️ pipeline staged deployment effectively covers this, I think. If a health check, as a part of the deployment to `test`, failed, then the deployment won't proceed into `prod`.
