### ISSUE TITLE
`Static Site` svc deploy with copilot version > 1.28.0 fails

### ISSUE THREAD

**Issue by opusmagnum** [aws/copilot-cli#5337]
With the newest versions of copilot-cli -- 1.29.0 .. 1.30.1
```
$ copilot --version
copilot version: v1.30.1
$ copilot svc deploy -n portal-frontend -e dev --diff
✘ upload deploy resources for service portal-frontend: read custom resources for a "Static Site": read custom resource TriggerStateMachineFunction at path custom-resources/trigger-state-machine.js: read template custom-resources/trigger-state-machine.js: open templates/custom-resources/trigger-state-machine.js: file does not exist
```

After the downgrade to the older version, deployment runs normally.
```
$copilot  --version
copilot version: v1.28.0
$copilot svc deploy -n portal-frontend -e dev --diff
No changes.
...
```

Platform: macOS
All other types of Services can be deployed without any problems.

What could be the reason? Someone else has experienced it? Thanks in advance!

**Comment by Lou1415926** [comment]
Hey @opusmagnum. This is quite weird - I wasn't able to reproduce the issue. This looks quite similar to https://github.com/aws/copilot-cli/issues/2375. Can you see if that helps?

**Comment by opusmagnum** [comment]
Thank you @Lou1415926, for looking into it. Yes, the error message in #2375 reads similar to my. So you assume something is wrong with my local copilot binary? Possible, but my colleague on Windows (both cmd and git-bash) gets similar
results to my on Mac.
What I can try -- run it on Linux and see how my manifest & diet behaves there.

Just for better understanding, which step (command) has uploaded the code to this S3Bucket/S3Key, for the following CloudFormation Template snippet be successful?  Is it done in the environment deployment? Can it be out of sync or has to be upgraded with some special command/procedure?
```
 TriggerStateMachineFunction:
    Metadata:
      aws:copilot:description: A lambda that starts the process of moving files to the S3 bucket
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt TriggerStateMachineFunctionRole.Arn
      Runtime: nodejs16.x
      Timeout: 900
      MemorySize: 512
      Code:
        S3Bucket: stackset-v7-infrastructu-pipelinebuiltartifactbuc-1uzwb2h9lddjf
        S3Key: manual/scripts/custom-resources/triggerstatemachinefunction/d6f36a63b0d4f48acd8234b051521f1de2cc21be0c13b037b68d95bd7c1a801a.zip

```
