### ISSUE TITLE
frequently-encountered error: "deploy service X to environment Y: alias not supported: app version must be >= v1.0.0"

### ISSUE THREAD

**Issue by sibljon** [aws/copilot-cli#5347]
Hi there,

For context, here's our set up:
* We use AWS Copilot to spin up services for each Github PR that is created on our frontend project (via a CI).
* Thus, we are frequently creating and tearing down (when the PR is closed) services.
* Perhaps one difference of how we're using Copilot from what seems to be the norm would be that we don't commit the manifest.yml file for a given service: but rather, we always just generate it when we need it via `copilot svc show --app ${providerWebappAppName} --name ${serviceName} --manifest ${environment}` and then save it to disk in `copilot/[service-name]/manifest.yml`

We frequently get the following error when trying to redeploy (note: actual service name replaced with `X`):

_Note: this error is non-deterministic, which is to say that when we encounter this error, re-running the CI job will "fix it", where the service successfully deploys and the error isn't encountered._

```
copilot svc deploy --app app --env Y --name X --force

✘ deploy service X to environment Y: alias not supported: app version must be >= v1.0.0
```

What confuses me is that we install on the CI environment the latest Copilot every run:
```
sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
  && sudo chmod +x /usr/local/bin/copilot \
  && copilot --help
```

Furthermore, I can even see some confirmation that we're using the latest version in one of the docker steps:
> Step 8/8 : LABEL com.aws.copilot.image.version=v1.30.1

And finally, we run the following on every CI job run as well:
```
copilot app upgrade
Application app is already on the latest version v1.30.1, skip upgrade.
```

Does anyone have any idea what we're doing wrong? Thanks so much for your time.

**Comment by sibljon** [comment]
Here's an example manifest file for one of my services (some details replaced with X/Y/Z), in case that helps:

```
name: X
type: Request-Driven Web Service

image:
  build: dist/docker/Dockerfile
  port: 8000


cpu: 1024

memory: 2048

environments:
  dev:
    variables:
      APP_ENVIRONMENT: dev
  staging:
    variables:
      APP_ENVIRONMENT: staging

http:
  path: '/'
  alias: X.Z.com
```

**Comment by sibljon** [comment]
Update: I just noticed that my manifest.yml file on at least one of the CI jobs in which I encountered the error, is missing the bottom part:

```
...

environments:
  dev:
    variables:
      APP_ENVIRONMENT: dev
  staging:
    variables:
      APP_ENVIRONMENT: staging

http:
  path: '/'
  alias: X.Z.com
```

I can't yet connect that logically to the error `alias not supported: app version must be >= v1.0.0`, though.
