### ISSUE TITLE
Manifest unknown key handling - block in wrong level silently ignored

### ISSUE THREAD

**Issue by erno** [aws/copilot-cli#5380]
We had a manifest bug where a healthcheck block like this was added under a per-environment block in the manifest:

```
environments:
  env1:
    image: ...
  
    healthcheck:
      healthy_threshold: 2
      unhealthy_threshold: 2
      interval: 10s
      timeout: 5s
      grace_period: 80s
```

and the error in the above is that it should be in a `http:` block and hence it didn't do anything. 

I think this kind of thing should not pass validation silently.
