### ISSUE TITLE
Collision between `LoadBalancerDNSAlias`es

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#5381]
# Use case

I have bunch of Backend Services, which I am forced to expose with the following URL scheme due to backward compatibility:

```
https://myenv.example.com/service1 -> service 1
https://myenv.example.com/service2 -> service 2
```

I tried to use the shared ALB using the `http` feature of the Backend Services:

**copilot/environments/myenv/manifest.yml:**

```yaml
http:
  private:
    certificates:
      - arn:aws:acm:XXXXX
```

**copilot/service1/manifest.yml:**

```yaml
http:
  port: 8080/tcp
  target_port: 8080
  path: /service1

# ...

overrides:
  myenv:
    alias: myenv.example.com
    hosted_zone: XXXXXXXXX
  # other environments...
```

**copilot/service2/manifest.yml:**

```yaml
http:
  port: 8080/tcp
  target_port: 8080
  path: /service2

# ...

overrides:
  myenv:
    alias: myenv.example.com
    hosted_zone: XXXXXXXXX
  # other environments...
```

# Problem
The two workload stacks have a conflict, because both of them try to create the following resource (taken from the output of `copilot svc package -n service1`):

```yaml
LoadBalancerDNSAliasXXXXXXXXXX:
  Metadata:
    'aws:copilot:description': 'Alias records for the application load balancer in hosted zone XXXXXXXXXX'
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneId: XXXXXXXXXX
    Comment: !Sub "LoadBalancer aliases for service ${WorkloadName} in hosted zone XXXXXXXXXX"
    RecordSets:
      - Name: myenv.example.com
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt EnvControllerAction.InternalLoadBalancerHostedZone
          DNSName: !GetAtt EnvControllerAction.InternalLoadBalancerDNSName
```

And these resources will clash with the following error message:
```
Tried to create resource record set [name='myenv.example.com.', type='A'] but it already exists
```

# Proposed solution

The LoadBalancerDNSAlias records could be implemented in the environment stack instead of the workload stacks to prevent collision. However, I suspect that there is no easy static CloudFormation way to do it, some new Lambda controller has to be added.

# Workaround

Create a cfn patch for each service to remove this resource:

**copilot/service1/overrides/cfn.patches.yml and copilot/service2/overrides/cfn.patches.yml**

```yaml
- op: remove
  path: /Resources/LoadBalancerDNSAliasXXXXXXXXXXXXX
```

And instead create the resource as an addon in the environment stack:

**copilot/environments/addons/alb_http_alias.yml:**
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  InternalLoadBalancerDNS:
    Type: String
    Description: The DNS name of the internal Copilot-managed ALB
  InternalLoadBalancerHostedZone:
    Type: String
    Description: Internal load balancer hosted zone
Conditions:
  CreateInternalALB: !And
    - !Not [!Equals [!Ref InternalLoadBalancerDNS, ""]]
    - !Not [!Equals [!Ref InternalLoadBalancerHostedZone, ""]]
Mappings:
  Environments:
    myenvironment:
      HostedZoneId: XXXXXXXXXXXXX
      DNSName: myenv.example.com
    # ...
Resources:
  LoadBalancerDNSAlias:
    Metadata:
      "aws:copilot:description": "Alias records for the application load balancer"
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !FindInMap [Environments, !Ref Env, HostedZoneId]
      Comment: Shared load balancer alias
      RecordSets:
        - Name: !FindInMap [Environments, !Ref Env, DNSName]
          Type: A
          AliasTarget:
            HostedZoneId: !Ref InternalLoadBalancerHostedZone
            DNSName: !Ref InternalLoadBalancerDNS
    Condition: CreateInternalALB
```

**copilot/environments/addons/addons.parameters.yml**
```yaml
Parameters:
  InternalLoadBalancerDNS:
    Fn::If:
      - CreateInternalALB
      - !GetAtt InternalLoadBalancer.DNSName
      - ""
  InternalLoadBalancerHostedZone:
    Fn::If:
      - CreateInternalALB
      - !GetAtt InternalLoadBalancer.CanonicalHostedZoneID
      - ""
```

## Limitation of the workaround

Since the resource name (`LoadBalancerDNSAliasXXXXXXXXXXXXX`) contains the hosted zone's ID, I cannot reuse the same `copilot/service1/overrides/cfn.patches.yml` file across environments with different hosted zone IDs.
