### ISSUE TITLE
Add pipeline environment variable

### ISSUE THREAD

**Issue by jerometremblay** [aws/copilot-cli#5383]
I have two pipelines:

```
copilot/pipelines/pipeline_a/
  buildspec.yml
  manifest.yml
copilot/pipelines/pipeline_b/
  manifest.yml
```

Pipeline B manifest references buildspec.yml so it is shared between the two pipelines.

I customized the build script using variables I defined manually in the pipeline configuration console UI.
<img width="644" alt="wcHtp" src="https://github.com/aws/copilot-cli/assets/4490798/52ed3c44-f92f-4cb8-a6a2-93d26421740c">

In pipeline A, i set the value to "production" and in the pipeline B to "development.

Is it possible to declare those variables in code? I tried to declare the variables in the manifest.yml but they are not visible in the buildspec.

**Comment by iamhopaul123** [comment]
Hello @jerometremblay. I don't think right now in our pipeline manifest it is able to specify env var.

To quickly unblock the use case right now you can run `copilot pipeline override` and in your yaml patch file you can specify env vars like this

``` yaml
- op: add
  path: /Resources/BuildProject/Properties/Environment/EnvironmentVariables/-
  value:
    Name: ENVIRONMENT_NAME
    Value: production
```
