### ISSUE TITLE
How to encrypt copilot generated cloud watch group?

### ISSUE THREAD

**Issue by EricHeitmuller-Addition** [aws/copilot-cli#5385]
Hello,

I am generating a cloud watch log group for my scheduled job like so:

```
logging:
  destination:
    Name: cloudwatch
    region: us-east-2
    log_group_name: /copilot/${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-app-name
    log_stream_prefix: ${COPILOT_ENVIRONMENT_NAME}/
```

This creates and unencrypted log group. Looking at the examples here: https://aws.github.io/copilot-cli/docs/developing/sidecars/#sidecar-patterns I don't see anything about encryption that we can set up. Is it possible to do this from inside of copilot?

**Comment by iamhopaul123** [comment]
Hello @EricHeitmuller-Addition. Sorry it's not natively supported in Copilot. However, you can define an encrypted CloudWatch log group in your [addons file](https://aws.github.io/copilot-cli/docs/developing/addons/workload/), and the proper permission for task role to write to that log group. 

```yaml
# addons file
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.

Resources:
  myLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
      LogGroupName: !Sub "/copilot/${App}-${Env}-app-name"
      KmsKeyId: {{ YOUR KMS ID }}
  ServiceLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:DescribeLogStreams
          - logs:PutLogEvents
          Resource: !GetAtt myLogGroup.Arn
Outputs:
  ServiceLogPolicyArn:
    Description: An addon ManagedPolicy gets used by the ECS task role
    Value: !Ref ServiceLogPolicy
```


In the `logging` section, turn `auto_create_group` off so that it doesn't try to create an unencrypted one:

```yaml
logging:
  destination:
    Name: cloudwatch
    region: us-east-2
    log_group_name: /copilot/${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-app-name
    log_stream_prefix: ${COPILOT_ENVIRONMENT_NAME}/
    auto_create_group: false
```
