### ISSUE TITLE
An error occurs when deploying a YAML patched backend service that includes an ALB target group

### ISSUE THREAD

**Issue by laughingman7743** [aws/copilot-cli#5387]
Hello, when I deploy a backend service created in Copilot with a YAML patch and add it to an ALB target group that is not managed by Copilot, I get a validation error.
```
- No new infrastructure changes for stack foobar
✔ Forced an update for service foobar from environment dev.
✔ Deployed service foobar.
✘ get uri for environment dev: get host headers for listener rules : get listener rule for : ValidationError: Rule or listener must be specified
        status code: 400, request id: ****
```

The YAML patch is as follows:
```
- op: add
  path: /Resources/Service/Properties/LoadBalancers
  value:
    - ContainerName: foobar
      ContainerPort: 8080
      TargetGroupArn: !Ref TargetGroup

- op: add
  path: /Resources/TargetGroup
  value:
    Metadata:
      'aws:copilot:description': "A target group to connect the load balancer to your service on port 8080"
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /
      HealthCheckPort: 8080
      Matcher:
        HttpCode: 200,301,302
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      Port: 8080
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
        - Key: stickiness.enabled
          Value: false
      TargetType: ip
      VpcId: "vpc-12345"

- op: add
  path: /Resources/HTTPSListenerRule
  value:
    Metadata:
      'aws:copilot:description': 'An HTTPS listener rule for path `/foobar` that forwards HTTPS traffic to your tasks'
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: 'path-pattern'
          PathPatternConfig:
            Values:
              - /path*
      ListenerArn: "arn:aws:elasticloadbalancing:ap-northeast-1:12345:listener/app/foobar"
      Priority: 1
```

There seems to be an error in the generation of the recommended action message after deployment. I believe it is the following location.
https://github.com/aws/copilot-cli/blob/v1.31.0/internal/pkg/cli/svc_deploy.go#L589-L592

The service is deployed successfully, so I would like the error to not occur.
