### ISSUE TITLE
Pipeline s3 bucket allows HTTP access

### ISSUE THREAD

**Issue by gabelton** [aws/copilot-cli#5389]
A recent pen test highlighted that the s3 bucket created after running `copilot pipeline init` didn't have `SecureTransport: true` in its configuration. Is this by design? Seems like the secure-by-default option would automatically set this to true, to prevent manipulation of data in transit.

**Comment by KollaAdithya** [comment]
Thanks @gabelton for bringing to our attention. It is one of the [best practices](https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html#Enforce-encryption-of-data-in-transit) of S3 that should be followed to deny HTTP request on transit. I will mark this issue as an enhancement.

**Comment by gabelton** [comment]
Thanks for the speedy reply @KollaAdithya . I don't suppose you're able to give an estimate for when that change might be made? Our security team are asking for remediation by november 27th this year, so just trying to work out whether we need to produce an interim solution for this or can wait for your enhancement.

**Comment by KollaAdithya** [comment]
Hello @gabelton !

I have a open PR #5393 which will go in the next release. I suppose there is no easy workaround for this, instead go to IAM Console and change the `PipelieneArtifactBucketPolicy`. 
```
- Sid: ForceHTTPS
  Effect: Deny
  Principal: "*"
  Action: s3:*
  Resource:
    - !Sub ${PipelineBuiltArtifactBucket.Arn}
    - !Sub ${PipelineBuiltArtifactBucket.Arn}/*
  Condition:
    Bool:
      aws:SecureTransport: false
```
