### ISSUE TITLE
Specify an existing security group id for app runner

### ISSUE THREAD

**Issue by Danwakeem** [aws/copilot-cli#5397]
It doesn't look like there is a way to specify an existing security group when deploying a request driven web service.

It would be nice if there was a way to specify an existing security group like this 👇 

```
network:
  vpc:
    id: vpc-xxx
    subnets:
      public:
        - id: subnet-xxx
        - id: subnet-xxx
      private:
        - id: subnet-xxx
        - id: subnet-xxx
    security_group:
        - id: sg-xxx      
```
