### ISSUE TITLE
copilot pipeline deployments: indeed select services to deploy, but still build all services?

### ISSUE THREAD

**Issue by tyoc213** [aws/copilot-cli#5404]
Hi there, I have a problem with a service I deploy manually passing an argument like  https://github.com/aws/copilot-cli/discussions/5403 but the thing is that even if I opt out/remove this service called "`exclude-svc4`" with `deployments:`

```
stages:
    - name: staging
      deployments:
        svc0:
        svc1:
        svc2
          depends_on: [svc0]
        svc3:
```

The build of the corresponding `exclude-service` is still shown on step 2 on `codepipeline->pipeline` even that only svc0, svc1, svc2 and svc3 shows on step 3 of `codepipeline->pipeline`.

I think the desired output will be to skip all the docker builds of services not listed in deployments.
