### ISSUE TITLE
My Container does not up while i enable EFS volume: Failed to import necessary dependency botocore, please install botocore first. : unsuccessful EFS utils command execution; code: 1

### ISSUE THREAD

**Issue by sabin2018** [aws/copilot-cli#5419]
### this is my storage manifest:
```
storage:
  # readonly_fs: true       # Limit to read-only access to mounted root filesystems.
  volumes:
    myVolume:
      efs: true
      path: /common/var/efs
      read_only: false
```
