### ISSUE TITLE
Move a deployed app inside a VPC

### ISSUE THREAD

**Issue by musenaw** [aws/copilot-cli#5420]
Hi, I'm using version v1.28.0.

I'm trying to move an already deployed application inside to a VPC. Can this task could be done?
I added network configuration inside environment and in app manifest, but when i do  `copilot env deploy --name dev` I get the following error
```
Resource handler returned message: "Security group 'sg-xxxxxx' does not belong to VPC 'vpc-xxxxxx' (Service: ElasticLoadBalancingV2 , Status Code: 400
```

This is my app manifest
```yaml
name: app
type: Load Balanced Web Service

http:
  path: '/'
  healthcheck:
    path: '/health/'
    interval: 15s
    timeout: 10s


image:
  build: 
    dockerfile: copilot.Dockerfile
  port: 9595

  
exec: true     

env_file: .env

environments:
  dev:
    http:
     
    cpu: 512     
    memory: 1024  
    count:
      range: 1-2
      cooldown:
        in: 60s
        out: 30s
      cpu_percentage: 70
      memory_percentage: 70
    
    logging:
      retention: 365
    
    network:
      vpc:
        placement:
          subnets: ["subnet-xxxxxx", "subnet-xxxxx"]
        security_groups: ['sg-xxxxx']

```

and my environment manifest
```yaml

name: dev
type: Environment

network:
  vpc:
    id: "vpc-xxxxx"
    subnets: 
      public:
        - id: "subnet-xxxxxx"
        - id: "subnet-xxxxx"
      private:
        - id: "subnet-xxxxx"
        - id: "subnet-xxxxx"

observability:
  container_insights: false


```

If I deploy the app starting from the beginning with this configuration is inside the VPC without any problem, but i would like to move an existing app to a VPC
