### ISSUE TITLE
Unable to deploy service "SC service is already used"

### ISSUE THREAD

**Issue by squallstar** [aws/copilot-cli#5431]
Hello,

since this morning I'm unable to deploy my service via `copilot svc deploy` due to this error:

```
The following resource(s) failed to update: [Service]:

Resource handler returned message: "Invalid request provided: CreateSe
rvice error: SC service is already used by arn:aws:servicediscovery:us
-east-1:021748665536:namespace/ns-q7lwmdom5g42muaf (Service: AmazonECS
; Status Code: 400; Error Code: InvalidParameterException; Request ID:
687431c9-d72f-468d-a2bf-702a8688451b; Proxy: null)" (RequestToken: 7f
ec533e-2a93-7b55-73a5-45d231327066, HandlerErrorCode: InvalidRequest
```

For context, my service has a security group in its manifest linked to an export from the RDS addon:

```
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  vpc:
    security_groups:
      - from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-myDBSecurityGroup
```

---

I'm using the latest available version of the CLI.
