### ISSUE TITLE
Cannot init new services after accidentally deleting autogenerated cf,  unmarshal errors

### ISSUE THREAD

**Issue by jmiranda-edata** [aws/copilot-cli#5435]
# Explanation
Hi, I have an app with multiple services running. I accidentally deleted an autogenerated cloudformation related to a pipeline, after that I started to receive unmarshal errors if I tried to delete or regenerated the pipeline.

Now I can't create new services. I was checking the cloudformations to see if I saw a rollback state or errors but I'm lost. I don't know where is the yaml that is having unmarshal errors, I guess it's autogenerated.

This is what I get.

Thank you!

# Outputs
```
> copilot svc init -n celery-worker
Manifest file for service celery-worker already exists. Skipping configuration.
√ Manifest file for service celery-worker already exists at copilot\celery-worker\manifest.yml, skipping writing it.
Your manifest contains configurations like your container size and port.

X add service celery-worker to application customer-app: adding service celery-worker resources to application customer-app: parse previous deployed stackset yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `See #5140` into []string
```
I found this in the infrastructure cloudformation template:
```
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
# Cross-regional resources deployed via a stackset in the tools account
# to support the CodePipeline for a workspace
Description: Cross-regional resources to support the CodePipeline for a workspace
Metadata:
  TemplateVersion: 'v1.29.1'
  Version: 13
  Workloads:
    - Name: api
      WithECR: true
    - Name: customer-platform
      WithECR: false
    - Name: front-app
      WithECR: false
  Accounts:
    - 223972924621
  Services: "See #5140"
...
```
I guess that services should look different
