### ISSUE TITLE
Copilot fails to deploy an addon storage for already existing service

### ISSUE THREAD

**Issue by vshah11** [aws/copilot-cli#5436]
I have a service deployed on copilot that already contains an addon storage (Aurora db). I tried to create another addon stack for the same service since I need an additional S3 bucket to be deployed with this service and copilot is running into an error while doing the same.

The storage init commands runs fine and generates the yaml file but the service deployment is not working. Need some reference/suggestion to fix my addon definition to allow both the storages to be deployed along with my service.

It gives the error - 

```Initiate workload deployer: parse addons stack for workload service: parameter logical ID "Name" defined in "service-cluster.yml" at Ln 9, Col 5 is different than in "service-s3-storage.yml" at Ln 9, Col 5```

The starting segment of the addons is defined as - 

```
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
```

**Comment by iamhopaul123** [comment]
It seems like the value for `Name` defined in "service-cluster.yml" is different from the value defined in "service-s3-storage.yml". Can you check the [parameter files](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#customizing-the-parameters-section) and see if you have different values set for these two addons templates?

**Comment by vshah11** [comment]
Hey,

There is no parameter file present but I will recheck for the values during deployment.
The only place where the Name field is being set/referenced in the Aurora addon is under the Security Group in Resources -

```
studyemrclusterSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the DB cluster studyemrcluster'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'The Security Group for ${Name} to access DB cluster studyemrcluster.'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-${Name}-Aurora'
```
