### ISSUE TITLE
AWS CodeBuild not generating ContainerImage CodeBuild params output file

### ISSUE THREAD

**Issue by amucunguzi** [aws/copilot-cli#5455]
Here are the steps to reproduce the issue:

1. Installed copilot v1.13.0 (arm64)
2. Ran `copilot pipeline init`
3. Ran `copilot pipeline update` (BuildCode stage succeeds and generates `ContainerImage` in params)
4. Ran into a "nodejs12.x no longer supported for creation of new Lambda functions" in the Deploy stage (when creating `EventControllerFunction`). 
5. Updated copilot to v1.28.0 (arm64)
6. Ran `copilot svc deploy` and successfully deployed on ECS instances.
7. Ran `copilot pipeline update`
8. The CodeBuild step doesn't generate a `ContainerImage` in params output file.

Below are the configuration files (buildspec.yml, pipeline.yml, manifest.yml) alongside the params output file.

## Buildspec.yml
<details>
  <summary>Click to expand</summary>
  
   ```yaml
   \# Buildspec runs in the build stage of your pipeline.  
version: 0.2  
phases:  
  install:  
    runtime-versions:  
      docker: latest  
      ruby: 3.2  
      nodejs: 18  
    commands:  
      - echo "cd into $CODEBUILD_SRC_DIR"  
      - cd $CODEBUILD_SRC_DIR  
      \# Download the copilot linux binary.  
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-arm64-v1.28.0  
      - mv ./copilot-linux-arm64-v1.28.0 ./copilot-linux  
      - file ./copilot-linux  
      - chmod +x ./copilot-linux  
  build:  
    commands:  
      - ls -l  
      - export COLOR="false"  
      \# First, upgrade the cloudformation stack of every environment in the pipeline.  
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipeline.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')  
      - pl_envs=$(echo $pipeline | jq -r '.stages[].name')  
      - >  
        for pl_env in $pl_envs; do  
          ./copilot-linux env upgrade -n $pl_env;  
        done;  
      \# Find all the local services in the workspace.  
      - svc_ls_result=$(./copilot-linux svc ls --local --json)  
      - svc_list=$(echo $svc_ls_result | jq '.services')  
      - >  
        if [ ! "$svc_list" = null ]; then  
          svcs=$(echo $svc_ls_result | jq -r '.services[].name');  
        fi  
      \# Find all the local jobs in the workspace.  
      - job_ls_result=$(./copilot-linux job ls --local --json)  
      - job_list=$(echo $job_ls_result | jq '.jobs')  
      - >  
        if [ ! "$job_list" = null ]; then  
          jobs=$(echo $job_ls_result | jq -r '.jobs[].name');  
        fi  
      \# Raise error if no services or jobs are found.  
      - >  
        if [ "$svc_list" = null ] && [ "$job_list" = null ]; then  
          echo "No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote." 1>&2;  
          exit 1;  
        fi  
      \# Generate the cloudformation templates.  
      \# The tag is the build ID but we replaced the colon ':' with a dash '-'.  
      \# We truncate the tag (from the front) to 128 characters, the limit for Docker tags  
      \# (https://docs.docker.com/engine/reference/commandline/tag/)  
      - >  
        for env in $pl_envs; do  
          tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" | rev | cut -c 1-128 | rev)  
          for svc in $svcs; do  
          ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag;  
          done;  
          for job in $jobs; do  
          ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag;  
          done;  
        done;  
      - ls -lah ./infrastructure  
      - cat ./infrastructure/*.params.json  
      \# Concatenate jobs and services into one var for addons  
      \# If addons exists, upload addons templates to each S3 bucket and write template URL to template config files.  
      - WORKLOADS=$(echo $jobs $svcs)  
      - |  
        for workload in $WORKLOADS; do  
          ADDONSFILE=./infrastructure/$workload.addons.stack.yml  
          if [ -f "$ADDONSFILE" ]; then  
            tmp=$(mktemp)  
            timestamp=$(date +%s)  
            aws s3 cp "$ADDONSFILE" "s3://[REDACTED]/manual/$timestamp/$workload.addons.stack.yml";  
            jq --arg a "https://[REDACTED].s3.eu-central-1.amazonaws.com/manual/$timestamp/$workload.addons.stack.yml" '.Parameters.AddonsTemplateURL = $a' ./infrastructure/$workload-staging.params.json > "$tmp" && mv "$tmp" ./infrastructure/$workload-staging.params.json  
          fi  
        done;  
      \# Build images  
      \# - For each manifest file:  
      \#   - Read the path to the Dockerfile by translating the YAML file into JSON.  
      \#   - Run docker build.  
      \#   - For each environment:  
      \#     - Retrieve the ECR repository.  
      \#     - Login and push the image.  
      - |  
        set -exv  
        for workload in $WORKLOADS; do  
          if [ -z "$workload" ]; then  
            echo "Warning: No workload defined."  
            continue  
          fi  
          manifest=$(cat $CODEBUILD_SRC_DIR/copilot/$workload/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')  
          for env in $pl_envs; do  
            tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" | rev | cut -c 1-128 | rev)  
            images=$(echo $manifest | jq --arg env "$env" '{base_image: .image, env_image: (.environments? | .[$env]? | .image? // {}) }')  
            image=$(echo $images | jq 'if (.env_image | length == 0) then .base_image else (.base_image | del(.location)) * .env_image end')  
            image_location=$(echo $image | jq '.location')  
            if [ ! "$image_location" = null ]; then  
              echo "skipping image building because location is provided as $image_location";  
              continue  
            fi  
            base_dockerfile=$(echo $image | jq '.build')  
            build_dockerfile=$(echo $image | jq -r '.build?.dockerfile? // ""')  
            build_context=$(echo $image | jq -r '.build?.context? // ""')  
            build_target=$(echo $image | jq -r '.build?.target? // ""')  
            dockerfile_args=$(echo $image | jq '.build?.args? // "" | to_entries?')  
            build_cache_from=$(echo $image | jq -r '.build?.cache_from? // ""')  
            df_rel_path=$( echo $base_dockerfile | sed 's/"//g')  
            if [ -n "$build_dockerfile" ]; then   
              df_rel_path=$build_dockerfile  
            fi  
            df_path=$df_rel_path  
            df_dir_path=$(dirname "$df_path")  
            if [ -n "$build_context" ]; then  
              df_dir_path=$build_context  
            fi  
            platform_string=$(echo $manifest | jq -r '.platform // ""')  
            platform_os=$(echo $manifest | jq -r '.platform?.osfamily? // ""')  
            platform_arch=$(echo $manifest | jq -r '.platform?.architecture? // ""')  
            if [ "$platform_os" -a "$platform_arch" ]; then  
              platform_string="$platform_os/$platform_arch"  
            fi  
            build_args=  
            if [ -n "$dockerfile_args" ]; then  
              for arg in $(echo $dockerfile_args | jq -r '.[] | "\(.key)=\(.value)"'); do   
                build_args="$build_args--build-arg $arg "  
              done  
            fi  
            if [ -n "$build_target" ]; then  
              build_args="$build_args--target $build_target "  
            fi  
            if [ -n "$build_cache_from" ]; then  
              for arg in $(echo $build_cache_from | jq -r '.[]'); do  
                build_args="$build_args--cache-from $arg "  
              done  
            fi  
            if [ -n "$platform_string" ]; then  
              build_args="$build_args--platform $platform_string "  
            fi  
            echo "Name: $workload"  
            echo "Relative Dockerfile path: $df_rel_path"  
            echo "Docker build context: $df_dir_path"  
            echo "Docker build args: $build_args"  
            echo "Running command: docker build -t $workload:$tag $build_args -f $df_path $df_dir_path";  
            docker build -t $workload:$tag $build_args -f $df_path $df_dir_path;  
            image_id=$(docker images -q $workload:$tag);  
            repo=$(cat $CODEBUILD_SRC_DIR/infrastructure/$workload-$env.params.json | jq -r '.Parameters.ContainerImage');  
            region=$(echo $repo | cut -d'.' -f4);  
            docker login -u AWS -p $(aws ecr get-login-password --region $region) $AWS_ACCOUNT_ID.dkr.ecr.$region.amazonaws.com  
            docker tag $image_id $repo;  
            docker push $repo;  
          done;  
        done;  
artifacts:  
  files:  
    - "infrastructure/*"  
   ```
</details>
  
  ## Pipeline.yml
  
  <details>
    <summary>Click to expand</summary>
    
    ```yaml
\# The manifest for the "pipeline-vanoma-survey-api" pipeline.
\# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
\# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

name: my-pipeline-name

version: 1

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/username/repo.git
    connection_name: copilot-app

stages:
  - name: staging
    test_commands:
      - yum update -y && yum install -y sudo expect
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-arm64-v1.28.0
      - mv ./copilot-linux-arm64-v1.28.0 ./copilot-linux
      - chmod +x ./copilot-linux
      - unbuffer ./copilot-linux svc exec -c "python manage.py migrate" -n service-name -e staging --yes
  - name: production
    test_commands:
      - yum update -y && yum install -y sudo expect
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-arm64-v1.28.0
      - mv ./copilot-linux-arm64-v1.28.0 ./copilot-linux
      - chmod +x ./copilot-linux
      - unbuffer ./copilot-linux svc exec -c "python manage.py migrate" -n service-name -e production --yes

    ```
  </details>
  
  ## Manifest.yml
  <details>
    <summary>Click to expand</summary>
```yaml
# The manifest for the "survey-api" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

name: service-name
type: Backend Service

image:
  build: Dockerfile
  port: 8000

cpu: 256
memory: 512
platform: linux/arm64
count: 1
exec: true
command: gunicorn -k gevent --bind 0.0.0.0:8000 survey_api.wsgi:application

variables:
  // Key-value pairs of environment variables to set for the container.

environments:
  staging:
    variables:
      ENVIRONMENT: staging
      // Key-value pairs of environment variables to set for the container.
  production:
    cpu: 1024
    memory: 2048
    count:
      range: 1-5
      cooldown:
        in: 30s
        out: 30s
      cpu_percentage: 70
      memory_percentage: 80
    variables:
      ENVIRONMENT: production
      // Key-value pairs of environment variables to set for the container.

```
</details>

      ## Parms.json
  <details>
    <summary>Click to expand</summary>
```JSON
{
  "Parameters": {
    "AddonsTemplateURL": "",
    "AppName": "vanoma",
    "ContainerImage": "",
    "ContainerPort": "8000",
    "EnvFileARN": "",
    "EnvName": "staging",
    "LogRetention": "30",
    "TargetContainer": "survey-api",
    "TargetPort": "8000",
    "TaskCPU": "256",
    "TaskCount": "1",
    "TaskMemory": "512",
    "WorkloadName": "survey-api"
  },
  "Tags": {
    "copilot-application": "vanoma",
    "copilot-environment": "staging",
    "copilot-service": "survey-api"
  }
}
```
</details>
