### ISSUE TITLE
Designate the listener to use when importing a public-facing ALB

### ISSUE THREAD

**Issue by DaniAmaya** [aws/copilot-cli#5473]
Hi team! 
I have the following manifest.yml to designate an existing public-facing ALB for a specific Load-Balanced Web Service.

```
# Your service name will be used in naming your resources
name: prov-recos-copilot-service
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  path: '/'
  # Parameters for existing AWS LoadBalancer resources that your service requires.
  alb: '<load balacer arn>'

# Configuration for your containers and service.
image:
  # Docker build arguments.
  build: Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 8080

cpu: 4096       # Number of CPU units for the task.
memory: 8192    # Amount of memory in MiB used by the task.
platform: linux/x86_64
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
```

But I'm getting back the following error when I `copilot deploy`: `execute deployment 1 of 1 in group 1: deploy service prov-recos-copilot-service to environment demo: validate imported ALB configuration for "http": imported ALB <load balacer arn> must have either one or two listeners`

So I guess my question is, how do I add these parameters to my .yaml? Please

_Originally posted by @DaniAmaya in https://github.com/aws/copilot-cli/issues/3319#issuecomment-1810390637_

**Comment by Lou1415926** [comment]
(Moving my answer from the other thread to here)

@DaniAmaya Glad you are trying out the new feature! This error is just staying that Copilot expects the imported ALB to already have one or two listeners - it validates this by making API calls to retrieve the existing listeners on the ALB. Copilot will add listener rules to the existing listeners based on your manifest configuration, but it will not attempt to create any new listeners on the imported ALB.

To fix this, you will just add one or two listeners to your ALB. Typically, if you are fine with your service being accessible only on "http", then you just need to add one HTTP listener on port 80. If you want "https", then you will add an HTTP listener on port 80, and an HTTPS listener on port 443.

Hope this helps - let me know how it goes!

**Comment by ColeDCrawford** [comment]
Will this work with multiple different Copilot services? E.g. if I have multiple ACM managed SSL certs, I can add them all to the ALB - can Copilot set up the rules to use the correct certs? How would it know which cert to use?

**Comment by Lou1415926** [comment]
@ColeDCrawford The cert is attached to the listeners not the rules. When setting up listener rules, Copilot only needs to know the alias that you want to use (of course, the alias has to be covered by any one of the certs that you've attached), it will then create listener rules on host headers based on the aliases that you've specified.

**Comment by DaniAmaya** [comment]
Thank you @Lou1415926 ! I already have port 80 from the Load Balancer nested to another service, not related to the service I want to deploy with copilot. I've created the listener for the copilot service on port 81, but copilot is not able to find it. Do I need to specify it on the manifest? If so, how? Or should I specify the port elsewhere?

**Comment by Lou1415926** [comment]
@DaniAmaya oh I see, you have two HTTP listeners, and Copilot should use one of them. 

😞 Unfortunately, today Copilot errors out when it finds >2 listeners, or exactly two listeners that are both HTTP or HTTPS (i.e. it has to be one HTTP and one HTTPS)...We are happy to extend this feature in the future, but I'd like to understand your use case a bit better:
1. When you first tried out the feature, how had you expected to convey to Copilot that "the listener on port 81" should be the one that it adds listener rules to? In another word, is ⬇️  the manifest that you had?
```
image:
  port: 81

http:
  alb: <arn>
```
 2. It seems like both of your services are on HTTP (without the encryption), and one is expected to be put on port 81 (which, to my knowledge, is not as usual). I assume these services are for some test environment? Did it matter to you which port that the second service is put on, e.g. some port other than 81?
