### ISSUE TITLE
ADOT version outdated

### ISSUE THREAD

**Issue by bonclay7** [aws/copilot-cli#5484]
Deploying a copilot service and using AWS X-Ray with the config below:

```yaml
observability:
  tracing: awsxray
```

launches an ADOT collector **v0.17.0** when the latest ADOT release (including X-Ray W3C support) is [v0.35.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.35.0)
<img width="1231" alt="Screenshot 2023-11-16 at 10 06 51" src="https://github.com/aws/copilot-cli/assets/10175027/db71c969-8f87-431d-8658-2d6c8f9b5523">

Can we have this updated please?

**Comment by mhausenblas** [comment]
ADOT PM here. Thanks @bonclay7 and I'd recommend to do this after we've released Logs GA support, in a few weeks time.

**Comment by Lou1415926** [comment]
Hi @bonclay7 and @mhausenblas 👋🏼 We decided to hardcode the version because ADOT image's major version was and is still version 0, which means that there is no guarantee in backward compatibility. We want to avoid breaking customer's application unintentionally, so we opted _not_ to always stay on the latest ADOT version. 

And I saw #5486 - thank you very much for the contribution, we love contributions ❤️ Out of the same concern that I just described, I have a slightly different proposal: we should let users decide on their own which version to use and whether to bump the version. 

There are two ways to accomplish this proposal: yaml patch, and manifest.

#### YAML Patch
People could use this yaml patch to bump their ADOT version:
```yaml
- op: replace
  path: /Resources/TaskDefinition/ContainerDefinitions/2/Image # The number 2 may vary - depends on the number of container definitions that come before "aws-otel-collector".
  value: public.ecr.aws/aws-observability/aws-otel-collector:v0.35.0
```

#### Manifest
We could opt to introduce a manifest field to specify the version. For example (this is not a design, just an example):
```yaml
observability:
  tracing:
    awsxray:
      adot_version: 0.35.0
```

I hesitate to introduce this field _right now_, because I believe that the decision of "what goes into the manifest" is driven by - among other things - a) how frequent a user wants to configure the field b) how much impact it has on the architecture, or in anther word, the use cases.

I would like to wait for more users to jump in and share that they need to change the version (answers criteria a), or be confident that the versions change have large differences that it affects the general usability on common use cases.

Therefore, my suggestion is that we encourage users to use the YAML patch once they need to upgrade the ADOT version.
