### ISSUE TITLE
nlb with port:443/tls not working (?), or doc not complete ?

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5502]
**steps**

1.  get official demo app described in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/getting-started-aws-copilot-cli.html 
1.  init using a doman (with the --domain mydomain.com)
1. deploy and make sure it works
1. follow the doc in https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb-port and  replace 

```yaml
http:
    path: /
```
with
```yaml
http: false
nlb:
  port: 443/tls
  healthckeck:
    port: 80
```

5. deploy again

**expected**

1. it should deploy it using a NLB
1. the URL provided should work

**instead**

1. the URL is not opening

**Comment by KollaAdithya** [comment]
Hello @sebastianovide !

If you set port 443 for nlb, by default copilot assumes that the target container which is `nginx` in this case is running on 443.

But in this case  by default `nginx` is listening on port 80 and Healthcheck are passed because of this.

Can you modify the manifest to have ⬇️ 

```
http: false
nlb:
  port: 443/tls
  target_port: 80
  healthckeck:
    port: 80
```

https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb-target-port
