### ISSUE TITLE
Passing managed IAM policy at an environment level add-on to workloads?

### ISSUE THREAD

**Issue by HoosCoding** [aws/copilot-cli#5523]
I am particularly interested in understanding how to effectively pass a managed IAM policy at an environment level to individual workloads. This functionality is crucial for ensuring that each service or task within my application has the necessary permissions tailored to its specific needs, while also maintaining a clean and organized IAM structure. Could you provide guidance or documentation on how to implement this, or let me know if this feature is supported in AWS Copilot?

For more context to the use case, I have a load balancer service and a scheduled job that need the same permissions to be functional. As of now, I have duplicate policies, however, when developers release a new feature that requires new permissions sometimes the attachment of additional permissions is missed.

**Comment by Lou1415926** [comment]
@HoosCoding this is doable! The general idea is to create a managed IAM policy as an environment addon, and add that policy to task roles of the load balancer service and the scheduled job.

```yaml
# The environment addon.
Resources:
  MyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: #....
Outputs:
  MyPolicyARN:
    Description: #..
    Value: !Ref MyPolicy
    Export:
      Name: !Sub ${App}-${Env}-MyPolicyARN # You are free to choose your own export name - name-spacing it with app and env makes it less likely to collide with other export names. 
```
Then you can attach this managed policy to the task roles via. [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/)
```yaml
- op: add
   path: /Resources/TaskRole/Properties/ManagedPolicyArns
   value:
     - Fn::ImportValue:
          !Sub '${AppName}-${EnvName}-MyPolicyARN' # Import the export from the env addon.
```

**Comment by HoosCoding** [comment]
Thank you!!!! @Lou1415926

**Comment by thomaswitt** [comment]
AddOn, because I've found this very helpful for defining IAM policies on environmental level and using them on workload level without copying them.

If you want to attach-append to the existing ARNs, you must use a minus sign after the path. Example:

```
# copilot/web/overrides/cfn.patches.yml

- op: add
  path: /Resources/TaskRole/Properties/ManagedPolicyArns/-
  value:
    Fn::ImportValue: !Sub "${App}-${Env}-DdbAccessPolicyArn"

- op: add
  path: /Resources/TaskRole/Properties/ManagedPolicyArns/-
  value:
    Fn::ImportValue: !Sub "${App}-${Env}-OpenSearchAccessPolicyArn"
```

copilot/environments/addons/dynamodb-policy.yml needs then to define the output via (in this case assuming you defined a IAM policy 

```
# copilot/environments/addons/dynamodb-policy.yml

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
[... all your table create stuff ...]
  DdbTableAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
[... your policy here ...]

Outputs:
  ddbTableAccessPolicyArn:
    Description: "Managed policy for DynamoDB access"
    Value: !Ref DdbTableAccessPolicy
    Export:
      Name: !Sub "${App}-${Env}-DdbAccessPolicyArn"
```
