### ISSUE TITLE
nlb listening to the port port 443/tls and 80/tcp same time ? 

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5536]
following https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb-additional-listeners  (and https://github.com/orgs/aws/projects/82?pane=issue&itemId=14249767) it seems that 1 container can listen to the port 80 and 443 at the same time... but it seems that cannot use different protocols (with a simple docker listening to the port 80)

```
nlb:
  port: 443/tls
  target_port: 80
  additional_listeners:
    - port: 80
```

error: `validate manifest against environment "dev": validate unique exposed ports: validate "nlb.additional_listeners[0]": container "web-ping" is exposing the same port 80 with protocol TCP and TLS`

ideas?
