### ISSUE TITLE
bug or feature request ? Cross-zone load balancing on NLB

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5548]
Hello

using the ALB, I can see that Copilot set "Cross-zone load balancing" while using a NLB sets it to off.

Is that a feature or a bug?

would know know how to turn it on? 

Thanks

**Comment by iamhopaul123** [comment]
Hello @sebastianovide. Sorry I don't think I follow for "Cross-zone load balancing". Can you elaborate or show me the CloudFormation template snippet that Copilot generates?

**Comment by sebastianovide** [comment]
Hi @iamhopaul123. I'm very new to CloudFormation, so I don't really know where to look. However, from the console, I can see that the NLB newly created by Copilot has "Cross-zone load balancing" turned off (apparently, it is the default for AWS). On the other hand, if the load balancer is an ALB, then the same property is on (also guessing that it is a default). Probably, I'm answering my own question: I'm guessing that the only way to turn it on is by applying a patch? (still not sure if it is as intended and therefore it would be a feature request or if instead it is a bug)

```
- op: add
  path: /Resources/PublicNetworkLoadBalancer/Properties/LoadBalancerAttributes
  value:
    - Key: load_balancing.cross_zone.enabled
      Value: true
```
