### ISSUE TITLE
How do I update sidecar to use latest image?

### ISSUE THREAD

**Issue by gabelton** [aws/copilot-cli#5554]
More of a query than an issue. I have identical sidecar config in two different apps:

```
sidecars:
  nginx:
    port: 443
    image: public.ecr.aws/uktrade/nginx-reverse-proxy:latest
    variables:
      SERVER: localhost:8000
  ipfilter:
    port: 8000
    image: public.ecr.aws/uktrade/ip-filter:latest
    variables:
      PORT: 8000
      SERVER: localhost:8080
      APPCONFIG_PROFILES: ipfilter:default:default
      IPFILTER_ENABLED: True
      EMAIL: sre@digital.trade.gov.uk
      PROTECTED_PATHS: /
  appconfig:
    port: 2772
    image: public.ecr.aws/aws-appconfig/aws-appconfig-agent:2.x
    essential: true
    variables:
      ROLE_ARN: arn:aws:iam::763451185160:role/AppConfigIpFilterRole
```
When I build and push a new ip-filter image and run `copilot svc deploy --force`, I expect to see it use the latest version of the ip-filter. It doesn't. When I add the ip-filter as a completely new sidecar, however, and deploy without forcing (`copilot svc deploy`) it sees the latest config change and pulls in that latest image. Is there some kind of caching of sidecars that I'm missing here?
