### ISSUE TITLE
Updating hosting from count: 1 to a load balanced configuration doesn't work with http.alb

### ISSUE THREAD

**Issue by joelypolly** [aws/copilot-cli#5557]
We have an existing ALB which is populated in the `http.alb` field. When used in conjunction with a load balanced hosting setup as specified below we get an error in deploying the service. Note: Deploying a single host works (`count: 1`), Target Group shows `IP` in the `Target Type` field for single host deployments.

```
deploy service service to environment beta: deploy service: check if changeset is empty: create change set copilot-ID for stack app-beta-service: ValidationError: Template error: instance of Fn::GetAtt references undefined resource TargetGroup
	status code: 400, request id: ID: describe change set copilot-dd029c74-a3e8-49fe-9802-4f1d06593d22 for stack app-beta-service: ValidationError: Stack [app-beta-service] does not exist
	status code: 400, request id: ID: describe stack: describe stack events for stack app-beta-service: ValidationError: Stack [app-beta-service] does not exist
	status code: 400, request id: ID
```

Load Balancing Config
```
    http:
      # Import the existing ownit-shared-lb
      alb: arn:aws:elasticloadbalancing:us-east-1:account:loadbalancer/app/shared-beta-lb/restofarn
    count: 
      range: 1-2
      cooldown:
        in: 60s
        out: 30s
      cpu_percentage: 70
      memory_percentage: 80
      response_time: 2s
```

**Comment by iamhopaul123** [comment]
Looks like it is related to this bug https://github.com/aws/copilot-cli/issues/5485. We are working on a patch release which shall fix this issue.

**Comment by iamhopaul123** [comment]
Hello! The fix is now released in v1.32.1: https://github.com/aws/copilot-cli/releases/tag/v1.32.1

**Comment by joelypolly** [comment]
@iamhopaul123 
Using the `v1.32.1` doesn't seem to resolve the issue. 
Same error as the original comment.
```
copilot --version
copilot version: v1.32.1
```

I delete the stack complete and ran it with the following yaml
```
  beta:
    cpu: 512 # Number of CPU units for the task.
    memory: 1024 # Amount of memory in MiB used by the task.
    platform: linux/arm64 # See https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform
    count: # Number of tasks that should be running in your service. https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count-range
      range: 1-2
      cooldown:
        in: 60s
        out: 30s
      cpu_percentage: 70
      memory_percentage: 80
      response_time: 2s
    exec: true # Enable running commands in your container.
    network:
    connect: true # Enable Service Connect for intra-environment traffic between services.
    variables:
      IS_AWS: true
      ASPNETCORE_ENVIRONMENT: Beta
    http:
      # Import the existing shared-lb
      alb: arn:aws:elasticloadbalancing:us-east-1:accountid:loadbalancer/app/shared-beta-lb/id
      path: "/"
      # Healthcheck endpoint from the SystemModule
      healthcheck:
        path: "/api/system/heartbeat"
        healthy_threshold: 2
        unhealthy_threshold: 2
        grace_period: 10s
        interval: 6s
        timeout: 5s
      deregistration_delay: 5s # Speeds up deploys
      redirect_to_https: true
      alias: "example.com"
      hosted_zone: "ZONEID"
```

**Comment by iamhopaul123** [comment]
Hello @joelypolly. You are right. I am terribly sorry about that. It is because we didn't fix the part for target group referencing the ALB metric (`response_time`) when users import ALB. Would you mind using [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) for a temporary workaround?

```yaml
- op: replace
  path: /Resources/AutoScalingPolicyALBAverageResponseTime/Properties/TargetTrackingScalingPolicyConfiguration/CustomizedMetricSpecification/Dimensions/1/Value
  value: !GetAtt TargetGroupForImportedALB.TargetGroupFullName
```

**Comment by joelypolly** [comment]
That fixed the problem. Thanks @iamhopaul123

**Comment by d-flood** [comment]
I'm experiencing a related problem. When trying to import an existing ALB into a Copilot service manifest that includes autoscaling, I get the following error:
```
✘ Proposing infrastructure changes for stack amendments-prod-amendments
✘ deploy service amendments to environment prod: deploy service: check if changeset is empty: create change set copilot-f99e579c-f5af-477e-b59c-fb58561aa26b for stack amendments-prod-amendments: ValidationError: Template error: instance of Fn::GetAtt references undefined resource TargetGroup
        status code: 400, request id: c2feacc3-42a0-464d-b45e-029c8b006127: describe change set copilot-f99e579c-f5af-477e-b59c-fb58561aa26b for stack amendments-prod-amendments: ChangeSetNotFound: ChangeSet [copilot-f99e579c-f5af-477e-b59c-fb58561aa26b] does not exist
```

The relevant portion of the service manifest:
```yaml
    count:
      cooldown:
        in: 30s
        out: 60s
      cpu_percentage: 70
      memory_percentage:
        value: 80
        cooldown:
          in: 60s
          out: 160s
      requests: 1000 # problem is here
      response_time: 3s
      range:
        min: 1
        max: 3
   ```

When I remove `requests`, the service deploys deploys and uses the imported ALB.
