### ISSUE TITLE
Add load balancer configuration: security groups

### ISSUE THREAD

**Issue by sasaki-kouhei** [aws/copilot-cli#5562]
We would like to limit requests with public and private load balancers.

For example, could it be done this way?

```
http:
  path: '/'
  healthcheck:
    path: '/'
    healthy_threshold: 2
    unhealthy_threshold: 2
    interval: 10s
    timeout: 5s
    grace_period: 300s
    success_codes: '200,301'
  redirect_to_https: true
  security_groups:
    groups:
      - sg-xxxxxxx
```

I think this would make development much more efficient as it would prevent unintentional requests, etc., and allow centralized management.
