### ISSUE TITLE
Placement in specific subnet WITH Auto-assign public IPv4

### ISSUE THREAD

**Issue by bynov** [aws/copilot-cli#5572]
Hi,

Right now I have a VPC with several subnets each in different AZ.
My goal is to launch all tasks in specific subnet (to fix inter AZ costs issue).
I'm trying to include this into my manifest:
```yaml
network:
  vpc:
    placement:
      subnets: ["subnet-xxx"]
```

This subnetID is a public subnet so I expected my tasks will have Public IPs.

Actual result:
No public IP auto assigned.

Any suggestions how I can achieve that goal?

Copilot version: v1.21.1

**Comment by bynov** [comment]
I achieved that by using overrides:

```yaml
network:
  vpc:
    placement:
      subnets: ["subnet-xxx"]
```

Override:
```yaml
- op: replace
  path: /Resources/Service/Properties/NetworkConfiguration/AwsvpcConfiguration/AssignPublicIp
  value: ENABLED
```

Would be great if anyone can tell if it could be done easier :)
