### ISSUE TITLE
Support EFS Elastic Throughput

### ISSUE THREAD

**Issue by ytanay** [aws/copilot-cli#5573]
Copilot currently creates an environment-level EFS filesystem set to Bursting throughput mode.

For some of our workloads we've seen that [Elastic Throughput](https://docs.aws.amazon.com/efs/latest/ug/performance.html#throughput-modes) is more appropriate (and it also seems to be the AWS recommended default). 

Would it be possible to expose this configuration (presumably - at the environment level)?

**Comment by Lou1415926** [comment]
@ytanay Hi! I think [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) can help you achieve it. I haven't tested this snippet but I'd imagine you'd need a patch like this:
```yaml
# In copilot/environments/overrides/cfn.patches.yml
- op: replace
  path: /Resources/FileSystem/Properties/ThroughputMode
  value: elastic
```
