### ISSUE TITLE
Specify vpc and subnet deployment within environment

### ISSUE THREAD

**Issue by chrisschaub** [aws/copilot-cli#5599]
We have an application with a qa and production environment. Each of those environments has a separate public/private vpc setup. We need to be able to deploy to both qa and production, on separate private subnets for placement. But there does not seem to be a way to specify subnet placement within environment manifests, only within application manifests ... but we can only have 1 application manifest. Is there a way to NOT specify the private subnet placement in the main manifest? That way, we could let the environment manifest specify the default placement. Thank you.

**Comment by iamhopaul123** [comment]
Hello @chrisschaub. Do you mean you want to have different placement setting for different environments for a specific application (service)? If that's the case, you can set the default placement in the service manifest and then override the setting for specific envs. For example:

```yaml
network:
  vpc:
    placement: private
environments:
  prod:
    network:
      vpc:
        placement:
          subnets: ["SubnetID1", "SubnetID2"]
```
