### ISSUE TITLE
is entrypoint working on local ?

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5619]
Hello,

I've added `entrypoint` as explained in https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#entrypoint but it is ignored completely.

Does it work ?

Thanks

**Comment by Lou1415926** [comment]
When you run `copilot svc package --output-dir infra`, do you see the configuration under `Resources.TaskDefinition.Properties.ContainerDefinitions.[-Name: <your workload name>].Entrypoint`?

I tested the ⬇️  manifest, and was able to find the configuration translated into CloudFormation correctly:
```yaml
type: Load-Balanced Web Service
entrypoint: "echo something"
```

```yaml
Resources:
  TaskDefinition:
    Properties:
      ContainerDefinitions:
        - Name: !Ref WorkloadName
          EntryPoint:
            - echo
            - something
```

**Comment by sebastianovide** [comment]
yes it does... 

```yaml
Resources: # If a bucket URL is specified, that means the template exists.
  LogGroup:
    Metadata:
      'aws:copilot:description': 'A CloudWatch log group to hold your service logs'
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/copilot/, !Ref AppName, '-', !Ref EnvName, '-', !Ref WorkloadName]]
      RetentionInDays: !Ref LogRetention
  TaskDefinition:
    Metadata:
      'aws:copilot:description': 'An ECS task definition to group your containers and run them on ECS'
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: !Join ['', [!Ref AppName, '-', !Ref EnvName, '-', !Ref WorkloadName]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref TaskCPU
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: !Ref WorkloadName
          Image: !Ref ContainerImage
          Environment:
            - Name: COPILOT_APPLICATION_NAME
              Value: !Sub '${AppName}'
            - Name: COPILOT_SERVICE_DISCOVERY_ENDPOINT
              Value: dev.mobile.local
            - Name: COPILOT_ENVIRONMENT_NAME
              Value: !Sub '${EnvName}'
            - Name: COPILOT_SERVICE_NAME
              Value: !Sub '${WorkloadName}'
          EnvironmentFiles:
            - !If
              - HasEnvFile
              - Type: s3
                Value: !Ref EnvFileARN
              - !Ref AWS::NoValue
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: copilot
          EntryPoint:
            - entrypoint-copilot.sh
```

my Dockerfile has no entrypoint and no entrypoint is executed. 

If I add 

```
ENTRYPOINT [ "./entrypoint.sh" ]
```

then the `entrypoint.sh` is executed but not the one in the copilot manifest (`entrypoint-copilot.sh`)

my `entrypoint.sh` has a 
```bash
echo "entrypoint.sh"
```

and my `entrypoint-copilot.sh` has a 
```bash
echo "entrypoint-copilot.sh"
```

I still see the `entrypoint.sh` being executed instead the `entrypoint-copilot.sh`
