### ISSUE TITLE
Sidecar can't access to DB secret

### ISSUE THREAD

**Issue by MAkcanca** [aws/copilot-cli#5639]
I'm trying to set up a simple stack with Django (load balanced), S3, and RDS/Aurorav2 (storage init), all created by copilot.
Now I want to implement certain steps like `python manage.py collectstatic` and `migrate` which are startup operations and do not need to be ran for every scaled instance. 
Collecstatic stores static/media files to S3, and migrate just runs the migrations for RDS. 
When I tested it, sidecar wasn't able to access to the database injected variable `DJANGODB_SECRET`, while main app could. It wasn't set on the sidecar.
```
sidecars:
  startup:
    essential: false
    entrypoint: ["sh","-c","python manage.py migrate && python manage.py collectstatic --noinput"]
    image:
      build: django_app/Dockerfile.copilot
    variables:
      AWS_STORAGE_BUCKET_NAME:
        from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-djangostaticBucketName
image:
  build: django_app/Dockerfile.copilot
  # Port exposed through your container to route traffic to it.
  port: 8000
  depends_on:
    startup: success
```

Another thing I noticed is I need to set variables for both main app and sidecars, sidecars did not inherit any env variables set in the root level manifest variables.

It's taking around 10 minutes to try out, deploy, fail and wait for rollback so I can't test out all the possible features, am I missing something? Is there a better way to implement this kind of behavior/pattern?

Thanks!

**Comment by KollaAdithya** [comment]
Hello @MAkcanca !

> When I tested it, sidecar wasn't able to access to the database injected variable DJANGODB_SECRET, while main app could. It wasn't set on the sidecar.

This is true. By default Copilot injects `DJANGODB_SECRET` to main container but not in case of sidecar container.


1. You can modify the `addons template` to have

```
Outputs:
  DJANGODB_SECRET:
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref myclusterAuroraSecret
    Export:
      Name: DJANGODB_SECRET
```

2. In the Service manifest you can add `DJANGODB_SECRET` as an environment variable in the sidecar container.

```
sidecars:
  startup:
    essential: false
    entrypoint: ["sh","-c","python manage.py migrate && python manage.py collectstatic --noinput"]
    image:
      build: django_app/Dockerfile.copilot
    variables:
      AWS_STORAGE_BUCKET_NAME:
        from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-djangostaticBucketName
      DJANGODB_SECRET: # exported value from the addon template
        from_cfn: DJANGODB_SECRET
```

> Another thing I noticed is I need to set variables for both main app and sidecars, sidecars did not inherit any env variables set in the root level manifest variables.

Copilot does not inherit all the variables injected in the main container to all the sidecar containers. If you want to use same `environment variables` across containers then you can use [`env-file`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#env_file)

**Comment by MAkcanca** [comment]
@KollaAdithya Thank you for your response. The examples you provided did not work for me. 
First of all, we can't use underscores in Export names so 
```
Export:
      Name: DJANGODB_SECRET
```
Produces an error, we can use a different name like `DJANGODB-SECRET`, or maybe a different output like
```
  djangodbExportedSecret:
    Description: "The secret to be exported to other stacks."
    Value: !Ref djangodbAuroraSecret
    Export:
      Name: djangodbExportedSecret
```
However, even this throws out error:
`  No export named djangodbExportedSecret found `
When used like
```
sidecars:
  startup:
    essential: false
    entrypoint: ["sh","-c","python manage.py migrate && python manage.py collectstatic --noinput"]
    image:
      build: django_app/Dockerfile.copilot
    variables:
      AWS_STORAGE_BUCKET_NAME:
        from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-djangostaticBucketName
      DJANGODB_SECRET:
        from_cfn: djangodbExportedSecret

```
So sidecars got injected with none of the outputs/exports specified for the addons/django-db.yml in app directory? 
https://aws.github.io/copilot-cli/docs/developing/addons/workload/ in here, it states that
```
# For example, the output MyTableName will be injected in capital snake case, MY_TABLE_NAME, to your task.
  MyTableName:
    Description: "The name of this DynamoDB."
    Value: !Ref MyTable
```
So can't we infer it will automatically inject/export, in capital snake case? But even if we manually specify Export with name, it doesn't inject at all. To me it's inconsistent or undocumented behavior and it makes me wonder how others use sidecars for scenarios like this.

**Comment by KollaAdithya** [comment]
@MAkcanca 
> So can't we infer it will automatically inject/export, in capital snake case? But even if we manually specify Export with name, it doesn't inject at all. To me it's inconsistent or undocumented behavior and it makes me wonder how others use sidecars for scenarios like this.


Currently with our implementation secrets outputs/exports from an addon stack are injected to main container but not to the sidecar containers. Main concern with injecting secrets to the sidecar container by default is customers might not want to expose their secrets to all containers and they want control on how to inject them.


Sorry for the previous approach, It does not work. I had a new approach which I tested and it works. Can you try this and let me know how it goes

Assuming Addon is at workload level.

1. Output the secret from addons nested stack

```
  djangodbExportedSecret:
    Description: "The secret to be exported to other stacks."
    Value: !Ref djangodbAuroraSecret
    Export:
      Name: djangodbExportedSecret
 ```
 
 2. Run command `copilot svc override --tool yamlpatch` and add the patch below
 
```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/< placeholder for a integer number to replace>
  value:
    Name: DJANGODB_SECRET
    ValueFrom: 
      Fn::GetAtt: [AddonsStack, Outputs.djangodbExportedSecret]
```
 3. Run `copilot svc deploy` to deploy the service.

**Comment by KollaAdithya** [comment]
**What should Copilot improve on this issue**

Update the documentation to reflect that only the main container will be automatically injected secrets from the exports of an addon stack but not sidecar containers.

https://aws.github.io/copilot-cli/docs/developing/addons/workload/#writing-the-outputs-section

**Comment by MAkcanca** [comment]
@KollaAdithya Thanks for your response. I also tested it, and sadly it did not work for me. DJANGODB_SECRET is None, app throws an error for sidecar.
```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Environment/-
  value:
    Name: DJANGODB_SECRET
    Value: 
      Fn::GetAtt: [AddonsStack, Outputs.djangodbExportedSecret]
```
This is added to overrides folder for django.
```
.
├── django
│   ├── addons
│   │   ├── django-db.yml
│   │   └── django-static-access-policy.yml
│   ├── overrides
│   │   └── cfn.patches.yml
│   └── manifest.yml
└── environments
    ├── addons
    │   └── django-static.yml
    └── test
        └── manifest.yml
```
Here is the folder structure. Is override correct? Or should it be in environments?

**Comment by KollaAdithya** [comment]
Hello @MAkcanca !

1. How many sidecar containers do you have in your `django` manifest ?
2. Is RDS Aurora v2 template is located at `./django/addons/django-db.yml` or `./environments/addons/django-static.yml`?
3. Can you run `copilot svc package` and verify if `DJANGODB_SECRET` is injected into sidecar?

**Comment by MAkcanca** [comment]
1. A single one, like I mentioned in the initial issue
2. Yes RDS Aurora v2 template is located in `django/addons/django-db.yml`
3. In package output, I can see that
```
                    - Name: DJANGODB_SECRET
                      Value:
                        Fn::GetAtt: [AddonsStack, Outputs.djangodbExportedSecret]
```
exists under ContainerDefinitions->Environment

and 
```

                    - Name: DJANGODB_SECRET
                      ValueFrom:
                        Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]

```
exists under ContainerDefinitions->Secrets.

Outputs for addons/django-db.yml
```

Outputs:
  djangodbSecret: # injected as DJANGODB_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref djangodbAuroraSecret
  djangodbSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref djangodbSecurityGroup
  djangodbExportedSecret:
    Description: "The secret to be exported to other stacks."
    Value: !Ref djangodbAuroraSecret
    Export:
      Name: djangodbExportedSecret
```

**Comment by KollaAdithya** [comment]
You do not need to have multiple outputs for the same secret. Can you modify the output section to

```
Outputs:
  djangodbSecret: # injected as DJANGODB_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref djangodbAuroraSecret
    Export:
      Name: djangodbSecret
  djangodbSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref djangodbSecurityGroup
```

And also modify yaml patch to add the `DJANGODB_SECRET` as secret to container instead of Environment variable.

```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/<placeholder for a integer number to replace>
  value:
    Name: DJANGODB_SECRET
    ValueFrom: 
      Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]
```

Edit: modified the yaml patch to have `ValueFrom`

**Comment by MAkcanca** [comment]
Yes, I tried both cases, with djangodbSecret and djangodbExportedSecret, thinking maybe I might be getting in the way of the copilot magic. I switched it back to your suggestion.

Now getting back to the patch, I used path `/Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/1`
and confirmed by svc package if it added it correctly, here is the result
```
                  Secrets:
                    - Name: PLACEHOLDER
                      ValueFrom: 1
                    - Name: DJANGODB_SECRET
                      Value:
                        Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]

```
Looks good, however when deploying, it fails again. 
```
  - An ECS task definition to group your containers and run them on ECS              [update failed]                        [4.4s]
    Resource handler returned message: "Model validation failed (#: extran                                                  
    eous key [Value] is not permitted)" (RequestToken: d5d9dfd8-10d5-d355-                                                  
    6e98-3256bcbc24db, HandlerErrorCode: InvalidRequest)                                                                    
```

I also monkey tested these random configs I purely made up, hoping it might just work (spoilers: didn't work)
```
- op: replace
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/0
  value: Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]
```
and 
```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/0
  value:
    DJANGODB_SECRET: Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]

```
throws
does not conform to the YAML patch document schema: yaml: line 19: mapping values are not allowed in this context

**Comment by KollaAdithya** [comment]
Sorry for the churn. I just modified the YamlPatch to have `ValueFrom` instead of `Value`

Here is the yamlpatch

```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/<placeholder for a integer number to replace>
  value:
    Name: DJANGODB_SECRET
    ValueFrom: 
      Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]
```

**Comment by MAkcanca** [comment]
Throws
```
      - [10f3cb5a]: ResourceInitializationError: unable to pull secrets or reg                                                                         
        istry auth: execution resource retrieval failed: unable to retrieve se                                                                         
        crets from ssm: service call has been retried 1 time(s): AccessDeniedE                                                                         
        xception: User: arn:aws:sts::xxx:assumed-role/django-app-test                                                                         
        -django-ExecutionRole-0GkTVxbLE8AS/10f3cb5a956e423b81737b131abd962d is                                                                         
```

**Comment by KollaAdithya** [comment]
1. Can you paste all the secrets injecting to the sidecar and main container ?
2. Can also verify whether all the secrets are tagged with `copilot-application` and `copilot-environment`. Because if you are bringing your own secrets, then they  have to be tagged.
3. Can you paste complete error message with redacted sensitive information

https://aws.github.io/copilot-cli/docs/developing/secrets/#bring-your-own-secrets

**Comment by MAkcanca** [comment]
Here are the manifest parts
```

sidecars:
  startup:
    essential: false
    entrypoint: ["sh","-c","python manage.py migrate && python manage.py collectstatic --noinput"]
    image:
      build: django_app/Dockerfile.copilot
    secrets:
      PLACEHOLDER: 1
    variables:
      AWS_STORAGE_BUCKET_NAME:
        from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-djangostaticBucketName

image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: django_app/Dockerfile.copilot
  # Port exposed through your container to route traffic to it.
  port: 8000
  depends_on:
    startup: success

variables:                    # Pass environment variables as key value pairs.
  AWS_STORAGE_BUCKET_NAME:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-djangostaticBucketName
secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
  FIREBASE_JSON_CREDENTIALS: /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/FIREBASE_JSON_CREDENTIALS  # The key is the name of the environment variable, the value is the name of the SSM parameter.
```


```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets/1
  value:
    Name: DJANGODB_SECRET
    ValueFrom:
      Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]
```

I have no problem using all these variables and setup normally, without a sidecar. Issue is within the sidecar, sidecar needs DB secrets, but cannot get it. If I remove everything related to sidecar, and keep everything as it is, it deploys without a problem. If you want me to remove the FIREBASE_JSON_CREDENTIALS secret I can try with that as well, however I don't receive any errors related to that AFAIK.

Full error when tried what you last suggested
```

  - An ECS service to run and maintain your tasks in the environment cluster                           [update in progress]                   [50.9s]
    Deployments                                                                                                                               
               Revision  Rollout        Desired  Running  Failed  Pending                                                                              
      PRIMARY  42        [in progress]  1        0        0       0                                                                                    
      ACTIVE   37        [completed]    1        1        0       0                                                                                    
    Latest 1 stopped task                                                                                                                     
      TaskId    CurrentStatus   DesiredStatus                                                                                                          
      287cc257  DEPROVISIONING  STOPPED                                                                                                                
                                                                                                                                                       
    ✘ Latest 1 task stopped reason                                                                                                   
      - [287cc257]: ResourceInitializationError: unable to pull secrets or reg                                                                         
        istry auth: execution resource retrieval failed: unable to retrieve se                                                                         
        crets from ssm: service call has been retried 1 time(s): AccessDeniedE                                                                         
        xception: User: arn:aws:sts::xxxxxx:assumed-role/django-app-test                                                                         
        -django-ExecutionRole-0GkTVxbLE8AS/287cc2577e2f4910a2865aa280d03423 is                                                                         
         not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm                                                                         
        :us-east-1:xxxxx:parameter/1 because no identity-based policy a                                                                         
        llows the ssm:GetParameters action status code: 400, request id: 6f349                                                                         
        8e6-fe3f-42cf-999a-b5fb4c0377fd                                                                                                                
                                                                                                                                                       
    Troubleshoot task stopped reason                                                                                                          
      1. You can run `copilot svc logs --previous` to see the logs of the last stopped task.                                                  
      2. You can visit this article: https://repost.aws/knowledge-center/ecs-task-stopped.                                                    
```

**Comment by KollaAdithya** [comment]
Can you remove this secret `PLACEHOLDER: 1` from the sidecar manifest section because the secret has to be from SSM parameter store or secrets manger.

And update the yaml patch to have

```
- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Secrets
  value:
    - Name: DJANGODB_SECRET
      ValueFrom: 
        Fn::GetAtt: [AddonsStack, Outputs.djangodbSecret]
```
