### ISSUE TITLE
Deploying a service changes lambda resource deployed with environment

### ISSUE THREAD

**Issue by gabelton** [aws/copilot-cli#5665]
In summary, I deploy a lambda function using a vpc configuration addon file with `copilot env deploy`. Then when I deploy a web service using `copilot svc deploy` I see that the lambda configuration has changed to use vpc resources created as part of this second command. Is this intended behaviour? The result is that after I delete my service, my lambda loses connection to the internet and then I'm blocked from deleting my env and have to manually delete a load of resources.

More detail:

In my deploy repo I have an `environments/addons/vpc.yml` file. This looks like:

```
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

  EnvironmentSecurityGroup:
    Type: String
  PrivateSubnets:
    Type: String
  PublicSubnets:
    Type: String
  VpcId:
    Type: String

Resources:
  # Secrets Manager VPC endpoint
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    # Resource based metadata block to ignore reference to resources in other addon templates. Do not remove.
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            # https://github.com/aws-cloudformation/cfn-lint/blob/main/docs/rules.md
            - E1010
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !GetAtt demodjangoPostgresDBClusterSecurityGroup.GroupId
        - !GetAtt demodjangoRdsPostgresSecurityGroup.GroupId
        - !Ref EnvironmentSecurityGroup
      ServiceName: 'com.amazonaws.eu-west-2.secretsmanager'
      SubnetIds: !Split [ ",", !Ref PrivateSubnets ]
      VpcEndpointType: Interface
      VpcId: !Ref VpcId

  AdditionalNatGatewayAttachment1:
    Metadata:
      'aws:copilot:description': 'An Elastic IP for an additional NAT Gateway 1'
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AdditionalNatGatewayAttachment2:
    Metadata:
      'aws:copilot:description': 'An Elastic IP for an additional NAT Gateway 2'
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AdditionalNatGateway1:
    Metadata:
      'aws:copilot:description': 'Additional NAT Gateway 1'
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt AdditionalNatGatewayAttachment1.AllocationId
      SubnetId: !Select [ 0, !Split [ ",", !Ref PublicSubnets ] ]
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-Additional-NAT-Gateway-1'

  AdditionalNatGateway2:
    Metadata:
      'aws:copilot:description': 'Additional NAT Gateway 2'
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt AdditionalNatGatewayAttachment2.AllocationId
      SubnetId: !Select [ 1, !Split [ ",", !Ref PublicSubnets ] ]
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-Additional-NAT-Gateway-2'

  AdditionalPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId

  AdditionalPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId

  AdditionalPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AdditionalPrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref AdditionalNatGateway1

  AdditionalPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AdditionalPrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref AdditionalNatGateway2

  AdditionalPrivateRouteTable1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AdditionalPrivateRouteTable1
      SubnetId: !Select [ 0, !Split [ ",", !Ref PrivateSubnets ] ]

  AdditionalPrivateRouteTable2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AdditionalPrivateRouteTable2
      SubnetId: !Select [ 1, !Split [ ",", !Ref PrivateSubnets ] ]
```

Meanwhile in the same env addons folder I have a postgres db addon featuring my lambda function:

```
demodjangoPostgresLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-${Env}-aurora-create-user"
      Handler: index.handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:eu-west-2:763451185160:layer:python-postgres:1
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt demodjangoPostgresLambdaFunctionExecutionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref demodjangoPostgresDBClusterSecurityGroup
        SubnetIds: !Split [ ",", !Ref PrivateSubnets ]
      Code:
        # code not included
```

I also have an `addons.parameters.yml` file in the same folder:
```
Parameters:
  EnvironmentSecurityGroup: !Ref EnvironmentSecurityGroup
  DefaultPublicRoute: !Ref DefaultPublicRoute
  InternetGateway: !Ref InternetGateway
  InternetGatewayAttachment: !Ref InternetGatewayAttachment
  PrivateSubnets: !Join [ ',', [ !Ref PrivateSubnet1, !Ref PrivateSubnet2, ] ]
  PublicRouteTable: !Ref PublicRouteTable
  PublicSubnet1RouteTableAssociation: !Ref PublicSubnet1RouteTableAssociation
  PublicSubnet2RouteTableAssociation: !Ref PublicSubnet2RouteTableAssociation
  PublicSubnets: !Join [ ',', [ !Ref PublicSubnet1, !Ref PublicSubnet2, ] ]
  VpcId: !Ref VPC
```

When env is first deployed (before service is deployed) PrivateSubnet1 and PrivateSubnet2 (part of env parent stack) connect to AdditionalNatGateway1 and AdditionalNatgateway2 via AdditionalPrivateRoute1 and AdditionalPrivateRoute2 (all part of addons stack)

After deploying the service, the private subnets connect to NatGateway1 and NatGateway2 (part of the main demodjango-gabe env stack rather than env addons stack) via PrivateRoute1 and PrivateRoute2 (also part of main env parent stack)

After deleting the service (and before deleting the env) the lambda uses PrivateSubnet1 and PrivateSubnet2 (part of the env parent stack) and these are no longer connected to a nat gateway.

After manually adding the AdditionalPrivateRoute1 to the lambda subnets, recreating the original setup before a service is deployed, I am able to delete the env without an issue.

Do you have any idea why this is happening and if I can prevent it? I would prefer to just keep the env and svc resources independent of one another, to make it easier to delete services and environments via the `delete` commands, rather than through AWS console

**Comment by KollaAdithya** [comment]
Hello again @gabelton!

I'll help you understand why this was happening.

Copilot utilizes a custom resource called [**env-controller.js**](https://github.com/aws/copilot-cli/blob/mainline/cf-custom-resources/lib/env-controller.js), which updates environment stack resources shared across workloads. In this case, when deleting the workload stack triggers the environment to remove the [`NATWorkloads`](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/environment/cf.yml#L21) parameter from environment stack

Here's the sequence of events:

1. Deleting the workload stack triggers the `env-controller.js` lambda function with a delete event.
2. `env-controller.js` lambda function then causes an update to the environment stack.
3. The update to the environment stack leads to the [deletion of resources](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/environment/partials/nat-gateways.yml) like `Natgateway` and `PrivateRoutetable`, which are part of the main environment stack.
4. This is the reason why the lambda (addons) doesn't have a `Natgateway` attached created as part of parent environment stack.

**Workaround:**

One approach to address this issue is to move the lambda function to a workload level as an addon. For example, you can create a addon file `lbws/addons/lambda.yml`.

You need to modify lambda function a little bit to import the private subnets and security groups that are exported from a environment stack

``` 
demodjangoPostgresLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-${Env}-aurora-create-user"
      Handler: index.handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:eu-west-2:763451185160:layer:python-postgres:1
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt demodjangoPostgresLambdaFunctionExecutionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue <replace with name of the export of securitygroup>
        SubnetIds: !Split [ ",", !ImportValue <replace with env stack name>-PrivateSubnets ]
      Code:
        # code not included 
```


In this way, both the service and lambda will be deleted at the same time, preventing unnecessary errors such as **cloudformation drift for addons resouces** when deleting the environment.

**Comment by gabelton** [comment]
Thanks v much for this @KollaAdithya . So can I check is there no way to ensure that my lambda uses the resources in my `vpc.yml` file even after deploying the service? I'd prefer to try and keep it as part of my postgres env addon file, as the lambda includes logic for creating a postgres application user:

```
demodjangoPostgresApplicationUser:
    Type: 'Custom::demodjangoPostgresApplicationUser'
    DeletionPolicy: !FindInMap [demodjangoPostgresEnvironmentConfigMap, !Ref Env, DeletionPolicy]
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !GetAtt 'demodjangoPostgresLambdaFunction.Arn'
      CopilotApplication: !Sub "${App}"
      CopilotEnvironment: !Sub "${Env}"
      MasterUserSecret: !Ref demodjangoPostgresAuroraSecret
      SecretDescription: !Sub Aurora application user secret for ${AWS::StackName}
      SecretName: !Sub '/copilot/${App}/${Env}/secrets/DEMODJANGO_POSTGRES_APPLICATION_USER'
      DefaultPublicRoute: !Ref DefaultPublicRoute
      InternetGateway: !Ref InternetGateway
      InternetGatewayAttachment: !Ref InternetGatewayAttachment
      PublicRouteTable: !Ref PublicRouteTable
      PublicSubnet1RouteTableAssociation: !Ref PublicSubnet1RouteTableAssociation
      PublicSubnet2RouteTableAssociation: !Ref PublicSubnet2RouteTableAssociation
      Snapshot: !If [demodjangoPostgresUseSnapshot, !FindInMap [demodjangoPostgresEnvironmentConfigMap, !Ref Env, SnapshotIdentifier], ""]
    # Resource based metadata block to ignore reference to resources in other addon templates. Do not remove.
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            # https://github.com/aws-cloudformation/cfn-lint/blob/main/docs/rules.md
            - E3005
    DependsOn:
      - VpcEndpoint
      - demodjangoPostgresDBWriterInstance
      - AdditionalNatGateway1
      - AdditionalNatGateway2
      - AdditionalPrivateRoute1
      - AdditionalPrivateRouteTable1
      - AdditionalPrivateRouteTable1Association
      - AdditionalPrivateRoute2
      - AdditionalPrivateRouteTable2
      - AdditionalPrivateRouteTable2Association
      - demodjangoPostgresSecretAuroraClusterAttachment
      - demodjangoPostgresEnvironmentIngress
      - demodjangoPostgresSecretsManagerIngress
      - demodjangoPostgresLambdaIngress
      - demodjangoPostgresSecretsManagerEgress
      - demodjangoPostgresLambdaEgress
      - demodjangoPostgresHTTPSEgress
      - demodjangoPostgresKeyAlias
```
