### ISSUE TITLE
`http.alias` domain unreachable after deployment

### ISSUE THREAD

**Issue by cworksbrian** [aws/copilot-cli#5671]
This is a follow-up issue from #5661. Because the scope of the problem is quite different, I have opened this as a separate issue.

I am attempting to use [`http.alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) to specify a test domain created in Route 53 for a Load-Balanced Web Service. However, attempting to reach the service via `curl` produced the following error: `(6) Could not resolve host`. I took a number of steps to confirm the issue, waiting at least 72 hours to rule out a delay in DNS propagation and attempting a `curl` request using Google's 8.8.8.8/8.8.4.4 DNS servers. I also attempted to access the service via a browser instead, but nothing was able to establish a connection with the domain.

Investigating the issue, I discovered that `dig` reported an SOA record for the domain, but not an A record. I confirmed via contact with AWS Support that no A record exists for the corresponding hosted zone, preventing the domain from being reached. However, I also observe that a CNAME record does exist in the hosted zone.

DNS is not my specialty, and I am not sure why Copilot would forgo creating an A record when deploying a service. Is there any explanation as to why this behavior occurs; any option I missed? Is the lack of an A record even the issue here? In the web console, AWS itself suggests creating a CNAME record to connect to the ALB instead of an A record, but even though a CNAME record appears to exist, I am unable to resolve the domain.

**Comment by KollaAdithya** [comment]
Hello @cworksbrian !

Do you use [imported certificates](https://aws.github.io/copilot-cli/docs/developing/domain/#use-domain-in-your-existing-validated-certificates) in your environment manifest ?

```
http:
  public:
    certificates:
      - arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
```

If this is the case, can you modify your workload manifest to have [`hosted_zone`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-hosted-zone) field so that Copilot adds the A-record to the hostedzone pointing to load balancer.

```
# in copilot/{service name}/manifest.yml
http:
  path: '/'
  alias: example.com
  hosted_zone: Z0873220N255IR3MTNR4
```
