### ISSUE TITLE
Specifying multiple storage volumes always results in changes when deploying

### ISSUE THREAD

**Issue by mattnenterprise** [aws/copilot-cli#5691]
If you specify multiple volumes like the following in your manifest anytime you deploy there will be changes.
```
storage:
      volumes:
       v1:
          path: "/path1"
          read_only: false
          efs:
            id: fs-someid
        v2:
          path: "/path2"
          read_only: false
          efs:
            id: fs-someid2
        v3:
          path: "/path3"
          read_only: false
          efs:
            id: fs-someid3
        v4:
          path: "/path4"
          read_only: false
          efs:
            id: fs-someid4
```

If you then run something like `copilot svc deploy --env prod --diff` you will get a diff where it just moves things around in the CloudFormation template. I think this is due to the fact that the volumes are represented as a map in the code and iteration order of maps is random in Go.
