### ISSUE TITLE
Does copilot scheduled job support map type

### ISSUE THREAD

**Issue by jhtann** [aws/copilot-cli#5697]
Currently, the copilot job only support `string` type which must be one of 'public' or 'private'. However, we have the need to specify the subnets as what the Copilot backend service is. 

Would appreciate it if this were added to the roadmap!

link -> https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/

**Comment by Lou1415926** [comment]
oops `network.vpc.placement.subnets` is actually supported! The documentation is out-of-date. Thanks for bringing this to our attention. Try it out and let me know if it works for you!

**Comment by jhtann** [comment]
tried, seem cannot :(

we use copilot version: v1.33.1

the manifest:
```
type: Scheduled Job

network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  vpc:
    # placement: private # THIS will be replaced using patch overrides to value due to Job not supported subnets MAP type
    placement:
      subnets: ["SubnetID1", "SubnetID2"]
```

the error we got:
```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnStateMachineProps"
  definitionSubstitutions: element 'Subnets': ["SubnetID1","SubnetID2"] should be a string.
```

looks like the value not escaped
