### ISSUE TITLE
AWS COPILOT | SVC DEPLOY | ALIAS

### ISSUE THREAD

**Issue by astrokathi** [aws/copilot-cli#5701]
**copilot version: v1.33.1**

I am facing an issue related to the SSL certificate, I have imported the certificate into AWS Certificate manager and obtained an ARN as per the documentation.
The domains listed under the certificate are:
`*.example.com` and `example.com` - (2)

I have a environment manifest file located under copilot/environments/test/manifest.yml
```
name: test
type: Environment
# Import your own VPC and subnets or configure how they should be created.
# network:
#   vpc:
#     id:

# Configure the load balancers in your environment, once created.
http:
 public:
   certificates:
     - arn:aws:acm:us-east-1:XXXXXXXXX:certificate/XXXXXXXXX
```

I have executed the following commands

```
copilot env init
```

My service manifest is as follows:

```
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  healthcheck:
    path: '/'     # The protocol to use for health checks (HTTP or HTTPS).
    port: 8761
    success_codes: '200'
    interval: 30s         # The interval (in seconds) between health checks.
    timeout: 29s           # The number of consecutive failed health checks required before considering the target unhealthy.
    start_period: 0s       # The amount of time (in seconds) to wait before performing the first health check.
    healthy_threshold: 2
    unhealthy_threshold: 9

  alias:
    - name: 'subdomain.example.com'
```

I am getting the following error when I try to deploy the service.
```
copilot svc deploy
```

Error:

Please use aliases that are protected by 1 certificate your imported:
"arn:aws:acm:us-east-1:XXXXXXXXX:certificate/XXXXXXXXX": *.example.com , example.com

✘ deploy service service-registry to environment test: validate ALB runtime configuration for "http": validate aliases against the imported public ALB certificate for env test: subdomain.example.com is not a valid domain against arn:aws:acm:us-east-1:XXXXXXXXX:certificate/XXXXXXXXX

Could I know, how to resolve this issue.

Thanks,
Kathi
