### ISSUE TITLE
Support for exporting multiple ports

### ISSUE THREAD

**Issue by al-dpopowich** [aws/copilot-cli#5707]
When defining a service or sidecar you can only configure a single port for export. For example, with the following manifest, other services can connect to `compute:9000` (using `Service Connect`):

```yaml
name: compute
type: Backend Service

image:
   build: ./compute/Dockerfile
   port: 9000

network:
   connect: true
```

But if the image actually publishes two (or more) ports one needs to jump through hoops to expose the other port(s).  Let's say the above  Dockerfile has:

```dockerfile
EXPOSE 9000
EXPOSE 9001
```

The only way to allow intra-service communication on port `9001` is by adding a yaml patch or by configuring an internal ALB/NLB (see #5702).

Proposal:

Deprecate `image.port` and `sidecars.<name>.port` in favor of:
```
ports - Array of Integer

sidecars.<name>.ports - Array of Integer
```

To be clear: I'm suggesting deprecating `image.port` in favor of a top-level `ports` property.

Two reasons:

1. The plural is more descriptive.
2. This fixes the current asymmetry of where ports are defined, on the main image vs the sidecars.  Also, this is more in keeping with a docker-compose view of the world where the image definition (location of, or how to build) and the exposed port(s) definition are both properties of the service.

The above manifest can look like this:

```yaml
name: compute
type: Backend Service

image:
      build: ./compute/Dockerfile
      
ports: [9000, 9001]

network:
   connect: true
```
