### ISSUE TITLE
got an error when delete static site

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#5711]
Hello!
I'm using static site and add a s3 bucket to store output of Athena.
Got an error when trying to delete svc.

> clean resources: get bucket name: more than one S3 bucket with tags "copilot-application"="my-app","copilot-environment"

here is part of my addons

```yaml
Resources:
  # other stuffs
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub
        - '${App}-${Env}-athena-result-bucket-${BucketNameSuffix}'
        - BucketNameSuffix: !Select [ 0, !Split [ "-", !Select [ 2, !Split [ "/", !Ref AWS::StackId ] ] ] ]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

copilot version: 1.33.1
