### ISSUE TITLE
unmarshal manifest for Load Balanced Web Service: unmarshal "variables": cannot unmarshal field to a string or into a map

### ISSUE THREAD

**Issue by richardgavel-ordinaryexperts** [aws/copilot-cli#5731]
I think either the string interpolation capability or an update to it broke something. The following, which is considered value YAML, no longer works and results in the error specified in the title:

Unfortunately, this is causing an issue because I need >= 1.29.0 to take in a fix when a env cluster has been deleted and recreated. But I can't because the interpolation was included before that.

```
environments:
  dev:
    http:
      healthcheck:
        timeout: 10s

    variables:
      STAFF_EMAILS: '["me@gmail.com"]'
```

**Comment by KollaAdithya** [comment]
Hello @richardgavel-ordinaryexperts !

Can you update the manifest to have the below config so that it will skip interpolation at variables.
```
environments:
  dev:
    http:
      healthcheck:
        timeout: 10s
variables:
  STAFF_EMAILS: | 
    ["me@gmail.com", "ak@gmail.com"]
```
