### ISSUE TITLE
Auto scaling not enabled when deployed via copilot

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5742]
I tried to enable autoscaling using the info from documentation but the autoscaling was not enabled.

```
name: dashboard
type: Load Balanced Web Service
environments:
  dev:
    http:
      path: '/'
      healthcheck: '/healthcheck'
    image:
      build: Dockerfile.dev
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count:
      range: 1-10
      cooldown:
        in: 30s
        out: 60s
      cpu_percentage: 10
      requests: 30
      response_time: 30s
    exec: true
    network:
      vpc:
        placement:
          subnets: ["xx"]
      connect: true
  uat:
    http:
      path: '/'
      healthcheck: '/healthcheck'
    image:
      build: Dockerfile.uat
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count: 1
    exec: true
    network:
      vpc:
        placement:
          subnets: ["xx"]
      connect: true
  prod:
    http:
      path: '/'
      healthcheck: '/healthcheck'
    image:
      build: Dockerfile.prod
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count: 1
    exec: true
    network:
      vpc:
        placement:
          subnets: ["xx"]
      connect: true

```
