### ISSUE TITLE
Access Denied when trying to update S3 Public Access

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5746]
I just added this to my environment addon for managing my s3 bucket and I get access denied (which is particularly weird since this access key created this bucket). 

```
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false 
        RestrictPublicBuckets: false 
```

I've tried explicitly adding this to the copilot generated execution role that appears to be used during an `env deploy` but it doesn't change anything:
```
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutBucketPublicAccessBlock"
            ],
            "Resource": "*"
        }
```
I think this is directly related to [this ticket](https://github.com/aws/copilot-cli/issues/1345), it's just generally unclear what permissions should be for the IAM user who's access key we're using (docs say not to use root but offer no other details) or these copilot generated execution roles.
