### ISSUE TITLE
Environment Specific Patches?

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5747]
Not sure if this is a feature request or just a question, but I'm trying to figure out how to implement different patches per environment or at least set parameters/variables per environment?

For example, if I have a staging and production environment how can I add this patch such that it doesn't get added to both load balancers or at least has slightly different values for each environment?
```
- op: add
  path: /Resources/HTTPSListenerRuleRedirect
  value:
    Metadata:
        'aws:copilot:description': 'An HTTPS listener redirect rule'
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            Host: 'production.com'
            Path: '/foo'
            Query: '#{query}'
            StatusCode: HTTP_301
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - production.org
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /
      Priority: 40000
      ListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
```
