### ISSUE TITLE
Support triggers in CodePipeline

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#5751]
CodePipeline recently introduced support for triggers and execution modes: [codepipeline-trigger-filters-execution-modes](https://aws.amazon.com/about-aws/whats-new/2024/02/codepipeline-trigger-filters-execution-modes/)

codepipeline created via copilot today is triggered for any file change in repository. 
Triggers gives us bit more control over when the build triggers. One of the feature we are interested in is the ability to ignore build when specific files change.

Please support triggers in codepipeline.
As v2 pipeline cost is based on action executions, it would be good to still let users create v1 pipelines if they want to.

p.s. Copilot YAML Patch Overrides can be used to add the triggers for now.

**Comment by leon-xz** [comment]
It would be great if copilot can configure pipeline trigger in manifest file. Right now I have workaround using 'pipeline override'. Below yamlpatch override works for me, it triggers the 'Environments' pipeline only when there is change in 'copilot/environments/'

```
- op: add
  path: /Resources/Pipeline/Properties/PipelineType
  value: V2

- op: add
  path: /Resources/Pipeline/Properties/Triggers
  value:
    - ProviderType: CodeStarSourceConnection
      GitConfiguration:
        Push:
          - Branches:
              Includes:
                - main
            FilePaths:
              Includes:
                - copilot/environments/**
        PullRequest:
          - Branches:
              Includes:
                - main
            FilePaths:
              Includes:
                - copilot/environments/**
            Events:
              - CLOSED
        SourceActionName: SourceCodeFor-hello
```
