### ISSUE TITLE
alias not working with imported certificate

### ISSUE THREAD

**Issue by sri-sp** [aws/copilot-cli#5773]
1. I have obtained a certificate in PFX format, which I converted to PEM encoded format successfully.

2. I imported the PEM certificate into AWS Certificate Manager (ACM) using OpenSSL, following the steps outlined in [this AWS blog post](https://aws.amazon.com/blogs/security/how-to-import-pfx-formatted-certificates-into-aws-certificate-manager-using-openssl/#:~:text=To%20import%20the%20certificates%20Open%20the%20ACM%20console.,the%20Get%20started%20button.%20Select%20Import%20a%20certificate.).

3. I added the certificate to my environment and deployed the application using the Copilot command copilot env deploy.

4. However, I am unable to access the application via HTTPS. It throws an insecure HTTPS error when I try to access it.

here is my manifest file 

```yaml
name: web
type: Load Balanced Web Service

http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'
  healthcheck:
    path: '/'
    success_codes: '200,301'
    healthy_threshold: 3
    unhealthy_threshold: 2
    interval: 6s
    timeout: 5s
    grace_period: 598s
  deregistration_delay: 5s
  stickiness: false
  alias: ["staging.***********.com", "my.staging.**********.com"]
  # Add this to setup a proxy target container
  target_container: proxy-443-8080

sidecars:
  proxy-443-8080:
    port: 443
    image: ************.dkr.ecr.us-east-1.amazonaws.com/stage/proxy-443-8080:latest


alb:
  port: 443/tls


  

# Configuration for your containers and service.
image:
  location: ***********.dkr.ecr.us-east-1.amazonaws.com/stage-web-imagerepository-ubqp:latest
  # Port exposed through your container to route traffic to it.
  port: 8080

cpu: 1024       # Number of CPU units for the task.
memory: 2048    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

network:
  vpc:
    placement: private
```

====================

Any help or insights into resolving this HTTPS error would be highly appreciated.
