### ISSUE TITLE
Updated pipeline after added service is not working

### ISSUE THREAD

**Issue by faisalil** [aws/copilot-cli#5793]
- I am adding a new backend service to the aws-copilot managed app that I have. 
- I did `copilot pipeline deploy` to recreate the pipeline so the new service gets deployed going forward.
- when I tried to run the build, it failed with the error
```
[Container] 2024/04/25 03:17:00.424193 Phase complete: DOWNLOAD_SOURCE State: FAILED
[Container] 2024/04/25 03:17:00.424206 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime named 'docker'. This build image has the following runtimes: dotnet, golang, java, nodejs, php, python, ruby
```
- Based on this, and after few trials, I updated the `buildspec.yml` from:
```
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.24.0
      - mv ./copilot-linux-v1.24.0 ./copilot-linux
      - chmod +x ./copilot-linux
      .....
```
to 
```
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.24.0
      - mv ./copilot-linux-v1.24.0 ./copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - echo "Run your tests"
      # - make test
```
- The issue is that the pipeline is now failing the build step and the failures have no error message or way to understand what is going on. Here is the log that I see. Note that everything was working fine before I tried to recreate/deploy the pipeline. 
 
```
#16 123.5 408:13  Warning: 'seedIds' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
#16 123.5 432:13  Warning: 'seedIds' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
#16 123.5 
#16 123.5 ./lib/apolloClient.ts
#16 123.5 129:43  Warning: 'forward' is defined but never used. Allowed unused args must match /^_/u.  @typescript-eslint/no-unused-vars
#16 123.5 
#16 123.5 ./lib/withApollo.tsx
#16 123.5 186:32  Warning: 'finished' is deprecated. Use `writableEnded` instead.  deprecation/deprecation
#16 123.5 
#16 123.5 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#16 123.5    Creating an optimized production build ...
#16 292.6 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#16 292.6 error Command failed with signal "SIGKILL".
#16 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
------
 > [builder 5/5] RUN yarn build:
123.5 ./lib/apolloClient.ts
123.5 129:43  Warning: 'forward' is defined but never used. Allowed unused args must match /^_/u.  @typescript-eslint/no-unused-vars
123.5 
123.5 ./lib/withApollo.tsx
123.5 186:32  Warning: 'finished' is deprecated. Use `writableEnded` instead.  deprecation/deprecation
123.5 
123.5 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
123.5    Creating an optimized production build ...
292.6 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
292.6 error Command failed with signal "SIGKILL". 
------
Dockerfile:51
--------------------

```
