### ISSUE TITLE
How to open up a port 22 apart from port 80?

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5810]
I would like to open up port 22 for a Whitebox VA scanning. What is the best way to achieve it? 

Right now, I am getting no response in ssh

<img width="392" alt="image" src="https://github.com/aws/copilot-cli/assets/60873542/e47ea028-d220-4fc3-8df5-97272cf9be89">

Below is my manifest file:

```
name: fulfillment-api
type: Load Balanced Web Service

environments:
  dev:
    http:
      path: '/'
      healthcheck: '/api/healthcheck'
    image:
      build: Dockerfile.dev
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count: 1
    exec: true
    network:
      vpc:
        placement:
          subnets: ["ccc"]
      connect: true
  uat:
    http:
      path: '/'
      healthcheck: '/api/healthcheck'
    image:
      build: Dockerfile.uat
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count: 1
    exec: true
    network:
      vpc:
        placement:
          subnets: ["bbb"]
      connect: true
  prod:
    http:
      path: '/'
      healthcheck: '/api/healthcheck'
    image:
      build: Dockerfile.prod
      port: 80
    cpu: 256
    memory: 512
    platform: linux/x86_64
    count: 1
    exec: true
    network:
      vpc:
        placement:
          subnets: ["aaa"]
      connect: true

```
