### ISSUE TITLE
Question: How can I use "variables"  to substitute commands in "command" property?

### ISSUE THREAD

**Issue by takaesu-junya** [aws/copilot-cli#5840]
Thank you all for the hard work to maintain such an great project!
I have been using aws copilot for years now and I really appreciate the tool.

Kindly, I have a question.

I have a copilot manifest file as below.

```yaml
name: maxscale-svc
type: Backend Service

command: ["/wait-for-it.sh", "${MYSQL_SERVER_IP}:3306", "-t", "0", "--", "/bin/sh", "-c", "maxscale-start && monit -I"]

variables:
  MYSQL_SERVER_IP: mysql-svc.${COPILOT_ENVIRONMENT_NAME}.${COPILOT_APPLICATION_NAME}.local
```

NOTE: I omitted things that are irrelevant to the topic.

I tried to connect maxscale server to mysql server both of which are containers run by ecs fargate which is provisioned by copilot cli.

But the problem is that, `MYSQL_SERVER_IP` is read from the environment variables which reside on my computer. I want it to read the value from the 'variables' property of the manifest file.

Is there any way to achieve what I want?

**Comment by huanjani** [comment]
Hi, @takaesu-junya! Thank you for the kind words. 
[This response](https://github.com/aws/copilot-cli/issues/5480#issuecomment-1813339483) from my teammate may help you.

**Comment by takaesu-junya** [comment]
@huanjani 

Thank you for pointing me to the comment. I guess using secret and pulling the value manually is kind of tedious for me.

And I have also confliction between environment variables for the one used only in my shell and the other that is needed for copilot deploying to ecs.  

I'm just going from this:

```yaml
name: maxscale-svc
type: Backend Service

command: ["/wait-for-it.sh", "${MYSQL_SERVER_IP}:3306", "-t", "0", "--", "/bin/sh", "-c", "maxscale-start && monit -I"]

variables:
  MYSQL_SERVER_IP: mysql-svc.${COPILOT_ENVIRONMENT_NAME}.${COPILOT_APPLICATION_NAME}.local
```

to this for now.

```yaml
name: maxscale-svc
type: Backend Service

### I decided to use hard code for the mysql host value here instead of using ${MYSQL_SERVER_IP}.  ###
command: ["/wait-for-it.sh", "mysql-svc.${COPILOT_ENVIRONMENT_NAME}.${COPILOT_APPLICATION_NAME}.local:3306", "-t", "0", "--", "/bin/sh", "-c", "maxscale-start && monit -I"]

variables:
  MYSQL_SERVER_IP: mysql-svc.${COPILOT_ENVIRONMENT_NAME}.${COPILOT_APPLICATION_NAME}.local
```
