### ISSUE TITLE
Alternate Domain Names not being set on Cloudfront

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5859]
### Description:
I added a `cdn` to an existing deployment, it's being created just fine, the SSL certificate is working, but there are no domain names being added to the Alternate Domain Names and as such nothing resolves properly. If I add them manually it works. I've tried specifying an `http.alias` section explicitly in the `env` manifest but it makes no difference. Is this expected behavior to add these manually? I would have thought it would add the alias' defined in the http services. 

## Environment Manifest:
```
name: staging
type: Environment

cdn:
    certificate: arn:aws:acm:us-east-1:<redated>:certificate/a0fe4117-8d5f-4e17-a82e-67f09ddea510
    terminate_tls: true

http:
    alias:
        - '${COPILOT_ENVIRONMENT_NAME}.example.com'
        - '${COPILOT_ENVIRONMENT_NAME}.foo.example.com'
    public:
        ingress:
            cdn: true

observability:
    container_insights: true # Enable CloudWatch Container Insights for your environment.
```
