### ISSUE TITLE
[Feature Request] Support deploy a Copilot svc in different environment with different svc configuration

### ISSUE THREAD

**Issue by leon-xz** [aws/copilot-cli#5883]
### Describe your idea/feature/enhancement

It's very common to create a ECS service (eg. mysvc) in different workload environments with different configurations (eg. container specs, number of containers, image tags). I cannot find a easier way to have different svc manifest or cloudformation for different environments. the override feature seems apply to all environments. I end up have to create different services (eg. mysvc-dev, mysvc-qa, mysvc-stag, mysvc-prod) for different environment, and set 'network.connect.alias' to 'mysvc' so that the service maintain the unified internal name in different environment. 

It would be great if Copilot allow us to have different svc configuration for different environments.

### Proposal

two options I can think of

1. support having different svc manifest files for different environments. for example `copilot svc init -n mysvc -e qa,prod` to create extra manifest files for qa and prod environments.

mysvc
          - manifest.yml
          - manifest.qa.yml
          - manifest.prod.yml

2. support override the cloudformation for specific environment

### Additional Details

**Comment by Haren7** [comment]
Please explain how this can be done

**Comment by leon-xz** [comment]
turn out service manifest already support environment specific override. therefore no need to have separate svc manifest for different environments. Here is a sample

```
# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: hello-whale
type: Load Balanced Web Service
# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'
# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build: app/hello-whale/Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80
cpu: 256 # Number of CPU units for the task.
memory: 512 # Amount of memory in MiB used by the task.
count: 1 # Number of tasks that should be running in your service.
exec: true # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  vpc:
    placement: private

environments:
  dev:
    observability:
      container_insights: true
  prod:
    count:
      range:
        min: 2
        max: 5
        spot_from: 3
      cpu_percentage: 80
      memory_percentage: 80
```
