### ISSUE TITLE
[Bug]: Error unmarshalling when variable contains a string of a string array

### ISSUE THREAD

**Issue by CharlieDigital** [aws/copilot-cli#5907]
### Description:

Receiving the following error when using an environment variable which is a string of a string array (JSON array string)

Possibly related: 

- #1120 
- #1292

```
unmarshal manifest for Load Balanced Web Service: unmarshal "variables": cannot unmarshal field to a string or into a map
```

### Details:

Per Neo4j documentation, the environment variable `NEO4J_PLUGINS` accepts a value which is a string like so:

```shell
docker run -it --rm \
  --publish=7474:7474 --publish=7687:7687 \
  --env NEO4J_AUTH=none \
  --env NEO4J_PLUGINS='["apoc", "graph-data-science"]' \
  neo4j:5.22.0
```

See: https://neo4j.com/docs/operations-manual/current/docker/plugins/

When specifying this as a variable in `manifest.yaml`:

```yaml
variables:
  NEO4J_apoc_export_file_enabled: true
  NEO4J_apoc_import_file_enabled: true
  NEO4J_apoc_import_file_use__neo4j__config: true
  NEO4J_PLUGINS: '["apoc", "apoc-extended", "graph-data-science"]'
  NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*,algo.*,spatial.*
  NEO4J_server_directories_neo4j__home: /var/efs/neo4j 
```

Yields the error as described.

### Observed result:

```
➜  neo4j-poc git:(main) ✗ copilot svc deploy \
  --app neo4j-poc \
  --name neo4j-db \
  --env beta
✘ unmarshal service neo4j-db manifest: unmarshal manifest for Load Balanced Web Service: unmarshal "variables": cannot unmarshal field to a string or into a map
```

### Expected result:

The environment variable is set as expected.

### Debugging:

Commenting out this line allows the container to be deployed, but with this line uncommented, the deploy fails during unmarshalling of the config.
