### ISSUE TITLE
[Feature Request]: Ability to add custom Tags at the Environments level 

### ISSUE THREAD

**Issue by libert-xyz** [aws/copilot-cli#5914]
### Describe your idea/feature/enhancement

For billing and cost allocation purposes we want to be able to add custom tags in the Environments.

### Proposal

Currently the Environments only sets two custom tags

```Tags

  Key                  Value
  ---                  -----
  copilot-application  my-app
  copilot-environment  staging
```

We want to be able to add a custom tag in the `manifest.yml` file

something like

```
name: staging
type: Environment
http:
  hosted_zone: ZNZO1xxxx
  public:
    certificates:
      - arn:aws:acm:xxxx
network:
  vpc:
    id: vpc-xxxx
    subnets:
      public:
        - id: subnet-xxxx
        - id: subnet-xxxx
      private:
        - id: subnet-xxxx
        - id: subnet-xxxx
## Custom tags
tags:
  Company: ACME
```
