### ISSUE TITLE
[Feature Request]: Configure SSL policy of the CDN (cdn.ssl_policy)

### ISSUE THREAD

**Issue by alquerci** [aws/copilot-cli#5932]
Hello there,

Big thanks for this tool.

version 1.34.0

### Describe your feature

In order to configure SSL policy of the CDN.

I wish Copilot would avoid us to patch the environment template.

This will save us time in setting up.
And having SSL polices in one file.

### Proposal

Like #1342 for ALB.

```yaml
# copilot/environments/<name>/manifest.yml
cdn:
  ssl_policy: TLSv1.2_2019
```

### Actual workaround

Now we need to have knowledge or search on documentation to do it. And the result will be this override:

```yaml
# copilot/environments/overrides/cfn.patches.yml
- op: add
  path: /Resources/CloudFrontDistribution/Properties/DistributionConfig/ViewerCertificate/MinimumProtocolVersion
  value: TLSv1.2_2019
```
