### ISSUE TITLE
Misleading Doc: On sidecars, the depends_on attributes is not on image attribute

### ISSUE THREAD

**Issue by alquerci** [aws/copilot-cli#5945]
### Actual

On the doc
https://aws.github.io/copilot-cli/docs/developing/sidecars/#image-depends-on

```yaml
image:
  build: ./Dockerfile
  depends_on:
    nginx: start
    startup: success
```

![image](https://github.com/user-attachments/assets/ad06e025-74e4-4b2f-bb41-545bc5126239)

### Expected/Working

```yaml
sidecars:
  some_sidecar:
    image:
      build: ./Dockerfile
    depends_on:
      nginx: start
      startup: success
```
