### ISSUE TITLE
[Bug]: Deployments Spent 4 minutes after complete

### ISSUE THREAD

**Issue by iamnafets** [aws/copilot-cli#5957]
### Description:
Deployments spend 4 extra minutes after new hosts are running and old hosts are gone.

Note here that by 177s, all the new hosts are running and the old task has no hosts, but the deployment stays open with DRAINING.
![image](https://github.com/user-attachments/assets/b7cdbdd8-4a5f-4c0e-8f4c-ed02883dddcf)

### Details:
Here's the manifest: 

```
name: web
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  healthcheck:
    interval: 5s
    path: '/'
    port: 8080
    healthy_threshold: 3
    unhealthy_threshold: 2
    timeout: 3s
    grace_period: 60s
  deregistration_delay: 30s
```

### Observed result:
Deployments take twice as long.

### Expected result:
I expect the hosts in the old task to live no longer than 30s before the deployment is marked complete.

### Debugging:
I've set `deregistration_delay`, I've tuned `healthcheck` settings.
