### ISSUE TITLE
[Bug]: Unrecognized resource types: [AWS::Timestream::InfluxDBInstance] when using addons

### ISSUE THREAD

**Issue by joerayme** [aws/copilot-cli#5977]
### Description:

When trying to create an addon resource using a Cloudformation template, we're getting the error that `AWS::Timestream::InfluxDBInstance` is an unrecognized resource type. It's [documented in the Cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-timestream-influxdbinstance.html) so we think it should work.

### Details:

Copilot version: v1.34.0

Example configuration:

```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.

Resources:
  MonitoringDatastore:
    Type: AWS::Timestream::InfluxDBInstance
    Properties:
      Name: !Sub '${App}-${Env}-${Name}-monitoring-datastore'
      DbInstanceType: db.influx.medium
      DbStorageType: 'InfluxIOIncludedT1'
      AllocatedStorage: 40
      Username: username
      Password: password
      Bucket: bucket
      DeploymentType:
        Fn::If:
          - IsProduction
          - 'WITH_MULTIAZ_STANDBY'
          - 'SINGLE_AZ'
      Organization: some-org
      PubliclyAccessible: false
      VpcSecurityGroupIds:
        - !GetAtt DatastoreSecurityGroup.id
      VpcSubnetIds:
        Fn::ImportValue: !Sub '${App}-${Env}-PrivateSubnets'
  DatastoreSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${App}-${Env}-${Name}-monitoring-datastore'
      GroupDescription: 'Ingress for the InfluxDB instance'
      VpcId:
        Fn::ImportValue: !Sub '${App}-${Env}-VpcId'
      Tags:
        - Key: Name
          Value: !Sub '${App}-${Env}-${Name}-monitoring-datastore'
      SecurityGroupIngress:
        - FromPort: 8086
          ToPort: 8086
          IpProtocol: tcp
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub '${App}-${Env}-EnvironmentSecurityGroup'

Conditions:
  IsProduction: !Equals [!Ref Env, 'prod']

Outputs:
  MonitoringDatastore:
    Value: !Ref MonitoringDatastore
```

### Observed result:

```
deploy service <name> to environment <environment>: deploy service: wait for creation of change set <changeset> for stack <stack name>: ResourceNotReady: failed waiting for successful resource state: Template format error: Unrecognized resource types: [AWS::Timestream::InfluxDBInstance]: Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: 7c870ca6-096c-67b1-f12e-94021ccf9f84, HandlerErrorCode: GeneralServiceException)
```

### Expected result:

The resource is created successfully.

### Debugging:

We've run through what we can in the list in [this re:Post answer](https://repost.aws/questions/QUdVsxYe2KSuqZ_tszvIMENA/unrecognized-resource-types-aws-timestream-influxdbinstance) (i.e. double-checked the resource type, checked permissions, verified the region) and we're using the latest version of Copilot.

We've manually created the resource through the console with the same parameters and that works.
