### ISSUE TITLE
Documentation of over-arching design decisions

### ISSUE THREAD

**Issue by aidansteele** [aws/copilot-cli#730]
Hi,

I love the tool and love that it's being developed out in the open. As a person who is keen to contribute, here a couple of things holding me back, where it would be useful to have some clarity.

**1.** The first question I had was: why v2? Why didn't the team choose to continue iterating on v1? I assume there were probably good reasons for this, but without some docs explaining why, I'd be reluctant to propose features that were in v1 but not v2 - maybe they're not there for a reason!

The same goes for:

**2.** Why this in addition to the Fargate CLI? To be honest, I had never even heard of it until I saw it mentioned in an issue elsewhere here. And now I wonder: why wasn't that enhanced instead? Again, probably a good reason, but without knowing the why I feel like I don't really understand the project's vision.

**3.** Why are templates generated client-side rather than server-side like the `AWS::Serverless-2016-10-31` transform? I can guess at why, but an explanation would help clarify what's driving the team's decisions.

**4.** What features have the team currently explicitly decided against? I imagine there's an intention to avoid so much feature creep that the tool loses the simplicity that is a key selling point. Having a list of "we thought about this, but have decided against it for now because X" would be so useful.

**5.** Some philosophical ones, like: is using GitHub Actions on the table? @clareliguori has done some 💯 work on the AWS-provided actions, so AWS clearly isn't ignoring them - but this project is currently using CodeBuild for CI checks. When I submit a PR I get a ✔️ /  ╳, but I can't view what failed due to not having access to the CodeBuild logs.

Thanks for considering these! Any light you can shed would help build confidence in my ability to make meaningful contributions to the project.

**Comment by kohidave** [comment]
I want to answer all of these, but i'll just take a stab at #5 tonight, and will get to the rest tomorrow.

I've actually been using this tool for GH Actions for a while. It's a *little* cumbersome right now, but my workflow file looks like the one pasted below. I'd love to make this trivial to add as a CI step. 

```yaml
on: push
jobs:
  deploy:
    name: Deploy Changes to ECS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Download ECS CLI V2
      run: |
        wget https://ecs-cli-v2-release.s3.amazonaws.com/ecs-preview-linux-v0.0.6
        mv ./ecs-preview-linux-v0.0.6 ./ecs-preview
        chmod +x ecs-preview
    - name: ECS CLI V2 Deploy To Test
      run: |
        ./ecs-preview app deploy --env test
```
